SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Es muss eine Verbindung zwischen\n"
	.string "SOOTOPOLIS CITY und dem MT. PYRE geben.\p"
	.string "Meine Freunde und ich haben ein\n"
	.string "bisschen nachgeforscht - im Labor,\l"
	.string "in dem wir gearbeitet haben.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "Mein großer Bruder studiert das Meer.$"

