LittlerootTown_MaysHouse_2F_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, LittlerootTown_MaysHouse_2F_OnTransition
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, LittlerootTown_MaysHouse_2F_OnWarp
	.byte 0

LittlerootTown_MaysHouse_2F_OnTransition:
	call_if_lt VAR_LITTLEROOT_RIVAL_STATE, 2, LittlerootTown_MaysHouse_2F_EventScript_CheckSetReadyToMeetMay
	call_if_ge VAR_LITTLEROOT_RIVAL_STATE, 3, LittlerootTown_MaysHouse_2F_EventScript_CheckShouldUpdateMayPos
	call_if_eq VAR_LITTLEROOT_INTRO_STATE, 4, PlayersHouse_2F_EventScript_BlockStairsUntilClockIsSet
	call SecretBase_EventScript_SetDecorationFlags
	setvar VAR_SECRET_BASE_INITIALIZED, 0
	end

LittlerootTown_MaysHouse_2F_EventScript_CheckShouldUpdateMayPos::
	goto_if_set FLAG_MET_RIVAL_LILYCOVE, LittlerootTown_MaysHouse_2F_EventScript_TryUpdateMayPos
	goto_if_ge VAR_BIRCH_LAB_STATE, 2, LittlerootTown_MaysHouse_2F_EventScript_Ret
	goto LittlerootTown_MaysHouse_2F_EventScript_TryUpdateMayPos

LittlerootTown_MaysHouse_2F_EventScript_TryUpdateMayPos::
	return

LittlerootTown_MaysHouse_2F_EventScript_Ret::
	return

LittlerootTown_MaysHouse_2F_EventScript_CheckSetReadyToMeetMay::
	checkplayergender
	goto_if_eq VAR_RESULT, MALE, LittlerootTown_MaysHouse_2F_EventScript_SetReadyToMeetMay
	return

LittlerootTown_MaysHouse_2F_EventScript_SetReadyToMeetMay::
	setvar VAR_LITTLEROOT_RIVAL_STATE, 2
	return

LittlerootTown_MaysHouse_2F_OnWarp:
	map_script_2 VAR_SECRET_BASE_INITIALIZED, 0, LittlerootTown_MaysHouse_2F_EventScript_CheckInitDecor
	.2byte 0

LittlerootTown_MaysHouse_2F_EventScript_CheckInitDecor::
	checkplayergender
	goto_if_eq VAR_RESULT, FEMALE, SecretBase_EventScript_InitDecorations
	end

LittlerootTown_MaysHouse_2F_EventScript_RivalsPokeBall::
	lockall
	goto_if_eq VAR_LITTLEROOT_RIVAL_STATE, 2, LittlerootTown_MaysHouse_2F_EventScript_MeetMay
	msgbox RivalsHouse_2F_Text_ItsRivalsPokeBall, MSGBOX_DEFAULT
	releaseall
	end

LittlerootTown_MaysHouse_2F_EventScript_MeetMay::
	return

LittlerootTown_MaysHouse_2F_EventScript_MeetMayNorth::
	return

LittlerootTown_MaysHouse_2F_EventScript_MeetMaySouth::
	return

LittlerootTown_MaysHouse_2F_EventScript_MeetMayWest::
	return

LittlerootTown_MaysHouse_2F_EventScript_MeetMayEast::
	return

LittlerootTown_MaysHouse_2F_Movement_MayEnters:
	walk_down
	walk_down
	walk_in_place_faster_right
	step_end

LittlerootTown_MaysHouse_2F_Movement_MayApproachPlayerNorth:
	walk_right
	walk_right
	walk_down
	walk_down
	walk_right
	step_end

LittlerootTown_MaysHouse_2F_Movement_MayWalkToPCNorth:
	walk_up
	walk_up
	walk_up
	walk_in_place_faster_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_in_place_faster_up
	step_end

LittlerootTown_MaysHouse_2F_Movement_PlayerWatchMayNorth:
	delay_16
	walk_in_place_faster_up
	delay_16
	delay_16
	delay_16
	delay_16
	walk_in_place_faster_right
	step_end

LittlerootTown_MaysHouse_2F_Movement_MayApproachPlayerSouth:
	walk_right
	walk_right
	walk_right
	step_end

LittlerootTown_MaysHouse_2F_Movement_MayWalkToPCSouth:
	walk_up
	walk_in_place_faster_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_in_place_faster_up
	step_end

LittlerootTown_MaysHouse_2F_Movement_PlayerWatchMaySouth:
	delay_16
	walk_in_place_faster_up
	delay_16
	delay_16
	walk_in_place_faster_right
	step_end

LittlerootTown_MaysHouse_2F_Movement_MayApproachPlayerWest:
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_in_place_faster_down
	step_end

LittlerootTown_MaysHouse_2F_Movement_MayWalkToPCWest:
	walk_up
	walk_right
	walk_right
	walk_in_place_faster_up
	step_end

@ Unused, the player is already facing this direction so its unneeded
LittlerootTown_MaysHouse_2F_Movement_PlayerWatchMayWest:
	delay_16
	delay_16
	walk_in_place_faster_right
	step_end

LittlerootTown_MaysHouse_2F_Movement_MayApproachPlayerEast:
	walk_right
	walk_right
	walk_down
	walk_in_place_faster_right
	step_end

LittlerootTown_MaysHouse_2F_Movement_MayWalkToPCEast:
	walk_up
	walk_up
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_in_place_faster_up
	step_end

LittlerootTown_MaysHouse_2F_Movement_PlayerWatchMayEast:
	delay_16
	walk_in_place_faster_up
	delay_16
	delay_16
	walk_in_place_faster_right
	step_end

RivalsHouse_2F_EventScript_Rival::
	lockall
	goto_if_set FLAG_MET_RIVAL_LILYCOVE, RivalsHouse_2F_EventScript_RivalPostLilycove
	checkplayergender
	goto_if_eq VAR_RESULT, MALE, RivalsHouse_2F_EventScript_May
	goto_if_eq VAR_RESULT, FEMALE, RivalsHouse_2F_EventScript_Brendan
	end

RivalsHouse_2F_EventScript_May::
	msgbox RivalsHouse_2F_Text_MayGettingReady, MSGBOX_DEFAULT
	releaseall
	end

RivalsHouse_2F_EventScript_Brendan::
	msgbox RivalsHouse_2F_Text_BrendanGettingReady, MSGBOX_DEFAULT
	releaseall
	end

RivalsHouse_2F_EventScript_RivalPostLilycove::
	applymovement VAR_LAST_TALKED, Common_Movement_FacePlayer
	waitmovement 0
	checkplayergender
	call_if_eq VAR_RESULT, MALE, RivalsHouse_2F_EventScript_MayPostLilycove
	call_if_eq VAR_RESULT, FEMALE, RivalsHouse_2F_EventScript_BrendanPostLilycove
	setflag FLAG_MET_RIVAL_IN_HOUSE_AFTER_LILYCOVE
	releaseall
	end

RivalsHouse_2F_EventScript_MayPostLilycove::
	goto_if_set FLAG_MET_RIVAL_IN_HOUSE_AFTER_LILYCOVE, RivalsHouse_2F_EventScript_MayWhereShouldIGoNext
	msgbox RivalsHouse_2F_Text_MayJustCheckingMyPokedex, MSGBOX_DEFAULT
	return

RivalsHouse_2F_EventScript_BrendanPostLilycove::
	goto_if_set FLAG_MET_RIVAL_IN_HOUSE_AFTER_LILYCOVE, RivalsHouse_2F_EventScript_BrendanWhereShouldIGoNext
	msgbox RivalsHouse_2F_Text_BrendanJustCheckingMyPokedex, MSGBOX_DEFAULT
	return

RivalsHouse_2F_EventScript_MayWhereShouldIGoNext::
	msgbox RivalsHouse_2F_Text_MayWhereShouldIGoNext, MSGBOX_DEFAULT
	return

RivalsHouse_2F_EventScript_BrendanWhereShouldIGoNext::
	msgbox RivalsHouse_2F_Text_BrendanWhereShouldIGoNext, MSGBOX_DEFAULT
	return

LittlerootTown_MaysHouse_2F_EventScript_PC::
	lockall
	checkplayergender
	goto_if_eq VAR_RESULT, MALE, LittlerootTown_MaysHouse_2F_EventScript_CheckRivalsPC
	goto_if_eq VAR_RESULT, FEMALE, LittlerootTown_MaysHouse_2F_EventScript_CheckPlayersPC
	end

LittlerootTown_MaysHouse_2F_EventScript_CheckRivalsPC::
	msgbox gText_PokemonTrainerSchoolEmail, MSGBOX_DEFAULT
	releaseall
	end

LittlerootTown_MaysHouse_2F_EventScript_CheckPlayersPC::
	setvar VAR_0x8004, PC_LOCATION_MAYS_HOUSE
	special DoPCTurnOnEffect
	playse SE_PC_ON
	msgbox gText_PlayerHouseBootPC, MSGBOX_DEFAULT
	special BedroomPC
	releaseall
	end

LittlerootTown_MaysHouse_2F_EventScript_TurnOffPlayerPC::
	setvar VAR_0x8004, PC_LOCATION_MAYS_HOUSE
	playse SE_PC_OFF
	special DoPCTurnOffEffect
	releaseall
	end

RivalsHouse_2F_Text_MayWhoAreYou:
	.string "Was?\n"
	.string "Wer… Wer bist du denn?\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Ach, du bist {PLAYER}{KUN}!\n"
	.string "Du bist heute hierher gezogen.\p"
	.string "Ähm… Ich bin MAIKE.\n"
	.string "Schön, dich kennen zu lernen.\p"
	.string "Ich… Ich habe diesen Traum…\n"
	.string "Mit POKéMON in der ganzen Welt\l"
	.string "Freundschaft zu schließen.\p"
	.string "Ich… Ich habe schon von dir gehört.\n"
	.string "Mein Vater, PROF. LUNTE, hat mir von\l"
	.string "dir erzählt.\p"
	.string "Ich habe gehofft, dass du nett bist,\n"
	.string "{PLAYER}{KUN}, und wir Freunde werden.\p"
	.string "Ist das nicht albern? Ich… Ich habe\n"
	.string "dich doch gerade erst kennen gelernt.\p"
	.string "Hihihihi…\p"
	.string "Oh, nein! Das habe ich ja total\n"
	.string "vergessen!\p"
	.string "Ich sollte Vati doch helfen, ein paar\n"
	.string "wilde POKéMON zu fangen!\p"
	.string "{PLAYER}{KUN}, wir treffen uns später!$"

RivalsHouse_2F_Text_MayGettingReady:
	.string "POKéMON: Bei guter Gesundheit!\n"
	.string "Items: Verstaut. Fehlt noch… Was?$"

RivalsHouse_2F_Text_BrendanWhoAreYou:
	.string "Hey!\n"
	.string "Du…\p"
	.string "Wer bist du denn?\p"
	.string "Ach ja, du bist {PLAYER}, richtig?\n"
	.string "Du bist nebenan eingezogen, stimmt’s?\p"
	.string "Ich wusste nicht, dass du ein Mädchen\n"
	.string "bist.\p"
	.string "Vater, PROF. LUNTE, hat mir erzählt, dass\n"
	.string "nebenan das Kind eines ARENALEITERs\p"
	.string "einzieht und irgendwie habe ich\n"
	.string "gedacht, du seiest ein Junge.\p"
	.string "Ich heiße übrigens BRIX.\n"
	.string "Also: Hallo, Nachbarin!\p"
	.string "Was? {PLAYER}, du hast kein einziges\n"
	.string "POKéMON?\p"
	.string "Soll ich eines für dich fangen?\p"
	.string "Ach, Mist, das habe ich ganz vergessen…\p"
	.string "Ich muss meinem Vater helfen, einige\n"
	.string "wilde POKéMON zu fangen.\p"
	.string "Ein anderes Mal, okay?$"

RivalsHouse_2F_Text_BrendanGettingReady:
	.string "POKéMON: Bei guter Gesundheit!\n"
	.string "Items: Verstaut. Fehlt noch… Was?$"

RivalsHouse_2F_Text_ItsRivalsPokeBall:
	.string "Der POKéBALL gehört {RIVAL}!\n"
	.string "Lass ihn besser liegen!$"

RivalsHouse_2F_Text_MayJustCheckingMyPokedex:
	.string "MAIKE: {PLAYER}{KUN}!\p"
	.string "Ich prüfe gerade meinen POKéDEX.\p"
	.string "Es gibt eine Menge POKéMON, die ich\n"
	.string "gesehen, aber nicht gefangen habe.\p"
	.string "Und es gibt viele, von denen ich\n"
	.string "annehme, dass sie sich bald entwickeln.\p"
	.string "Jetzt überlege ich, wo ich hingehen\n"
	.string "soll, um weitere POKéMON zu fangen.$"

RivalsHouse_2F_Text_MayWhereShouldIGoNext:
	.string "MAIKE: Ich überlege, wo ich hingehen\n"
	.string "soll, um weitere POKéMON zu fangen.\p"
	.string "Wäre es nicht lustig, wenn wir uns dabei\n"
	.string "über den Weg laufen würden?$"

RivalsHouse_2F_Text_BrendanJustCheckingMyPokedex:
	.string "BRIX: Hey, {PLAYER}!\p"
	.string "Ich prüfe gerade meinen POKéDEX.\p"
	.string "Es gibt noch viele POKéMON, die ich\n"
	.string "fangen muss, aber er sieht schon sehr\l"
	.string "gut aus.\p"
	.string "Immer wenn ich den POKéDEX betrachte,\n"
	.string "bekomme ich Lust zu reisen.$"

RivalsHouse_2F_Text_BrendanWhereShouldIGoNext:
	.string "BRIX: Ich habe lange überlegt, wo ich\n"
	.string "hingehen soll, um weitere POKéMON\l"
	.string "zu fangen.\p"
	.string "Hey, {PLAYER}, wenn ich dich auf meiner\n"
	.string "Suche treffe, können wir ja einen\l"
	.string "POKéMON-Kampf austragen.$"
