BattleFrontier_Lounge4_MapScripts::
	.byte 0

BattleFrontier_Lounge4_EventScript_Woman::
	msgbox BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Cook::
	msgbox BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Man::
	msgbox BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles, MSGBOX_NPC
	end

BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring:
	.string "Ich frage mich, ob sie heute Interviews\n"
	.string "mit starken TRAINERn ausstrahlen!$"

BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere:
	.string "Wenn ich hier ein Restaurant eröffnen\n"
	.string "würde, würde meine Kasse klingeln!$"

BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles:
	.string "Huuuh…\p"
	.string "Nach solch anstrengenden Kämpfen\n"
	.string "brauche ich eine Verschnaufpause…\p"
	.string "Aber auch in Pausen denke ich über neue\n"
	.string "Strategien und Combos nach!$"

