gText_ApprenticeChallenge0::
	.string "Äh, ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Schnief… Die Spannung zerrt an mir…$"

gText_ApprenticeChallenge1::
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Jetzt komme ich!$"

gText_ApprenticeChallenge2::
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Stell dich meiner Herausforderung!$"

gText_ApprenticeChallenge3::
	.string "Äh, ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Meinst du, ich kann gewinnen?$"

gText_ApprenticeChallenge4::
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Ich fordere dich heraus!$"

gText_ApprenticeChallenge5::
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1} und\n"
	.string "außerdem schwer beschäftigt!$"

gText_ApprenticeChallenge6::
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Freut mich, dich kennen zu lernen!$"

gText_ApprenticeChallenge7::
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Darf ich anfangen?$"

gText_ApprenticeChallenge8::
	.string "Hiii! Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Ich werde mein Bestes geben!$"

gText_ApprenticeChallenge9::
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Hiiyaa! Los geht’s!$"

gText_ApprenticeChallenge10::
	.string "Ich bin der 1.000ste Schüler von\n"
	.string "{STR_VAR_1}. Äh, der {STR_VAR_2}. Schüler! Los jetzt!$"

gText_ApprenticeChallenge11::
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Auf geht’s! Lass die Erde beben!$"

gText_ApprenticeChallenge12::
	.string "Man nennt mich Schüler Nr. {STR_VAR_2}\n"
	.string "von {STR_VAR_1}. Yeah!$"

gText_ApprenticeChallenge13::
	.string "Hust! Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Nett, dich kennen zu lernen! Hust!$"

gText_ApprenticeChallenge14::
	.string "Ist das alles Nerven zerreißend…\n"
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Ehrlich wahr und nicht gelogen!$"

gText_ApprenticePleaseTeach0::
	.string "Waaahaaa… Bist du es, {PLAYER}?!?\n"
	.string "Oooh… Heul… Jammer… Schnief…\p"
	.string "Tu-tut mir L-Leid…\n"
	.string "Ich bin so nervös, da muss ich einfach\l"
	.string "weinen… Heul…\p"
	.string "Ich bin {STR_VAR_1} und du bist mein\n"
	.string "großes Vorbild, {PLAYER}… Jammer…\p"
	.string "Ich hatte diesen Traum - dass ich dich\n"
	.string "eines Tages etwas über POKéMON fragen\l"
	.string "würde… Schnief…\p"
	.string "Bitte, bitte, {PLAYER}!\n"
	.string "Bring mir etwas über POKéMON bei!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… Ab-ber, ab-ber…\n"
	.string "Heul… Waaaaaahaaaaaa…\p"
	.string "Bitte!\n"
	.string "Ich flehe dich an… Jammer…$"

gText_ApprenticeWhichLevelMode0::
	.string "Echt? Ganz wirklich?!?\n"
	.string "Unglaublich! Fantastisch! Juhuuuuuu…\p"
	.string "Oh… Entschuldige…\n"
	.string "Ich freue mich so sehr, ich könnte glatt\l"
	.string "wieder weinen…\p"
	.string "Äh… Also, dann erzähl mir bitte\n"
	.string "etwas über den DUELLTURM.\p"
	.string "Soll ich an den Level 50 oder den \n"
	.string "Offenen Kämpfen teilnehmen?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaahaaaaaaa…\p"
	.string "Oh, tut mir Leid! Aber du hast mich\n"
	.string "so glücklich gemacht, da muss ich\l"
	.string "einfach weinen… Heul…\p"
	.string "Schnüff…\n"
	.string "Vielen, vielen Dank! Ich hoffe, du\l"
	.string "hilfst mir bald wieder… Heul…$"

gText_ApprenticePleaseTeach1::
	.string "Wuhuuu! Du bist doch {PLAYER},\n"
	.string "oder? Du bist sehr stark, oder?\p"
	.string "Ich bin {STR_VAR_1}!\n"
	.string "Ich bin gerade erst ein TRAINER\l"
	.string "geworden!\p"
	.string "{PLAYER}, bitte! Du kannst mir nicht\n"
	.string "etwas über TRAINER beibringen, oder?$"

gText_ApprenticeRejectTeaching1::
	.string "Oooh, warum nicht?\n"
	.string "Bitte?Ja? Bitte, bitte, bitte, bitte…\l"
	.string "Bitte, werde mein Lehrer, bitte, bitte…$"

gText_ApprenticeWhichLevelMode1::
	.string "Juhuuu! Super!\p"
	.string "Ich möchte dich gerne etwas über den\n"
	.string "DUELLTURM fragen.\p"
	.string "Level 50 oder Offene Kämpfe…\n"
	.string "Was würdest du mir empfehlen?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}? Jawohl!\n"
	.string "Ich werde mein Bestes geben!\p"
	.string "Du bringst mir doch noch mehr bei, wenn\n"
	.string "wir uns wiedersehen, oder?$"

gText_ApprenticePleaseTeach2::
	.string "Äh… Du bist {PLAYER}?\n"
	.string "Ich bin {STR_VAR_1}.\p"
	.string "Ich möchte gerne ein TRAINER werden,\n"
	.string "aber ich weiß nicht wie…\p"
	.string "Und da dachte ich mir, dass du mir\n"
	.string "weiterhelfen könntest. Du bist doch\l"
	.string "berühmt für dein Talent.\p"
	.string "{PLAYER}, hilfst du mir?$"

gText_ApprenticeRejectTeaching2::
	.string "Aber…\p"
	.string "Ich würde doch so gerne ein TRAINER\n"
	.string "werden!\p"
	.string "Bitte, gib mir doch ein paar Tipps, ja?$"

gText_ApprenticeWhichLevelMode2::
	.string "Vielen Dank!\n"
	.string "Und hier kommt auch schon meine erste\l"
	.string "Frage!\p"
	.string "Der DUELLTURM bietet Level 50\n"
	.string "und Offene Kämpfe an.\p"
	.string "An welchen Kämpfen soll ich teilnehmen?$"

gText_ApprenticeLevelModeThanks2::
	.string "Ach, {STR_VAR_1}?\n"
	.string "Ja, abgemacht!\p"
	.string "Und wenn ich noch mehr Fragen habe,\n"
	.string "dann warte ich hier auf deinen Rat.$"

gText_ApprenticePleaseTeach3::
	.string "Wie? Du bist…\n"
	.string "Nein, das kann einfach nicht sein!\p"
	.string "Jemand wie ich kann doch nicht das\n"
	.string "Glück haben, {PLAYER} zu treffen.\p"
	.string "Du bist wirklich… {PLAYER}?\n"
	.string "Ich fass es nicht! Ich spreche\l"
	.string "mit {PLAYER}!\p"
	.string "Bei so viel Glück wird mir bestimmt\n"
	.string "etwas Schreckliches passieren!\l"
	.string "Das weiß ich ganz genau…\p"
	.string "Tut mir Leid…\n"
	.string "Ich heiße… {STR_VAR_1}…\p"
	.string "Nun, ich habe nichts, auf das ich stolz\n"
	.string "sein müsste…\p"
	.string "Und du wirst meinen Namen bestimmt\n"
	.string "ganz schnell wieder vergessen…\p"
	.string "Ich hatte diesen Traum! Dass ich dich,\n"
	.string "sollte ich dich jemals treffen,\l"
	.string "{PLAYER}… Um Rat fragen würde!\p"
	.string "Dich, als TRAINER! Aber das würdest\n"
	.string "du bestimmt ablehnen…\p"
	.string "Oder bist du so nett und verrätst mir\n"
	.string "ein paar Geheimnisse?$"

gText_ApprenticeRejectTeaching3::
	.string "Ich wusste es…\p"
	.string "Da ich ein langweiliger Niemand bin…\p"
	.string "Aber ich hatte doch gehofft…\n"
	.string "Du würdest es dir nicht noch einmal\l"
	.string "überlegen, oder?\p"
	.string "Ich kann dich doch jetzt nicht einfach\n"
	.string "so gehen lassen!\p"
	.string "Wo ich doch ausnahmsweise mal Glück\n"
	.string "habe und dich traf.\p"
	.string "Könntest du mir nicht doch einen Rat\n"
	.string "geben?$"

gText_ApprenticeWhichLevelMode3::
	.string "Wirklich?!? Ich kann es kaum glauben!!!\n"
	.string "Ich kann es nicht glauben, dass du mir\l"
	.string "einen Rat geben wirst!\p"
	.string "Ich… bin sooooo froh…\p"
	.string "Meine Frage ist eigentlich recht dumm,\n"
	.string "aber ich kann mich nicht entscheiden…\p"
	.string "Im DUELLTURM kannst du an Level 50\n"
	.string "und Offenen Kämpfen teilnehmen.\p"
	.string "Welche Kämpfe kommen für mich wohl\n"
	.string "in Frage?!?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? Ja!\n"
	.string "Aber glaubst du wirklich, jemand wie\l"
	.string "ich hat da überhaupt eine Chance?\p"
	.string "Ich werde mein Bestes geben, auch wenn\n"
	.string "ich weiß, dass das nichts nützt.\p"
	.string "Vielen Dank, dass du deine kostbare\n"
	.string "Zeit jemandem wie mir gewidmet hast.$"

gText_ApprenticePleaseTeach4::
	.string "Hi! Du bist {PLAYER}{KUN}?\p"
	.string "Ich habe gehört, du bist talentiert im\n"
	.string "Umgang mit POKéMON!\p"
	.string "Ich bin {STR_VAR_1}.\n"
	.string "Wir werden bestimmt gute Freunde\l"
	.string "werden.\p"
	.string "Weißt du was?\p"
	.string "Du kannst in der BATTLE FRONTIER nicht\n"
	.string "gewinnen, wenn du dich auf das\p"
	.string "verlässt, was du in der TRAINERSCHULE\n"
	.string "gelernt hast…\p"
	.string "Daher würde ich auch gerne etwas von\n"
	.string "dir lernen. Bist du einverstanden?$"

gText_ApprenticeRejectTeaching4::
	.string "Was? Warum lehnst du ab?\n"
	.string "Ich bin’s doch!\l"
	.string "Überleg dir das noch einmal!$"

gText_ApprenticeWhichLevelMode4::
	.string "Na, das hört sich doch gut an. Ich\n"
	.string "möchte, dass du mir bei einer\l"
	.string "Entscheidung hilfst.\p"
	.string "Im DUELLTURM gibt es doch die Level 50\n"
	.string "und die Offenen Kämpfe.\p"
	.string "An welchen soll ich teilnehmen,\n"
	.string "{PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "{STR_VAR_1} kommt also für mich in\n"
	.string "Frage? Vielen Dank!\p"
	.string "Und da ich weiß, dass dieser Rat von dir\n"
	.string "kommt, {PLAYER}{KUN}, werde ich auch eine\l"
	.string "Niederlage ertragen können.\p"
	.string "Ich hoffe, ich kann dich bald mal wieder\n"
	.string "um Rat fragen! Mach’s gut!$"

gText_ApprenticePleaseTeach5::
	.string "Hallo! {PLAYER}{KUN}! Ich kenne dich!\n"
	.string "Du bist ja berühmt! Ich bin {STR_VAR_1}!\l"
	.string "Schön, dich kennen zu lernen!\p"
	.string "Ich bin ein TRIATHLET. Ich halte mich\n"
	.string "fit und ziehe nebenbei noch POKéMON\l"
	.string "auf.\p"
	.string "Ich arbeite, schlafe, tanze und habe \n"
	.string "noch viele andere Dinge zu tun…\p"
	.string "Und da ich so beschäftigt bin, ist es\n"
	.string "nicht leicht für mich, ein ordentlicher\l"
	.string "TRAINER zu werden.\p"
	.string "Mir kommt da gerade eine Idee!\p"
	.string "Es kann kein Zufall sein, dass wir uns\n"
	.string "begegnet sind. {PLAYER}{KUN}, darf ich an\l"
	.string "deinem Wissen teilhaben?$"

gText_ApprenticeRejectTeaching5::
	.string "Ach, komm schon. Bitte?\n"
	.string "Ich kann einen Lehrer wie dich gut\l"
	.string "gebrauchen, {PLAYER}{KUN}!\p"
	.string "Ich brauche wirklich ganz dringend\n"
	.string "deinen Rat.$"

gText_ApprenticeWhichLevelMode5::
	.string "Danke! Das hört sich doch schon viel\n"
	.string "besser an! Also, hier ist eine einfache\l"
	.string "Frage!\p"
	.string "Im DUELLTURM kann man an Level 50\n"
	.string "oder Offenen Kämpfen teilnehmen.\p"
	.string "An welchen sollte ein beschäftigter Typ\n"
	.string "wie ich teilnehmen?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}? Fein. Ich werde\n"
	.string "irgendwie die Zeit dafür finden und\l"
	.string "daran teilnehmen.\p"
	.string "Jetzt muss ich aber wirklich wieder an\n"
	.string "die Arbeit…\l"
	.string "Vielen Dank! Man sieht sich!$"

gText_ApprenticePleaseTeach6::
	.string "Das gibt’s ja gar nicht!!!\n"
	.string "Bist du es wirklich, {PLAYER}?\p"
	.string "Ahah! Fantastisch! Ich bin {STR_VAR_1}.\n"
	.string "Toll, dass ich dich mal kennen lerne!\p"
	.string "Du bist wirklich stark und talentiert,\n"
	.string "nicht wahr, {PLAYER}?\p"
	.string "Alle sprechen über dich!\p"
	.string "Mir kommt da eine großartige Idee!!!\n"
	.string "Du gibst mir einen Rat, {PLAYER}!\l"
	.string "Dadurch werde ich bestimmt stärker!\p"
	.string "Ist das nicht eine Superidee?\n"
	.string "Bitte, ich muss an deiner Klugheit\l"
	.string "teilhaben. Ja?$"

gText_ApprenticeRejectTeaching6::
	.string "Hahahaha, du tust doch nur so, als ob du\n"
	.string "gemein seist. Du kannst mich nicht an\l"
	.string "der Nase herumführen! Du hilfst mir?$"

gText_ApprenticeWhichLevelMode6::
	.string "Siehst du! Ich wusste doch, du hast ein\n"
	.string "gutes Herz, {PLAYER}!\p"
	.string "Mh, was frage ich dich jetzt als Erstes?\n"
	.string "Mal sehen… Hah, ich weiß!\p"
	.string "Trommelwirbel, bitte!\n"
	.string "Meine Frage lautet…\p"
	.string "An welchen Kämpfen soll ich im\n"
	.string "DUELLTURM teilnehmen?\p"
	.string "Level 50 oder Offene Kämpfe?\n"
	.string "Welche passen zu mir?$"

gText_ApprenticeLevelModeThanks6::
	.string "Ooooh, wow!\n"
	.string "{STR_VAR_1}, meinst du?!?\l"
	.string "Eine coole Antwort. Danke!\p"
	.string "Ich glaube, das ist alles, was ich heute\n"
	.string "von dir wissen will.\p"
	.string "Wir müssen uns bald mal wieder treffen!\n"
	.string "Danke und bis bald!$"

gText_ApprenticePleaseTeach7::
	.string "Ich bitte vielmals um Verzeihung, aber…\n"
	.string "Bist du {PLAYER}?\p"
	.string "Ich bin {STR_VAR_1}.\n"
	.string "Schön, dich kennen zu lernen!\p"
	.string "Ich bewundere dich schon lange…\p"
	.string "… … … … …\n"
	.string "…\p"
	.string "Wenn es dir nicht zu viel ausmacht,\n"
	.string "würde ich dich gerne um etwas bitten…\p"
	.string "Darf ich deine Schülerin\n"
	.string "werden, {PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Oh…\p"
	.string "… … … … … \n"
	.string "…\l"
	.string "… … … … …\l"
	.string "…\p"
	.string "Ich muss vor Schreck in Ohnmacht\n"
	.string "gefallen sein… Ich habe dich\l"
	.string "bestimmt falsch verstanden!\p"
	.string "Bitte! Nimm mich als deine Schülerin\n"
	.string "an. Ja?$"

gText_ApprenticeWhichLevelMode7::
	.string "Oh… Das freut mich!!!\p"
	.string "Ich möchte deine Zeit nicht übermäßig\n"
	.string "in Anspruch nehmen, daher stelle ich dir\l"
	.string "eine einzige Frage.\p"
	.string "Ich möchte gern im DUELLTURM antreten.\p"
	.string "Aber zu welchen Kämpfen soll ich\n"
	.string "mich anmelden?\p"
	.string "Level 50 oder Offene Kämpfe?\n"
	.string "Welche kommen für mich in Frage?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1}, sagst du?\n"
	.string "Ja! Ich werde mein Bestes geben!\l"
	.string "Vielen Dank, {PLAYER}!\p"
	.string "Ich hoffe, du stehst mir auch in\n"
	.string "Zukunft mit Rat und Tat zur Seite!\l"
	.string "Pass auf dich auf!$"

gText_ApprenticePleaseTeach8::
	.string "Iiihiii! {PLAYER}!\n"
	.string "Du hast mich angesprochen!!!\l"
	.string "Ich… kann mein Glück kaum fassen!\p"
	.string "Ich? Ich bin {STR_VAR_1}!\n"
	.string "Ich bin gerade erst TRAINER geworden.\p"
	.string "Ich freue mich, dich getroffen zu\n"
	.string "haben, {PLAYER}. Du bist eine\l"
	.string "Berühmtheit in POKéMON-Kreisen!\p"
	.string "Diese Gelegenheit möchte ich nutzen!\n"
	.string "Darf ich dich um einen Riesengefallen\l"
	.string "bitten, {PLAYER}?\p"
	.string "Bitte nimm mich als deine Schülerin an!\n"
	.string "Ich möchte so gerne von dir lernen!$"

gText_ApprenticeRejectTeaching8::
	.string "Waaaaahaaaa! {PLAYER} hat mich\n"
	.string "abgelehnt… Und dabei wäre\l"
	.string "es eine unbezahlbare Erfahrung!\p"
	.string "Bitte, {PLAYER}! Ich würde so gerne ein\n"
	.string "Ja von dir hören!\p"
	.string "Ich bitte dich! Bitte, ja?$"

gText_ApprenticeWhichLevelMode8::
	.string "Hiiihiii! {PLAYER} hat Ja gesagt!\n"
	.string "{PLAYER} hat Ja gesagt!\p"
	.string "Heute Nacht werde ich mit Sicherheit\n"
	.string "nicht schlafen können…\p"
	.string "Und hier ist meine Frage!\p"
	.string "Soll ich im DUELLTURM in Level 50 oder\n"
	.string "an den Offenen Kämpfen teilnehmen?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Superfein!\n"
	.string "Ich freu mich so sehr! Mir ist\l"
	.string "richtig schwindelig vor Glück!\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um Rat fragen.$"

gText_ApprenticePleaseTeach9::
	.string "Whoa! Das kann nicht sein…\n"
	.string "Bist du eventuell… {PLAYER}{KUN}?!?\l"
	.string "Dieser starke und berühmte TRAINER?\p"
	.string "Ich muss ein Glückzilp… Äh… Glückspilz\n"
	.string "sein! Ich heiße {STR_VAR_1}!\p"
	.string "Ich bin auf der Suche nach einem\n"
	.string "POKéMON-Lehrer!\p"
	.string "So etwas nenn ich perfektes Timing,\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Bitte nimm mich unter deine Eittichf…\n"
	.string "Äh… Fittiche!$"

gText_ApprenticeRejectTeaching9::
	.string "Guaaaah!\n"
	.string "Du bist so cool und abgebrüht…\p"
	.string "Komm sei nicht so!\n"
	.string "Ich bitte chid… Äh… dich!$"

gText_ApprenticeWhichLevelMode9::
	.string "Nun, mit der Antwort kann ich was\n"
	.string "anfangen! Eine exzellente Antwort!\p"
	.string "Wie wäre es, wenn du mir einen Rat\n"
	.string "zu dem DUELLTURM geben würdest?\p"
	.string "Level 50 oder Offene Kämpfe? An\n"
	.string "was soll ich teilnehmen?$"

gText_ApprenticeLevelModeThanks9::
	.string "Ha, {STR_VAR_1} also!\n"
	.string "Nief… Äh… Fein!\l"
	.string "Ich werde mein Bestes geben!\p"
	.string "Und du bist ab sofort mein Lehrer!\n"
	.string "Bis bald nand… Äh… dann!$"

gText_ApprenticePleaseTeach10::
	.string "Hey, du bist doch {PLAYER}{KUN}, oder?\n"
	.string "Die Polizei sucht dich!!!\p"
	.string "… … … …\n"
	.string "Hahaha, ich hab dich auf den Arm\l"
	.string "genommen! Dein blödes Gesicht…\p"
	.string "Ich bin {STR_VAR_1}. Ich sehe vielleicht\n"
	.string "nicht so aus, aber du stehst vor dem\l"
	.string "POKéMON-CHAMP! Jawohl!\p"
	.string "Haha! Ich habe dich schon wieder auf\n"
	.string "den Arm genommen!\p"
	.string "Ich bin kein talentierter Kämpfer.\n"
	.string "Und diesmal sag ich die Wahrheit!\p"
	.string "Wie wäre es, wenn du mich als deinen\n"
	.string "Schüler annimmst?$"

gText_ApprenticeRejectTeaching10::
	.string "Ich werde dir zeigen, wie ich auf so eine\n"
	.string "rüde Abfuhr reagiere!\p"
	.string "Waaaah! Heul! Jammer! Klag!\n"
	.string "Hick…\p"
	.string "Hahaha! Das waren meine TRUGTRÄNEn!\n"
	.string "Reingelegt!\p"
	.string "Komm, bitte nimm mich als deinen\n"
	.string "Schüler!$"

gText_ApprenticeWhichLevelMode10::
	.string "Jipiii!\n"
	.string "Dafür schenke ich dir ein großes Boot!\p"
	.string "Nee, ich nehme dich schon wieder hoch!\n"
	.string "Aber… Ich danke dir!\p"
	.string "Im DUELLTURM kann man doch an\n"
	.string "Level 50 und Offenen Kämpfen\l"
	.string "teilnehmen.\p"
	.string "Ich kann mich nicht entscheiden, an\n"
	.string "welchen Kämpfen ich teilnehmen soll…\p"
	.string "Kannst du das für mich entscheiden,\n"
	.string "mein Lehrer?$"

gText_ApprenticeLevelModeThanks10::
	.string "Aha! {STR_VAR_1}.\n"
	.string "Dann werde ich an den anderen Kämpfen\l"
	.string "teilnehmen, das ist klar!\p"
	.string "Haha! Das war ein Witz! Ich werde\n"
	.string "natürlich auf deinen Rat hören, Lehrer!\p"
	.string "Vielen Dank, Meister! Ich hoffe,\n"
	.string "du hilfst mir auch in Zukunft.$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi und Hallo!\p"
	.string "Ich bin der MATROSE {STR_VAR_1}!\p"
	.string "Du bist dran!\n"
	.string "Nenn mir deinen Namen, Mann!\p"
	.string "Aha, aha!\n"
	.string "{PLAYER}{KUN} bist du,\l"
	.string "und POKéMON gehören auch dazu.\p"
	.string "Wird die Welt dir zur Bühne,\n"
	.string "musst du sein der starke Kühne.\p"
	.string "Was ich dir damit eigentlich sage,\n"
	.string "du bist der zehnte TRAINER, den ich\l"
	.string "heut frage.\p"
	.string "Lass mich nicht im Regen stehn,\n"
	.string "möchte dich als meinen Lehrer sehn.$"

gText_ApprenticeRejectTeaching11::
	.string "Aber!\n"
	.string "Du musst mich als Schüler annehmen!\p"
	.string "Sei doch nicht so gemein!\n"
	.string "Lass mich bitte dein Schüler sein!$"

gText_ApprenticeWhichLevelMode11::
	.string "{PLAYER}, das ist die richtige\n"
	.string "Einstellung!\p"
	.string "Ich habe eine Frage, die\n"
	.string "wird dir zur Plage!\p"
	.string "Der DUELLTURM, da komm ich mir\n"
	.string "vor wie ein Wurm.\p"
	.string "Level 50 oder Offene Kämpfe,\n"
	.string "was soll ich wählen? Ich muss auf deine\l"
	.string "Entscheidung zählen.$"

gText_ApprenticeLevelModeThanks11::
	.string "{STR_VAR_1} sagst du?\n"
	.string "Gut, ich hörte dir zu.\p"
	.string "{PLAYER}, auch in Zukunft, das ist klar,\n"
	.string "frag ich dich um Rat, das ist wahr.$"

gText_ApprenticePleaseTeach12::
	.string "Sag, bist du nicht {PLAYER}? Was mache\n"
	.string "ich jetzt nur? Mit dir reden? Warum\l"
	.string "nicht? Ich rede ja eh schon mir dir.\p"
	.string "{PLAYER}, habe ich dich überrascht?\n"
	.string "Ich sage dir besser, mit wem du es zu\l"
	.string "tun hast!\p"
	.string "Du darfst mich {STR_VAR_1} nennen. Ich\n"
	.string "bin der beste Gitarrist, den es gibt! Ja,\l"
	.string "das sage ich in aller Bescheidenheit!\p"
	.string "Nimmst du mir das ab?\n"
	.string "Du nimmst es mir ab!\p"
	.string "Da ich so viel Glück habe, werde ich dies\n"
	.string "weiter auf die Probe stellen.\l"
	.string "Ich habe eine Bitte an dich!\p"
	.string "{PLAYER}, bitte nimm mich als deinen\n"
	.string "Schüler an! Ich möchte alles von\l"
	.string "dir lernen!$"

gText_ApprenticeRejectTeaching12::
	.string "Du lehnst mich also ab, was?\n"
	.string "Dann werde ich dich einfach nochmal\l"
	.string "fragen.\p"
	.string "{PLAYER}, nimmst du mich als deinen\n"
	.string "Schüler an? Ich möchte alles von\l"
	.string "dir lernen!$"

gText_ApprenticeWhichLevelMode12::
	.string "Ich bade im Glück, hähähä!\n"
	.string "Und schon habe ich eine Frage!\p"
	.string "Da wir hier im DUELLTURM\n"
	.string "sind, drängt sich mir diese Frage auf!\p"
	.string "Welche Kämpfe soll ich hier bestreiten?$"

gText_ApprenticeLevelModeThanks12::
	.string "Du meinst also {STR_VAR_1}?\n"
	.string "Das wird dann wohl das Beste sein!\p"
	.string "Nun, {PLAYER}, dann vergiss mich nicht!\p"
	.string "Man sieht sich.$"

gText_ApprenticePleaseTeach13::
	.string "Oh, hallo! Du da! Dich meine ich!\n"
	.string "Kannst du mir nicht meine Schultern\l"
	.string "massieren?\p"
	.string "Ja… Genau da! Oh, ja!\n"
	.string "Auaaa! Au! das tut gut!\p"
	.string "Ich heiße {STR_VAR_1}!\n"
	.string "Ich trainiere Karate, aber mein Körper\l"
	.string "mag das gar nicht leiden…\p"
	.string "Daher überlege ich, ob ich nicht an\n"
	.string "POKéMON-Kämpfen teilnehmen soll, um\l"
	.string "meine Muskeln aufzubauen.\p"
	.string "Du bist {PLAYER}{KUN}, stimmt’s?\n"
	.string "Der CHAMP der POKéMON LEAGUE?\p"
	.string "Kannst du mir nicht mit Rat und Tat zur\n"
	.string "Seite stehen?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, warum nicht?\p"
	.string "Ich werde dich auch nicht nerven!\n"
	.string "Ehrlich nicht! Komm schon, ja?$"

gText_ApprenticeWhichLevelMode13::
	.string "Vielen Dank! Das ist megacool von dir!\n"
	.string "Hust… Hust…\p"
	.string "Röchel… Ich muss mich wirklich\n"
	.string "sportlich betätigen…\p"
	.string "Ich kämpfe sofort hier weiter!!\n"
	.string "Aber soll ich an Level 50 oder den\l"
	.string "Offenen Kämpfen teilnehmen?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, gut. {STR_VAR_1}.\n"
	.string "Ich mache mich sofort auf den Weg!\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um deinen Rat bitten?$"

gText_ApprenticePleaseTeach14::
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Oh, schau mich nicht so an. Du machst\n"
	.string "mich ganz verlegen!\p"
	.string "Ich… Ich bin {STR_VAR_1}.\p"
	.string "Es ist mir ja schrecklich peinlich\n"
	.string "es zuzugeben, aber ich untersuche\l"
	.string "alte Ruinen und so was.\p"
	.string "Und es ist noch peinlicher, dass ich\n"
	.string "Interesse an der BATTLE FRONTIER habe.\p"
	.string "Du hast den Ruf eines starken\n"
	.string "TRAINERs, {PLAYER}{KUN}…\p"
	.string "Es fällt mir schwer, das zu sagen, aber\n"
	.string "ich möchte dich etwas fragen.\p"
	.string "Kannst du nicht mein Lehrer werden\n"
	.string "und mir mit Rat und Tat zur Seite\l"
	.string "stehen?$"

gText_ApprenticeRejectTeaching14::
	.string "Bitte, weis mich nicht so einfach ab!\n"
	.string "Ich kann mit dieser Peinlichkeit\l"
	.string "nicht leben!\p"
	.string "Bitte, werde mein Lehrer!\n"
	.string "Ich brauche deine Weisheit!$"

gText_ApprenticeWhichLevelMode14::
	.string "Da-Danke…\p"
	.string "Schau mich nicht so an!\n"
	.string "Ich werde ja ganz rot.\p"
	.string "Bitte antworte mir, ohne mir in die\n"
	.string "Augen zu schauen.\p"
	.string "Im DUELLTURM… An welchen Kämpfen\n"
	.string "soll ich da teilnehmen?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… Okay!\n"
	.string "Ich werde mich gewiss anstrengen.\p"
	.string "Ich hoffe, ich werde mich nicht allzu\n"
	.string "sehr blamieren, wenn ich mich da\l"
	.string "versuche…\p"
	.string "Vielen Dank, {PLAYER}{KUN}!\n"
	.string "Wenn wir uns wiedersehen, habe ich\l"
	.string "bestimmt eine neue Frage an dich.$"

gText_ApprenticePleaseTeach15::
	.string "Hm? Du scheinst {PLAYER}{KUN} zu sein.\n"
	.string "Aber bist du wirklich du?\p"
	.string "Du kannst mich {STR_VAR_1} nennen.\p"
	.string "Ich überlege gerade, ob ich mir nicht\n"
	.string "einen starken TRAINER als Lehrer\l"
	.string "suchen soll.\p"
	.string "Da habe ich Glück, dass du hier\n"
	.string "vorbeigekommen bist.\l"
	.string "Du bist doch {PLAYER}{KUN}, oder?\p"
	.string "Also, wenn du echt bist, ist alles in\n"
	.string "Ordnung. Ich möchte nur, dass du mich\l"
	.string "als deinen Schüler annimmst.$"

gText_ApprenticeRejectTeaching15::
	.string "Oh? Warum lehnst du mich ab?\p"
	.string "Ich entschuldige mich, dass ich an\n"
	.string "deiner Identität gezweifelt habe.\p"
	.string "Nimm meine Entschuldigung und mich\n"
	.string "als deinen Schüler an. Bitte.$"

gText_ApprenticeWhichLevelMode15::
	.string "Du nimmst mich wirklich an?\n"
	.string "Ich möchte auf keinen Fall unreif\l"
	.string "erscheinen.\p"
	.string "Wenn das wahr ist, dann entschuldige\n"
	.string "ich mich, dass ich an deiner Identität\l"
	.string "gezweifelt habe.\p"
	.string "Ich möchte im DUELLTURM antreten.\n"
	.string "Soll ich an Level 50 oder Offenen\l"
	.string "Kämpfen teilnehmen?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Bist du dir da ganz sicher?\p"
	.string "Verstehe. In dem Fall danke ich dir,\n"
	.string "dass du dir Zeit für mich genommen hast.\p"
	.string "Ich weiß, manchmal nerve ich. Umso mehr\n"
	.string "freut es mich, dass du mich angenommen\l"
	.string "hast.\p"
	.string "Bis bald mal!$"

gText_ApprenticeWhatHeldItem0::
	.string "Seufz… Jammer…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Ich habe ein Problem, bei dem ich zu\n"
	.string "keiner Lösung komme.\p"
	.string "Ich kann mich nicht entscheiden,\n"
	.string "welches Item mein {STR_VAR_1} tragen\l"
	.string "soll.\p"
	.string "Sag du es mir, {PLAYER}.\n"
	.string "Welches Item soll ich ihm geben?$"

gText_ApprenticeHoldNothing0::
	.string "Oh? Ich soll meinem {STR_VAR_1} nichts\n"
	.string "geben?!?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Oh, okay! Gut, dass wir das Problem\n"
	.string "gelöst haben. Herrlich! Juhuu!\p"
	.string "Vielen, vielen Dank!$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, da bin ich aber froh…\n"
	.string "Ich müsste sogar {STR_VAR_1} haben.\p"
	.string "Bin ich froh, dass wir das Problem\n"
	.string "gelöst haben! Herrlich! Juhuu!\p"
	.string "Vielen, vielen Dank!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Waaahaaa! Das ist sooo gemein!\p"
	.string "{STR_VAR_1} wurde mir vorher auch\n"
	.string "schon mal vorgeschlagen… Schnief…\p"
	.string "Oder meinst du, mein {STR_VAR_2} sollte\n"
	.string "besser gar nichts tragen?$"

gText_ApprenticeWhatHeldItem1::
	.string "Hey! Du bist es, {PLAYER}! Sehr gut!\n"
	.string "Ich wollte dich nämlich was fragen!\p"
	.string "Halten deine POKéMON Items? Ich\n"
	.string "möchte meinen auch Items geben, aber…\p"
	.string "Welches Item soll mein {STR_VAR_1}\n"
	.string "nur tragen? Ich weiß es einfach nicht…\p"
	.string "Was meinst du?$"

gText_ApprenticeHoldNothing1::
	.string "Wie? Du meinst, {STR_VAR_1} braucht\n"
	.string "kein Item?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Oh, verstehe! Das mache ich! Genau!\n"
	.string "Vielen Dank für deine Hilfe!$"

gText_ApprenticeThanksHeldItem1::
	.string "Oh, wow! {STR_VAR_1}?!?\n"
	.string "Okay, das gebe ich ihm.\p"
	.string "Vielen Dank für deinen Rat!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Oh, so habe ich das aber gar nicht\n"
	.string "gemeint! Ich wollte wissen, wie sich die\l"
	.string "Items unterscheiden.\p"
	.string "Manche kenne ich, manche eben nicht.\n"
	.string "Oder meinst du, mein POKéMON benötigt\l"
	.string "kein Item?$"

gText_ApprenticeWhatHeldItem2::
	.string "Hallo {PLAYER}!\n"
	.string "Es geht um mein {STR_VAR_1}…\p"
	.string "Ich würde ihm gerne ein gutes Item zum\n"
	.string "Tragen geben. Aber welches?$"

gText_ApprenticeHoldNothing2::
	.string "Oh, mein {STR_VAR_1} benötigt kein\n"
	.string "Item?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "Oh, verstehe!\n"
	.string "Bis später dann!$"

gText_ApprenticeThanksHeldItem2::
	.string "Oh, {STR_VAR_1}?\n"
	.string "Klar!\p"
	.string "Ich werde mir Mühe geben, das Item zu\n"
	.string "finden. Bis später dann!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Jemand hat mir bereits zu {STR_VAR_1}\n"
	.string "geraten.\p"
	.string "Aber ich möchte meinem POKéMON ein\n"
	.string "anderes Item zum Tragen geben.\p"
	.string "Oder meinst du, mein {STR_VAR_2}\n"
	.string "benötigt kein Item?$"

gText_ApprenticeWhatHeldItem3::
	.string "Hallo, {PLAYER}…\n"
	.string "Ich muss dich noch mal belästigen. Ich\l"
	.string "habe eine wichtige Frage.\p"
	.string "Ich glaube nicht, dass ich gut genug\n"
	.string "bin, um einen Kampf zu gewinnen. Daher\l"
	.string "überlege ich, meinem {STR_VAR_1} ein\p"
	.string "Item zum Tragen zu geben.\n"
	.string "Aber ich weiß nicht, welches.\p"
	.string "{PLAYER}, kannst du das nicht für mich\n"
	.string "entscheiden?$"

gText_ApprenticeHoldNothing3::
	.string "Ein POKéMON, das zu jemandem wie mir\n"
	.string "gehört, benötigt kein Item?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Ah, ich verstehe…\n"
	.string "Du sagst, ich soll mich nicht nur auf\l"
	.string "Items verlasen.\p"
	.string "Ich werde mein Bestes geben!\n"
	.string "Vielen, vielen Dank!$"

gText_ApprenticeThanksHeldItem3::
	.string "{STR_VAR_1}? Okay!\n"
	.string "Ich bin nicht sicher, ob ich dieses Item\l"
	.string "besorgen kann… Aber ich versuche es.\p"
	.string "Vielen, vielen Dank!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, aber…\n"
	.string "Ich glaube, das habe ich schon mal\l"
	.string "gehört…\p"
	.string "Vielleicht, weil ich mit {STR_VAR_1}\n"
	.string "nicht geschickt genug umgegangen bin?\p"
	.string "Oder meinst du damit, dass mein\n"
	.string "{STR_VAR_2} gar kein Item benötigt?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Ich muss dich unbedingt etwas fragen!\p"
	.string "Du hast mir geraten, welches POKéMON\n"
	.string "ich einsetzen soll.\p"
	.string "Aber ich habe dich nicht gefragt,\n"
	.string "welches Item es tragen soll.\p"
	.string "Du hast mir schon einmal einen tollen\n"
	.string "Rat gegeben. Kannst du mir wieder\l"
	.string "helfen?\p"
	.string "Welches Item wäre gut? Ich möchte\n"
	.string "meinem {STR_VAR_1} etwas geben.$"

gText_ApprenticeHoldNothing4::
	.string "Oh, mein {STR_VAR_1} soll also mit\n"
	.string "leeren Händen dastehen?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Wenn du das für das Beste hältst, werde\n"
	.string "ich mich an deinen Rat halten.\p"
	.string "Und da ich weiß, dass dieser Rat von dir\n"
	.string "kommt, {PLAYER}{KUN}, werde ich auch eine\l"
	.string "Niederlage ertragen können.\p"
	.string "Ich hoffe, ich kann dich bald mal wieder\n"
	.string "um Rat fragen! Mach’s gut!$"

gText_ApprenticeThanksHeldItem4::
	.string "{STR_VAR_1}?\n"
	.string "Klingt gut. Ich werde es probieren.\p"
	.string "Und da ich weiß, dass dieser Rat von dir\n"
	.string "kommt, {PLAYER}{KUN}, werde ich auch eine\l"
	.string "Niederlage ertragen können.\p"
	.string "Ich hoffe, ich kann dich bald mal wieder\n"
	.string "um Rat fragen! Mach’s gut!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Bitte? Was sagst du denn da? Du hast\n"
	.string "mir doch schon einmal zu dem Item\l"
	.string "{STR_VAR_1} geraten.\p"
	.string "Oder meinst du damit, dass mein\n"
	.string "{STR_VAR_2} kein Item benötigt?$"

gText_ApprenticeWhatHeldItem5::
	.string "Hi, {PLAYER}{KUN}!\p"
	.string "Wir sind ja beide schwer beschäftigt\n"
	.string "und laufen uns doch ständig über den\l"
	.string "Weg.\p"
	.string "Heute betätige ich mich beim Hausputz\n"
	.string "sportlich.\p"
	.string "Ich hatte bisher keine Zeit, meinem\n"
	.string "{STR_VAR_1} etwas zu kaufen.\p"
	.string "Da ich kaum Zeit zum Suchen habe, frage\n"
	.string "ich dich, welches Item zum Tragen\l"
	.string "wohl für mein {STR_VAR_1} geeignet ist.$"

gText_ApprenticeHoldNothing5::
	.string "Oh, du meinst, mein {STR_VAR_1} benötigt\n"
	.string "kein Item?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Sehr schön. Dann brauche ich\n"
	.string "mich damit auch nicht weiter\l"
	.string "aufzuhalten.\p"
	.string "Vielen Dank! Man sieht sich!$"

gText_ApprenticeThanksHeldItem5::
	.string "Okay, dann werde ich mir die Zeit nehmen\n"
	.string "und das Item {STR_VAR_1} besorgen.\p"
	.string "Ich bin froh, dass ich dich als Mentor\n"
	.string "gefunden habe! Danke! Man sieht sich!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Bitte? Aber das mit dem {STR_VAR_1}\n"
	.string "weiß ich doch schon längst.\p"
	.string "Ach, jetzt verstehe ich! Du meinst\n"
	.string "damit, dass mein {STR_VAR_2} gar kein\l"
	.string "Item benötigt?$"

gText_ApprenticeWhatHeldItem6::
	.string "Hiya {PLAYER}! Ich bin’s! Ich brauche\n"
	.string "wieder dein Gehirnschmalz…\l"
	.string "Äh, deinen Rat!\p"
	.string "Trommelwirbel, bitte!\n"
	.string "Ich habe folgende Frage…\p"
	.string "Welches Item soll ich meinem\n"
	.string "{STR_VAR_1} zum Tragen geben?$"

gText_ApprenticeHoldNothing6::
	.string "Echt? Mein {STR_VAR_1} benötigt gar\n"
	.string "kein Item zum Tragen?$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Oh, genau das werde ich machen!\p"
	.string "Ich glaube, das ist alles, was ich heute\n"
	.string "von dir wissen will.\p"
	.string "Wir müssen uns bald mal wieder treffen!\n"
	.string "Danke und bis bald!$"

gText_ApprenticeThanksHeldItem6::
	.string "Oh hoooh! {STR_VAR_1}…\n"
	.string "Das ist echt cool!\l"
	.string "Das werde ich sofort ausprobieren!\p"
	.string "Ich glaube, das ist alles, was ich heute\n"
	.string "von dir wissen will.\p"
	.string "Wir müssen uns bald mal wieder treffen!\n"
	.string "Danke und bis bald!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahahahaha! Das ist ja witzig!\n"
	.string "Du hast mir bereits schon einmal zu\l"
	.string "{STR_VAR_1} geraten!\p"
	.string "Geht es dir auch wirklich gut, {PLAYER}?\p"
	.string "Ach, jetzt verstehe ich!!! Mein\n"
	.string "{STR_VAR_2} benötigt kein Item.\l"
	.string "Meinst du das damit?!?$"

gText_ApprenticeWhatHeldItem7::
	.string "Hallo, {PLAYER}. Ich hoffe, dir geht es\n"
	.string "gut!\p"
	.string "Darf ich dich um einen Rat bitten?\p"
	.string "In den letzten Kämpfen hatten meine\n"
	.string "Gegner ihren POKéMON immer Items\l"
	.string "gegeben, die diese dann hielten.\p"
	.string "Und deshalb wurde ich immer besiegt…\p"
	.string "Ich möchte auch mal siegen!\n"
	.string "Ich möchte meinem {STR_VAR_1} auch\l"
	.string "ein Item zum Tragen geben.\p"
	.string "Du würdest mir echt eine Freude machen,\n"
	.string "wenn du mir da einen Rat geben\l"
	.string "könntest. Welches Item ist richtig?$"

gText_ApprenticeHoldNothing7::
	.string "Mit anderen Worten… Mein POKéMON\n"
	.string "benötigt gar kein Item?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Jetzt wird es mir klar wie Kloßbrühe!\n"
	.string "Das werde ich ausprobieren!\p"
	.string "Vielen Dank, {PLAYER}!\p"
	.string "Ich hoffe, du stehst mir auch in\n"
	.string "Zukunft mit Rat und Tat zur Seite!\l"
	.string "Pass auf dich auf!$"

gText_ApprenticeThanksHeldItem7::
	.string "Dann soll es also {STR_VAR_1} sein!\n"
	.string "Ich werde das Item gleich bestellen!\p"
	.string "Vielen Dank, {PLAYER}!\p"
	.string "Ich hoffe, du stehst mir auch in\n"
	.string "Zukunft mit Rat und Tat zur Seite!\l"
	.string "Pass auf dich auf!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Du hast mir doch schon dazu geraten\n"
	.string "und ich habe das Item auch sofort\l"
	.string "besorgt.\p"
	.string "Oder meinst du damit… Mein POKéMON\n"
	.string "benötigt gar kein Item?$"

gText_ApprenticeWhatHeldItem8::
	.string "Iiihiii! {PLAYER}!!!\n"
	.string "Ich… Ich freu mich soooo sehr, dich\l"
	.string "wiederzusehen!\p"
	.string "Oh! Und ich muss dich unbedingt etwas\n"
	.string "Wichtiges fragen, {PLAYER}!\p"
	.string "Was soll ich meinem {STR_VAR_1} zum\n"
	.string "Tragen geben?$"

gText_ApprenticeHoldNothing8::
	.string "Oh! Diese Antwort hatte ich nicht\n"
	.string "erwartet! Ein Item ist also nicht nötig?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Alles klar! Dann werde ich ihm kein Item\n"
	.string "geben!\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um Rat fragen.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! Genau das nehme ich!\p"
	.string "Äh… {PLAYER}, kann es sein, dass deine\n"
	.string "POKéMON auch Items tragen?\p"
	.string "Ich werde mir das Item sofort besorgen.\n"
	.string "Ich hoffe, ich darf dich auch in\l"
	.string "Zukunft um Rat fragen.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Ach? Aber zu {STR_VAR_1} hast du mir\n"
	.string "schon einmal geraten.\p"
	.string "Ist das das beste Item zum Tragen?\n"
	.string "Oder meinst du damit, dass mein\l"
	.string "{STR_VAR_2} gar kein Item benötigt?$"

gText_ApprenticeWhatHeldItem9::
	.string "Holla… Äh… Hallo!\n"
	.string "Meister {PLAYER}{KUN}!\p"
	.string "Ich muss dich in einer dringenden\n"
	.string "POKéMON-Angelegenheit um Rat fragen.\p"
	.string "Was meinst du? Welches Item soll ich\n"
	.string "meinem {STR_VAR_1} zum Tragen geben?\p"
	.string "Sei ruhig ehrlich!\n"
	.string "Spuck’s einfach aus!$"

gText_ApprenticeHoldNothing9::
	.string "Echt? Du meinst, mein {STR_VAR_1} kann,\n"
	.string "auch ohne ein Item zu tragen, gewinnen?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Genua… Äh… Genau!\n"
	.string "Ich werde mein Bestes geben! Ohne Item.\p"
	.string "Sehr schön! Und vielen Dank!\n"
	.string "Mach’s tug… Äh… gut!$"

gText_ApprenticeThanksHeldItem9::
	.string "Ho… Äh… Oh! {STR_VAR_1}?\n"
	.string "Ich werde mir sofort dieses Item\l"
	.string "besorgen!\p"
	.string "Sehr schön! Und vielen Dank!\n"
	.string "Mach’s tug… Äh… gut!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "Nein, nein, nein! Zu {STR_VAR_1} hast\n"
	.string "du mir doch schon geraten!\p"
	.string "Ach, jetzt warte mal eine Sekunde…\n"
	.string "Du meinst, mein {STR_VAR_2} kann, auch\l"
	.string "ohne ein Item zu tragen, gewinnen?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, das wirst du nicht glauben!\n"
	.string "Etwas UNGLAUBLICHES ist passiert!!!\p"
	.string "Als ich morgens aufwachte, hatte mein\n"
	.string "POKéMON 10 NUGGETs!\p"
	.string "Natüüürlich ist das eine Lüge!!!\n"
	.string "Muahahahahaha!\p"
	.string "Ich denke darüber nach, welche Items\n"
	.string "meine POKéMON tragen sollen.\l"
	.string "Und das ist keine Lüge!\p"
	.string "Nun, dann entscheide du doch mal für\n"
	.string "mich, welches Item mein {STR_VAR_1}\l"
	.string "tragen soll.$"

gText_ApprenticeHoldNothing10::
	.string "Was soll das denn heißen?\n"
	.string "Ich soll ihm gar nichts geben?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Okay, es soll also nichts tragen. Na,\n"
	.string "dann besorge ich das doch gleich mal!\p"
	.string "Ha ha! Das war ein Witz!\n"
	.string "Ich werde deinem weisen Rat folgen,\l"
	.string "oh großer Leerer.\p"
	.string "Vielen Dank, Meister! Ich hoffe,\n"
	.string "du hilfst mir auch in Zukunft.$"

gText_ApprenticeThanksHeldItem10::
	.string "Okay, es soll also {STR_VAR_1} tragen.\n"
	.string "Na, dann werde ich das besser mal\l"
	.string "nicht kaufen!\p"
	.string "Ha ha! Das war ein Witz!\n"
	.string "Ich werde deinem weisen Rat folgen,\l"
	.string "oh großer Lehrer.\p"
	.string "Vielen Dank, Meister! Ich hoffe,\n"
	.string "du hilfst mir auch in Zukunft.$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Äh… Dazu hast du mir schon einmal\n"
	.string "geraten, oder nicht?\p"
	.string "Gibt es denn kein anderes Item?\p"
	.string "Oder meinst du damit, dass mein\n"
	.string "{STR_VAR_2} kein Item tragen soll?$"

gText_ApprenticeWhatHeldItem11::
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Ich bin ein MATROSE!\n"
	.string "Ich habe eine Frage, die\l"
	.string "wird dir zur Plage!\p"
	.string "Ein Problem mit einem Item,\n"
	.string "die Lösung kenn ich nicht bei weitem.\p"
	.string "Mein {STR_VAR_1} braucht etwas zu\n"
	.string "tragen, daher muss ich dich jetzt\l"
	.string "fragen.$"

gText_ApprenticeHoldNothing11::
	.string "Ist das denn auch richtig? Für mein\n"
	.string "{STR_VAR_1} sind Items nicht wichtig?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Verstanden, verstanden! Mein POKéMON\n"
	.string "wird auch so einen Sieg landen.\p"
	.string "{PLAYER}, auch in Zukunft, das ist klar,\n"
	.string "frag ich dich um Rat, das ist wahr.$"

gText_ApprenticeThanksHeldItem11::
	.string "Okay! {STR_VAR_1}!\n"
	.string "Das setze ich ein, das ist fein!\p"
	.string "{PLAYER}, auch in Zukunft, das ist klar,\n"
	.string "frag ich dich um Rat, das ist wahr.$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Okay! {STR_VAR_1}!\n"
	.string "Das hast du schon mal gesagt,\l"
	.string "keine neue Idee an dir nagt?\p"
	.string "Ist das denn auch richtig? Für mein\n"
	.string "POKéMON sind Items nicht wichtig?$"

gText_ApprenticeWhatHeldItem12::
	.string "Hey, du da! {PLAYER}!\n"
	.string "So sieht man sich also wieder!\p"
	.string "Und was soll ich jetzt machen? Na, da\n"
	.string "ich bereits mit dir rede, kann ich dich\l"
	.string "auch um einen Rat bitten.\p"
	.string "{PLAYER}, du bist doch nicht angenervt\n"
	.string "von mir? Neeee, das kann nicht sein…\p"
	.string "Also, darf ich dich was fragen?\n"
	.string "Ich brauche wirklich deinen Rat.\p"
	.string "Welches Item soll mein {STR_VAR_1}\n"
	.string "tragen?$"

gText_ApprenticeHoldNothing12::
	.string "Mein {STR_VAR_1} braucht kein Item?\n"
	.string "Gar keins?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Wenn du meinst, dass es kein Item\n"
	.string "benötigt, werde ich mich daran halten.\p"
	.string "Nun, {PLAYER}, dann vergiss mich nicht!\p"
	.string "Man sieht sich.$"

gText_ApprenticeThanksHeldItem12::
	.string "{STR_VAR_1} ist also dein Rat? Gut,\n"
	.string "dann werde ich mich daran halten.\p"
	.string "Nun, {PLAYER}, dann vergiss mich nicht!\p"
	.string "Man sieht sich.$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Hast du mir nicht vor kurzem auch zu\n"
	.string "{STR_VAR_1} geraten?\l"
	.string "Ich bin mir ziemlich sicher…\p"
	.string "Ich brauche aber etwas Neues!\n"
	.string "Oder braucht mein {STR_VAR_2} kein\l"
	.string "Item?$"

gText_ApprenticeWhatHeldItem13::
	.string "Auaaaa au au au! {PLAYER}{KUN}, mein Arm\n"
	.string "ist gebrochen! Nicht anfassen, bitte!\p"
	.string "Ich muss ihn mir gebrochen haben, als\n"
	.string "ich verschiedene Items ausprobierte,\l"
	.string "um sie meinen POKéMON zum Tragen \p"
	.string "zu geben. Das ist ein Notfall! Kannst\n"
	.string "du bitte für mich eine Entscheidung\l"
	.string "fällen?\p"
	.string "Welches Item könnte mein {STR_VAR_1}\n"
	.string "tragen, {PLAYER}{KUN}?$"

gText_ApprenticeHoldNothing13::
	.string "Auaaaa…\p"
	.string "Du bist überzeugt, mein {STR_VAR_1}\n"
	.string "benötigt kein Item?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Oh, das erleichtert mir einiges. Das ist\n"
	.string "in der momentanen Situation echt gut.\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um deinen Rat bitten?$"

gText_ApprenticeThanksHeldItem13::
	.string "Gut. {STR_VAR_1}. Der Arm meines\n"
	.string "POKéMON ist gesund, da kann ich das\l"
	.string "Item gleich meinem POKéMON geben.\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um deinen Rat bitten?$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "Oh, aber du hast mir doch früher schon\n"
	.string "mal etwas über {STR_VAR_1} gesagt,\l"
	.string "erinnerst du dich?\p"
	.string "Hast du keinen besseren Vorschlag für\n"
	.string "mich?\p"
	.string "Jetzt warte mal. Das soll doch nicht\n"
	.string "heißen, dass mein {STR_VAR_2} gar kein\l"
	.string "Item tragen soll, oder?$"

gText_ApprenticeWhatHeldItem14::
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Schau mich bitte nicht so an!\n"
	.string "Meine POKéMON haben keine Items.\p"
	.string "Das ist mir ja auch echt peinlich…\n"
	.string "Aber ich brauche dabei deinen Rat.\p"
	.string "Ich weiß nicht, welches Item ich meinem\n"
	.string "{STR_VAR_1} zum Tragen geben soll,\l"
	.string "damit es stark wird.\p"
	.string "Du weißt das doch bestimmt, oder,\n"
	.string "{PLAYER}{KUN}?$"

gText_ApprenticeHoldNothing14::
	.string "Oh… Du meinst, mein {STR_VAR_1}\n"
	.string "braucht kein Item zu tragen?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… Okay!\n"
	.string "Dann gebe ich ihm keines!\p"
	.string "Das ist dann aber echt Nerven\n"
	.string "zerreißend! Aber auch total cool!\p"
	.string "Vielen Dank, {PLAYER}{KUN}!\n"
	.string "Wenn wir uns wiedersehen, habe ich\l"
	.string "bestimmt eine neue Frage an dich.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… Okay!\n"
	.string "Ich gebe ihm {STR_VAR_1}.\p"
	.string "Das ist dann aber echt Nerven\n"
	.string "zerreißend! Aber auch total cool!\p"
	.string "Vielen Dank, {PLAYER}{KUN}!\n"
	.string "Wenn wir uns wiedersehen, habe ich\l"
	.string "bestimmt eine neue Frage an dich.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "A-aber das hast du mir doch schon mal\n"
	.string "gesagt.\p"
	.string "Bitte, speis mich nicht einfach so ab!\n"
	.string "Ich kann mit dieser Peinlichkeit nicht\l"
	.string "leben!\p"
	.string "Oh… Jetzt verstehe ich dich!\n"
	.string "Du meinst damit, dass mein {STR_VAR_2}\l"
	.string "gar kein Item benötigt?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hm… Du scheinst {PLAYER}{KUN} zu sein.\n"
	.string "Aber bist du es wirklich?\l"
	.string "Oder bist du ein Zwilling?\p"
	.string "Nein, nein, nein! Keine Angst!\n"
	.string "Wenn du wirklich {PLAYER} bist, dann\l"
	.string "verzeih bitte meine Ungehobeltheit!\p"
	.string "Ich würde dich gerne um einen Rat\n"
	.string "bitten.\p"
	.string "Ich habe hier mein {STR_VAR_1} und\n"
	.string "würde ihm gerne ein Item zum Tragen\l"
	.string "geben.\p"
	.string "Aber welches soll ich ihm bloß geben?$"

gText_ApprenticeHoldNothing15::
	.string "Es ist besser, wenn es kein Item trägt?\n"
	.string "Bist du dir da sicher?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Na, dann werde ich einfach deinem Rat\n"
	.string "folgen.\p"
	.string "Danke! Bis bald mal!$"

gText_ApprenticeThanksHeldItem15::
	.string "{STR_VAR_1}?\n"
	.string "Bist du sicher?\p"
	.string "Na, dann werde ich deinem Rat folgen.\n"
	.string "Ich danke dir für deine Zeit.\p"
	.string "Ich hoffe, mein POKéMON wird es gut\n"
	.string "zu nutzen wissen.\p"
	.string "Bis bald mal!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Nein, jetzt warte mal! Das hast du\n"
	.string "mir letztes Mal doch schon geraten!\p"
	.string "Ich möchte dich bitten, mir zu etwas\n"
	.string "anderem zu raten.\p"
	.string "Oder meinst du damit, dass mein\n"
	.string "{STR_VAR_2} kein Item benötigt?\l"
	.string "Bist du sicher?$"

gText_ApprenticeWhichMonFirst0::
	.string "Waaahaaa, {PLAYER}!\n"
	.string "Ich habe ein Problem… Heul, Jammer…\p"
	.string "Ich würde so gerne an Kämpfen\n"
	.string "teilnehmen, aber ich weiß nicht, was\l"
	.string "ich tun soll.\p"
	.string "In welcher Reihenfolge sollen meine\n"
	.string "POKéMON stehen, damit sie richtig\l"
	.string "stark sind?\p"
	.string "Bitte, hilf mir, {PLAYER}!\n"
	.string "Welches dieser POKéMON würdest du\l"
	.string "an die erste Stelle setzen?$"

gText_ApprenticeMonFirstThanks0::
	.string "Mein {STR_VAR_1} soll als erstes in den\n"
	.string "Kampf? Waaaahaaa… Schnüff…\p"
	.string "Oh, tut mir Leid!\n"
	.string "Du machst mich glücklich, weil du das\l"
	.string "erste POKéMON bestimmt hast. Heul…\p"
	.string "Vielen Dank! Schnüff… Heul…$"

gText_ApprenticeWhichMonFirst1::
	.string "Hey! Du bist es, {PLAYER}! Sehr gut!\n"
	.string "Ich wollte dich nämlich was fragen!\p"
	.string "Welches meiner POKéMON soll als\n"
	.string "Erstes in den Kampf gehen?$"

gText_ApprenticeMonFirstThanks1::
	.string "Mein {STR_VAR_1}?!? Wirklich?\n"
	.string "Okay, dann machen wir das so!\p"
	.string "Vielen Dank für deine Hilfe!$"

gText_ApprenticeWhichMonFirst2::
	.string "Hallo {PLAYER}!\p"
	.string "Ich finde, es ist wichtig, welches\n"
	.string "POKéMON im Kampf als Erstes antritt.\p"
	.string "Welches von meinen POKéMON soll\n"
	.string "ich als Erstes einsetzen?$"

gText_ApprenticeMonFirstThanks2::
	.string "Mein {STR_VAR_1} soll zuerst rausgehen?\n"
	.string "Okay, gut!\p"
	.string "Bis später dann!$"

gText_ApprenticeWhichMonFirst3::
	.string "Hallo, {PLAYER}…\n"
	.string "Ich muss dich schon wieder belästigen.\l"
	.string "Ich habe noch eine wichtige Frage.\p"
	.string "Ich habe nicht gerade viel\n"
	.string "Selbstvertrauen und wüsste echt nicht,\l"
	.string "was ich ohne dich machen würde.\p"
	.string "Vielleicht vergeude ich ja auch meine\n"
	.string "Zeit mit unnützen Gedanken, aber ich\l"
	.string "kann mich nicht entscheiden…\p"
	.string "Welches meiner POKéMON soll ich als\n"
	.string "Erstes im Kampf einsetzen?$"

gText_ApprenticeMonFirstThanks3::
	.string "Mein {STR_VAR_1}?\n"
	.string "Ah, ich verstehe!\p"
	.string "Ich wundere mich echt, dass ich dir\n"
	.string "nicht mit meinen ganzen Fragen auf die\l"
	.string "Nerven gehe!\p"
	.string "Ich bin dir so dankbar, dass du\n"
	.string "überhaupt mit mir sprichst…\p"
	.string "Vielen, vielen Dank!$"

gText_ApprenticeWhichMonFirst4::
	.string "Oh, {PLAYER}{KUN}! Ich bin’s!\n"
	.string "Ich bin froh, dich zu treffen, denn ich\l"
	.string "habe da ein Problem!\p"
	.string "Ich weiß nicht, wie ich meine POKéMON\n"
	.string "anordnen soll. Kannst du mir helfen?\p"
	.string "Du musst nicht alle neu anordnen. Sag\n"
	.string "mir nur, welches ich als Erstes im Kampf\p"
	.string "einsetzen soll. Ja, machst du das?$"

gText_ApprenticeMonFirstThanks4::
	.string "Mein {STR_VAR_1}? Großartig!\p"
	.string "Und da ich weiß, dass dieser Rat von dir\n"
	.string "kommt, {PLAYER}{KUN}, werde ich auch eine\l"
	.string "Niederlage ertragen können.\p"
	.string "Ich hoffe, ich kann dich bald mal wieder\n"
	.string "um Rat fragen! Mach’s gut!$"

gText_ApprenticeWhichMonFirst5::
	.string "Hi, {PLAYER}{KUN}, mein Lehrer!\n"
	.string "Auch heute bin ich immens beschäftigt!\p"
	.string "Ich muss Rad fahren, einkaufen und\n"
	.string "diverse andere Dinge erledigen.\p"
	.string "Ich habe noch nicht einmal die Zeit zu\n"
	.string "entscheiden, in welcher Reihenfolge ich\p"
	.string "meine POKéMON für den Kampf aufstellen\n"
	.string "soll.\p"
	.string "Kannst du dir nicht bitte mein Team\n"
	.string "anschauen und mir sagen, welches ich\l"
	.string "als Erstes im Kampf einsetzen soll?$"

gText_ApprenticeMonFirstThanks5::
	.string "Okay, verstanden. Wenigstens habe\n"
	.string "ich so viel Zeit, mein {STR_VAR_1} an die\l"
	.string "erste Stelle zu setzen!\p"
	.string "Hups, meine Freundin wartet bereits\n"
	.string "auf mich. Vielen Dank! Und tschüss!$"

gText_ApprenticeWhichMonFirst6::
	.string "Hiya {PLAYER}!\n"
	.string "Du siehst irgendwie immer stark aus.\p"
	.string "Du, ich brauche schon wieder dein\n"
	.string "Gehirnschmalz. Wie so üblich…\p"
	.string "Trommelwirbel, tadaa!\n"
	.string "Ich habe eine Frage zu meinem Team.\p"
	.string "Welches POKéMON soll ich als Erstes\n"
	.string "im Kampf einsetzen?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmmm…\n"
	.string "{STR_VAR_1}, meinst du?\l"
	.string "Das ist eine coole Entscheidung!\p"
	.string "Und damit hast du mein heutiges\n"
	.string "Problem gelöst.\p"
	.string "Wir müssen uns bald mal wieder treffen.\n"
	.string "Danke und bis bald!$"

gText_ApprenticeWhichMonFirst7::
	.string "Vielen Dank, dass du dir die Zeit nimmst,\n"
	.string "mit mir zu reden, {PLAYER}!\p"
	.string "Ich weiß, ich nutze deine\n"
	.string "Freundlichkeit aus, aber darf ich dich\l"
	.string "um einen Rat bitten?\p"
	.string "Könntest du mir helfen, die Reihenfolge\n"
	.string "meiner POKéMON festzulegen?\p"
	.string "Welches POKéMON soll ich im Kampf als\n"
	.string "Erstes einsetzen?$"

gText_ApprenticeMonFirstThanks7::
	.string "Mein {STR_VAR_1}! Dann setze ich das\n"
	.string "sofort an die erste Stelle!\l"
	.string "Vielen Dank, {PLAYER}!\p"
	.string "Ich hoffe, du stehst mir auch in\n"
	.string "Zukunft mit Rat und Tat zur Seite!\l"
	.string "Pass auf dich auf!$"

gText_ApprenticeWhichMonFirst8::
	.string "Iiihiii! {PLAYER}!!!\n"
	.string "Ich… Ich freu mich soooo sehr, dich\l"
	.string "wiederzusehen!\p"
	.string "Meine POKéMON sind mittlerweile\n"
	.string "viel, viel stärker geworden!\p"
	.string "Aber ich gewinne trotzdem nicht immer!\n"
	.string "Es liegt wohl an dem POKéMON, das ich\l"
	.string "als Erstes im Kampf einsetze? \p"
	.string "Bitte, {PLAYER}, ich brauche deine Hilfe!\p"
	.string "Welches POKéMON soll ich als Erstes\n"
	.string "im Kampf einsetzen?$"

gText_ApprenticeMonFirstThanks8::
	.string "Seufz… Mir ist vor Freude ganz\n"
	.string "schwindelig…\p"
	.string "Es ist wie in einem Traum. Du hast für\n"
	.string "mich entschieden, {PLAYER}.\p"
	.string "Und ich habe den Sinn verstanden.\n"
	.string "Ich werde mein {STR_VAR_1} an die erste\l"
	.string "Stelle setzen.\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um Rat fragen.$"

gText_ApprenticeWhichMonFirst9::
	.string "Holla… Äh… Hallo!\n"
	.string "Meister {PLAYER}{KUN}! Lass mich\l"
	.string "bitte an deiner Weisheit teilhaben!\p"
	.string "Schau, ich habe ein Team von drei\n"
	.string "POKéMON zusammengestellt.\p"
	.string "Aber ich weiß nicht, in welcher\n"
	.string "Reihenfolge ich sie kämpfen lassen soll.\p"
	.string "Und hier kommst du ins Spiel, {PLAYER}{KUN}!\n"
	.string "Du entscheidest das jetzt für mich!\p"
	.string "Und sei bloß nicht schüchtern.\n"
	.string "Spuck’s einfach aus!$"

gText_ApprenticeMonFirstThanks9::
	.string "Ah, mein {STR_VAR_1} hat die Nase vorn!\n"
	.string "Elassk… Äh… Klasse!\l"
	.string "Ich ändere die Reihenfolge sofort!\p"
	.string "Sehr schön! Und vielen Dank!\n"
	.string "Bis dalb… Äh… bald!$"

gText_ApprenticeWhichMonFirst10::
	.string "Hör mal, {PLAYER}{KUN}!\n"
	.string "Ich habe hier einen Notfall!\p"
	.string "Alle meine drei POKéMON gehen\n"
	.string "grundsätzlich ZUSAMMEN in einen Kampf.\l"
	.string "Alle auf einmal!!!\p"
	.string "Nee, das stimmt natürlich nicht!\n"
	.string "Muahahahahaha!\p"
	.string "Aber ich weiß nicht, in welcher\n"
	.string "Reihenfolge ich meine POKéMON setzen\l"
	.string "soll. Und das ist keine Lüge!\p"
	.string "Wie wäre es, wenn du für mich\n"
	.string "entscheidest, welches POKéMON ich als\l"
	.string "Erstes einsetzen soll?$"

gText_ApprenticeMonFirstThanks10::
	.string "Ah, mein {STR_VAR_1} soll also das\n"
	.string "Erste sein? Okay, dann setze ich ein\l"
	.string "anderes POKéMON an die erste Stelle.\p"
	.string "Hahahaha! Das war doch ein guter Witz!\n"
	.string "Äh, nicht?!? Okay, ich folge deinem Rat.\p"
	.string "Vielen Dank, Meister! Ich hoffe,\n"
	.string "du hilfst mir auch in Zukunft.$"

gText_ApprenticeWhichMonFirst11::
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Ich bin ein MATROSE!\n"
	.string "Ich habe eine Frage, die\l"
	.string "wird dir zur Plage!\p"
	.string "Ein Problem mit meinen POKéMON.\n"
	.string "Gib mir die Antwort, nun mach schon.\p"
	.string "Welches von diesen soll als Erstes\n"
	.string "in den Kampf düsen?$"

gText_ApprenticeMonFirstThanks11::
	.string "Ich habe verstanden! So soll es sein!\n"
	.string "Dieses wird das erste POKéMON sein.\p"
	.string "{PLAYER}, auch in Zukunft, das ist klar,\n"
	.string "frag ich dich um Rat, das ist wahr.$"

gText_ApprenticeWhichMonFirst12::
	.string "Hey, {PLAYER}!\n"
	.string "Wie geht’s denn so?\p"
	.string "Wie es mir geht? Ich überlege, ob\n"
	.string "ich dich um einen Rat anhauen soll.\l"
	.string "Ich habe da ein Problem!\l"
	.string "Dabei könntest du mir bestimmt helfen.\p"
	.string "Welches meiner POKéMON soll ich als\n"
	.string "Erstes im Kampf einsetzen?$"

gText_ApprenticeMonFirstThanks12::
	.string "Mein {STR_VAR_1}? Ja!\n"
	.string "Damit bin ich auf der sicheren Seite.\p"
	.string "Nun, {PLAYER}, dann vergiss mich nicht!\p"
	.string "Man sieht sich.$"

gText_ApprenticeWhichMonFirst13::
	.string "Auaaaa au au au! {PLAYER}{KUN}…\n"
	.string "Ich habe Bauchschmerzen… Auaaaaaa…\p"
	.string "Aber ich glaube, jetzt gerade wird es\n"
	.string "besser…\p"
	.string "Das liegt bestimmt daran, dass ich mir\n"
	.string "Gedanken gemacht habe, wie ich meine\l"
	.string "POKéMON anordnen soll.\p"
	.string "Aber jetzt bist du ja da. Welches\n"
	.string "POKéMON soll ich als Erstes im Kampf\l"
	.string "einsetzen? So dass ich sicher gewinne?$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, ja, gut.\n"
	.string "Mein {STR_VAR_1} wird das erste\l"
	.string "POKéMON sein.\p"
	.string "Ich schlag mir jetzt den Bauch voll\n"
	.string "und dann ordne ich die POKéMON\l"
	.string "neu an.\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um deinen Rat bitten?$"

gText_ApprenticeWhichMonFirst14::
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}?\l"
	.string "…\p"
	.string "Schau mich doch nicht immer so an.\n"
	.string "Du bringst mich ganz aus dem Konzept.\p"
	.string "Äh…\n"
	.string "Ich brauche deinen Rat…\p"
	.string "Es ist mir peinlich, aber ich weiß nicht,\n"
	.string "in welcher Reihenfolge ich meine drei\l"
	.string "POKéMON anordnen soll.\p"
	.string "Welches POKéMON soll ich als Erstes im\n"
	.string "Kampf einsetzen?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… Okay!\n"
	.string "Mein {STR_VAR_1} soll es also sein.\p"
	.string "Ich hoffe, ich werde mich nicht\n"
	.string "wieder blamieren.\p"
	.string "Vielen Dank, {PLAYER}{KUN}!\n"
	.string "Wenn wir uns wiedersehen, habe ich\l"
	.string "bestimmt eine neue Frage an dich.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm? Du bist {PLAYER}{KUN}?!?\n"
	.string "Bist du es wirklich? Nicht, dass ich hier\l"
	.string "einen Doppelgänger vor mir habe…\p"
	.string "Nein, nein, nein! Keine Angst!\n"
	.string "Wenn du wirklich {PLAYER} bist, dann\l"
	.string "verzeih bitte meine Dreistigkeit!\p"
	.string "Ich brauche deinen weisen Rat!\p"
	.string "Schau dir meine POKéMON an. Welches\n"
	.string "soll ich als Erstes im Kampf einsetzen?$"

gText_ApprenticeMonFirstThanks15::
	.string "Mein {STR_VAR_1}…\n"
	.string "Und du führst mich auch nicht an der\l"
	.string "Nase herum?\p"
	.string "Nein?!? Dann werde ich deinem Rat\n"
	.string "folgen. Vielen Dank, dass du mir etwas\l"
	.string "von deiner Zeit geschenkt hast.\p"
	.string "Ich bin, was ich bin und werde mein\n"
	.string "Bestes geben.\p"
	.string "Bis hoffentlich bald mal!$"

gText_ApprenticeWhichMon0::
	.string "Heul… Jammer… Schnüff…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Du kommst gerade recht!\n"
	.string "Ich kann mich nicht entscheiden…\p"
	.string "Ich kann mich nicht zwischen meinem\n"
	.string "{STR_VAR_1} und meinem {STR_VAR_2}\l"
	.string "entscheiden… Heul…\p"
	.string "Was meinst du, {PLAYER}, mit welchem\n"
	.string "habe ich die besten Chancen zu\l"
	.string "gewinnen?$"

gText_ApprenticeMonThanks0::
	.string "Heul… Jammer… Schnüff…\n"
	.string "Hihi, tut mir Leid… Du hast mich so froh\l"
	.string "gemacht, dass ich weinen muss… Heul…\p"
	.string "Ich werde mich anstrengen, ein\n"
	.string "{STR_VAR_1} zu fangen!\p"
	.string "Vielen Dank! Waaahaa… Heul…$"

gText_ApprenticeWhichMon1::
	.string "Hey, du bist es, {PLAYER}!\n"
	.string "Gut, dass du hier bist. Ich brauche mal\l"
	.string "wieder deinen Rat!\p"
	.string "Ich bin schon ganz konfus… Soll ich\n"
	.string "mein {STR_VAR_1} oder mein {STR_VAR_2}\l"
	.string "einsetzen…\p"
	.string "Welches soll ich aufziehen und stärker\n"
	.string "machen, {PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Mein {STR_VAR_1} ist also besser?\n"
	.string "Gut, dann weiß ich, was ich machen muss.\p"
	.string "Vielen Dank für deinen Rat!$"

gText_ApprenticeWhichMon2::
	.string "Hallo {PLAYER}!\n"
	.string "Ich habe ein Frage an dich.\p"
	.string "Ich weiß nicht, ob ich ein {STR_VAR_1}\n"
	.string "oder ein {STR_VAR_2} fangen soll.\p"
	.string "Welches der beiden wird wohl das\n"
	.string "Stärkere werden?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} meinst du?\n"
	.string "Ja.\p"
	.string "Ich werde mir sofort ein starkes\n"
	.string "{STR_VAR_1} fangen!\p"
	.string "Bis später dann!$"

gText_ApprenticeWhichMon3::
	.string "Hallo {PLAYER}…\p"
	.string "Du weißt bestimmt nicht mehr, wer ich\n"
	.string "bin…\p"
	.string "Aber das macht nichts… Solange\n"
	.string "du mir trotzdem einen Rat gibst…\p"
	.string "Ich weiß nicht, welches POKéMON ich\n"
	.string "aufziehen soll…\p"
	.string "Ich kann mich nicht zwischen einem\n"
	.string "{STR_VAR_1} oder einem {STR_VAR_2}\l"
	.string "entscheiden…\p"
	.string "Ich weiß, ich nerve, {PLAYER}… Aber\n"
	.string "kannst du mir nicht doch helfen?$"

gText_ApprenticeMonThanks3::
	.string "Aber wird ein wildes {STR_VAR_1} mich \n"
	.string "überhaupt bemerken?\p"
	.string "Ich versuche es!\p"
	.string "Auch wenn ich niemals eines fangen\n"
	.string "werde… Ich werde mich anstrengen!\p"
	.string "Vielen, vielen Dank!$"

gText_ApprenticeWhichMon4::
	.string "Bin ich froh, dich zu sehen, {PLAYER}{KUN}!\n"
	.string "Ich habe dich schon gesucht!\p"
	.string "Ich weiß nicht, welches POKéMON ich\n"
	.string "fangen soll.\p"
	.string "Was hältst du von einem {STR_VAR_1}\n"
	.string "oder einem {STR_VAR_2}?\p"
	.string "Welches ist deiner Meinung nach\n"
	.string "besser?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? Das ist ja großartig!\p"
	.string "Und da ich weiß, dass dieser Rat von dir\n"
	.string "kommt, {PLAYER}{KUN}, werde ich auch eine\l"
	.string "Niederlage ertragen können.\p"
	.string "Ich hoffe, ich kann dich bald mal wieder\n"
	.string "um Rat fragen! Mach’s gut!$"

gText_ApprenticeWhichMon5::
	.string "Wenn das nicht {PLAYER}{KUN} ist. Wie geht’s?\n"
	.string "Ich bin wie immer schwer im Stress!\p"
	.string "Ich möchte auch mit POKéMON gut sein,\n"
	.string "aber ich weiß nicht, welche ich fangen\l"
	.string "soll.\p"
	.string "{STR_VAR_1} sieht stark aus, meinst\n"
	.string "du nicht? Aber {STR_VAR_2} ist auch\l"
	.string "nicht so ohne.\p"
	.string "Gib mir bitte einen Rat, {PLAYER}{KUN}!\n"
	.string "Welches soll ich fangen?$"

gText_ApprenticeMonThanks5::
	.string "Verstanden!\n"
	.string "Ich werde die Zeit finden, ein\l"
	.string "{STR_VAR_1} zu fangen!\p"
	.string "Ich bin froh, dass du mein Mentor bist!\p"
	.string "Vielen Dank! Man sieht sich!$"

gText_ApprenticeWhichMon6::
	.string "Hey! Da ist ja {PLAYER}!\p"
	.string "Ich habe nicht viel Zeit damit\n"
	.string "verbracht, vor meinen Freunden zu\l"
	.string "prahlen, dass ich dich kenne.\p"
	.string "Ich brauche heute wieder dein\n"
	.string "Köpfchen. Diesmal wird es einfach für\l"
	.string "dich!\p"
	.string "Trommelwirbel, bitte!\n"
	.string "Meine Frage lautet…\p"
	.string "Wenn ich ein POKéMON fangen will und ich\n"
	.string "die Wahl zwischen einem {STR_VAR_1} und\p"
	.string "einem {STR_VAR_2} habe, welches nehme\n"
	.string "ich?$"

gText_ApprenticeMonThanks6::
	.string "Aaah!\n"
	.string "Das {STR_VAR_1} also!\l"
	.string "Vielen Dank für deine coole Antwort!\p"
	.string "Ich glaube, das ist alles, was ich heute\n"
	.string "von dir wissen will.\p"
	.string "Wir müssen uns bald mal wieder treffen!\n"
	.string "Danke und bis bald!$"

gText_ApprenticeWhichMon7::
	.string "Du bist das, {PLAYER}!\n"
	.string "Schön, dich wiederzusehen!\p"
	.string "Seit ich deine Schülerin bin, bin\n"
	.string "ich viel selbstbewusster geworden!\p"
	.string "Ich glaube, ich bin so weit, ein eigenes\n"
	.string "POKéMON aufzuziehen.\p"
	.string "{PLAYER}, würdest du mir sagen, welches\n"
	.string "ich aufziehen soll?\p"
	.string "Ein {STR_VAR_1} oder ein {STR_VAR_2}?\n"
	.string "Welches ist das richtige POKéMON\l"
	.string "für mich?$"

gText_ApprenticeMonThanks7::
	.string "Ein {STR_VAR_1}!\n"
	.string "Ich werde mir sofort eines fangen!\p"
	.string "Vielen Dank, {PLAYER}.\p"
	.string "Ich hoffe, du stehst mir auch in\n"
	.string "Zukunft mit Rat und Tat zur Seite!\l"
	.string "Pass auf dich auf!$"

gText_ApprenticeWhichMon8::
	.string "Iiihiii! {PLAYER}! So trifft man sich\n"
	.string "wieder! Ich bin ja so glücklich…\p"
	.string "Ja, ja, ja! Ich weiß! Diese Chance muss\n"
	.string "ich einfach wahrnehmen!\p"
	.string "Darf ich dich um etwas bitten, {PLAYER}?\n"
	.string "Bitte wähle ein POKéMON für mich aus.\p"
	.string "Welches ist besser? Ein {STR_VAR_1}\n"
	.string "oder ein {STR_VAR_2}?$"

gText_ApprenticeMonThanks8::
	.string "Wow! Du hast mir geholfen!\n"
	.string "Ich werde ein {STR_VAR_1} aufziehen,\l"
	.string "so gut ich eben kann!\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um Rat fragen.$"

gText_ApprenticeWhichMon9::
	.string "Hey, hey!\n"
	.string "Mein Lehrer, {PLAYER}{KUN}!\p"
	.string "Ich brauche wieder deinen weisen Tar…\n"
	.string "Äh… Rat!\p"
	.string "Welches POKéMON passt zu mir? Ein \n"
	.string "{STR_VAR_1} oder ein {STR_VAR_2}?\p"
	.string "Nur nicht schüchtern. Spuck’s aus!$"

gText_ApprenticeMonThanks9::
	.string "Ein {STR_VAR_1}…\n"
	.string "Gut, ich nehme einen Lalb… Äh… Ball und\l"
	.string "dann… zack!\p"
	.string "Sehr schön! Vielen Dank!\n"
	.string "Wir sehen snu… Äh… uns!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}! Stell dir das mal vor!!!\n"
	.string "Ich habe ein unsichtbares POKéMON\l"
	.string "gefangen!!!\p"
	.string "Nee, ich erzähl schon wieder eine\n"
	.string "Lügengeschichte! Muahahahaha!\p"
	.string "Ich bin nicht gut im Fangen von\n"
	.string "POKéMON. Und das ist leider die\l"
	.string "Wahrheit.\p"
	.string "Meister, kannst du mir nicht sagen,\n"
	.string "welches POKéMON ich fangen soll?\p"
	.string "Ein {STR_VAR_1} oder ein {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Du würdest ein {STR_VAR_1} fangen?\n"
	.string "Gut, dann fange ich das andere!\p"
	.string "Hahaha! Du bist drauf reingefallen!\n"
	.string "Ich werde deinem Rat folgen!\p"
	.string "Vielen Dank, Meister! Ich hoffe,\n"
	.string "du hilfst mir auch in Zukunft.$"

gText_ApprenticeWhichMon11::
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Ich bin ein MATROSE!\n"
	.string "Du erinnerst dich an mich?\p"
	.string "Ich habe eine Frage, die\n"
	.string "wird dir zur Plage!\p"
	.string "{STR_VAR_1} oder {STR_VAR_2}?\n"
	.string "Welches ist das richtige?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}?\n"
	.string "Das werd ich mir fangen.\p"
	.string "{PLAYER}, auch in Zukunft, das ist klar,\n"
	.string "frag ich dich um Rat, das ist wahr.$"

gText_ApprenticeWhichMon12::
	.string "Hey, wenn das nicht {PLAYER} ist!\p"
	.string "Und wieder stellt sich mir die Frage, Rat\n"
	.string "holen oder nicht? Dabei rede ich doch\l"
	.string "bereits mit dir.\p"
	.string "Es ist ja schon lange her, aber\n"
	.string "ich tue so, als sei es gestern gewesen\l"
	.string "und frage dich direkt.\p"
	.string "Welches POKéMON soll ich fangen?\n"
	.string "Ein {STR_VAR_1} oder ein {STR_VAR_2}?$"

gText_ApprenticeMonThanks12::
	.string "Du hältst das {STR_VAR_1} für das\n"
	.string "bessere POKéMON? Okay!\p"
	.string "Nun, {PLAYER}, dann vergiss mich nicht!\p"
	.string "Man sieht sich.$"

gText_ApprenticeWhichMon13::
	.string "Oh, hallo {PLAYER}{KUN}…\n"
	.string "Diesmal habe ich Kopfschmerzen, und\l"
	.string "frag nicht wie!\p"
	.string "Ich zerbreche mir nämlich gerade den\n"
	.string "Kopf darüber, welches POKéMON ich \l"
	.string "aufziehen soll.\p"
	.string "Kannst du das nicht für mich\n"
	.string "entscheiden?\p"
	.string "Ein {STR_VAR_1} oder ein {STR_VAR_2}?\n"
	.string "Welches würdest du an meiner Stelle\l"
	.string "fangen?$"

gText_ApprenticeMonThanks13::
	.string "Ein {STR_VAR_1}.\n"
	.string "Sobald es mir besser geht, werde ich\l"
	.string "eines suchen.\p"
	.string "Ich hoffe, ich darf dich auch das\n"
	.string "nächste Mal um Hilfe anhauen.$"

gText_ApprenticeWhichMon14::
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Du schaust mich schon wieder so an,\n"
	.string "dass ich ganz verlegen werde…\l"
	.string "Und ich brauche doch deinen Rat…\p"
	.string "Es ist mir mehr als peinlich… Aber ich\n"
	.string "kann mich bei den POKéMON nicht\l"
	.string "entscheiden…\p"
	.string "{STR_VAR_1} oder {STR_VAR_2}… Welches\n"
	.string "soll ich nehmen?$"

gText_ApprenticeMonThanks14::
	.string "Oh… Okay!\n"
	.string "Dann werde ich ein {STR_VAR_1} fangen.\p"
	.string "Ich hoffe, ich blamiere mich dabei\n"
	.string "nicht…\p"
	.string "Vielen Dank, {PLAYER}{KUN}!\n"
	.string "Wenn wir uns wiedersehen, habe ich\l"
	.string "bestimmt eine neue Frage an dich.$"

gText_ApprenticeWhichMon15::
	.string "Du scheinst {PLAYER}{KUN} zu sein.\n"
	.string "Aber bist du wirklich echt?\p"
	.string "Wenn du echt bist, ist alles in Ordnung.\n"
	.string "Dann würde ich dich gerne um Rat\l"
	.string "fragen.\p"
	.string "Es geht um POKéMON, die ich aufziehen\n"
	.string "möchte.\p"
	.string "Wäre ein {STR_VAR_1} oder ein\n"
	.string "{STR_VAR_2} besser für mich?$"

gText_ApprenticeMonThanks15::
	.string "Ein {STR_VAR_1}?\n"
	.string "Du bist dir da ganz sicher?\p"
	.string "Dann ist es ja gut.\n"
	.string "Ich danke dir für deine kostbare Zeit.\p"
	.string "Da werde ich ganz gelassen rangehen\n"
	.string "können.\p"
	.string "Danke! Bis bald mal!$"

gText_ApprenticeWhichMove0::
	.string "Waaaahaaa! Oh, {PLAYER}!\n"
	.string "Schnüff… Hick… Hick…\p"
	.string "Ich habe ein Problem… Waaahaaa…\n"
	.string "Welche Attacke soll ich meinem\l"
	.string "{STR_VAR_1} beibringen… Heul…\p"
	.string "Bitte, bitte, {PLAYER}.\n"
	.string "Kannst du mir das nicht sagen?\p"
	.string "Soll ich meinem {STR_VAR_1}\n"
	.string "{STR_VAR_2} oder {STR_VAR_3}\l"
	.string "beibringen?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaahaaa… Hick…\p"
	.string "Oh, tut mir Leid… Hick…\n"
	.string "Du hast mich mit deiner Entscheidung…\p"
	.string "Hick… so glücklich gemacht, dass\n"
	.string "ich weinen muss… Schnüff…\p"
	.string "Schnüff… Hick…\n"
	.string "Vielen… Hick… Dank! Hick…$"

gText_ApprenticeWhichMove1::
	.string "Hi {PLAYER}!\n"
	.string "Ich brauche mal wieder deine Hilfe.\p"
	.string "Ich möchte meinem {STR_VAR_1} eine\n"
	.string "coole Attacke beibringen.\p"
	.string "Entweder {STR_VAR_2} oder\n"
	.string "{STR_VAR_3}. Aber welche soll ich\l"
	.string "nehmen? Sag du es mir.$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} ist besser? Das dachte\n"
	.string "ich mir. Ich werde deinem Rat folgen.\p"
	.string "Sobald wir uns hier wieder treffen,\n"
	.string "musst du mir unbedingt was Neues\l"
	.string "beibringen.$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, hallo!\n"
	.string "Es geht um mein {STR_VAR_1}. Ich habe\l"
	.string "Probleme mit seinen Attacken.\p"
	.string "Ich habe die Attacken {STR_VAR_2}\n"
	.string "und {STR_VAR_3} zur Auswahl.\p"
	.string "Aber welche ist die bessere für\n"
	.string "mein {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} meinst du?\n"
	.string "Okay, einverstanden.\p"
	.string "Ich werde meinem POKéMON gleich\n"
	.string "{STR_VAR_1} beibringen!\p"
	.string "Bis später dann!$"

gText_ApprenticeWhichMove3::
	.string "Ooooh, {PLAYER}…\n"
	.string "Ich bin ein hoffnungsloser Fall! Echt!\p"
	.string "Da habe ich mich entschlossen, ein\n"
	.string "POKéMON aufzuziehen und nun weiß\p"
	.string "ich nicht, welche Attacke ich ihm\n"
	.string "beibringen soll…\p"
	.string "Für dich ist das sicher kein Problem,\n"
	.string "{PLAYER}.\p"
	.string "Aber für mich schon…\p"
	.string "Bitte, {PLAYER}, kannst du nicht eine\n"
	.string "Attacke für mein {STR_VAR_1}\l"
	.string "aussuchen?\p"
	.string "Wir haben die Wahl zwischen\n"
	.string "{STR_VAR_2} und {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "Ich verstehe!\p"
	.string "Aber wird es {STR_VAR_1} auch mögen?\n"
	.string "Ach, ich werde mein Bestes geben!\p"
	.string "Vielen Dank!$"

gText_ApprenticeWhichMove4::
	.string "{PLAYER}{KUN}!\n"
	.string "Wir treffen uns immer im richtigen\l"
	.string "Augenblick.\p"
	.string "Ich frage mich gerade, welche Attacke\n"
	.string "zu meinem {STR_VAR_1} passen würde.\p"
	.string "Kannst du mir helfen? Kannst du das\n"
	.string "für mich entscheiden?\p"
	.string "Wir müssen zwischen {STR_VAR_2} und\n"
	.string "{STR_VAR_3} wählen.\l"
	.string "Welche ist besser geeignet?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? Spitze!\p"
	.string "Und da ich weiß, dass dieser Rat von dir\n"
	.string "kommt, {PLAYER}{KUN}, werde ich auch eine\l"
	.string "Niederlage ertragen können.\p"
	.string "Ich hoffe, ich kann dich bald mal wieder\n"
	.string "um Rat fragen! Mach’s gut!$"

gText_ApprenticeWhichMove5::
	.string "Wie kommt es, dass immer alles in Stress\n"
	.string "ausarten muss?\l"
	.string "Hey, wenn das nicht {PLAYER}{KUN} ist?!?\p"
	.string "Seit ich aufgestanden bin, bin ich\n"
	.string "beschäftigt. Joggen, Schwimmen und\l"
	.string "Kochen!\p"
	.string "Du glaubst gar nicht, wie viel ich immer\n"
	.string "zu tun habe!\p"
	.string "Ich habe noch nicht einmal Zeit zu\n"
	.string "entscheiden, welche Attacke mein\l"
	.string "{STR_VAR_1} lernen soll.\p"
	.string "{STR_VAR_2} wäre eine Möglichkeit.\n"
	.string "Aber auch {STR_VAR_3} ist gut.\p"
	.string "{PLAYER}{KUN}, bitte entscheide du für\n"
	.string "mich!$"

gText_ApprenticeMoveThanks5::
	.string "Okay, okay! Ich werde mir die Zeit\n"
	.string "nehmen und ihm die Attacke\l"
	.string "beibringen… Wenn ich Zeit habe…\p"
	.string "Ich bin froh, einen Mentor wie dich zu\n"
	.string "haben! Vielen Dank! Man sieht sich!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Was habe ich wieder für ein Glück!\n"
	.string "Da treffe ich dich, {PLAYER}, genau dann,\l"
	.string "wenn ich dein Gehirnschmalz brauche!\p"
	.string "Trommelwirbel, bitte!\n"
	.string "Hier kommt meine Frage…\p"
	.string "Welche Attacke eignet sich für mein\n"
	.string "{STR_VAR_1}? {STR_VAR_2} oder\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Aahaa!\n"
	.string "{STR_VAR_1}!\l"
	.string "Vielen Dank für die schnelle Antwort.\p"
	.string "Ich glaube, das ist alles, was ich heute\n"
	.string "von dir wissen will.\p"
	.string "Wir müssen uns bald mal wieder treffen!\n"
	.string "Danke und bis bald!$"

gText_ApprenticeWhichMove7::
	.string "Hallo, {PLAYER}!\n"
	.string "Ich hoffe, dir geht es gut?\p"
	.string "Ich brauche wieder deinen Rat…\n"
	.string "Es geht um mein geliebtes {STR_VAR_1}.\p"
	.string "Welche Attacke wird es mögen?\n"
	.string "{STR_VAR_2} oder {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1}!\n"
	.string "Die werde ich ihm gleich beibringen.\p"
	.string "Vielen Dank, {PLAYER}.\p"
	.string "Ich hoffe, du stehst mir auch in\n"
	.string "Zukunft mit Rat und Tat zur Seite!\l"
	.string "Pass auf dich auf!$"

gText_ApprenticeWhichMove8::
	.string "Iihiii! {PLAYER}! {PLAYER}!\n"
	.string "Oh… Ich bin außer mir vor Freude, dich\l"
	.string "hier zu treffen!\p"
	.string "Immer wenn ich dich brauche, bist du\n"
	.string "auch schon da, {PLAYER}!\p"
	.string "Du musst mir heute bei den Attacken\n"
	.string "helfen!\p"
	.string "Ich will eine für mein {STR_VAR_1}\n"
	.string "auswählen.\p"
	.string "Aber welche? {STR_VAR_2} oder\n"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Oh oh oh! Vielen Dank!\n"
	.string "{STR_VAR_1} soll es sein!\l"
	.string "Die ist bestimmt perfekt!\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um Rat fragen.$"

gText_ApprenticeWhichMove9::
	.string "Guten Gat… Äh… Tag, {PLAYER}{KUN}!\n"
	.string "Darf ich auch heute an deiner Weisheit\l"
	.string "teilhaben?\p"
	.string "Welche ist die richtige Attacke für mein\n"
	.string "{STR_VAR_1}?\p"
	.string "Ich will doch immer newinneg…\n"
	.string "Äh… gewinnen!\p"
	.string "Also? {STR_VAR_2} oder\n"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "{STR_VAR_1}!\n"
	.string "Ykao… Äh… Okay!\l"
	.string "Das werde ich ihm zack zack beibringen.\p"
	.string "Und dir wie immer vielen Dank!\n"
	.string "Udiea… Äh… Adieu!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, dies hier ist komplett\n"
	.string "verrückt!\p"
	.string "Mein POKéMON!\n"
	.string "Es hat SECHS Attacken gelernt!!!\p"
	.string "Muahahahaha!\n"
	.string "Nee, das war dick gelogen!\p"
	.string "Ich bin, und das ist die Wahrheit, nicht\n"
	.string "gut in der Wahl von Attacken.\p"
	.string "Kannst du nicht für mich entscheiden,\n"
	.string "welche ich ihm beibringen soll?\p"
	.string "{STR_VAR_2} oder {STR_VAR_3}?\n"
	.string "Was meinst du?$"

gText_ApprenticeMoveThanks10::
	.string "{STR_VAR_1}? Mmmmh…\n"
	.string "Dann bringe ich ihm die andere\l"
	.string "Attacke bei!!!\p"
	.string "Nee, das war doch wieder nur ein Witz!\n"
	.string "Nimm nicht immer alles so ernst!\p"
	.string "Vielen Dank, Meister! Ich hoffe, du\n"
	.string "hilfst mir auch in Zukunft.$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Ich bin ein MATROSE.\n"
	.string "Habe ein Problem, das an mir klebt\l"
	.string "wie Lehm.\p"
	.string "Ich habe eine Frage, die\n"
	.string "wird dir zur Plage!\p"
	.string "{STR_VAR_2} oder {STR_VAR_3}?\n"
	.string "Welche Attacke ist gut für\l"
	.string "mein {STR_VAR_1}?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}!\n"
	.string "Das werde ich ihm beibringen.\p"
	.string "{PLAYER}, auch in Zukunft, das ist klar,\n"
	.string "frag ich dich um Rat, das ist wahr.$"

gText_ApprenticeWhichMove12::
	.string "Oh, {PLAYER}!\p"
	.string "Da ich dich jetzt bereits angequatscht\n"
	.string "habe, kann ich dir auch eine Frage\l"
	.string "stellen.\p"
	.string "{PLAYER}, überrasch mich mit deiner\n"
	.string "Weisheit.\p"
	.string "Mein {STR_VAR_1} - welche Attacke soll\n"
	.string "es lernen? {STR_VAR_2} oder\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks12::
	.string "{STR_VAR_1} ist also die beste\n"
	.string "Attacke.\p"
	.string "Nun, {PLAYER}, dann vergiss mich nicht!\p"
	.string "Man sieht sich.$"

gText_ApprenticeWhichMove13::
	.string "Hatschi… Hust… Schniiief…\n"
	.string "Ich habe diese doofe Erkältung…\p"
	.string "Ich möchte meinem POKéMON eine\n"
	.string "Attacke beibringen, aber ich weiß nicht,\l"
	.string "welche…\p"
	.string "Und wie die Dinge so stehen, musst du\n"
	.string "das für mich entscheiden.\p"
	.string "Mein {STR_VAR_1}… Soll es {STR_VAR_2}\n"
	.string "oder {STR_VAR_3} lernen?$"

gText_ApprenticeMoveThanks13::
	.string "{STR_VAR_1}, also gut. Hust…\n"
	.string "Sobald es mir besser geht, werde ich ihm\l"
	.string "die beibringen. Schniiief… Hust…\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um deinen Rat bitten?$"

gText_ApprenticeWhichMove14::
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Schau mich nicht so an…\n"
	.string "Ich bin schon verlegen genug…\l"
	.string "Dabei brauche ich doch deine Hilfe…\p"
	.string "Es ist eine peinliche Angelegenheit,\n"
	.string "aber ich kann mich nicht entscheiden,\p"
	.string "welche Attacke ich meinem POKéMON\n"
	.string "beibringen soll.\l"
	.string "Ich meine mein {STR_VAR_1}…\p"
	.string "{STR_VAR_2} oder {STR_VAR_3}?\n"
	.string "Welche ist besser?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… Okay!\n"
	.string "Ich werde es mit {STR_VAR_1}\l"
	.string "versuchen.\p"
	.string "Ich hoffe nur, ich kann ihm das auch\n"
	.string "beibringen…\l"
	.string "Das macht mich ganz nervös…\p"
	.string "Vielen Dank, {PLAYER}{KUN}!\n"
	.string "Wenn wir uns wiedersehen, habe ich\l"
	.string "bestimmt eine neue Frage an dich.$"

gText_ApprenticeWhichMove15::
	.string "Hm? Bist du {PLAYER}{KUN} oder bist du\n"
	.string "es nicht?\p"
	.string "Vielleicht bist du ja eine Marionette?\p"
	.string "Wenn du echt bist, ist alles in Ordnung.\n"
	.string "Du brauchst nicht gleich wütend zu\l"
	.string "werden.\p"
	.string "Ich brauche nämlich wieder deinen Rat.\n"
	.string "Es geht um mein {STR_VAR_1}.\p"
	.string "Soll ich ihm {STR_VAR_2} oder\n"
	.string "{STR_VAR_3} beibringen?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Und da gibt es keinen Zweifel dran?\p"
	.string "Nun, dann ist es ja gut.\n"
	.string "Vielen Dank für deine Zeit.\p"
	.string "Ich hoffe, mein POKéMON ist in der\n"
	.string "Lage, die Attacke zu lernen…\p"
	.string "Bis bald mal!$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… {PLAYER}?\n"
	.string "Es ist tatsächlich {PLAYER}!\l"
	.string "Heul… Jammer… Schnüff…\p"
	.string "Wenn ich kämpfe, bin ich immer so\n"
	.string "nervös, dass ich in Tränen ausbreche…\l"
	.string "Selbst wenn ich gewinne, weine ich…\p"
	.string "Heul… Dabei würde ich gerne mal was\n"
	.string "Cooles sagen, wenn ich gewinne…\l"
	.string "Jammer… Schnüff…\p"
	.string "Bitte, {PLAYER}! Was kann ich Cooles\n"
	.string "sagen, anstatt zu weinen? \l"
	.string "Heul… Jammer… Schnüff…$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Klasse! Spitze! Fantastisch!\n"
	.string "Das ist wirklich cool!\p"
	.string "Heul… Jammer… Tut mir Leid…\n"
	.string "Ich bin glücklich, daher weine ich…\l"
	.string "Heul…\p"
	.string "Schnüff… {PLAYER}!\n"
	.string "Vielen, vielen Dank!\p"
	.string "Ich werde mich für dich anstrengen,\n"
	.string "{PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "Das nächste Mal… sollten wir\l"
	.string "gegeneinander kämpfen!$"

gText_ApprenticePickWinSpeech1::
	.string "Hui! {PLAYER}! Hallo!\n"
	.string "Ich muss dich wieder etwas fragen!\p"
	.string "Ich möchte etwas wirklich Cooles sagen,\n"
	.string "wenn ich gewinne.\p"
	.string "Weißt du nicht, was ich sagen könnte?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Wow! Das ist echt cool!!!\n"
	.string "Das werde ich sagen!\p"
	.string "Vielen Dank für deinen Rat und deine\n"
	.string "Geduld, die du immer mit mir hast.\p"
	.string "Ich werde mich anstrengen, egal,\n"
	.string "wohin ich gehe!\p"
	.string "Das nächste Mal, wenn wir uns sehen,\n"
	.string "dann frage ich dich nicht um Rat,\l"
	.string "sondern fordere dich zum Kampf heraus.$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}! Hallo!\p"
	.string "Meine POKéMON sind zu allem bereit.\n"
	.string "Aber eine Sache ist noch offen.\p"
	.string "Ich würde gerne etwas Tolles rufen,\n"
	.string "wenn ich gewonnen habe!\p"
	.string "Fällt dir nicht etwas Tolles ein?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "Cool…\n"
	.string "Das passt zu mir!\p"
	.string "Ich werde jetzt überall in Kämpfen\n"
	.string "antreten.\p"
	.string "Und wer weiß? Vielleicht kämpfen wir\n"
	.string "auch bald gegeneinander, {PLAYER}?\p"
	.string "Nächstes Mal werde ich dich\n"
	.string "herausfordern.$"

gText_ApprenticePickWinSpeech3::
	.string "Hallo, {PLAYER}…\n"
	.string "Ich bin ein hoffnungsloser Fall, ich\l"
	.string "muss dich schon wieder nerven…\p"
	.string "Sogar wenn ich… Wenn ich gewinne,\n"
	.string "fehlen mir die Worte… Ich würde\l"
	.string "dann gerne etwas Besonderes sagen…\p"
	.string "Dir bedeutet das vielleicht nichts,\n"
	.string "{PLAYER}…\p"
	.string "Aber mir bedeutet es sehr viel…\p"
	.string "Bitte, {PLAYER}, was soll ich sagen, wenn\n"
	.string "ich einen Kampf gewinne?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "Das ist inspirierend…\p"
	.string "Und… Äh… Ist das auch wirklich in\n"
	.string "Ordnung, wenn jemand wie ich das sagt?\p"
	.string "Ja! Ich werde von nun an mein\n"
	.string "Bestes geben!\p"
	.string "{PLAYER}, ich danke dir für die Geduld,\n"
	.string "die du mit mir hattest…\p"
	.string "Ich bin sicher, jemanden wie mich wirst\n"
	.string "du schnell vergessen, aber wir müssen\l"
	.string "uns trotzdem bald mal wieder treffen!$"

gText_ApprenticePickWinSpeech4::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Ich muss etwas mit dir besprechen.\p"
	.string "Ich weiß, ich komme nicht immer nett\n"
	.string "und freundlich rüber…\p"
	.string "Und wenn ich gewinne, wirke ich, glaube\n"
	.string "ich, ganz schön arrogant…\p"
	.string "Ich möchte aber, dass die Leute mich\n"
	.string "mögen, daher möchte ich etwas Nettes\l"
	.string "zu meinem Gegner sagen.\p"
	.string "Mir fällt aber absolut nichts ein!\n"
	.string "Weißt du nicht etwas Nettes?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Das klingt nicht schlecht!\n"
	.string "Ja, das werde ich von nun an sagen!\p"
	.string "Ich werde mich nun auf den Weg machen,\n"
	.string "und das, was du mir beigebracht hast,\l"
	.string "beherzigen!\p"
	.string "Tut mir Leid, dass ich dich immer wieder\n"
	.string "mit Fragen bedrängt habe.\p"
	.string "Nächstes Mal kämpfen wir gegen-\n"
	.string "einander, einverstanden? Bis dann!$"

gText_ApprenticePickWinSpeech5::
	.string "Ich verstehe nicht, wieso ich immer so\n"
	.string "im Stress bin! Hey, dich habe ich schon\l"
	.string "gesucht, {PLAYER}{KUN}!\p"
	.string "Und? Alles klar?\n"
	.string "Bei mir ist alles beim Alten.\p"
	.string "Ich renne, kämpfe und bin auch sonst\n"
	.string "ziemlich beschäftigt.\p"
	.string "Aber auch wenn ich nie Zeit habe,\n"
	.string "möchte ich mich nach einem Kampf nicht\l"
	.string "einfach auf dem Absatz umdrehen\p"
	.string "und gehen. Ich möchte etwas sagen, was\n"
	.string "meine Coolness unterstreicht, bevor ich\l"
	.string "weggehe. Aber was, {PLAYER}{KUN}?$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Okay!\n"
	.string "Das zu sagen, nimmt auch nicht viel Zeit\l"
	.string "in Anspruch. Das schaffe ich locker.\p"
	.string "Ich bin echt froh, einen so guten\n"
	.string "Mentor wie dich gefunden zu haben!\p"
	.string "Wenn ich meine Zeit anders aufteile,\n"
	.string "werde ich auch die Zeit finden, mehr zu\l"
	.string "kämpfen.\p"
	.string "Vielen Dank für alles, {PLAYER}{KUN}!\n"
	.string "Eines Tages werden auch wir gegen-\l"
	.string "einander kämpfen. Bis dahin mach’s gut!$"

gText_ApprenticePickWinSpeech6::
	.string "Und wieder lächelt mir das Glück zu!\n"
	.string "Ich freu mich, dich zu sehen, {PLAYER}!\l"
	.string "Und wie immer brauche ich deinen Rat!\p"
	.string "Trommelwirbel, bitte!\n"
	.string "Dies wird meine letzte Frage…\p"
	.string "Gewinne ich einen Kampf, würde ich\n"
	.string "gerne etwas Cooles sagen.\l"
	.string "Aber ich weiß nicht was!$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Das… Das ist klasse!!!\n"
	.string "Seriös und doch cool!\l"
	.string "Das werde ich sagen!\p"
	.string "Ich bin mittlerweile richtig gut\n"
	.string "geworden…\p"
	.string "Und daher denke ich darüber nach,\n"
	.string "andere TRAINER herauszufordern.\p"
	.string "Du hast mir sehr geholfen, {PLAYER}.\p"
	.string "Vielleicht werden auch wir eines Tages\n"
	.string "gegeneinander antreten!\p"
	.string "Vielen Dank! Pass auf dich auf!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}!\n"
	.string "Ich bin froh, dich zu sehen!\p"
	.string "Ich habe keine Bedenken mehr, was meine\n"
	.string "POKéMON angeht.\p"
	.string "Jetzt mache ich mir Gedanken über mich…\p"
	.string "Weißt du, was ein TRAINER sagen kann,\n"
	.string "wenn er einen Kampf gewonnen hat?\p"
	.string "Ich würde nämlich auch gerne etwas\n"
	.string "sagen.\p"
	.string "Kannst du mir da nicht weiterhelfen?\n"
	.string "Hast du eine Idee, was ich sagen kann?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Oh! Das ist wirklich eine Aussage! Da\n"
	.string "fühle ich mich richtig gut mit!\p"
	.string "Das werde ich gleich mal ausprobieren.\p"
	.string "Ich muss dich jetzt verlassen,\n"
	.string "{PLAYER}…\p"
	.string "Ich werde viele TRAINER treffen, aber\n"
	.string "dich und deine Hilfe werde ich nie\l"
	.string "vergessen!\p"
	.string "Und vielleicht eines Tages…\n"
	.string "Lebewohl!$"

gText_ApprenticePickWinSpeech8::
	.string "Iiihiii! Ich habe dich gesehen, {PLAYER}!\n"
	.string "Ich freue mich total, dass du hier bist…\p"
	.string "Und wieder habe ich eine dringende\n"
	.string "Frage an dich!\p"
	.string "Vor kurzem habe ich einen Kampf\n"
	.string "gewonnen! Das war einfach lächerlich…\p"
	.string "Aber ich war so erfreut darüber, dass\n"
	.string "mir die Worte im Halse stecken\l"
	.string "blieben und ich stumm wie ein Fisch war.\p"
	.string "{PLAYER}, kannst du dir nicht etwas\n"
	.string "ausdenken, das ich sagen kann, nachdem\l"
	.string "ich einen Kampf gewonnen habe?$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Waaaaauuu!\n"
	.string "Das soll ich wirklich sagen?!?\l"
	.string "Iihiii! Ich freu mich total darüber!!!\p"
	.string "Vielen, vielen Dank!\n"
	.string "Nun habe ich keine Wünsche mehr offen!\p"
	.string "Ich kann durch das Land reisen und\n"
	.string "viele Menschen treffen.\p"
	.string "Und das verdanke ich allein dir,\n"
	.string "{PLAYER}. Wirklich! Vielen, vielen Dank!\p"
	.string "Ich muss jetzt los, aber ich hoffe, wir\n"
	.string "sehen uns bald wieder und kämpfen\l"
	.string "dann mal gegeneinander! Mach’s gut!$"

gText_ApprenticePickWinSpeech9::
	.string "Holla… Äh… Hallo!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Weißt du, ich würde gerne durch die\n"
	.string "Gegend ziehen und kämpfen.\p"
	.string "Aber bevor ich aufbreche, brauche ich\n"
	.string "noch einmal deinen Rat.\p"
	.string "Wenn ich einen Kampf gewinne, was soll\n"
	.string "ich dann zu dem besiegten TRAINER\l"
	.string "sagen?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Oh ja, das gefällt mir!\n"
	.string "Ja, hirklicw… Äh… wirklich!\l"
	.string "Genau das werde ich von nun an sagen!\p"
	.string "Und nun heißt es Auf Wiedersehen!\n"
	.string "Vielen Dank für alles!\p"
	.string "Wir müssen bald mal gegeneinander\n"
	.string "kämpfen! Web lohl… Äh… Leb wohl!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, der Weltuntergang steht\n"
	.string "bevor!\p"
	.string "Wenn ich einen Kampf gewinne, stehe ich\n"
	.string "vier Stunden später immer noch auf dem\p"
	.string "Platz und überlege, was ich zu meinem\n"
	.string "Sieg sagen könnte.\l"
	.string "Und mein Gegner ist längst gegangen.\p"
	.string "Nee, das war natürlich gelogen.\n"
	.string "Muahahahaha!\p"
	.string "Aber es ist keine Lüge, wenn ich dir\n"
	.string "verrate, dass ich tatsächlich nicht\l"
	.string "weiß, was ich nach einem Sieg sagen soll.\p"
	.string "Hast du nicht eine Idee?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "Das soll ich also sagen?\n"
	.string "Okay, dann wird das nicht über meine\l"
	.string "Lippen kommen!\p"
	.string "Haha! Da habe ich dich wieder auf den\n"
	.string "Arm genommen! Ich höre auf deinen Rat!\p"
	.string "Vielen Dank für alles, was du mir\n"
	.string "beigebracht hast, Meister!\p"
	.string "Nun weiß ich, was es heißt, ein TRAINER\n"
	.string "zu sein!\p"
	.string "Ich werde nun auf die Reise gehen und\n"
	.string "viele TRAINER herausfordern.\p"
	.string "Und eines Tages vielleicht auch dich!\p"
	.string "Bis dahin wünsche ich dir alles Gute,\n"
	.string "mein Meister!$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Ich bin ein MATROSE!\n"
	.string "Habe eine letzte Frage an dich,\l"
	.string "dann verabschiede ich mich.\p"
	.string "Gewinne ich einen Kampf, fehlen mir\n"
	.string "die Worte, das ist echt ein Krampf.\p"
	.string "Ein cooles Wort wäre die Tat.\n"
	.string "Weißt du Rat?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Perfekt! Das werde ich sagen!\n"
	.string "Es war gut, dich zu fragen.\p"
	.string "Und nun, das ist die beste Weise,\n"
	.string "begebe ich mich auf die Reise.\p"
	.string "Vielen Dank für alles!\p"
	.string "Ich grüße dich zum Abschied,\n"
	.string "hoffe, dass man sich mal sieht.$"

gText_ApprenticePickWinSpeech12::
	.string "Yeah, {PLAYER}!\n"
	.string "So sieht man sich wieder!\p"
	.string "Soll ich dich was fragen? Klar,\n"
	.string "wo ich doch schon mal mit dir rede…\p"
	.string "{PLAYER}, ich brauche dringend deinen\n"
	.string "Rat. Hör gut zu!\p"
	.string "Was soll ich sagen, wenn ich einen Kampf\n"
	.string "gewonnen habe? Irgendetwas Cooles\l"
	.string "soll es sein.\p"
	.string "Hast du nicht einen Spruch auf Lager?$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "Sehr gut! Sehr gut!\n"
	.string "Das ist wirklich supergut!\p"
	.string "Und nun heißt es für uns\n"
	.string "Abschied nehmen.\p"
	.string "Sollten wir uns eines Tages\n"
	.string "wiedersehen, werde ich dich um einen\l"
	.string "Kampf bitten.\p"
	.string "Aber genug geredet.\n"
	.string "Vielen Dank, {PLAYER}, und pass auf\l"
	.string "dich auf!\p"
	.string "Bis bald mal!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, ich hab’s geschafft!\n"
	.string "Aber meine Nase hört nicht auf zu\l"
	.string "laufen…\p"
	.string "Ich überlegte, was ich nach einem\n"
	.string "Sieg sagen kann.\p"
	.string "Und vor lauter Inspiration fing ich an\n"
	.string "zu weinen und meine Nase an zu laufen…\p"
	.string "Und da ich mit einer laufenden Nase\n"
	.string "nicht denken kann…\p"
	.string "Bitte ich dich, mir zu raten, was ich\n"
	.string "nach einem Sieg sagen kann.$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … … … …\p"
	.string "Das ist guuut! Total inspirierend!\n"
	.string "Das treibt mir glatt wieder die\l"
	.string "Tränen in die Augen!\p"
	.string "Aber auch mit Tränen in den Augen und\n"
	.string "einer laufenden Nase werde ich diese\l"
	.string "Worte aussprechen!\p"
	.string "Von nun an sind wir Rivalen und werden\n"
	.string "bald gegeneinander kämpfen.\p"
	.string "Trotzdem vielen Dank für alles,\n"
	.string "{PLAYER}{KUN}!$"

gText_ApprenticePickWinSpeech14::
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Du schaust mich immer wieder so an,\n"
	.string "dass ich total nervös und verlegen\l"
	.string "werde. Lass das bitte!\p"
	.string "Ich… brauche wieder deinen Rat.\n"
	.string "Diesmal wird es das letzte Mal sein… \p"
	.string "Es ist zwar sehr peinlich, aber ich muss\n"
	.string "dich fragen, was ich nach einem Sieg\l"
	.string "sagen soll. Hilf mir bitte.$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… Okay!\n"
	.string "Ich werde das sagen!\l"
	.string "Falls ich nicht zu nervös dazu bin…\p"
	.string "Vielen Dank, {PLAYER}{KUN}.\n"
	.string "Und nun muss ich mich von dir\l"
	.string "verabschieden.\p"
	.string "Ich werde mich an das halten, was du mir\n"
	.string "beigebracht hast. {PLAYER}{KUN}, ich werde\l"
	.string "mein Bestes geben!$"

gText_ApprenticePickWinSpeech15::
	.string "Hm? Du bist scheinbar {PLAYER}{KUN}…\n"
	.string "Oder doch nicht?\l"
	.string "Bist du eventuell eine {PLAYER}-Puppe?\p"
	.string "Oh, keine Sorge!\n"
	.string "Wenn du echt bist, dann verzeih bitte\l"
	.string "meine Grobheit!\p"
	.string "Du musst nicht gleich wütend werden.\n"
	.string "Ich möchte dich doch gerne um einen\l"
	.string "Rat bitten.\p"
	.string "Es geht um bestimmte Worte.\p"
	.string "Was soll ich sagen, wenn ich einen\n"
	.string "Kampf gewonnen habe?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … …\n"
	.string "…\l"
	.string "Wenn ich einen Kampf gewinne…\p"
	.string "{STR_VAR_1}\p"
	.string "Meinst du das wirklich so?\p"
	.string "Nun, dann ist es ja gut.\n"
	.string "Ich danke dir für deine Zeit.\p"
	.string "Ich hoffe, ich werde in der Lage sein,\n"
	.string "diese Worte oft zu sagen.\p"
	.string "Du hast mir alles beigebracht, was ich\n"
	.string "wissen muss.\p"
	.string "Es ist an der Zeit, dass sich unsere\n"
	.string "Wege trennen.\p"
	.string "Vielen Dank, mein Mentor! Und\n"
	.string "entschuldige meine dauernde Skepsis!$"
