FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Willkommen im KAMPFCAMP von\n"
	.string "LAUBWECHSELFELD!\p"
	.string "Ich begleite dich zu dem K.O.-\n"
	.string "Teamturnier.$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Möchtest du dich der Herausforderung\n"
	.string "des K.O.-Kampfturniers stellen?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Wir freuen uns auf deine nächste\n"
	.string "Herausforderung.$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "Im KAMPFCAMP von LAUBWECHSELFELD\n"
	.string "findet das K.O.-Teamturnier statt.\p"
	.string "Jeder Teilnehmer darf drei POKéMON\n"
	.string "in den Kampf mitnehmen.\p"
	.string "Diese müssen in der Reihenfolge\n"
	.string "angeordnet werden, in der sie kämpfen\l"
	.string "sollen.\p"
	.string "Diese Reihenfolge wird im Kampf strikt\n"
	.string "eingehalten.\p"
	.string "Ein POKéMON bleibt solange im Kampf,\n"
	.string "bis der Kampf entschieden ist.\p"
	.string "Wenn ein Kampf nach drei Runden noch\n"
	.string "nicht entschieden ist, wird der Sieger\l"
	.string "durch ein richterliches Urteil bestimmt.\p"
	.string "Wenn du deine Herausforderung\n"
	.string "unterbrechen möchtest, speichere\l"
	.string "bitte dein Spiel.\p"
	.string "Wenn du ohne Speichern unterbrichst,\n"
	.string "ist die Herausforderung beendet.\p"
	.string "Besiegst du drei TRAINER in Folge,\n"
	.string "gewinnst du einen fantastischen Preis.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Bevor du das KAMPFCAMP betrittst,\n"
	.string "musst du dein Spiel speichern. Okay?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "We offer two levels of challenge,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Sehr schön! Dann bestimme jetzt bitte\n"
	.string "deine drei POKéMON.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Verehrter Herausforderer!\p"
	.string "Leider besitzt du keine drei POKéMON,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "EIer{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Verehrter Herausforderer!\p"
	.string "Leider besitzt du keine drei POKéMON,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Du brauchst drei verschiedene POKéMON.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "EIer{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Ich werde dich nun zum KAMPFCAMP\n"
	.string "begleiten.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Verehrter Herausforderer!\p"
	.string "Du hast, bevor du die Herausforderung\n"
	.string "abgebrochen hast, nicht gespeichert.\p"
	.string "Daher wirst du leider für diese\n"
	.string "Herausforderung disqualifiziert.\l"
	.string "Schade!\p"
	.string "Natürlich kannst du dich einer neuen\n"
	.string "Herausforderung stellen!$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Hervorragend! Du hast drei TRAINER in\n"
	.string "Folge besiegt!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Dein Erfolg wird gespeichert.\n"
	.string "Bitte warten.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "In Anerkennung deines dreifachen\n"
	.string "Sieges überreichen wir dir diesen Preis.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} gewinnt\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh, dein BEUTEL ist voll.\p"
	.string "Bitte schaffe Platz in deinem BEUTEL\n"
	.string "und komme dann wieder.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Vielen Dank für die Teilnahme!\p"
	.string "Das Ergebnis wird gespeichert.\n"
	.string "Bitte warten.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Wir freuen uns auf deine nächste\n"
	.string "Herausforderung.$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Wir haben schon auf dich gewartet!\p"
	.string "Bevor du das KAMPFCAMP betrittst,\n"
	.string "wird dein Spiel gespeichert.\l"
	.string "Bitte warten.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Willkommen im KAMPFCAMP von\n"
	.string "WIESENFLUR!\p"
	.string "Hier wird das Vertrauen der TRAINER in\n"
	.string "ihre POKéMON getestet.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Möchtest du dich der Herausforderung\n"
	.string "des WIESENFLUR KAMPFCAMPs stellen?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "Im KAMPFCAMP von WIESENFLUR gibt es\n"
	.string "eine entscheidende Regel, die beachtet\l"
	.string "werden muss.\p"
	.string "TRAINER dürfen ihre POKéMON lediglich\n"
	.string "in den Kampf rufen und zurückziehen.\p"
	.string "Ansonsten ist es ihnen nicht erlaubt,\n"
	.string "in den Kampf einzugreifen.\p"
	.string "Die POKéMON sollen sich gemäß ihres\n"
	.string "Wesens verhalten und kämpfen.\p"
	.string "Du musst deinen POKéMON vertrauen und\n"
	.string "sie beobachten.\p"
	.string "Wenn du es schaffst, drei TRAINER in\n"
	.string "Folge zu besiegen, bekommst du einen\l"
	.string "Preis von uns.\p"
	.string "Wenn du deine Herausforderung\n"
	.string "unterbrechen willst, speichere bitte\l"
	.string "dein Spiel.\p"
	.string "Brichst du die Herausforderung ohne zu\n"
	.string "speichern ab, wirst du disqualifiziert.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Hast du dein Herz gestärkt und deine\n"
	.string "POKéMON, dann komm wieder.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "There are two levels of difficulty,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice of a challenge?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Seufz…\p"
	.string "Leider besitzt du keine drei POKéMON,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Du brauchst drei verschiedene POKéMON.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "EIer{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Seufz…\p"
	.string "Leider besitzt du keine drei POKéMON,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Du brauchst drei verschiedene POKéMON.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "EIer{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Gut. Dann bestimme jetzt deine drei\n"
	.string "POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Bevor du das KAMPFCAMP betrittst,\n"
	.string "musst du dein Spiel speichern. Okay?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Gut. Dann folge mir bitte.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Ich fühle mich geehrt, dass ich deinen\n"
	.string "POKéMON zuschauen durfte.\p"
	.string "Das Ergebnis wird gespeichert.\n"
	.string "Bitte warte einen Moment.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Drei Siege in Folge…\p"
	.string "Das Band zwischen dir und deinen\n"
	.string "POKéMON ist wirklich stark.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Dein Erfolg wird gespeichert.\n"
	.string "Bitte warte einen Moment.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Für deinen dreifachen Sieg bekommst du\n"
	.string "von uns diesen Preis überreicht.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Willkommen im KAMPFCAMP von\n"
	.string "GRAPHITPORT.\p"
	.string "Ich begleite dich zum Wechselkampf-\n"
	.string "Turnier.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Möchtest du am Wechselkampf\n"
	.string "teilnehmen?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Hier im KAMPFCAMP von GRAPHITPORT\n"
	.string "halten wir Wechselkampf-Turniere ab,\l"
	.string "die mit Leih-PKMN ausgetragen werden.\p"
	.string "Als Erstes leihst du dir drei POKéMON.\p"
	.string "Mit diesen kannst du an einem\n"
	.string "EINZELKAMPF teilnehmen.\p"
	.string "Gewinnst du, darfst du ein Leih-\n"
	.string "POKéMON tauschen.\p"
	.string "Wiederhole diese Folge von Siegen und\n"
	.string "Tausch. Gewinnst du drei Mal in Folge,\l"
	.string "erhältst du einen Preis.\p"
	.string "Wenn du die Herausforderung abbrechen\n"
	.string "willst, speichere dein Spiel.\p"
	.string "Wenn du ohne zu speichern abbrichst,\n"
	.string "wirst du disqualifiziert.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Wir freuen uns auf deine nächste\n"
	.string "Herausforderung.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Which level do you wish to challenge?\n"
	.string "Level 50 or Level 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Bevor du dich der Herausforderung\n"
	.string "stellst, speichere ich dein Spiel. Okay?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Okay, I will hold your POKéMON for\n"
	.string "safekeeping while you compete.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Bitte hier entlang.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Vielen Dank für deine Teilnahme!\p"
	.string "Ich gebe dir nun deine POKéMON\n"
	.string "zurück.\p"
	.string "Ich werde das Ergebnis speichern.\n"
	.string "Bitte warte einen Moment.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Herzlichen Glückwunsch!\n"
	.string "Du hast drei Kämpfe in Folge gewonnen!\p"
	.string "Ich gebe dir nun deine POKéMON\n"
	.string "zurück.\p"
	.string "Ich werde deinen Erfolg speichern.\n"
	.string "Bitte warte einen Moment.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "Für deinen dreifachen Sieg bekommst du\n"
	.string "von uns diesen Preis überreicht.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh, dein BEUTEL ist voll.\p"
	.string "Bitte schaffe Platz in deinem BEUTEL\n"
	.string "und komme dann wieder.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Wir haben auf dich gewartet!\p"
	.string "Bevor du die Herausforderung\n"
	.string "fortsetzt, speichere ich dein Spiel.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Entschuldigung!\p"
	.string "Du hast, bevor du die Herausforderung\n"
	.string "abgebrochen hast, nicht gespeichert.\p"
	.string "Daher wirst du für diese Herausforde-\n"
	.string "rung disqualifiziert. Schade!$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "We’ll return your personal POKéMON.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "The Battle Swap rules are listed.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which heading do you want to read?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "In einem Wechselkampf darfst du\n"
	.string "nur drei POKéMON einsetzen.\p"
	.string "Egal, ob du sie dir ausleihst oder\n"
	.string "tauschst, du darfst keine zwei gleichen\l"
	.string "POKéMON in deinem Team haben.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Du kannst mit dem TRAINER POKéMON\n"
	.string "tauschen, den du besiegt hast.\p"
	.string "Allerdings nur die POKéMON, die dieser\n"
	.string "im Kampf eingesetzt hat. Ein genereller\l"
	.string "Tausch ist nicht möglich.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Nach jedem gewonnenen Kampf kannst du\n"
	.string "eines deiner POKéMON gegen das deines\l"
	.string "Gegners tauschen.\p"
	.string "Du kannst mit dem dritten TRAINER\n"
	.string "allerdings keine POKéMON tauschen.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Beim POKéMON-Tausch musst du auf zwei\n"
	.string "Dinge achten!\p"
	.string "Du kannst den Status des POKéMON, das\n"
	.string "du haben möchtest, vor dem Tausch\l"
	.string "nicht überprüfen.\p"
	.string "Denk daran, dass deine POKéMON in einer\n"
	.string "bestimmten Reihenfolge angeordnet\l"
	.string "sind.\p"
	.string "Diese bleibt auch nach dem Tausch\n"
	.string "unverändert.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Die POKéMON im KAMPFCAMP von\n"
	.string "GRAPHITPORT sind alle Leih-POKéMON.\p"
	.string "Diese stehen auf Level 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "The VERDANTURF BATTLE TENT\n"
	.string "rules are listed.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which heading do you want to read?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Here at the VERDANTURF BATTLE TENT,\n"
	.string "POKéMON are required to think and\l"
	.string "battle by themselves.\p"
	.string "Unlike in the wild, POKéMON that live\n"
	.string "with people behave differently\l"
	.string "depending on their nature.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Depending on its nature, a POKéMON\n"
	.string "may prefer to attack no matter what.\p"
	.string "Another POKéMON may prefer to protect\n"
	.string "itself from any harm.\p"
	.string "Yet another may enjoy vexing or\n"
	.string "confounding its foes.\p"
	.string "Depending on its nature, a POKéMON\n"
	.string "will have favorite moves that it is good\l"
	.string "at using.\p"
	.string "It may also dislike certain moves that\n"
	.string "it has trouble using.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "There are offensive moves that inflict\n"
	.string "direct damage on the foe.\p"
	.string "There are defensive moves that are\n"
	.string "used to prepare for enemy attacks or\l"
	.string "used to heal HP and so on.\p"
	.string "There are also other somewhat-odd\n"
	.string "moves that may enfeeble the foes with\l"
	.string "stat problems including poison and \l"
	.string "paralysis.\p"
	.string "POKéMON will consider using moves in\n"
	.string "these three categories.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "When not under command by its TRAINER,\n"
	.string "a POKéMON may be unable to effectively\l"
	.string "use certain moves.\p"
	.string "A POKéMON is not good at using any\n"
	.string "move that it dislikes.\p"
	.string "If a POKéMON only knows moves that\n"
	.string "do not match its nature, it will often\l"
	.string "be unable to live up to its potential.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Depending on its nature, a POKéMON may\n"
	.string "start using moves that don’t match its\l"
	.string "nature when it is in trouble.\p"
	.string "If a POKéMON begins behaving oddly\n"
	.string "in a pinch, watch it carefully.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "In diesem KAMPFCAMP werden die Level\n"
	.string "der gegnerischen POKéMON an die Level\l"
	.string "deiner POKéMON angepasst.\p"
	.string "Trotzdem wird kein TRAINER, auf den du\n"
	.string "triffst, POKéMON unter Level 30 haben.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Die Regeln des WIESENFLUR KAMPFCAMPs\n"
	.string "hängen öffentlich aus.$"
