PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "VATER: Hallo, {PLAYER}!\p"
	.string "Ich habe gerade eine sehr seltene\n"
	.string "BEERE erhalten. Die schenke ich dir.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Wenn du BEEREn siehst, die im Lehmboden\n"
	.string "wachsen, pflücke sie ruhig.\p"
	.string "Aber pflanze eine neue BEERE an der\n"
	.string "Stelle. Das ist einfache Höflichkeit.\p"
	.string "Hier, das ist für dich.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Du siehst aus wie ein TRAINER. Du\n"
	.string "bist auch einer, stimmt’s?\p"
	.string "TRAINER geben ihren POKéMON manchmal\n"
	.string "BEEREn zu tragen.\p"
	.string "Es liegt an dir, ob du BEEREn pflanzt\n"
	.string "oder verwendest.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Ich gieße die Pflanzen jeden Tag.\n"
	.string "Dann bekommen sie viele Blüten.\p"
	.string "Und daraus werden dann viele BEEREn.\p"
	.string "Hier, die ist für dich.\n"
	.string "Du kannst sie haben.$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Ich werde mich anstrengen und einige\n"
	.string "BEEREn in verschiedenen Farben\l"
	.string "züchten!\p"
	.string "Ich hoffe, du strengst dich auch an.$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Ich frage mich, welche BEEREn-Farbe ich\n"
	.string "heute wählen soll.$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "Ich liebe die BEERENMÜHLE, daher sammle\n"
	.string "ich alle BEEREn, die ich finde.\p"
	.string "Ich schenk dir eine, wenn du magst.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Du solltest die BEERENMÜHLE unbedingt\n"
	.string "zusammen mit deinen Freunden\l"
	.string "ausprobieren.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Welche BEERE sollte man pflanzen?\n"
	.string "Sollte man BEEREn einsetzen oder\l"
	.string "sammeln?\p"
	.string "Es macht Spaß, darüber nachzudenken.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "BEEREn gedeihen im Sonnenlicht, das\n"
	.string "sie aufnehmen.\p"
	.string "Und ich versorge sie regelmäßig mit\n"
	.string "Wasser.\p"
	.string "Es ist ein Ausdruck der Liebe, richtig?$"

Route120_Text_YesYouUnderstand:
	.string "Ja, ja.\n"
	.string "Du verstehst, was ich meine.\p"
	.string "Das hier ist für dich.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… Aber es ist wichtig, dass man sich\n"
	.string "einen eigenen Eindruck verschafft…\p"
	.string "Hier. Das kannst du haben.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Dies ist eine seltene BEERE. Ich hoffe,\n"
	.string "du gehst sorgfältig mit ihr um.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Ich habe einige BEEREn vom\n"
	.string "BEERENMEISTER erhalten.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Also, im Grunde ist es so…\p"
	.string "Ein Anzug passt zu mir wie die\n"
	.string "Brise zum Meer - perfekt!\p"
	.string "Und bei dir… Eine BEERE passt zu\n"
	.string "“T”…\p"
	.string "Warum ist das so?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Also, im Grunde ist es so…\p"
	.string "Weil du ein TRAINER bist.$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Grundsätzlich verhält es sich so…\p"
	.string "So, wie die würdevolle Einfachheit mich\n"
	.string "ziert, zieren {POKEBLOCK} POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Du kannst mich BEERENMEISTER\n"
	.string "nennen.\p"
	.string "Ich träume davon, die Welt mit hübschen\n"
	.string "Blumen zu bereichern, daher züchte ich\l"
	.string "BEEREn und gebe sie an andere weiter.\p"
	.string "Du hast dir auch eine verdient!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Sei nicht so schüchtern.\n"
	.string "Nimm dir noch eine!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Besuch unbedingt den BLÜTENTRAUM\n"
	.string "BLUMENLADEN bei METAROST CITY.\p"
	.string "Lasst die Welt in Blumen schwelgen.$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "Für heute bin ich fertig.\n"
	.string "Komm ein anderes Mal wieder.\p"
	.string "Lasst die Welt in Blumen schwelgen!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Mein Mann züchtet BEEREn. Er ist be-\n"
	.string "stimmt der beste Züchter der Welt.\p"
	.string "Er macht mich unglaublich stolz.\p"
	.string "Sag mal, Kind, du kennst nicht zufällig\n"
	.string "einen guten Spruch?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! Was für ein wunderbarer Spruch!\n"
	.string "So inspirierend!\p"
	.string "Das hier möchte ich dir schenken.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! Das ist ein guter Spruch!\n"
	.string "Du bist bemerkenswert!\p"
	.string "Das hier möchte ich dir schenken.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Unsere vier Enkelkinder sollen noch\n"
	.string "begabter als mein Mann werden.\p"
	.string "Das Leben erfüllt einen immer wieder mit\n"
	.string "Freude!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Hallo!\p"
	.string "Dies ist der BLÜTENTRAUM BLUMENLADEN.\n"
	.string "Verwandelt die Welt in ein Blumenmeer!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, möchtest du etwas über\n"
	.string "BEEREn lernen?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Wie heißt du?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Das ist aber ein hübscher Name.\p"
	.string "Möchtest du etwas über BEEREn lernen?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "BEEREn wachsen an Bäumen, die nur in\n"
	.string "dunklem Lehmboden gedeihen.\p"
	.string "Wenn du BEEREn pflückst, pflanze\n"
	.string "immer neue in den Boden ein.\p"
	.string "Eine gepflanzte BEERE wird bald an-\n"
	.string "fangen zu sprießen, dann mit einer\p"
	.string "wunderhübschen Blüte erblühen, die\n"
	.string "bald zu einer BEERE wird.\p"
	.string "Ich würde die ganze Welt am liebsten mit\n"
	.string "wunderhübschen Blüten bedeckt sehen.\l"
	.string "Das ist mein Traum.\p"
	.string "Bitte, hilf mir, {PLAYER}{KUN}. Pflanze BEEREn\n"
	.string "und bring so Blüten in die Welt.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Blumen erfreuen jedes Herz, nicht\n"
	.string "wahr?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Hallo!\p"
	.string "Je mehr du dich um die Blumen kümmerst,\n"
	.string "desto schöner werden sie blühen.\p"
	.string "Auch du hast Blumen gerne.\n"
	.string "Das weiß ich genau. Das ist für dich.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Nachdem du die BEEREn eingepflanzt\n"
	.string "hast, musst du sie mit der\l"
	.string "WAILMERKANNE wässern.\p"
	.string "Oh, und noch etwas!\p"
	.string "Wenn die BEEREn nicht gepflückt\n"
	.string "werden, fallen sie zu Boden. Aber sie\l"
	.string "werden wieder nachwachsen.\p"
	.string "Ist das nicht unglaublich? Es ist, als\n"
	.string "hätten sie den Willen zu leben.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Ich versuche, so zu sein wie meine große\n"
	.string "Schwester. Ich züchte auch Blumen!\p"
	.string "Hier, das ist für dich!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Du kannst eine BEERE pflanzen und sie\n"
	.string "wachsen lassen, oder du gibst sie einem\l"
	.string "POKéMON zum Tragen.\p"
	.string "Und neuerdings gibt es eine Maschine,\n"
	.string "mit der kann man die verschiedensten\l"
	.string "BEEREn mixen und Süßigkeiten für die\l"
	.string "POKéMON daraus machen.\p"
	.string "Ich möchte auch Süßigkeiten haben.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Hi, wie heißt du?\p"
	.string "… … … … … … … … …\n"
	.string "Okay. Netter Name!\p"
	.string "Ich heiße BERTA.\p"
	.string "Meine Eltern haben mich so genannt,\n"
	.string "damit ich gesund und warmherzig werde.\l"
	.string "Das war ihr Wunsch.\p"
	.string "Hier, das schenke ich dir.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "BERTA will dir auch diese BEERE geben.\n"
	.string "Ich mag sie sehr!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Ich frage mich, welcher Wunsch in\n"
	.string "deinem Namen verborgen ist.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Frühling, Sommer, Herbst und Winter.\p"
	.string "Wenn du im Frühling geboren bist, magst\n"
	.string "du dann den Frühling? Wenn du im Sommer\l"
	.string "geboren bist, magst du den Sommer?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Dann wurde BERTA im Herbst geboren,\n"
	.string "denn ich liebe den Herbst!\p"
	.string "Welche Jahreszeit hast du am liebsten?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "Das macht nichts…\p"
	.string "Es gibt so viel, was ich wissen möchte…$"
