gText_Birch_Welcome::
	.string "Ouh NJIERI!!\p"
	.string "Ich bin de Professor LUNTE.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "$"

gText_Birch_MainSpeech::
	.string "Hesch Lust uf e wahri\n"
	.string "Challenge?\p"
	.string "Ich laber dich au noed lang voll.\n"
	.string "Du weisch doch, wie's lauft.\p"
	.string "Hol dini POKéMON bi mir ab\n"
	.string "und denn gib ihm!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "$"

gText_Birch_BoyOrGirl::
	.string "$"

gText_Birch_WhatsYourName::
	.string "$"

gText_Birch_SoItsPlayer::
	.string "$"

gText_Birch_YourePlayer::
	.string "$"

gText_Birch_AreYouReady::
	.string "$"