BerryBlender_Text_BlendWithTheBlendMaster:
	.string "MIXMEISTER: Genau das bin ich!\n"
	.string "Ich bin der MIXMEISTER!\p"
	.string "Mixe mit mir und du wirst Zeuge meines\n"
	.string "meisterhaften Mixens!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "MIXMEISTER: Hmm! Du willst mich also\n"
	.string "in Aktion sehen?!?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmmm!\p"
	.string "Du bist also im Moment zu beschäftigt.\p"
	.string "Aber keine Angst!\n"
	.string "Ich bin den ganzen Tag hier!\l"
	.string "Beeil dich und komm wieder.$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmmm!\p"
	.string "Du hast keine einzige BEERE!\p"
	.string "Ich bin den ganzen Tag hier!\n"
	.string "Besorg dir BEEREn und komm wieder.$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Sicher!\n"
	.string "Sicher!\p"
	.string "Übrigens…\n"
	.string "Weißt du eigentlich, wie man aus BEEREn\l"
	.string "{POKEBLOCK} herstellt?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmm!\p"
	.string "Das ist so etwas von einfach!\p"
	.string "Wenn der Pfeil des BEERENMIXERs an\n"
	.string "deine Markierung gelangt, musst du den\l"
	.string "A-Knopf drücken.\p"
	.string "Das ist auch schon alles, was du zu tun\n"
	.string "hast.\p"
	.string "Schau dir an, wie präzise ich den\n"
	.string "A-Knopf drücke, dann wird es dir klar.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Sehr schön!\p"
	.string "Dann lass uns loslegen!\p"
	.string "Lass uns zusammen mit dem\n"
	.string "MIXMEISTER BEEREn MIXEN!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmm!\p"
	.string "Du hast keine {POKEBLOCK}BOX!\p"
	.string "Ich bin den ganzen Tag hier!\n"
	.string "Hol dir die {POKEBLOCK}BOX und komm dann\l"
	.string "wieder.$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmm!\p"
	.string "Deine {POKEBLOCK}BOX scheint voll zu sein.\p"
	.string "Ich bin den ganzen Tag hier!\n"
	.string "Verwende einige {POKEBLOCK} und komm\l"
	.string "dann wieder.$"

BerryBlender_Text_WhoaAwesome:
	.string "Whoa!\n"
	.string "Wahnsinn!!!$"

BerryBlender_Text_WickedlyFast:
	.string "Unglaublich schnell!$"

BerryBlender_Text_WhatAnExpert:
	.string "Das ist ein wahrer Experte!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Als ich mit dem Meister gemixt habe,\n"
	.string "haben wir die besten {POKEBLOCK}\l"
	.string "hergestellt!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Augen, die dem Pfeil unermüdlich und\n"
	.string "genau folgen…\p"
	.string "Eine Hand, die den A-Knopf mit der\n"
	.string "Präzision einer Uhr drückt…\p"
	.string "Diese Fähigkeiten machen den MIX-\n"
	.string "MEISTER zu dem Meister schlechthin!$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Der MIXMEISTER arbeitet im Gebirge\n"
	.string "an der Vollendung seiner Fähigkeiten.\p"
	.string "Manchmal kommt er nach SEEGRASULB, um\n"
	.string "den ganzen Tag BEEREn zu mixen.$"
