EventTicket_Text_OldSeaMapTooFar:
	.string "Nun, was gibt’s, Kindchen?\p"
	.string "Wie? Du besitzt eine alte, zerknitterte\n"
	.string "Karte?\p"
	.string "Zeig sie mir mal.\n"
	.string "… … … … …\l"
	.string "…\p"
	.string "Junge, Junge. Das ist aber weit weg. Ich\n"
	.string "glaube nicht, dass ich dir helfen kann…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRACK: Warte einen Moment!\p"
	.string "Warum sollte ich jemandem Hilfe\n"
	.string "verweigern, dem ich so viel zu\l"
	.string "verdanken habe?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, es tut mir schrecklich Leid!\p"
	.string "Du hast mich um Hilfe gebeten und ich\n"
	.string "hätte dich beinahe im Stich gelassen.\p"
	.string "Nun, lass mich das wieder hinbiegen.\p"
	.string "Wir setzen sofort Segel!\p"
	.string "Schauen wir auf die ALTE KARTE.\n"
	.string "Wo wir die Insel finden.$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "Ach, du besitzt dieses komische Ticket?\p"
	.string "Willst du zu dieser Insel, die weit, weit\n"
	.string "weg ist?\p"
	.string "Niemand kann sagen, was uns dort\n"
	.string "erwartet…\p"
	.string "Und das bringt mein Seemannsblut\n"
	.string "in Wallung, so gespannt bin ich!\p"
	.string "Dann komm an Bord, Kindchen!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "KAPITÄN BRACK ist manchmal\n"
	.string "unberechenbar…\p"
	.string "Möchtest du zurück nach SEEGRASULB?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Diese Insel hat wirklich eine höchst\n"
	.string "merkwürdige Form, findest du nicht?\l"
	.string "Möchtest du zurück nach SEEGRASULB?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "Ach, du besitzt diese merkwürdigen\n"
	.string "Tickets.\p"
	.string "Hm… … …\p"
	.string "Damit kannst du zu diesen weit, weit\n"
	.string "entfernten Inseln fahren.\p"
	.string "Niemand weiß, was einen dort erwartet\n"
	.string "oder was dort alles passieren kann.\p"
	.string "Und das bringt mein Blut in Wallung, so\n"
	.string "spannend finde ich das.\p"
	.string "Dann komm an Bord, Kindchen!\n"
	.string "Wohin fahren wir zuerst?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Hast du… Hast du gehört?\n"
	.string "Von dort unten kam ein Knurren.\p"
	.string "Bist du sicher, dass es nicht gefährlich\n"
	.string "ist? Sollten wir nicht lieber umkehren?$"

FarawayIsland_Entrance_Text_Sign:
	.string "Die Schrift ist verblasst, so als sei sie\n"
	.string "vor uralten Zeiten geschrieben worden…\p"
	.string "“…ber, 6. Tag\n"
	.string "Sollte jemals wieder ein Mensch… seinen\l"
	.string "Fuß auf die Insel… ffe, dass es\l"
	.string "ein weichherziger Mens…\p"
	.string "…it dieser Hoffnung gehe i…$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"
