EventTicket_Text_ShowOldSeaMap:
	.string "Die Fähre nach GRAPHITPORT ist…\p"
	.string "Verzeihung? Ob wir zu diesem Ort, der\n"
	.string "auf der Karte eingezeichnet ist,\l"
	.string "fahren können?\p"
	.string "Ich rufe jemanden, der dir weiterhelfen\n"
	.string "kann. Bitte warte einen Moment.$"

EventTicket_Text_ThatPass:
	.string "Die Fähre nach GRAPHITPORT CITY ist…\p"
	.string "Oh!\n"
	.string "Der FAHRSCHEIN…$"

EventTicket_Text_ShowEonTicket:
	.string "Aye, Maat, hast du den alten FAHRSCHEIN\n"
	.string "mitgebracht?\p"
	.string "Ich sage dir, du bist auf dem Weg zu\n"
	.string "einer briefmarkengroßen Insel im Süden.\p"
	.string "Niemand kann sagen, was uns dort er-\n"
	.string "warten wird, aye. Und das erschüttert\l"
	.string "meine alten Knochen!\p"
	.string "Alle Mann an Bord!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Aye, Maat, auf dieser gottverlassenen\n"
	.string "Insel gibt’s nichts zu sehen und zu tun.\p"
	.string "Sollen wir nicht nach SEEGRASULB CITY\n"
	.string "zurücksegeln?$"

EventTicket_Text_SailHome:
	.string "Aye, alles klar!\n"
	.string "Segeln wir nach Hause!$"

EventTicket_Text_AsYouLike:
	.string "Aye, ganz wie du willst.$"

SouthernIsland_Interior_Text_Sign:
	.string "“Alle Träume sind nur eine andere\n"
	.string "Realität. Vergiss das nicht…”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Die, denen die Erinnerung verblasst,\n"
	.string "versuchen, sie im Herzen zu halten.”$"
