LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Dies ist die POKéMON-LOTTERIE.\p"
	.string "Alle Besucher des EINKAUFSZENTRUMs\n"
	.string "können einen POKéMON-LOTTOSCHEIN\l"
	.string "ziehen.\p"
	.string "Wenn die Nummer des LOTTOSCHEINs mit\n"
	.string "der ID-Nummer eines deiner POKéMON\l"
	.string "übereinstimmt, gewinnst du einen Preis.\p"
	.string "Möchtest du einen\n"
	.string "POKéMON-LOTTOSCHEIN ziehen?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Bitte, komme morgen wieder.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Bitte, komm bald wieder.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Bitte, ziehe einen LOTTOSCHEIN.\n"
	.string "…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "Der LOTTOSCHEIN hat die Nummer {STR_VAR_1}.\p"
	.string "Ich muss diese Nummer jetzt prüfen,\n"
	.string "um zu sehen, ob sie mit der ID-Nummer\l"
	.string "eines deiner POKéMON übereinstimmt.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Herzlichen Glückwunsch!\p"
	.string "Die ID-Nummer deines {STR_VAR_1} im\n"
	.string "Team stimmt mit der des LOTTO-\l"
	.string "SCHEINs überein!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Herzlichen Glückwunsch!\p"
	.string "Die ID-Nummer deines {STR_VAR_1} in\n"
	.string "der Box des PCs stimmt mit der des\l"
	.string "LOTTOSCHEINs überein!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Tut mir Leid.\n"
	.string "Keine der Nummern stimmt überein.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Zwei Ziffern stimmen überein,\n"
	.string "daher bekommst du den dritten Preis!\l"
	.string "Du gewinnst {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Drei Ziffern stimmen überein,\n"
	.string "daher bekommst du den zweiten Preis!\l"
	.string "Du gewinnst {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Vier Ziffern stimmen überein,\n"
	.string "daher bekommst du den ersten Preis!\l"
	.string "Du gewinnst {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Meine Güte! Alle fünf Ziffern stimmen\n"
	.string "überein!\p"
	.string "Du hast den Jackpot geknackt!\n"
	.string "Du gewinnst {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Oh! Du scheinst keinen Platz\n"
	.string "dafür zu haben.\p"
	.string "Wenn du wieder Platz in deinem BEUTEL\n"
	.string "hast, lass es mich wissen.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Ja, ich habe dich schon erwartet.\p"
	.string "Diesen Preis habe ich für dich\n"
	.string "aufbewahrt.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Bitte komm bald wieder.$"
