@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " so hübsch!$"

GiddyText_SoDarling::
	.string " so reizend!$"

GiddyText_SoRelaxed::
	.string " so lässig!$"

GiddyText_SoSunny::
	.string " so überwältigend!$"

GiddyText_SoDesirable::
	.string " so erstrebenswert!$"

GiddyText_SoExciting::
	.string " so aufregend!$"

GiddyText_SoAmusing::
	.string " so amüsant!$"

GiddyText_SoMagical::
	.string " so zauberhaft!$"

GiddyText_Is::
	.string " klingt$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "Findest du nicht auch?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Ich will unbedingt verreisen!\n"
	.string "Kennst du ein hübsches Reiseziel?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "Ich habe 120 verschiedene Farbstifte\n"
	.string "gekauft! Das ist doch toll, oder?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Wäre es nicht herrlich, wir könnten auf\n"
	.string "einer Luftblasenwolke davonschweben?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Eine Botschaft in Sand geschrieben\n"
	.string "wird weggespült. Das ist traurig.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "Wie der Meeresgrund wohl ist? Ich\n"
	.string "würde ihn so gerne einmal erleben!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Sehnst du dich beim Anblick der unter-\n"
	.string "gehenden Sonne nach deinem Zuhause?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Einfach so im grünen Gras liegen…\n"
	.string "Oh, das ist so was von angenehm!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "GEHEIMBASen sind superklasse!\n"
	.string "Findest du das nicht auch aufregend?$"
