MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Diese Attacke kann nur einmal\n"
	.string "erlernt werden! Ist das in Ordnung?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! Mein POKéMON ist das Beste!\n"
	.string "Kein anderes ist so cool wie meins!\p"
	.string "Ich bin herumstolziert und habe\n"
	.string "angegeben, bis ein VORSITZENDER mich\l"
	.string "zu Fall brachte.\p"
	.string "Das hat meinen Hochmut abgekühlt.\p"
	.string "Wenn du magst, dann bringe ich einem\n"
	.string "deiner POKéMON ANGEBEREI bei.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Echt nicht? Erkennst du denn nicht\n"
	.string "den tieferen Sinn dahinter?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Sehr schön! Und welches POKéMON soll\n"
	.string "es lernen?$"

MoveTutor_Text_SwaggerTaught:
	.string "Ich werde von nun an meine POKéMON\n"
	.string "loben, ohne anzugeben.$"

MoveTutor_Text_RolloutTeach:
	.string "Wusstest du, dass du von hier lange\n"
	.string "in diese Richtung dort gehen kannst,\l"
	.string "ohne die Richtung wechseln zu müssen?\p"
	.string "Ich bin sogar in der Lage, den ganzen\n"
	.string "Weg entlang zu walzen.\p"
	.string "Ob eines deiner POKéMON das auch\n"
	.string "gerne tun würde? Was meinst du?\p"
	.string "Ich kann ihm WALZER beibringen, wenn\n"
	.string "du magst.$"

MoveTutor_Text_RolloutDeclined:
	.string "Ach, sei doch nicht so schüchtern.\n"
	.string "Walzen macht doch Spaß!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Hehehe. Wäre doch klasse, wenn das\n"
	.string "POKéMON so aussehen würde wie ich.$"

MoveTutor_Text_RolloutTaught:
	.string "Ich walze total gerne durch Gras.\n"
	.string "Komm, ich lade dich zum Walzen ein.$"

MoveTutor_Text_FuryCutterTeach:
	.string "Es gibt eine Attacke, die stärker wird,\n"
	.string "wenn du sie mehrmals hintereinander\l"
	.string "einsetzt.\p"
	.string "Sie ist vom Typ KÄFER und megacool!\p"
	.string "Sie heißt ZORNKLINGE.\n"
	.string "Soll ich sie einem POKéMON beibringen?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Wir haben offensichtlich nicht die\n"
	.string "gleiche Wellenlänge.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Ja, klasse! Und welches POKéMON soll die\n"
	.string "Attacke lernen?$"

MoveTutor_Text_FuryCutterTaught:
	.string "Es ist einfach toll zu sehen, wenn die\n"
	.string "Attacke mehrmals hintereinander\l"
	.string "trifft.$"

MoveTutor_MimicTeach:
	.string "Ah, Jungchen!\p"
	.string "Ich bin auch noch jung, aber ich ahme\n"
	.string "die Sprache der älteren Leute nach, die\l"
	.string "ich in diesem Ort treffe.\p"
	.string "Was meinst du, Kindchen?\n"
	.string "Würde es dich freuen, wenn ich einem\l"
	.string "deiner POKéMON MIMIKRY beibringe?$"

MoveTutor_MimicDeclined:
	.string "Oh, buuuuh! Und ich wollte doch so gerne\n"
	.string "einem POKéMON MIMIKRY beibringen…$"

MoveTutor_Text_MimicWhichMon:
	.string "Hahaha! So soll es sein! Zeig mir das\n"
	.string "POKéMON, welches die Attacke lernen\l"
	.string "soll.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIKRY ist eine Attacke mit Tiefe.\p"
	.string "Kannst du sie so perfekt anwenden, wie\n"
	.string "ich es kann?$"

MoveTutor_Text_MetronomeTeach:
	.string "Ich will alles Mögliche haben… Aber\n"
	.string "ich habe mein ganzes Geld ausgegeben…\p"
	.string "Ach, ich fände es toll, wenn es einen\n"
	.string "Spruch gäbe, bei dem man nur mit dem\l"
	.string "Finger wackelt und schon hat man Geld.\p"
	.string "Wenn du möchtest, bringe ich einem\n"
	.string "deiner POKéMON METRONOM bei.\p"
	.string "Dadurch bekommst du kein Geld, aber\n"
	.string "dein POKéMON wackelt mit dem Finger.$"

MoveTutor_Text_MetronomeDeclined:
	.string "Okay. Solltest du es dir anders\n"
	.string "überlegen - du findest mich hier.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay. Ich werde es ihm beibringen.\n"
	.string "Und welchem soll ich es beibringen?$"

MoveTutor_Text_MetronomeTaught:
	.string "Wackelt ein POKéMON mit seinem Finger\n"
	.string "wie ein METRONOM, passieren die\l"
	.string "schönsten Dinge.\p"
	.string "Wäre das toll, wenn wir das auch\n"
	.string "könnten. Meinst du nicht auch?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Hmpf! Meine Frau vertraut auf\n"
	.string "KRAFTRESERVE, um wach zu bleiben.\p"
	.string "Sie sollte lieber ein Nickerchen halten\n"
	.string "und eine SCHLAFREDE halten.\p"
	.string "Ich kann einem deiner POKéMON\n"
	.string "SCHLAFREDE beibringen. Interessiert?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Schon gut, schon gut. Dann bleib doch\n"
	.string "wach, dank KRAFTRESERVE.$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Oh, was für ein verständiges Kind!\n"
	.string "Welchem POKéMON soll ich es beibringen?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Ich kann meine Frau einfach nicht\n"
	.string "überlisten…\p"
	.string "Stattdessen hört sie interessiert\n"
	.string "meiner SCHLAFREDE zu…$"

MoveTutor_Text_SubstituteTeach:
	.string "Wenn ich die weite Welt von hier oben\n"
	.string "aus betrachte…\p"
	.string "dann wünschte ich mir, es gäbe mich\n"
	.string "mehr als einmal, damit ich alle schönen\l"
	.string "Dinge des Lebens genießen kann.\p"
	.string "Aber das ist ja leider nicht möglich…\n"
	.string "Kicher…\p"
	.string "Ich weiß! Soll ich einem deiner POKéMON\n"
	.string "DELEGATOR beibringen?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh? Nicht?\p"
	.string "Ein POKéMON könnte damit aber einen\n"
	.string "Doppelgänger von sich schaffen!$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Kicher…\n"
	.string "Welchem POKéMON soll ich es beibringen?$"

MoveTutor_Text_SubstituteTaught:
	.string "Wir Menschen sollten unser Leben voll\n"
	.string "ausschöpfen und genießen!\p"
	.string "Ich hoffe, du tust das bereits!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Ich kann nicht mehr!\p"
	.string "Das ist doch absolut hoffnungslos!\p"
	.string "Ich bin ein KAMPF-TRAINER, daher kann\n"
	.string "ich in der ARENA von MOOSBACH einfach\p"
	.string "nicht gewinnen, egal, wie sehr ich mich\n"
	.string "auch anstrenge!\p"
	.string "Argh! Schlag! Wucht! Schlag!\n"
	.string "Schlag! Wucht! Schlag!\p"
	.string "Hey, was starrst du mich so an?!?\n"
	.string "Ich schlage doch nur auf den Boden ein!\p"
	.string "Oder möchtest du, dass ich einem deiner\n"
	.string "POKéMON WUCHTSCHLAG beibringe?!?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Mist! Du machst dich lustig über mich!!!\n"
	.string "Schlag! Wucht! Schlag!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Das möchtest du? Das ist klug von dir!\n"
	.string "Welchem POKéMON soll ich es beibringen?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Ich möchte, dass du in der ARENA von\n"
	.string "MOOSBACH gewinnst, indem du\l"
	.string "WUCHTSCHLAG einsetzt.$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Seufz…\p"
	.string "Der ARENALEITER von XENEROVILLE ist\n"
	.string "einfach anbetungswürdig.\p"
	.string "Aber das heißt auch, dass ich viele\n"
	.string "Rivalinnen habe, die um seine Gunst\l"
	.string "kämpfen.\p"
	.string "Er wurde mit RISIKOTACKLE verzaubert.\n"
	.string "Unsere Augen trafen sich nicht.\p"
	.string "Darf ich einem deiner POKéMON\n"
	.string "RISIKOTACKLE beibringen?$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Auch du lehnst mich also ab…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Schön!!! Welchem POKéMON soll ich\n"
	.string "RISIKOTACKLE beibringen?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Ich werde nicht mehr für die Liebe\n"
	.string "leben! Ich werde stark werden!$"

MoveTutor_Text_ExplosionTeach:
	.string "Ich habe nicht vor, lange hier in der\n"
	.string "Ödnis zu bleiben.\p"
	.string "Pass nur auf! Ich werde diesen Ort\n"
	.string "verlassen und ganz groß rauskommen!\p"
	.string "Ernsthaft! Mein Ruhm wird\n"
	.string "explosionsartig zum Vorschein kommen.\p"
	.string "Wenn du an mich glaubst, bringe ich\n"
	.string "einem deiner POKéMON EXPLOSION bei.$"

MoveTutor_Text_ExplosionDeclined:
	.string "Argh! Nur weil ich in der Pampa lebe,\n"
	.string "ignorierst du mein Angebot?!?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Super! Das wird eine EXPLOSION!\n"
	.string "Welchem POKéMON soll ich es beibringen?$"

MoveTutor_Text_ExplosionTaught:
	.string "Schon lange bringe ich POKéMON\n"
	.string "EXPLOSION bei. Jetzt wird es Zeit an\l"
	.string "meine eigene EXPLOSION zu denken…\p"
	.string "Vielleicht bin ich schon so lange hier,\n"
	.string "weil es mir hier doch gefällt?!?$"
