gText_ObtainedTheItem::
	.string "{STR_VAR_2} erhalten!$"

gText_TheBagIsFull::
	.string "Der BEUTEL ist voll…$"

gText_PutItemInPocket::
	.string "{PLAYER} packt {STR_VAR_2} in die\n"
	.string "{STR_VAR_3}-TASCHE.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} hat {STR_VAR_2} gefunden!$"

gText_TooBadBagIsFull::
	.string "Zu schade!\n"
	.string "Der BEUTEL ist voll…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} packt {STR_VAR_2}\n"
	.string "in den BEUTEL.$"

gText_ObtainedTheDecor::
	.string "{STR_VAR_2} erhalten.$"

gText_NoRoomLeftForAnother::
	.string "Zu schade! Es ist kein Platz für\n"
	.string "{STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} wurde auf den PC\n"
	.string "übertragen.$"

gText_ObtainedTheItems::
	.string "{STR_VAR_1} {STR_VAR_2} erhalten!$"

gText_PlayerFoundItems::
	.string "{PLAYER} hat {STR_VAR_1} {STR_VAR_2}\n"
	.string "gefunden!$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} legt die MÜNZEN in den\n"
	.string "MÜNZKORB.$"

gText_FoundXCoins::
	.string "{PLAYER} hat\n"
	.string "{STR_VAR_1} {STR_VAR_2} gefunden!$"

gText_FoundXItems::
	.string "{PLAYER} hat\n"
	.string "{STR_VAR_1} {STR_VAR_2} gefunden!$"

gText_CoinCaseIsFull::
	.string "Zu schade!\n"
	.string "Der MÜNZKORB ist voll…$"

gText_NothingToPutThemIn::
	.string "Zu schade!\n"
	.string "Es gibt nichts, um sie aufzubewahren…$"
