Text_BootUpPC:
	.string "{PLAYER} booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Zugriff auf wessen PC?$"

gText_AccessedSomeonesPC::
	.string "Verbindung zu JEMANDES PC hergestellt.$"

gText_StorageSystemOpened::
	.string "POKéMON-Lagerungs-System geöffnet.$"

gText_AccessedPlayersPC::
	.string "Verbindung mit PC von {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Verbindung zu LANETTEs PC hergestellt.$"

gText_AccessedBillsPC::
	.string "Accessed BILL's PC.$"
