gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} wurde auf JEMANDES PC\n"
	.string "übertragen.\p"
	.string "Es wurde in BOX\n"
	.string "“{STR_VAR_1}” abgelegt.$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} wurde auf LANETTEs PC\n"
	.string "übertragen.\p"
	.string "Es wurde in BOX\n"
	.string "“{STR_VAR_1}” abgelegt.$"
#if IS_FRLG
#else
#endif

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "BOX “{STR_VAR_3}” in\n"
	.string "JEMANDES PC ist voll.\p"
	.string "{STR_VAR_2} wurde in BOX\n"
	.string "“{STR_VAR_1}” übertragen.$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "BOX “{STR_VAR_3}” in\n"
	.string "LANETTEs PC ist voll.\p"
	.string "{STR_VAR_2} wurde in BOX\n"
	.string "“{STR_VAR_1}” übertragen.$"
#if IS_FRLG
#else
#endif

gText_PkmnSentToPCAfterCatch::
	.string "{STR_VAR_2} wurde in\n"
	.string "{B_PC_CREATOR_NAME} PC geschickt.\p"
	.string "Es kam in\n"
	.string "BOX “{STR_VAR_1}”.$"

gText_PlayerObtainedTheMon::
	.string "{PLAYER} erhält\n"
	.string "{STR_VAR_1}!$"

gText_NoMoreRoomForPokemon::
	.string "Es ist kein Platz mehr für POKéMON\n"
	.string "vorhanden!\p"
	.string "Die POKéMON BOXen sind voll und\n"
	.string "es kann kein POKéMON mehr\l"
	.string "abgelegt werden!$"

gText_NicknameThisPokemon::
	.string "Möchtest du {STR_VAR_1} einen\n"
	.string "Spitznamen geben?$"
