gText_WouldYouLikeToRestYourPkmn::
	.string "Ouh NJERI, söll ich dini\n"
	.string "Pokemon heile?$"

gText_IllTakeYourPkmn::
	.string "Also guet, denn dun ich sie\n"
	.string "schnell i die gflashti\l"
	.string "Machine da.$"

gText_RestoredPkmnToFullHealth::
	.string "Tip-top!\p"
	.string "Dini Pokemon sind wieder\n"
	.string "back im Biz!$"

gText_WeHopeToSeeYouAgain::
	.string "Bis denn!$"

gText_WelcomeCutShort::
	.string "Ouh NJERI, söll ich dini\n"
	.string "Pokemon heile?$"

gText_NoticesGoldCard::
	.string "Ouh NJERI!\p"
	.string "Sogar mit ere Goldcharte?\n"
	.string "Wild, aber egal.\p"
	.string "Ich heil dini Pokemon jetzt\n"
	.string "extra professionell.$"

gText_YouWantTheUsual::
	.string "Ouh NJERI!\n"
	.string "Söll ich wie immer dini\l"
	.string "Pokemon heile?$"

gText_IllTakeYourPkmn2::
	.string "Also guet, denn dun ich sie\n"
	.string "schnell i die gflashti\l"
	.string "Machine da.$"

gText_ThankYouForWaiting::
	.string "Tip-top!\p"
	.string "Dini Pokemon sind wieder\n"
	.string "back im Biz!$"

gText_WeHopeToSeeYouAgain2::
	.string "Bis denn!$"