gBirchDexRatingText_AreYouCurious::
	.string "PROF. LUNTE: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte\n"
	.string "mit dem POKéDEX zeigen?$"

gBirchDexRatingText_Cancel::
	.string "Ach? Du hast erst so wenige\n"
	.string "POKéMON gefangen, dass es sich\l"
	.string "nicht lohnt, ihn mir zu zeigen?$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "Oh, du hast {STR_VAR_1} POKéMON gesehen\n"
	.string "und {STR_VAR_2} POKéMON gefangen…$"

gBirchDexRatingText_LessThan10::
	.string "Du solltest mehr ins hohe Gras\n"
	.string "gehen und mehr auf POKéMON\l"
	.string "achten.$"

gBirchDexRatingText_LessThan20::
	.string "So langsam bekommst du den Bogen\n"
	.string "raus. Aber es wird immer schwieriger\l"
	.string "werden!$"

gBirchDexRatingText_LessThan30::
	.string "Einige POKéMON tauchen nur in be-\n"
	.string "stimmten Regionen auf.\l"
	.string "Hab nur Geduld.$"

gBirchDexRatingText_LessThan40::
	.string "Nun, er könnte mehr Einträge\n"
	.string "enthalten, aber es sieht schon\l"
	.string "eher nach einem POKéDEX aus.$"

gBirchDexRatingText_LessThan50::
	.string "Das läuft doch wunderbar.\n"
	.string "Mach weiter so.$"

gBirchDexRatingText_LessThan60::
	.string "Verwendest du irgendwelche\n"
	.string "ANGELn?\l"
	.string "Hier gibt es viele POKéMON im Meer.$"

gBirchDexRatingText_LessThan70::
	.string "Statt die POKéMON nur zu fangen,\n"
	.string "wie wäre es, sie sich entwickeln zu\l"
	.string "lassen?$"

gBirchDexRatingText_LessThan80::
	.string "Der POKéDEX wird einfach\n"
	.string "fantastisch.\l"
	.string "Das habe ich im Gefühl…$"

gBirchDexRatingText_LessThan90::
	.string "Du hast so viele gefangen…\n"
	.string "Du hast ein außergewöhnliches\l"
	.string "Talent!$"

gBirchDexRatingText_LessThan100::
	.string "Warst du schon mal in der\n"
	.string "SAFARI ZONE?\p"
	.string "Ich habe gehört, es gibt POKéMON,\n"
	.string "die man nur dort finden kann.$"

gBirchDexRatingText_LessThan110::
	.string "Du hast die 100er-Marke\n"
	.string "überschritten!\p"
	.string "Das ist ein beeindruckender\n"
	.string "POKéDEX!$"

gBirchDexRatingText_LessThan120::
	.string "Es gibt auch POKéMON, die man\n"
	.string "durch den Einsatz von\l"
	.string "ZERTRÜMMERER findet.$"

gBirchDexRatingText_LessThan130::
	.string "Du solltest einige POKéMON fangen\n"
	.string "und sie mit anderen tauschen.$"

gBirchDexRatingText_LessThan140::
	.string "Ich habe von POKéMON gehört, die\n"
	.string "sich entwickeln, wenn sie ihren\l"
	.string "TRAINER sehr lieben.$"

gBirchDexRatingText_LessThan150::
	.string "Ich hatte keine Ahnung, dass es in\n"
	.string "der HOENN-Region so viele\l"
	.string "verschiedene POKéMON-Arten gibt.$"

gBirchDexRatingText_LessThan160::
	.string "Manchmal erscheinen einige\n"
	.string "POKéMON in großer Anzahl\p"
	.string "wie bei einem Ausbruch.\n"
	.string "Das solltest du nicht verpassen!$"

gBirchDexRatingText_LessThan170::
	.string "Dein POKéDEX liefert einen\n"
	.string "erstaunlich guten Einblick in die\l"
	.string "POKéMON der HOENN-Region!$"

gBirchDexRatingText_LessThan180::
	.string "Ich sage, du hast dich bereits als\n"
	.string "guter POKéMON-PROFESSOR\l"
	.string "qualifiziert.$"

gBirchDexRatingText_LessThan190::
	.string "Mit diesem POKéDEX, der schon so\n"
	.string "weit gediehen ist, bist du ein\l"
	.string "echter Profi.$"

gBirchDexRatingText_LessThan200::
	.string "Du bist sehr nahe dran, den\n"
	.string "POKéDEX zu vervollständigen.\l"
	.string "Das fühle ich einfach.$"

gBirchDexRatingText_DexCompleted::
	.string "Herzlichen Glückwunsch!\n"
	.string "Dein POKéDEX ist vollständig!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "Auf nationaler Ebene…\p"
	.string "hast du {STR_VAR_1} POKéMON gesehen\n"
	.string "und {STR_VAR_2} POKéMON gefangen…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"
