Questionnaire_Text_FillOut::
	.string "Dort liegt ein Fragebogen.\n"
	.string "Möchtest du ihn ausfüllen?$"

Questionnaire_Text_ThankYou::
	.string "Danke, dass du dir die Zeit\n"
	.string "genommen hast, den\l"
	.string "Fragebogen auszufüllen.\l"
	.string "Deine Antworten werden ausgewertet\l"
	.string "und zukünftig berücksichtigt.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, hallo!\n"
	.string "Kennst du diese Worte?\p"
	.string "Das bedeutet, du weißt über die\n"
	.string "GEHEIMGESCHEHEN Bescheid.\p"
	.string "Von nun an kannst du\n"
	.string "GEHEIMGESCHEHEN empfangen.$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Sobald du dein Spiel gesichert\n"
	.string "hast, kannst du GEHEIMGESCHEHEN\l"
	.string "auswählen.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Oh, hallo!\n"
	.string "Kennst du diese Worte?\p"
	.string "Das bedeutet, du weißt über die\n"
	.string "GEHEIMGESCHEHEN Bescheid.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Sobald du dein Spiel gesichert\n"
	.string "hast, kannst du GEHEIMGESCHEHEN\l"
	.string "auswählen.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Danke, dass du das GEHEIM-\n"
	.string "GESCHEHEN benutzt hast.\p"
	.string "Du musst {PLAYER} sein.\n"
	.string "Hier ist ein Ticket für dich!$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Du kannst es am Hafen von\n"
	.string "SEEGRASULB CITY einsetzen.\p"
	.string "Warum probierst du es nicht\n"
	.string "einfach aus?$"
