	.align 2
gText_ConfirmSave::
	.string "Möchtest du das Spiel speichern?$"

gText_AlreadySavedFile::
	.string "Es gibt bereits einen Spielstand.\n"
	.string "Spielstand überschreiben?$"

gText_SavingDontTurnOff::
	.string "SPEICHERN…\n"
	.string "BITTE DAS GERÄT NICHT AUSSCHALTEN.$"

gText_PlayerSavedGame::
	.string "{PLAYER} hat das Spiel gespeichert.$"

gText_DifferentSaveFile::
	.string "ACHTUNG!\p"
	.string "Es gibt bereits einen Spielstand.\p"
	.string "Wenn jetzt gesichert wird, geht\n"
	.string "der andere Spielstand mit allen\l"
	.string "Items und POKéMON für immer\l"
	.string "verloren.\l"
	.string "Bist du sicher, dass du sichern\l"
	.string "und den anderen Spielstand\l"
	.string "überschreiben möchtest?$"

gText_SaveError::
	.string "Fehler beim Speichern!\p"
	.string "Bitte Backup Memory\n"
	.string "austauschen.$"

gText_SavingDontTurnOffPower::
	.string "SPEICHERN…\n"
	.string "BITTE DAS GERÄT NICHT AUSSCHALTEN.$"
