SecretBase_Text_Trainer0Intro:
	.string "Hast du dir schon eine SECRET BASE\n"
	.string "eingerichtet?\p"
	.string "Ich bin hier und dort, überall hin-\n"
	.string "gelaufen, bevor ich mich für diesen\l"
	.string "Ort entschieden habe.\p"
	.string "Da du schon mal hier bist… Hast du\n"
	.string "Lust zu kämpfen?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "Okay!\n"
	.string "Jetzt kommen wir!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Wie? Was? Wo?\n"
	.string "Du kannst doch nicht…$"

SecretBase_Text_Trainer0Defeated::
	.string "Ahaaargh! Du bist zu stark für mich! Ich\n"
	.string "habe verloren, aber verrate das nicht!$"

SecretBase_Text_Trainer0PostBattle:
	.string "Was hältst du von meiner SECRET BASE?\n"
	.string "Komm mich doch morgen wieder besuchen!$"

SecretBase_Text_Trainer0PreChampion:
	.string "Hast du dir schon eine SECRET BASE\n"
	.string "eingerichtet?\p"
	.string "Ich bin hier und dort, überall hin-\n"
	.string "gelaufen, bevor ich mich für diesen\l"
	.string "Ort entschieden habe.\p"
	.string "Schau dich ruhig in aller Ruhe um.$"

SecretBase_Text_Trainer5Intro:
	.string "Es gibt eine Menge Orte, an denen man\n"
	.string "eine SECRET BASE einrichten kann.\p"
	.string "Aber dieser hier gefällt mir am besten.\n"
	.string "Findest du es nicht auch nett hier?\p"
	.string "Oh, hast du Lust auf einen Kampf?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "Okay, los geht’s!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Oh…\n"
	.string "Du hast gerade keine Zeit.$"

SecretBase_Text_Trainer5Defeated::
	.string "Hmm… Das ist unsere Niederlage…\n"
	.string "Aber erzähl das bloß nicht weiter!\l"
	.string "Das ist ein streng geheimes Geheimnis!$"

SecretBase_Text_Trainer5PostBattle:
	.string "Wenn du wieder mal in der Nähe bist,\n"
	.string "komm mich doch besuchen!$"

SecretBase_Text_Trainer5PreChampion:
	.string "Es gibt eine Menge Orte, an denen man\n"
	.string "eine SECRET BASE einrichten kann.\p"
	.string "Aber dieser hier gefällt mir am besten.\n"
	.string "Findest du es nicht auch nett hier?$"

SecretBase_Text_Trainer1Intro:
	.string "Dies ist ein beliebter Platz.\n"
	.string "Er ist eigentlich immer besetzt.\p"
	.string "Ach, du wolltest dich hier auch\n"
	.string "häuslich niederlassen?\p"
	.string "Ich sag dir was: Du kannst den Platz\n"
	.string "haben, wenn du mich besiegen kannst.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "Okay! Ich werde meine\n"
	.string "SECRET BASE verteidigen!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Was? Stimmt das? Du hast gar\n"
	.string "kein Interesse an diesem Platz?!?$"

SecretBase_Text_Trainer1Defeated::
	.string "Ich kann nicht mehr!\n"
	.string "Ich gebe mich geschlagen!$"

SecretBase_Text_Trainer1PostBattle:
	.string "Okay, wenn ich eines Tages von hier\n"
	.string "fortziehe, kannst du den Platz haben.$"

SecretBase_Text_Trainer1PreChampion:
	.string "Dies ist ein beliebter Platz.\n"
	.string "Er ist eigentlich immer besetzt.\p"
	.string "Ich habe ewig gewartet, bis er wieder\n"
	.string "frei wurde. Endlich ist es soweit!$"

SecretBase_Text_Trainer6Intro:
	.string "Willkommen in meinem POKéMON-LABOR.\p"
	.string "Ich forsche, indem ich im Geheimen\n"
	.string "kämpfe.\p"
	.string "Möchtest du sehen, wie stark ich bin?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "Das war ja wohl nichts!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Oh.\n"
	.string "Ein anderes Mal vielleicht…$"

SecretBase_Text_Trainer6Defeated::
	.string "Hm… Ich muss noch viel lernen.\n"
	.string "Ich muss fleißiger studieren.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Danke, dass du mit mir gekämpft hast.\n"
	.string "Komm doch bitte morgen wieder.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Willkommen in meinem POKéMON-LABOR.\p"
	.string "Ich forsche, indem ich im Geheimen\n"
	.string "kämpfe.$"

SecretBase_Text_Trainer2Intro:
	.string "Ein großes Anwesen ist natürlich auch\n"
	.string "ganz nett, aber hier ist es schöner.\p"
	.string "Viele Leute kommen mich besuchen.\p"
	.string "So. Wie wäre es mit einem Kampf?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "Genauso muss es laufen!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "Wenn du bereit bist, sag Bescheid.$"

SecretBase_Text_Trainer2Defeated::
	.string "Ooch! Ich hab’s vergeigt!\n"
	.string "Aber es hat sehr viel Spaß gemacht!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Egal. Ich sollte mir auf jeden Fall\n"
	.string "einige Dekorationen und Möbel zulegen.\p"
	.string "Ich möchte, dass sich auch andere in\n"
	.string "meiner SECRET BASE wohl fühlen.$"

SecretBase_Text_Trainer2PreChampion:
	.string "Ein großes Anwesen ist natürlich auch\n"
	.string "ganz nett, aber hier ist es schöner.\p"
	.string "Viele Leute kommen mich besuchen.$"

SecretBase_Text_Trainer7Intro:
	.string "Ich liebe es, Dekorationen und Möbel\n"
	.string "zu kaufen!!!\p"
	.string "Ich liebe es genauso, POKéMON aufzu-\n"
	.string "ziehen!\p"
	.string "Wärest du so nett, mit meinen\n"
	.string "POKéMON zu kämpfen?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Danke schön.\n"
	.string "Bist du bereit?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Oh.\n"
	.string "Was für eine Enttäuschung.$"

SecretBase_Text_Trainer7Defeated::
	.string "Ich ergebe mich!$"

SecretBase_Text_Trainer7PostBattle:
	.string "Das war vielleicht ein Spaß! Und nun\n"
	.string "sollte ich mich dem Einkaufen widmen.$"

SecretBase_Text_Trainer7PreChampion:
	.string "Ich liebe es, Dekorationen und Möbel\n"
	.string "zu kaufen!!!\p"
	.string "Ich liebe es genauso, POKéMON aufzu-\n"
	.string "ziehen!$"

SecretBase_Text_Trainer3Intro:
	.string "Einige Leute richten ihre SECRET BASE\n"
	.string "an gut versteckten Orten ein. Wollen\l"
	.string "sie sich nicht mehr sehen lassen?\p"
	.string "Da du mich gefunden hast, lass uns\n"
	.string "doch gleich mal kämpfen.$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "Ich bin nicht einfach zu besiegen!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Oh. Sag bloß, du bist müde von der Suche\n"
	.string "nach diesem Platz?$"

SecretBase_Text_Trainer3Defeated::
	.string "Ich bin untergegangen…$"

SecretBase_Text_Trainer3PostBattle:
	.string "Wo ist deine SECRET BASE?\n"
	.string "Ich sollte dich dort mal besuchen.$"

SecretBase_Text_Trainer3PreChampion:
	.string "Einige Leute richten ihre SECRET BASE\n"
	.string "an gut versteckten Orten ein. Wollen\l"
	.string "sie sich nicht mehr sehen lassen?$"

SecretBase_Text_Trainer8Intro:
	.string "Einige Leute haben mir erzählt, dass\n"
	.string "man auf verschiedene Arten an Deko-\l"
	.string "rationen kommen kann.\p"
	.string "Wir sollten einen Wettbewerb veran-\n"
	.string "stalten, wer die schönsten Dinge hat.\p"
	.string "Aber zuerst lass uns kämpfen.$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "Das ist meine SECRET BASE.\n"
	.string "Ich kann hier gar nicht verlieren!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Ich kämpfe jederzeit mit dir.$"

SecretBase_Text_Trainer8Defeated::
	.string "Wie?\n"
	.string "Ich habe doch verloren?$"

SecretBase_Text_Trainer8PostBattle:
	.string "Ich werde den Wettbewerb um die\n"
	.string "schönsten Dekorationen nicht ver-\l"
	.string "lieren. Überzeuge dich selbst!$"

SecretBase_Text_Trainer8PreChampion:
	.string "Einige Leute haben mir erzählt, dass\n"
	.string "man auf verschiedene Arten an Deko-\l"
	.string "rationen kommen kann.\p"
	.string "Wir sollten einen Wettbewerb veran-\n"
	.string "stalten, wer die schönsten Dinge hat.$"

SecretBase_Text_Trainer4Intro:
	.string "Ich habe einen Ort gefunden, der mir\n"
	.string "gefällt und den ich mit meinen Lieb-\l"
	.string "lingsdekorationen ausgestattet habe.\p"
	.string "Dort ziehe ich meine Lieblings-POKéMON\n"
	.string "auf und werde mit ihnen stärker.\p"
	.string "Genau das mache ich.\n"
	.string "Möchtest du mit mir kämpfen?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Zeig mir, aus welchem Holz du\n"
	.string "geschnitzt bist.$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Ich glaube, es gibt immer wieder Zeiten,\n"
	.string "in denen man nicht so gut drauf ist.$"

SecretBase_Text_Trainer4Defeated::
	.string "Ich weiß jetzt genau, aus welchem Holz\n"
	.string "du geschnitzt bist.$"

SecretBase_Text_Trainer4PostBattle:
	.string "Wir können beide noch stärker werden!\n"
	.string "Das macht doch Mut!$"

SecretBase_Text_Trainer4PreChampion:
	.string "Ich habe einen Ort gefunden, der mir\n"
	.string "gefällt und den ich mit meinen Lieb-\l"
	.string "lingsdekorationen ausgestattet habe.\p"
	.string "Dort ziehe ich meine Lieblings-POKéMON\n"
	.string "auf und werde mit ihnen stärker.\p"
	.string "Jeder Tag ist mein Lieblingstag.$"

SecretBase_Text_Trainer9Intro:
	.string "Man lernt viel über den Geschmack und\n"
	.string "den Stil von Menschen, wenn man sich\l"
	.string "ihre Dekorationen und den Platz, auf\l"
	.string "dem sie stehen, anschaut.\p"
	.string "Wie findest du meinen Geschmack?\n"
	.string "Bist du sprachlos? Hihihi…\p"
	.string "Willst du mal meinen Kampfstil sehen?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "Es gibt kein Zurück mehr.$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Ich zeige dir gerne jederzeit wieder \n"
	.string "meinen erlesenen Kampfstil!$"

SecretBase_Text_Trainer9Defeated::
	.string "Du bist hoch talentiert! Deine Stärke\n"
	.string "scheint grenzenlos zu sein.$"

SecretBase_Text_Trainer9PostBattle:
	.string "Was hältst du von meinem Stil?\n"
	.string "Ich muss ihn noch mehr aufpolieren.$"

SecretBase_Text_Trainer9PreChampion:
	.string "Man lernt viel über den Geschmack und\n"
	.string "den Stil von Menschen, wenn man sich\l"
	.string "ihre Dekorationen und den Platz, auf\l"
	.string "dem sie stehen, anschaut.\p"
	.string "Wie findest du meinen Geschmack?\n"
	.string "Bist du sprachlos? Hihihi…$"
