Route102_Text_CalvinIntro:
	.string "Gefährlich,\n"
	.string "was ist hier los?!$"

Route102_Text_CalvinDefeat:
	.string "Scheisse man!$"

Route102_Text_CalvinNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route102_Text_CalvinAfter:
	.string "Wer fühlsch am meiste\n"
	.string "vo 187?$"

Route102_Text_CalvinPostBattle:
	.string "Wer fühlsch am meiste\n"
	.string "vo 187?$"

Route102_Text_CalvinRegister:
	.string "Ich habe hart gearbeitet, seit ich\n"
	.string "dich das letzte Mal gesehen habe!\p"
	.string "Ich würde gerne wieder gegen dich\n"
	.string "kämpfen. Kannst du mich bitte in deinen\l"
	.string "POKéNAV eintragen?$"

Route102_Text_CalvinRegisterShort:
	.string "Ich würde gerne wieder gegen dich\n"
	.string "kämpfen. Kannst du mich bitte in deinen\l"
	.string "POKéNAV eintragen?$"

Route102_Text_CalvinRematchIntro:
	.string "Seit ich gegen dich verloren habe,\n"
	.string "trainiere ich verzweifelt meine\l"
	.string "POKéMON. Sag nicht nein zu einem Kampf!$"

Route102_Text_CalvinRematchDefeated:
	.string "Aaaah, ich habe schon wieder verloren…\n"
	.string "Ob ich nicht richtig trainiere?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Wenn du stärker wirst, werde ich auch\n"
	.string "stärker.$"

Route102_Text_AllenIntro:
	.string "Ich zeig der wo de Hammer\n"
	.string "hängt, wie Obi Mitarbeiter!$"

Route102_Text_AllenDefeat:
	.string "Fuck!$"

Route102_Text_AllenNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route102_Text_AllenAfter:
	.string "Ich han nüüt gseit,\n"
	.string "gahn eifach wiiter.$"

Route102_Text_AllenPostBattle:
	.string "Ich han nüüt gseit,\n"
	.string "gahn eifach wiiter.$"

Route102_Text_RickIntro:
	.string "Ich suech de Japan Chäfer,\n"
	.string "aber jetzt trampsch du da\l"
	.string "uf de Wiese ume...$"

Route102_Text_RickDefeat:
	.string "Scheiss Viecher man...$"

Route102_Text_RickNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route102_Text_RickAfter:
	.string "Ich suech wieder de\n"
	.string "Japan Chäfer.\p"
	.string "Du bisch mer z' starch.$"

Route102_Text_RickPostBattle:
	.string "Ich suech wieder de\n"
	.string "Japan Chäfer.\p"
	.string "Du bisch mer z' starch.$"

Route102_Text_TianaIntro:
	.string "Mal luege, ob mini Pokemon\n"
	.string "gege so en NJERI wie dich\l"
	.string "chönd günne.$"

Route102_Text_TianaDefeat:
	.string "Egal, wenigstens bin ich\n"
	.string "hübscher als du.$"

Route102_Text_TianaNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route102_Text_TianaAfter:
	.string "Irgendwenn nimm ich's mit\n"
	.string "dir uuf, NJERI.$"

Route103_Text_DaisyIntro:
	.string "Ich zeig der es Pokemon\n"
	.string "wo du no nie gseh hesch.$"

Route103_Text_DaisyDefeated:
	.string "Wow!$"

Route103_Text_DaisyNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route103_Text_DaisyPostBattle:
	.string "Ich han Polle im Aug!$"

Route103_Text_AmyIntro:
	.string "Eusi Oma het eus e Villa\n"
	.string "gschenkt, will ihre die\l"
	.string "z'chlii worde isch.\p"
	.string "Also was wettsch du scho\n"
	.string "geg eus mache hmm?$"

Route103_Text_AmyDefeated:
	.string "WASSS?!$"

Route103_Text_AmyPostBattle:
	.string "Ich glaub mir bruuched\n"
	.string "e grösseri Villa.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route103_Text_LivIntro:
	.string "Eusi Oma het eus e Villa\n"
	.string "gschenkt, will ihre die\l"
	.string "z'chlii worde isch.\p"
	.string "Also was wettsch du scho\n"
	.string "geg eus mache hmm?$"

Route103_Text_LivDefeated:
	.string "WASSS?!$"

Route103_Text_LivPostBattle:
	.string "Ich glaub mir bruuched\n"
	.string "e grösseri Villa.$"

Route103_Text_LivNotEnoughPokemon:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

	Route103_Text_AmyLivRegister:
	.string "Mir gänd dir sicher nöd\n"
	.string "eusi Nummer.$"

Route103_Text_AmyRematchIntro:
	.string "Eusi Oma het eus e Villa\n"
	.string "gschenkt, will ihre die\l"
	.string "z'chlii worde isch.\p"
	.string "Also was wettsch du scho\n"
	.string "geg eus mache hmm?$"

Route103_Text_AmyRematchDefeated:
	.string "WASSS?!$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route103_Text_AmyRematchPostBattle:
	.string "Ich glaub mir bruuched\n"
	.string "e grösseri Villa.$"

Route103_Text_LivRematchIntro:
	.string "Eusi Oma het eus e Villa\n"
	.string "gschenkt, will ihre die\l"
	.string "z'chlii worde isch.\p"
	.string "Also was wettsch du scho\n"
	.string "geg eus mache hmm?$"

Route103_Text_LivRematchDefeated:
	.string "WASSS?!$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route103_Text_LivRematchPostBattle:
	.string "Ich glaub mir bruuched\n"
	.string "e grösseri Villa.$"

Route103_Text_AndrewIntro:
	.string "Pass uf! Mis Karpador isch\n"
	.string "10x besser als jedes andere\l"
	.string "Karpador wo du bis jetzt\l"
	.string "gseh hesch.$"

Route103_Text_AndrewDefeated:
	.string "Neii!!!\p"
	.string "Mis perfekte Karpador...$"

Route103_Text_AndrewNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route103_Text_AndrewPostBattle:
	.string "Wart's ab, irgendwenn\n"
	.string "besieg ich dich mitnem\l"
	.string "perfekte Garados!$"

Route103_Text_MiguelIntro:
	.string "Glaub mer es isch en\n"
	.string "Fehler gsii, mich\l"
	.string "ah z'spreche.$"

Route103_Text_MiguelDefeated:
	.string "Tami!$"

Route103_Text_MiguelNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route103_Text_MiguelPostBattle:
	.string "Bis jetzt han ich no\n"
	.string "nie verlore...$"

Route103_Text_MiguelRegister:
	.string "Ich muss dafür sorgen, dass du dir\n"
	.string "mein wunderbares POKéMON bald wieder\l"
	.string "anschaust.$"

Route103_Text_MiguelRematchIntro:
	.string "Hey, du! Mein anbetungswürdiges\n"
	.string "POKéMON ist noch anbetungswürdiger\l"
	.string "geworden.$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh!\n"
	.string "Mein geliebtes POKéMON.$"

Route103_Text_MiguelRematchPostBattle:
	.string "Je mehr Zeit ich mit ihm verbringe,\n"
	.string "desto anbetungswürdiger wird es.$"

Route103_Text_PeteIntro:
	.string "Diese kurze Strecke…\n"
	.string "Die kann man doch locker schwimmen.$"

Route103_Text_PeteDefeated:
	.string "Oh, das war starker Wellengang.$"

Route103_Text_PetePostBattle:
	.string "Mir ist klar, woher du kommst.\p"
	.string "Wenn ich ein POKéMON hätte, dem ich\n"
	.string "so vertrauen könnte, würde ich ihm\l"
	.string "auch SURFER beibringen.$"

Route103_Text_IsabelleIntro:
	.string "Pass doch auf, wo du hinsurfst!\n"
	.string "Wir stoßen noch zusammen!$"

Route103_Text_IsabelleDefeated:
	.string "Stöhn…$"

Route103_Text_IsabellePostBattle:
	.string "Ich bin eine lausige SCHWIMMERIN, daher\n"
	.string "übe ich hier… Tut mir Leid, dass\l"
	.string "ich fast in dich hineingeschwommen bin.$"

Route103_Text_RhettIntro:
	.string "Ich klatsch dich!$"

Route103_Text_RhettDefeated:
	.string "Verdammt! Du hesch mich\n"
	.string "wegklatscht...$"

Route103_Text_RhettNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route103_Text_RhettPostBattle:
	.string "Warts ab. Negscht mal\n"
	.string "klatsch ich dich!$"

Route103_Text_MarcosIntro:
	.string "DÜBI isch mini Heimat\n"
	.string "und ich verbüüte dir dett\l"
	.string "here z'gah!$"

Route103_Text_MarcosDefeated:
	.string "Holy Shi-$"

Route103_Text_MarcosNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route103_Text_MarcosPostBattle:
	.string "Ich erlaubs dir trotzdem\n"
	.string "nöd zum wiiter gah...\p"
	.string "Was? Es isch der egal\n"
	.string "was ich seg?\p"
	.string "Okay ich petz dich bide\n"
	.string "Frau Bedenikovic!$"

Route104_Text_GinaIntro:
	.string "GINA: Okay, dann lass uns mit unseren\n"
	.string "POKéMON kämpfen.$"

Route104_Text_GinaDefeat:
	.string "GINA: Wenn ich verliere, bin ich sauer.$"

Route104_Text_GinaPostBattle:
	.string "GINA: Du bist stark!\n"
	.string "Wir müssen doch mehr trainieren!$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: Oh, nur ein POKéMON?\n"
	.string "Dann können wir nicht kämpfen.\p"
	.string "Wenn du nur ein POKéMON hast, wird es\n"
	.string "sich einsam fühlen. Das ist nicht gut.$"

Route104_Text_MiaIntro:
	.string "MIA: Wir sind Zwillinge und kämpfen auch\n"
	.string "mit unseren POKéMON zusammen.$"

Route104_Text_MiaDefeat:
	.string "MIA: Wir haben zusammen gekämpft und\n"
	.string "auch zusammen verloren.$"

Route104_Text_MiaPostBattle:
	.string "MIA: Wir werden unsere POKéMON\n"
	.string "trainieren. Und dann gewinnen wir!$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: Du willst gegen uns kämpfen?\p"
	.string "Ein dickes NEIN - da du weniger als zwei\n"
	.string "POKéMON bei dir hast. Wir sind zu\l"
	.string "stark für dich!$"

Route104_Text_IvanIntro:
	.string "Warum soll ich ein Geheimnis daraus\n"
	.string "machen? Ich bin der…\p"
	.string "WASSER-POKéMON-Experte!\n"
	.string "Wie?!? Du kennst mich nicht?!?$"

Route104_Text_IvanDefeat:
	.string "Ich dachte, ich wäre gar nicht so\n"
	.string "schlecht. Aber… Ach, Mist…$"

Route104_Text_IvanPostBattle:
	.string "Über das Angeln habe ich glatt das\n"
	.string "Training meiner POKéMON vergessen.$"

Route104_Text_BillyIntro:
	.string "Spuren im Sand zu hinterlassen, ist\n"
	.string "total lustig!$"

Route104_Text_BillyDefeat:
	.string "Igitt! Ich habe Sand in den Schuhen!\n"
	.string "Das ist vielleicht unangenehm!$"

Route104_Text_BillyPostBattle:
	.string "Ich will meine Fußspuren im Sand hinter-\n"
	.string "lassen, aber sie verschwinden viel zu\l"
	.string "schnell wieder…$"

Route104_Text_HaleyIntro:
	.string "Soll ich…\n"
	.string "Oder soll ich nicht?\p"
	.string "Okay, natürlich kämpfe ich!$"

Route104_Text_HaleyDefeat:
	.string "Ich hätte doch nicht kämpfen sollen…$"

Route104_Text_HaleyPostBattle:
	.string "Wenn du vor einer Entscheidung stehst\n"
	.string "und einen anderen für dich entscheiden\l"
	.string "lässt, wirst du es bereuen. Egal, was\l"
	.string "dabei am Ende herauskommt.$"

Route104_Text_HaleyRegister1:
	.string "Du bist stark, aber soll ich dich\n"
	.string "wirklich in meinen POKéNAV eintragen?\l"
	.string "Vielleicht lieber nicht…\p"
	.string "Ach, sicher. Ich trage dich ein!$"

Route104_Text_HaleyRegister2:
	.string "Du bist stark, aber soll ich dich\n"
	.string "wirklich in meinem POKéNAV eintragen?\l"
	.string "Vielleicht lieber nicht…\p"
	.string "Ach, sicher. Ich trage dich ein!$"

Route104_Text_HaleyRematchIntro:
	.string "Komm schon, kämpf mit mir!$"

Route104_Text_HaleyRematchDefeat:
	.string "Oohh…\n"
	.string "Ich dachte, ich könnte gewinnen…$"

Route104_Text_HaleyPostRematch:
	.string "Ich kann diesen Verlust der Würde\n"
	.string "akzeptieren. Doch, doch…\p"
	.string "Aber trotzdem bin ich stinkig deswegen.$"

Route104_Text_WinstonIntro:
	.string "Oh, natürlich nehme ich die Heraus-\n"
	.string "forderung an! Ich habe eine Menge Geld.$"

Route104_Text_WinstonDefeat:
	.string "Warum konnte ich nicht gewinnen?$"

Route104_Text_WinstonPostBattle:
	.string "Manche Dinge kann man für Geld nicht\n"
	.string "kaufen. Das sind POKéMON…$"

Route104_Text_WinstonRegister1:
	.string "Hm?\n"
	.string "Oh, du hast einen POKéNAV erhalten.\p"
	.string "Ich werde dich sofort eintragen.\n"
	.string "Schließlich habe ich sehr viel Geld.$"

Route104_Text_WinstonRegister2:
	.string "Hm?\n"
	.string "Oh, du hast einen POKéNAV erhalten.\p"
	.string "Ich werde dich sofort eintragen.\n"
	.string "Schließlich habe ich sehr viel Geld.$"

Route104_Text_WinstonRematchIntro:
	.string "Nachdem ich gegen dich verloren hatte,\n"
	.string "habe ich viel über POKéMON gelernt.$"

Route104_Text_WinstonRematchDefeat:
	.string "Ich habe schon wieder verloren???\n"
	.string "Warum… kann… ich… nicht… gewinnen?$"

Route104_Text_WinstonPostRematch:
	.string "Ich bin unsagbar reich, aber einen\n"
	.string "Kampf kann ich nicht gewinnen…\p"
	.string "Sie ist so tiefgründig, die Welt der\n"
	.string "POKéMON.$"

Route104_Text_CindyIntro:
	.string "Das Schicksal hat uns zusammengeführt.\n"
	.string "Darf ich um einen Kampf bitten?$"

Route104_Text_CindyDefeat:
	.string "Oh, meine Güte!$"

Route104_Text_CindyPostBattle:
	.string "“Hallo” ist der Anfang von\n"
	.string "“Leb wohl”.\l"
	.string "Ich hoffe, wir sehen uns wieder.$"

Route104_Text_CindyRegister1:
	.string "Hallo, so trifft man sich wieder.\p"
	.string "Irgendwie scheinen wir uns anzuziehen.\n"
	.string "Wir sollten uns in unsere POKéNAVs\l"
	.string "eintragen.$"

Route104_Text_CindyRegister2:
	.string "Wir sollten uns stets daran erinnern,\n"
	.string "wie wir uns gegenseitig anziehen.\p"
	.string "Wir sollten uns in unsere POKéNAVs\n"
	.string "eintragen.$"

Route104_Text_CindyRematchIntro:
	.string "Hallo, so treffen wir uns wieder.\n"
	.string "Darf ich dich um einen Kampf bitten?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh je…\n"
	.string "Ich habe mein Bestes gegeben…$"

Route104_Text_CindyPostRematch:
	.string "“Hallo” ist der Anfang von\n"
	.string "“Leb wohl”.\l"
	.string "Ich hoffe, wir sehen uns wieder.$"

Route104_Text_DarianIntro:
	.string "Ich habe mir ein stark aussehendes\n"
	.string "POKéMON geangelt!\p"
	.string "Es besitzt magische Fähigkeiten!\n"
	.string "Aber es sieht sehr stark aus.\l"
	.string "Ja wirklich!$"

Route104_Text_DarianDefeat:
	.string "Was…$"

Route104_Text_DarianPostBattle:
	.string "Hey, KARPADOR, du wirst deinem Namen\n"
	.string "doch nicht gerecht?$"

Route105_Text_FosterIntro:
	.string "Hier in der Gegend soll es einen\n"
	.string "mystischen Felsen geben. Weißt\l"
	.string "du etwas darüber?$"

Route105_Text_FosterDefeated:
	.string "Ich habe zu sehr über den Felsen nach-\n"
	.string "gedacht, so dass meine POKéMON schwach\l"
	.string "blieben…$"

Route105_Text_FosterPostBattle:
	.string "Ich kann Stunden damit verbringen,\n"
	.string "einen Felsen anzustarren, ohne dass\l"
	.string "mir langweilig wird.$"

Route105_Text_LuisIntro:
	.string "Puuh! Als ich dich sah, habe ich zuerst\n"
	.string "gedacht, ein Kind würde ertrinken.\p"
	.string "Dir scheint nichts zu fehlen. Wie wäre\n"
	.string "es deshalb mit einem kleinen Kampf?$"

Route105_Text_LuisDefeated:
	.string "Blubb… blubbb… blubb…$"

Route105_Text_LuisPostBattle:
	.string "Wenn du zu ertrinken drohst, musst du\n"
	.string "mit einem Arm in Richtung Strand winken.$"

Route105_Text_DominikIntro:
	.string "Im tiefen, blauen Meer schwimmen…\n"
	.string "Das ist das Größte überhaupt!$"

Route105_Text_DominikDefeated:
	.string "Ich bin abgesoffen…$"

Route105_Text_DominikPostBattle:
	.string "Warum ist das Meer blau?\p"
	.string "Im MUSEUM in SLATEPORT CITY habe ich\n"
	.string "etwas dazu gelernt, habe es aber\l"
	.string "vergessen.$"

Route105_Text_BeverlyIntro:
	.string "Mein Körper fühlt sich im Wasser\n"
	.string "so leicht an, als hätte ich abgenommen.$"

Route105_Text_BeverlyDefeated:
	.string "Ich lasse mich treiben…$"

Route105_Text_PostBattle:
	.string "Dein Körpergewicht reduziert sich auf\n"
	.string "10 Prozent, wenn du im Wasser bist.\p"
	.string "Dann würde ich nur… Huups! Ich verrate\n"
	.string "dir doch nicht mein Gewicht!$"

Route105_Text_ImaniIntro:
	.string "Der blaue, blaue Himmel…\n"
	.string "Das unendliche Meer…\l"
	.string "Es ist so friedlich…$"

Route105_Text_ImaniDefeated:
	.string "Ich habe verloren, weil ich hier nur\n"
	.string "herumhänge…$"

Route105_Text_ImaniPostBattle:
	.string "So war der Kampf mit mir wenigstens\n"
	.string "entspannend. Kicher…$"

Route105_Text_AndresIntro:
	.string "Ich bin überzeugt, das Meer hat seine\n"
	.string "Geheimnisse vor uns.$"

Route105_Text_AndresDefeated:
	.string "Ja… Ich bin nicht sonderlich\n"
	.string "gut im Kämpfen…$"

Route105_Text_AndresPostBattle:
	.string "Ich weiß es einfach! In den Tiefen der \n"
	.string "Weltmeere liegen viele Geheimnisse, die\l"
	.string "darauf warten, enthüllt zu werden.\p"
	.string "Und ich werde sie alle entdecken!!!$"

Route105_Text_AndresRegister:
	.string "Echt? Ich bin so schwach und trotzdem\n"
	.string "möchtest du mich in deinen POKéNAV\l"
	.string "eintragen?$"

Route105_Text_AndresRematchIntro:
	.string "Ich habe dir doch gesagt, dass ich\n"
	.string "schwach bin… Willst du das wirklich?$"

Route105_Text_AndresRematchDefeated:
	.string "Ja… Ich dachte mir schon, dass\n"
	.string "ich verlieren würde.$"

Route105_Text_AndresRematchPostBattle:
	.string "Ich mag im Kampf schwach sein, aber\n"
	.string "mein Forscherdrang ist unschlagbar!\p"
	.string "Ich werde die Weltmeere bereisen und\n"
	.string "ihre Geheimnisse enthüllen!$"

Route105_Text_JosueIntro:
	.string "Ich bin vom Schwimmen ganz aus der\n"
	.string "Puste. Ich bin es nicht gewohnt.\p"
	.string "Und jetzt brauche ich einen Kampf. \n"
	.string "Damit ich wieder zu Atem komme.$"

Route105_Text_JosueDefeated:
	.string "Ich habe nur verloren, weil ich im Meer\n"
	.string "gekämpft habe.$"

Route105_Text_JosuePostBattle:
	.string "Der Himmel passt besser zu mir als\n"
	.string "das Meer.$"

Route106_Text_ElliotIntro:
	.string "Was bevorzugst du? Fischen im\n"
	.string "Meer oder im Fluss?$"

Route106_Text_ElliotDefeated:
	.string "Wie beim Tiefseefischen habe ich auch\n"
	.string "hier geradezu spektakulär verloren.$"

Route106_Text_ElliotPostBattle:
	.string "Angeln ist das Größte, egal, ob im Meer\n"
	.string "oder im Fluss. Stimmst du mir zu?$"

Route106_Text_ElliotRegister:
	.string "Angeln ist klasse, aber das sind\n"
	.string "Kämpfe auch. Hast du nicht Lust, dich\l"
	.string "bald mal wieder mit mir zu messen?$"

Route106_Text_ElliotRematchIntro:
	.string "Ich habe beim Angeln eine Menge\n"
	.string "POKéMON gefangen. Ich zeige sie dir!$"

Route106_Text_ElliotRematchDefeated:
	.string "Ich habe wieder ganz famos verloren!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Gewinnen, verlieren, POKéMON sind groß-\n"
	.string "artig! Stimmst du mir zu?$"

Route106_Text_NedIntro:
	.string "Was machen Angler, wenn sie mal auf die\n"
	.string "Toilette müssen?\p"
	.string "Ich gehe nicht. Niemals! In der Zeit\n"
	.string "könnte ja etwas anbeißen.$"

Route106_Text_NedDefeated:
	.string "Ich habe verloren, weil ich nicht auf die\n"
	.string "Toilette gegangen bin.$"

Route106_Text_NedPostBattle:
	.string "Oh! Ich habe das Gefühl, bald\n"
	.string "etwas Großes zu fangen.$"

Route106_Text_DouglasIntro:
	.string "Hahaha! Ich bin ein lausiger Läufer,\n"
	.string "aber im Wasser fängst du mich nicht!$"

Route106_Text_DouglasDefeated:
	.string "Ich gebe auf!$"

Route106_Text_DouglasPostBattle:
	.string "Beim Wettschwimmen wäre ich der Sieger!$"

Route106_Text_KylaIntro:
	.string "Das Meer ist mein Garten. Ich werde es\n"
	.string "dir nicht leicht machen, Kind!$"

Route106_Text_KylaDefeated:
	.string "Konntest du es mir nicht leicht machen?$"

Route106_Text_KylaPostBattle:
	.string "Sich auf den Wellen treiben lassen…\n"
	.string "Ich liebe das! Versuch es doch auch mal!$"

Route107_Text_DarrinIntro:
	.string "Gäähn…\p"
	.string "Ich muss wohl eingeschlafen sein, als\n"
	.string "ich mich auf den Wellen treiben ließ.$"

Route107_Text_DarrinDefeated:
	.string "Ahahaha, ich habe verloren…\n"
	.string "Ich mache jetzt ein Nickerchen…$"

Route107_Text_DarrinPostBattle:
	.string "Sich treiben und von den Wellen\n"
	.string "schaukeln lassen - als ob man in einem\l"
	.string "weichen, bequemen Bett schläft.$"

Route107_Text_TonyIntro:
	.string "Das Meer ist wie mein Garten.\n"
	.string "Lass uns kämpfen.$"

Route107_Text_TonyDefeated:
	.string "Ich habe in meinem eigenen Garten ver-\n"
	.string "loren… Ich bin geschockt!$"

Route107_Text_TonyPostBattle:
	.string "Ich schwimme im Meer, das Herz voller\n"
	.string "Träume…\p"
	.string "Das ist ein Lied!\n"
	.string "Wie auch immer, ich schwimme weiter.$"

Route107_Text_TonyRegister:
	.string "Du hast mich zu Tode erschreckt!\n"
	.string "Na, so schnell wirst du mich auch nicht\l"
	.string "vergessen…$"

Route107_Text_TonyRematchIntro:
	.string "Durch das Schwimmen im Meer ist\n"
	.string "mein POKéMON stärker geworden!$"

Route107_Text_TonyRematchDefeated:
	.string "Was für ein Schock!\p"
	.string "Mein POKéMON ist stärker geworden,\n"
	.string "aber ich bin ein Weichei von TRAINER.$"

Route107_Text_TonyRematchPostBattle:
	.string "Das, was du im Kampf lernst, macht dich\n"
	.string "zu einem starken TRAINER.\l"
	.string "Das haben mir die Wellen beigebracht.$"

Route107_Text_DeniseIntro:
	.string "Kennst du einen kleinen Ort namens\n"
	.string "DEWFORD TOWN?$"

Route107_Text_DeniseDefeated:
	.string "Ich hasse das!$"

Route107_Text_DenisePostBattle:
	.string "Verrücktheiten zu erzählen, ist der\n"
	.string "neue Trend in der DEWFORD TOWN HALLE.$"

Route107_Text_BethIntro:
	.string "Willst du gegen mich kämpfen?\n"
	.string "Natürlich trete ich gegen dich an!$"

Route107_Text_BethDefeated:
	.string "Ich war nicht gut genug für dich.$"

Route107_Text_BethPostBattle:
	.string "Ich denke, du wirst dich bemühen, noch\n"
	.string "besser zu werden. Das tue ich auch!$"

Route107_Text_LisaIntro:
	.string "BEA: Wir fordern dich als Bruder und\n"
	.string "Schwester heraus!$"

Route107_Text_LisaDefeated:
	.string "BEA: Unglaublich.\n"
	.string "Du bist in einer anderen Stärke-Klasse.$"

Route107_Text_LisaPostBattle:
	.string "BEA: Hast du Freunde, die mit dir an den\n"
	.string "Strand gehen würden?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "BEA: Wenn du gegen uns kämpfen willst,\n"
	.string "bring mehr POKéMON mit.$"

Route107_Text_RayIntro:
	.string "ERKO: Wir kämpfen immer mit POKéMON,\n"
	.string "meine Schwester und ich.\p"
	.string "Ich alleine verliere ständig, aber wir\n"
	.string "können dich 2-gegen-2 schlagen!$"

Route107_Text_RayDefeated:
	.string "ERKO: Huiuiui! Du kämpfst auf einem viel\n"
	.string "höheren Level als wir!$"

Route107_Text_RayPostBattle:
	.string "ERKO: Meine Schwester hat mir mein\n"
	.string "POKéMON gegeben und nun ist es mein\l"
	.string "Partner!$"

Route107_Text_RayNotEnoughPokemon:
	.string "ERKO: Wenn du gegen uns antreten\n"
	.string "willst, bring mehr POKéMON mit.$"

Route107_Text_CamronIntro:
	.string "Ich bin mitten in einem Triathlon und\n"
	.string "überhaupt nicht müde.$"

Route107_Text_CamronDefeated:
	.string "Das hat mich jetzt echt erschöpft…$"

Route107_Text_CamronPostBattle:
	.string "Ich muss jetzt noch Rad fahren und\n"
	.string "laufen.\p"
	.string "Ob das gesund ist?!?$"

Route108_Text_JeromeIntro:
	.string "Mein Traum ist es, durch die sieben\n"
	.string "Weltmeere zu schwimmen.$"

Route108_Text_JeromeDefeated:
	.string "So werde ich niemals in der Lage sein,\n"
	.string "die sieben Weltmeere zu durch-\l"
	.string "schwimmen.$"

Route108_Text_JeromePostBattle:
	.string "Mit maritimen POKéMON zu spielen, ist\n"
	.string "eine der Freuden beim Schwimmen.$"

Route108_Text_MatthewIntro:
	.string "Ahoi, da! Willst du auch zum\n"
	.string "ABANDONED SHIP?$"

Route108_Text_MatthewDefeated:
	.string "Ich gehe unter!\n"
	.string "Blubb… blubb… blubb…$"

Route108_Text_MatthewPostBattle:
	.string "Einige Leute gehen sogar in das\n"
	.string "ABANDONED SHIP hinein!$"

Route108_Text_TaraIntro:
	.string "Mein Freund, dieser Lügner, sagt,\n"
	.string "ich sähe klasse in dem Bikini aus…$"

Route108_Text_TaraDefeated:
	.string "Oh, buuuh!$"

Route108_Text_TaraPostBattle:
	.string "Auch wenn es eine Lüge ist, liebe ich es,\n"
	.string "Komplimente zu bekommen.\l"
	.string "Wir Mädchen sind so komplex…$"

Route108_Text_MissyIntro:
	.string "Ich liebe das Meer! Ich vergesse all\n"
	.string "meine Probleme, wenn ich schwimme.$"

Route108_Text_MissyDefeated:
	.string "Wenn ich verliere, bin ich total\n"
	.string "gestresst!$"

Route108_Text_MissyPostBattle:
	.string "Baue Stress durch Schwimmen ab.\n"
	.string "Das ist sehr gesund!$"

Route108_Text_CoryIntro:
	.string "Ich liebe WASSER-POKéMON.\n"
	.string "Und ich liebe auch andere POKéMON.$"

Route108_Text_CoryDefeated:
	.string "Waaahaaa! Ich habe verloren!\n"
	.string "Waaaaahaaaaa! Waaaaaaaaahaaaaaaaaa!$"

Route108_Text_CoryPostBattle:
	.string "Das laute Schreien ist wichtig für mich!\n"
	.string "Das hebt meine Stimmung!$"

Route108_Text_CoryRegister:
	.string "Ich liebe auch starke TRAINER.\n"
	.string "Trag mich in deinen POKéNAV ein!$"

Route108_Text_CoryRematchIntro:
	.string "Sieg oder Niederlage… Ich liebe es, im\n"
	.string "Meer zu kämpfen!$"

Route108_Text_CoryRematchDefeated:
	.string "Waaahaaa! Schon wieder verloren!\n"
	.string "Waaaaahaaaaa! Waaaaaaaaahaaaaaaaaa!$"

Route108_Text_CoryRematchPostBattle:
	.string "Wenn du dich einer Herausforderung\n"
	.string "gegenüber siehst, dann brüll einfach\l"
	.string "laut und schallend aufs Meer hinaus!$"

Route108_Text_CarolinaIntro:
	.string "Meine süßen POKéMON sind mein ganzer\n"
	.string "Stolz. Ich werde sie dir in einem\l"
	.string "schnellen Kampf zeigen!$"

Route108_Text_CarolinaDefeated:
	.string "Das war aber gar nicht niedlich und süß.$"

Route108_Text_CarolinaPostBattle:
	.string "Da ich hier im Meer schwimme, hätte\n"
	.string "ich nichts dagegen, einen niedlichen\l"
	.string "und süßen rosa Badeanzug zu tragen…$"

Route109_Text_DavidIntro:
	.string "Hiya! Schau dir meine gemeißelten \n"
	.string "Vollmatrosen an! Das nennt\l"
	.string "man einen “Schnitt”!$"

Route109_Text_DavidDefeated:
	.string "Aiyah!\n"
	.string "Ausgerutscht.$"

Route109_Text_DavidPostBattle:
	.string "Hiyah!\p"
	.string "Meine gemeißelten Vollmatrosen haben\n"
	.string "nichts mit meinen Kämpfen zu tun!$"

Route109_Text_AliceIntro:
	.string "Hast du dich auch gut mit Sonnenmilch\n"
	.string "eingerieben?$"

Route109_Text_AliceDefeated:
	.string "Aua, aua, aua.$"

Route109_Text_AlicePostBattle:
	.string "An den Wangen bekommt man als Erstes\n"
	.string "einen Sonnenbrand.$"

Route109_Text_HueyIntro:
	.string "Ich habe meinen Anker in vielen Häfen\n"
	.string "der Welt geworfen, aber SLATEPORT\l"
	.string "CITY ist der schönste Hafen.$"

Route109_Text_HueyDefeated:
	.string "Du bist der Beste!$"

Route109_Text_HueyPostBattle:
	.string "Im besten Hafen gibt es auch den\n"
	.string "besten TRAINER…$"

Route109_Text_EdmondIntro:
	.string "Urrrrppp…\n"
	.string "Kämpfen? Mit mir?$"

Route109_Text_EdmondDefeated:
	.string "Böör… Ooooooohhhhhh…\n"
	.string "Bööörrppp…$"

Route109_Text_EdmondPostBattle:
	.string "Normalerweise bin ich viel stärker!\n"
	.string "Ich bin seekrank!\p"
	.string "Ich bin MATROSE, aber…$"

Route109_Text_RickyIntro:
	.string "Ich bin durstig… Ich könnte im\n"
	.string "STRANDHAUS etwas SPRUDEL kaufen…$"

Route109_Text_RickyDefeated:
	.string "Grummel…$"

Route109_Text_RickyPostBattle:
	.string "Ich bin am Verhungern… Mein Schwimm-\n"
	.string "reifen sieht aus wie ein Schmalzkringel.$"

Route109_Text_RickyRegister:
	.string "Wirst du nochmal mit mir kämpfen, wenn\n"
	.string "ich keinen Durst mehr habe?$"

Route109_Text_RickyRematchIntro:
	.string "Ich habe tierischen Hunger, aber ich\n"
	.string "habe genug Kraft für einen Kampf!$"

Route109_Text_RickyRematchDefeated:
	.string "Ich habe verloren…\n"
	.string "Und das nur, weil ich so hungrig bin…$"

Route109_Text_RickyRematchPostBattle:
	.string "Wenn man am Strand sitzt und isst,\n"
	.string "schmeckt alles gleich viel besser.$"

Route109_Text_LolaIntro:
	.string "So ein Sonnenschirm sieht doch aus wie\n"
	.string "eine riesige Blume, findest du nicht?$"

Route109_Text_LolaDefeated:
	.string "Maaaami!$"

Route109_Text_LolaPostBattle:
	.string "Ein Strand sieht aus der Luft be-\n"
	.string "trachtet wie ein Blumengarten aus.$"

Route109_Text_LolaRegister:
	.string "Ich?\n"
	.string "Ich bin jeden Tag hier.$"

Route109_Text_LolaRematchIntro:
	.string "Ich verliere nicht wieder gegen dich!\n"
	.string "Schließlich habe ich einen Schwimm-\l"
	.string "reifen um!$"

Route109_Text_LolaRematchDefeated:
	.string "Maaaami!$"

Route109_Text_LolaRematchPostBattle:
	.string "Sobald ich den Schwimmreifen trage,\n"
	.string "sehen meine POKéMON und ich noch\l"
	.string "niedlicher aus!$"

Route109_Text_AustinaIntro:
	.string "Ohne Schwimmreifen kann ich nicht\n"
	.string "schwimmen, aber im Kampf siege ich.$"

Route109_Text_AustinaDefeated:
	.string "Habe ich verloren, weil ich einen\n"
	.string "Schwimmreifen trage?$"

Route109_Text_AustinaPostBattle:
	.string "Mein Schwimmreifen ist voll in Mode.\n"
	.string "Ohne ihn kann ich mich nicht sehen\l"
	.string "lassen!$"

Route109_Text_GwenIntro:
	.string "Hey, großer TRAINER!\n"
	.string "Kämpfst du mit mir?$"

Route109_Text_GwenDefeated:
	.string "Oh, bist du aber stark!$"

Route109_Text_GwenPostBattle:
	.string "Wie bist du so stark geworden?$"

Route109_Text_CarterIntro:
	.string "Hahaha! Dieser Kerl hier wird jetzt\n"
	.string "einen großen Fang machen!$"

Route109_Text_CarterDefeated:
	.string "Dieser Kerl hier hat ganz groß verloren.$"

Route109_Text_CarterPostBattle:
	.string "Dieser Kerl hier denkt, dass du ganz\n"
	.string "groß bist. Nein, ein Gernegroß bist!$"

Route109_Text_PaulIntro:
	.string "OLE: Nun, das ist ein Stimmungstöter!\p"
	.string "Ich wünschte, du würdest uns nicht \n"
	.string "unsere kostbare Zeit rauben!$"

Route109_Text_PaulDefeated:
	.string "OLE: Nun, ich gebe mich geschlagen.$"

Route109_Text_PaulPostBattle:
	.string "OLE: Nun, sag niemandem, dass wir\n"
	.string "hier sind. Das ist unsere kleine, private\l"
	.string "Welt!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "OLE: Wir sind total heftig ineinander\n"
	.string "verliebt. Deshalb lassen wir unsere\l"
	.string "POKéMON auch gemeinsam kämpfen.$"

Route109_Text_MelIntro:
	.string "GELI: Wir sind total ineinander verliebt.\n"
	.string "Unsere Romanze wärmt ganz HOENN!$"

Route109_Text_MelDefeated:
	.string "GELI: Wir haben verloren. Das ist meine\n"
	.string "Schuld. OLE wird mich hassen!$"

Route109_Text_MelPostBattle:
	.string "GELI: Ähm, OLE, bist du böse auf mich?\n"
	.string "Bitte sei nicht böse auf mich!$"

Route109_Text_MelNotEnoughPokemon:
	.string "GELI: Wir sind total heftig ineinander\n"
	.string "verliebt. Daher kämpfen wir auch mit\l"
	.string "unseren POKéMON zusammen.$"

Route109_Text_ChandlerIntro:
	.string "Tadaaah! Siehste?\n"
	.string "Mein Schwimmreifen ist gaaanz rund!$"

Route109_Text_ChandlerDefeated:
	.string "Oh oh!\n"
	.string "Schade!$"

Route109_Text_ChandlerPostBattle:
	.string "Und das, nachdem ich dir meinen schönen\n"
	.string "runden Schwimmreifen gezeigt habe…$"

Route109_Text_HaileyIntro:
	.string "Ich kann nicht schwimmen, also tue ich\n"
	.string "so als ob.$"

Route109_Text_HaileyDefeated:
	.string "Das dachte ich mir!\n"
	.string "Ich wusste, wir können nicht gewinnen!$"

Route109_Text_HaileyPostBattle:
	.string "Wenn ich Schwimmen lerne, werden meine\n"
	.string "POKéMON mit Sicherheit auch stärker.$"

Route109_Text_ElijahIntro:
	.string "Für einen echten Macho wie mich, sind\n"
	.string "diese POKéMON einfach perfekt!$"

Route109_Text_ElijahDefeated:
	.string "Ich bin sogar bei einer Niederlage\n"
	.string "noch cool!$"

Route109_Text_ElijahPostBattle:
	.string "Für einen echten Macho wie mich, ist ein\n"
	.string "Hafen der perfekte Ort.\p"
	.string "Ich denke, ich werde nach SLATEPORT\n"
	.string "CITY gehen.$"

Route110_Text_JacobIntro:
	.string "Wow! Pass auf! Ich glaube, du hast\n"
	.string "keine Übung im RAD-Rennen.$"

Route110_Text_JacobDefeated:
	.string "Wow! Pass auf!\n"
	.string "Meine Bremsen versagen!$"

Route110_Text_JacobPostBattle:
	.string "Platte Reifen und schwache Bremsen\n"
	.string "können zu Unfällen mit schweren Ver-\l"
	.string "letzungen führen! Also: Prüfe dein RAD!$"

Route110_Text_AnthonyIntro:
	.string "Hey, du!\n"
	.string "Kannst du mit mir mithalten?$"

Route110_Text_AnthonyDefeated:
	.string "Du hast die Schallmauer durchbrochen!$"

Route110_Text_AnthonyPostBattle:
	.string "Geschwindigkeit alleine lässt mich\n"
	.string "nicht gewinnen.\l"
	.string "Das darf ich nicht vergessen.$"

Route110_Text_BenjaminIntro:
	.string "Nur keine Panik, wenn dein RAD immer\n"
	.string "schneller wird!$"

Route110_Text_BenjaminDefeated:
	.string "Ich muss während eines POKéMON-\n"
	.string "Kampfes ruhig bleiben…$"

Route110_Text_BenjaminPostBattle:
	.string "Kein Grund zur Panik. Nimm’s leicht.\n"
	.string "Wir haben doch jede Menge Zeit.$"

Route110_Text_BenjaminRegister:
	.string "Ich werde weiter in die Pedale treten,\n"
	.string "völlig stressfrei und ohne Panik.\l"
	.string "Meld dich, wenn du magst.$"

Route110_Text_BenjaminRematchIntro:
	.string "Bist du nicht ein wenig zu schnell? \n"
	.string "Brems ab und lass uns kämpfen.$"

Route110_Text_BenjaminRematchDefeated:
	.string "Ich war ganz ruhig und habe doch\n"
	.string "verloren…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Kein Grund zur Panik. Nimm’s leicht.\n"
	.string "Wir haben doch jede Menge Zeit.$"

Route110_Text_AbigailIntro:
	.string "Ich bin vo Italie mitem\n"
	.string "Velo da here cho und finde\l"
	.string "kei einzigi Pizzeria...$"

Route110_Text_AbigailDefeated:
	.string "Mammma Mia...$"

Route110_Text_AbigailPostBattle:
	.string "...$"

Route110_Text_AbigailNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route110_Text_AbigailRegister:
	.string "Weißt du, ich mag dich.\n"
	.string "Wir sollten auf dem KÜSTENRADWEG\l"
	.string "noch einmal gegeneinander kämpfen.$"

Route110_Text_AbigailRematchIntro:
	.string "Gibt es etwas Eleganteres, als einen\n"
	.string "Kampf während man Rad fährt?$"

Route110_Text_AbigailRematchDefeated:
	.string "Wow…\n"
	.string "Wie kann man nur so stark sein?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Bist du auf der Jagd nach Rekorden?\p"
	.string "Tut mir Leid, wenn ich dich dabei auf-\n"
	.string "gehalten habe.$"

Route110_Text_JasmineIntro:
	.string "Ich radle ohne aufzuhören! Meine Ober-\n"
	.string "schenkel sind hart wie Stein!$"

Route110_Text_JasmineDefeated:
	.string "Muskelkrämpfe beunruhigen mich!$"

Route110_Text_JasminePostBattle:
	.string "Oh, du besitzt einige ORDEN der ARENen.\n"
	.string "Kein Wunder, dass du so stark bist!$"

Route110_Text_EdwardIntro:
	.string "Zeit für ein\n"
	.string "Du-du-du-du-du-DUELL!!$"

Route110_Text_EdwardDefeated:
	.string "Aber was isch mitem\n"
	.string "motivierende Yugioh Spruch?$"

Route110_Text_EdwardNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route110_Text_EdwardPostBattle:
	.string "Ich hett lieber sölle\n"
	.string "Poge Charte chaufe,\l"
	.string "statt Yugi-gag.$"

Route110_Text_JaclynIntro:
	.string "Ich zeig der warum de\n"
	.string "HARDWALD, HARD im Name het.$"

Route110_Text_JaclynDefeated:
	.string "Wow!$"

Route110_Text_JaclynNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route110_Text_JaclynPostBattle:
	.string "Okay, hett ich jetzt gunne,\n"
	.string "denn hett ich chönne sege,\l"
	.string "dass de HARDWALD wege mir\l"
	.string "HARD heisst...$"

Route110_Text_EdwinIntro:
	.string "Ich hab dir was\n"
	.string "midgebracht.$"

Route110_Text_EdwinDefeated:
	.string "Nein DIMOSY!$"

Route110_Text_EdwinPostBattle:
	.string "Ich dachte wir wären\n"
	.string "Freunde.$"

Route110_Text_EdwinNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route110_Text_EdwinRegister:
	.string "Ich sammle TRAINER/RUF-Einträge…$"

Route110_Text_EdwinRematchIntro:
	.string "Hi, hast du neue POKéMON gesammelt?\p"
	.string "Ich möchte einen Blick auf deine\n"
	.string "POKéMON werfen. Ganz kurz, bitte?$"

Route110_Text_EdwinRematchDefeated:
	.string "Deine POKéMON…\n"
	.string "Ich bin richtig neidisch!$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, ich möchte so gerne alle seltenen\n"
	.string "POKéMON besitzen.$"

Route110_Text_DaleIntro:
	.string "Ich droppe unerwartet\n"
	.string "i das Game wie ICH!$"

Route110_Text_DaleDefeated:
	.string "Gopf!$"

Route110_Text_DalePostBattle:
	.string "Wie hesch du mis Barschwa\n"
	.string "chönne besiege?$"

Route110_Text_DaleNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route110_Text_IsabelIntro:
	.string "Ich würde überall hingehen, um meine\n"
	.string "elysischen POKéMON zu präsentieren.$"

Route110_Text_IsabelDefeated:
	.string "Oh, Schönheit reicht nicht aus…$"

Route110_Text_IsabelPostBattle:
	.string "Ich sollte meine POKéMON vielleicht\n"
	.string "lieber im FANCLUB zeigen, anstatt zu\l"
	.string "kämpfen.$"

Route110_Text_IsabelRegister:
	.string "Das war schon nah dran an einer\n"
	.string "POKéMON-Präsentation.\p"
	.string "Ich möchte dich so oft wie möglich als\n"
	.string "Publikum haben.$"

Route110_Text_IsabelRematchIntro:
	.string "Ich zeige dir meine elysischen\n"
	.string "POKéMON, sooft du willst!$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, Schönheit reicht nicht aus…$"

Route110_Text_IsabelRematchPostBattle:
	.string "Ich glaube nicht, dass ich jemals\n"
	.string "aufhören werde, meine POKéMON zu\l"
	.string "zeigen.\p"
	.string "Aber ich liebe auch das Kämpfen.$"

Route110_Text_TimmyIntro:
	.string "Ich habe hier im hohen Gras einige coole\n"
	.string "POKéMON gefunden!$"

Route110_Text_TimmyDefeated:
	.string "Nur cool zu sein verhilft einem nicht\n"
	.string "zum Sieg…$"

Route110_Text_TimmyPostBattle:
	.string "Mit POKéMON zu kämpfen, die man gerade\n"
	.string "erst gefangen hat, ist verdammt schwer.$"

Route110_Text_AlyssaIntro:
	.string "Hey du, lueg mal mini\n"
	.string "herzige Reh ah.$"

Route110_Text_AlyssaDefeated:
	.string "Du bisch frech!$"

Route110_Text_AlyssaPostBattle:
	.string "Nimm de Pogeball und\n"
	.string "denn verschwind!$"

Route110_Text_AlyssaNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route110_Text_JosephIntro:
	.string "Chum da here!$"

Route110_Text_JosephDefeated:
	.string "ZAGSDZHSADZUHVB!!$"

Route110_Text_JosephPostBattle:
	.string "Mit dir kämpfe macht\n"
	.string "kei Spass.$"

Route110_Text_JosephNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

Route110_Text_KalebIntro:
	.string "Wenn süße POKéMON sich gegenseitig\n"
	.string "helfen… Es gibt keinen lieblicheren\l"
	.string "Anblick…$"

Route110_Text_KalebDefeated:
	.string "Hast du kein Mitleid?$"

Route110_Text_KalebPostBattle:
	.string "Okay, okay, ihr habt euer Bestes\n"
	.string "gegeben, meine Süßen.$"

Route111_Text_DrewIntro:
	.string "Ich han welle es Pule ide\n"
	.string "ÖLI grilliere,\l"
	.string "aber die Viecher hend mich\l"
	.string "usegjagt.\p"
	.string "Jetzt chan mich nur en\n"
	.string "Kampf beruhige!$"

Route111_Text_DrewDefeat:
	.string "AHfhashfha!!!$"

Route111_Text_DrewNotEnoughMons:
	.string "He, so gaht das nöd!\n"
	.string "Für en Doppelkampf bruchsch\l"
	.string "zwei kampffähigi POKéMON.$"

Route111_Text_DrewPostBattle:
	.string "Gopfetami!\n"
	.string "Jetzt isch mir s' Pule\l"
	.string "auno uf de Bode gheit :x$"

Route111_Text_HeidiIntro:
	.string "Ich han zu fest Angst\n"
	.string "vor de ÖLI.\p"
	.string "Ich bewach lieber\n"
	.string "de Ihgang!$"

Route111_Text_HeidiDefeat:
	.string "Tami!$"

Route111_Text_HeidiNotEnoughMons:
	.string "He, so gaht das nöd!\n"
	.string "Für en Doppelkampf bruchsch\l"
	.string "zwei kampffähigi POKéMON.$"

Route111_Text_HeidiPostBattle:
	.string "Wenn du ide ÖLI es Kilo\n"
	.string "Gold findsch,\p"
	.string "machemer Fiffty-fiffty?$"

Route111_Text_BeauIntro:
	.string "TÖÖÖRÖÖÖÖÖÖ!!!$"

Route111_Text_BeauDefeat:
	.string "Ach mann...$"

Route111_Text_BeauNotEnoughMons:
	.string "He, so gaht das nöd!\n"
	.string "Für en Doppelkampf bruchsch\l"
	.string "zwei kampffähigi POKéMON.$"

Route111_Text_BeauPostBattle:
	.string "Sie nenned mich Benjamin\n"
	.string "Blümchen weg mim fette Rüs...$"

Route111_Text_BeckyIntro:
	.string "Ich habe gehört, dass man in der Wüste\n"
	.string "Fossilien finden kann. Aber wo?$"

Route111_Text_BeckyDefeat:
	.string "Ich war in Gedanken bei den Fossilien…$"

Route111_Text_BeckyPostBattle:
	.string "Da man in der Wüste Fossilien finden\n"
	.string "kann, war hier früher sicher ein Meer…$"

Route111_Text_DustyIntro:
	.string "Ich bin so voller Staub\n"
	.string "vo dere ÖLI,\p"
	.string "dass ich als Wiener\n"
	.string "Schnitzel duregah chönnt.$"

Route111_Text_DustyDefeat:
	.string "SAPPERLOTT!$"

Route111_Text_DustyNotEnoughMons:
	.string "He, so gaht das nöd!\n"
	.string "Für en Doppelkampf bruchsch\l"
	.string "zwei kampffähigi POKéMON.$"

Route111_Text_DustyPostBattle:
	.string "Tami, wie hesch du\n"
	.string "mini Viecher chönne\l"
	.string "besiege?$"

Route111_Text_DustyRegister:
	.string "Ich habe noch nie nach starken POKéMON\n"
	.string "gesucht.\p"
	.string "Aber trotzdem finde ich so einen\n"
	.string "POKéNAV absolut klasse.$"

Route111_Text_DustyRematchIntro:
	.string "Seit 30 Jahren suche ich nach antiken\n"
	.string "Ruinen!\p"
	.string "Oder seit 40 Jahren???\n"
	.string "Egal! Forderst du mich heraus?$"

Route111_Text_DustyRematchDefeat:
	.string "Ich habe keine Ruinen und auch keine\n"
	.string "starken POKéMON gefunden…$"

Route111_Text_DustyPostRematch:
	.string "Seit 30 Jahren suche ich nach antiken\n"
	.string "Ruinen!\p"
	.string "Glaube ich… Es können auch schon\n"
	.string "40 Jahre sein…\p"
	.string "Hmm… Andererseits kämen 50 Jahre auch\n"
	.string "hin… Mein Gedächtnis ist eine Ruine…$"

Route111_Text_TravisIntro:
	.string "Ich bin voller Schwung und Elan!\n"
	.string "Und mein POKéMON nicht minder!$"

Route111_Text_TravisDefeat:
	.string "Mein POKéMON hat ausgeschwungen.$"

Route111_Text_TravisPostBattle:
	.string "Wenn ich einen TRAINER mit Schwung und\n"
	.string "Elan sehe, muss ich ihn anstarren.$"

Route111_Text_IreneIntro:
	.string "Ich weiß ja nicht, wo du hin willst, aber\n"
	.string "was sagst du zu einem Kämpfchen?$"

Route111_Text_IreneDefeat:
	.string "Hui, du bist außergewöhnlich gut!$"

Route111_Text_IrenePostBattle:
	.string "Ich denke, ich sollte zum MT. CHIMNEY\n"
	.string "gehen, aber hier ist es sooo schön…$"

Route111_Text_DaisukeIntro:
	.string "Achtung!\n"
	.string "Ich bin ziemlich starch!$"

Route111_Text_DaisukeDefeat:
	.string "Wow!$"

Route111_Text_DaisukeNotEnoughMons:
	.string "He, so gaht das nöd!\n"
	.string "Für en Doppelkampf bruchsch\l"
	.string "zwei kampffähigi POKéMON.$"

Route111_Text_DaisukePostBattle:
	.string "Du hesch es au\n"
	.string "richtig druff!$"

Route111_Text_WiltonIntro:
	.string "Nöd schlecht.\n"
	.string "Du hesch d' ÖLI hinder\l"
	.string "dich bracht.\p"
	.string "Ich mach der vorem\n"
	.string "Poke-Center jetz nomal\l"
	.string "s' Lebe schwer. >:)$"

Route111_Text_WiltonDefeat:
	.string "Uff...$"

Route111_Text_WiltonNotEnoughMons:
	.string "He, so gaht das nöd!\n"
	.string "Für en Doppelkampf bruchsch\l"
	.string "zwei kampffähigi POKéMON.$"

Route111_Text_WiltonPostBattle:
	.string "Krass, so wie du druff\n"
	.string "bisch,\p"
	.string "schaffsch du die nächst\n"
	.string "Arena ja locker.$"

Route111_Text_WiltonRegister:
	.string "Ich kann viel von dir lernen, wenn ich\n"
	.string "dein Training beobachte.\p"
	.string "Ich würde irgendwann gerne wieder\n"
	.string "gegen dich antreten.$"

Route111_Text_WiltonRematchIntro:
	.string "Wir trainieren hier, um im Spiel einen\n"
	.string "Level weiterzukommen.\l"
	.string "Bleib hier und trainiere mit uns!$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, du bist unglaublich!$"

Route111_Text_WiltonPostRematch:
	.string "Da du so stark bist, solltest du dir die\n"
	.string "POKéMON LEAGUE zum Ziel setzen.$"

Route111_Text_BrookeIntro:
	.string "Ich bin fame uf Insta\n"
	.string "und TikTok.\p"
	.string "Ziit für es POV-Video,\n"
	.string "wenn mer so en Lappe\l"
	.string "wie dich zerstört.$"

Route111_Text_BrookeDefeat:
	.string "Kei Akku meh...$"

Route111_Text_BrookeNotEnoughMons:
	.string "He, so gaht das nöd!\n"
	.string "Für en Doppelkampf bruchsch\l"
	.string "zwei kampffähigi POKéMON.$"

Route111_Text_BrookePostBattle:
	.string "Ja ja, wär min Empfang\n"
	.string "besser,\p"
	.string "wür ich dich hopps neh\n"
	.string "und dich im Internet\l"
	.string "bloss stelle.$"

Route111_Text_BrookeRegister:
	.string "Ich würde gern mit weiteren starken\n"
	.string "Leuten, wie du es bist, Freundschaft\l"
	.string "schließen.$"

Route111_Text_BrookeRematchIntro:
	.string "Abhängig von den Attacken, die du ihnen\n"
	.string "beibringst, sind deine POKéMON stärker\l"
	.string "oder schwächer.\p"
	.string "Welche Attacken haben deine POKéMON\n"
	.string "auf Lager?$"

Route111_Text_BrookeRematchDefeat:
	.string "Ihre Attacken sind wirklich gut.$"

Route111_Text_BrookePostRematch:
	.string "Meine POKéMON sollten sich vielleicht\n"
	.string "nicht entwickeln, bis sie wirklich\l"
	.string "gute Attacken gelernt haben…$"

Route111_Text_CeliaIntro:
	.string "Ich hätte nicht hierher kommen sollen,\n"
	.string "um ein Picknick zu veranstalten.$"

Route111_Text_CeliaDefeat:
	.string "Oooh! Ich hätte wirklich nicht\n"
	.string "hierher kommen sollen!$"

Route111_Text_CeliaPostBattle:
	.string "In einem Sandsturm wie diesem, finde ich\n"
	.string "einfach keinen Platz für ein Picknick.\l"
	.string "Selbst mit WÜSTENGLAS nicht…$"

Route111_Text_BryanIntro:
	.string "Wie stark du wohl bist?\n"
	.string "Wir werden dieses Geheimnis lüften.$"

Route111_Text_BryanDefeat:
	.string "Oh! Deine Stärke!\n"
	.string "Ist ein Mysterium!$"

Route111_Text_BryanPostBattle:
	.string "Die Wüste hütet ihre Mysterien im Sand.$"

Route111_Text_BrandenIntro:
	.string "Mini Pokemon schicked\n"
	.string "dich i d' Ecke!$"

Route111_Text_BrandenDefeat:
	.string "Ach...$"

Route111_Text_BrandenNotEnoughMons:
	.string "He, so gaht das nöd!\n"
	.string "Für en Doppelkampf bruchsch\l"
	.string "zwei kampffähigi POKéMON.$"

Route111_Text_BrandenPostBattle:
	.string "Mann, mis Kecleon isch\n"
	.string "Next-Level Bullshit.$"

Route111_Text_TyronIntro:
	.string "Dies ist mein Lieblings-POKéMON.$"

Route111_Text_TyronDefeat:
	.string "Moment!\n"
	.string "Hattest du auch genug Zeit, dir mein\l"
	.string "POKéMON anzuschauen?$"

Route111_Text_TyronPostBattle:
	.string "Während eines Kampfes bin ich immer\n"
	.string "begeistert, weil ich meine POKéMON\l"
	.string "zeigen kann.\p"
	.string "So geht es bestimmt jedem zu Beginn\n"
	.string "eines Kampfes.$"

Route111_Text_CelinaIntro:
	.string "Zeig mir, wie mein Leben aufregender\n"
	.string "werden kann.$"

Route111_Text_CelinaDefeat:
	.string "Oh… Ich…\n"
	.string "Also das war mir zu viel Aufregung.$"

Route111_Text_CelinaPostBattle:
	.string "Mein Puls rast immer noch.\n"
	.string "Du bist ein ausgezeichneter TRAINER!$"

Route111_Text_HaydenIntro:
	.string "Jemand, der halb verhungert ist, wie ich\n"
	.string "es bin, der kennt kein Mitleid.$"

Route111_Text_HaydenDefeat:
	.string "Grummel…$"

Route111_Text_HaydenPostBattle:
	.string "Mein Magen knurrt!\n"
	.string "Vielleicht kann ich ja ein paar BEEREn\l"
	.string "rösten…$"

Route111_Text_BiancaIntro:
	.string "Kommst du aus DÜBI? Dann\n"
	.string "steckst du bestimmt voller Energie.$"

Route111_Text_BiancaDefeat:
	.string "Ooh lala!\n"
	.string "Das ist aber heftig!$"

Route111_Text_BiancaPostBattle:
	.string "Diese Straße hier…\n"
	.string "Du hast einen weiten Weg vor dir.$"

Route112_Text_BriceIntro:
	.string "Hahahahahaha!\n"
	.string "Wie wäre es, wenn wir kämpfen?\l"
	.string "Du und ich!\l"
	.string "Hahahahahaha!$"

Route112_Text_BriceDefeat:
	.string "Ich habe verloren!\n"
	.string "Hahahahahaha!$"

Route112_Text_BricePostBattle:
	.string "Hahahahahaha! Irgendetwas ist mir in\n"
	.string "die Nase geflogen! Hahahahaaatschiii!$"

Route112_Text_TrentIntro:
	.string "Meine Beine sind durch das Klettern in\n"
	.string "den Bergen richtig muskulös geworden.\p"
	.string "So leicht werden sie also nicht\n"
	.string "einknicken, mein Freund!$"

Route112_Text_TrentDefeat:
	.string "Aua! Ich habe Muskelkrämpfe!$"

Route112_Text_TrentPostBattle:
	.string "Versuche mal, in den Bergen zu wandern.\n"
	.string "Und zwar mit richtig festem Schritt. Und\l"
	.string "das mit einem schweren Rucksack von\l"
	.string "mehreren Pfund Gewicht…\p"
	.string "So, mein Freund, bringst du deinen\n"
	.string "Körper richtig in Form.$"

Route112_Text_TrentRegister:
	.string "Au, ich habe Krämpfe in den Beinen!\n"
	.string "Kannst du mir bitte Bandagen aus\l"
	.string "meinem Rucksack geben?\p"
	.string "Nein, das ist mein POKéNAV.\n"
	.string "Ich trage dich ins Verzeichnis ein.$"

Route112_Text_TrentRematchIntro:
	.string "Ich halte mich mit Wandern fit!\n"
	.string "Dadurch strotze ich vor Kraft!$"

Route112_Text_TrentRematchDefeat:
	.string "Meine Ärmel waren wohl verknotet…$"

Route112_Text_TrentRematchPostBattle:
	.string "Ich habe gehört, dass es am Gipfel vom\n"
	.string "MT. CHIMNEY viele starke TRAINER gibt.\p"
	.string "Ich werde dort hochgehen und sie alle\n"
	.string "herausfordern!$"

Route112_Text_LarryIntro:
	.string "Ich bin stark. Ich weine bestimmt\n"
	.string "nicht, wenn ich verliere.$"

Route112_Text_LarryDefeat:
	.string "Waaahaaa! Heul… Schluchz…$"

Route112_Text_LarryPostBattle:
	.string "Ich weine, weil ich meine Maaaaamiiii\n"
	.string "vermisse! Schluchz… Jammer…$"

Route112_Text_CarolIntro:
	.string "Machst du ein Picknick, dann musst du\n"
	.string "einfach vor Freude laut singen!\l"
	.string "Komm, wir singen zusammen.$"

Route112_Text_CarolDefeat:
	.string "Oh, du triffst die Töne besser als ich!$"

Route112_Text_CarolPostBattle:
	.string "Es ist egal, ob du besser singst oder\n"
	.string "besser mit POKéMON kämpfen kannst.\p"
	.string "Wenn du Spaß hast, hast du schon\n"
	.string "gewonnen!$"

Route112_Text_BryantIntro:
	.string "Ich habe auf dem FEURIGEN PFAD heiße\n"
	.string "POKéMON gefangen. Guck mal!$"

Route112_Text_BryantDefeat:
	.string "Das war aber eine holprige\n"
	.string "Angelegenheit.$"

Route112_Text_BryantPostBattle:
	.string "Ich mag die Art, wie du kämpfst.\n"
	.string "Da fühlt man ein gewisses Flair.$"

Route112_Text_ShaylaIntro:
	.string "Du bist ein bewundernswerter TRAINER!\n"
	.string "Ich brauche jetzt einen romantischen\l"
	.string "Kampf! Ich bin auch anständig.$"

Route112_Text_ShaylaDefeat:
	.string "Du bist wirklich stark!\n"
	.string "Das hat mich richtig erschreckt.$"

Route112_Text_ShaylaPostBattle:
	.string "Hast du etwas Zeit? Ich dachte,\n"
	.string "vielleicht könnten wir mal wieder\l"
	.string "miteinander kämpfen… Aber wenn\l"
	.string "du keine Zeit hast, ist es auch okay.$"

Route113_Text_JaylenIntro:
	.string "Rate mal, warum es hier draußen so\n"
	.string "kühl ist.$"

Route113_Text_JaylenDefeat:
	.string "Puuuh äääh!\n"
	.string "Das stinkt!$"

Route113_Text_JaylenPostBattle:
	.string "Die Vulkanasche lässt die Sonnen-\n"
	.string "strahlen nicht durch. Es bleibt kalt.\p"
	.string "Ich finde das angenehm, ich mag\n"
	.string "Hitze nicht.$"

Route113_Text_DillonIntro:
	.string "Der Vulkanausbruch ist der eindeutige\n"
	.string "Beweis, dass die Erde lebt.$"

Route113_Text_DillonDefeat:
	.string "Du bist auf die eine oder andere\n"
	.string "Weise stark!$"

Route113_Text_DillonPostBattle:
	.string "Aua! Au au au! Ich kann nichts sehen!\n"
	.string "Ich habe ein Aschenauge!\p"
	.string "Hast du verstanden? Asche und Auge?\p"
	.string "Okay, blöder Witz, tut mir Leid…$"

Route113_Text_MadelineIntro:
	.string "Ich habe einen Sonnenschirm, um diese\n"
	.string "staubige, widerliche Vulkanasche von\l"
	.string "meinem niedlichen CAMAUB fernzuhalten.$"

Route113_Text_MadelineDefeat:
	.string "Keuch, pust…\n"
	.string "Ich bin total außer Atem…$"

Route113_Text_MadelinePostBattle:
	.string "Du bist wirklich sehr gut. Ich muss\n"
	.string "sagen, ich bin schwer beeindruckt.$"

Route113_Text_MadelineRegister:
	.string "Komm unter meinen Sonnenschirm.\n"
	.string "Ich trage dich in meinen POKéNAV ein.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh, hallo, wir haben uns ja ewig nicht\n"
	.string "gesehen. Ich lade dich zu einem\l"
	.string "Kampf ein.$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, suuuuuper!$"

Route113_Text_MadelinePostRematch:
	.string "Du bist immer noch sehr gut! Ich muss\n"
	.string "sagen, ich bin immer noch beeindruckt.$"

Route113_Text_LaoIntro:
	.string "Aus der Asche erhebe ich mich! Kiyaih!\n"
	.string "Herausfordern tue ich dich! Kiyaih!$"

Route113_Text_LaoDefeat:
	.string "Eine Ehre, von dir besiegt zu werden!$"

Route113_Text_LaoPostBattle:
	.string "Ich muss die Kunst des Versteckens\n"
	.string "verbessern. Mein Reimen auch. Leb wohl.$"

Route113_Text_LaoRegister:
	.string "Yiihaa! Werde Zeuge der Registrierung\n"
	.string "auf traditionelle Ninja-Art im POKéNAV.$"

Route113_Text_LaoRematchIntro:
	.string "Erhebe ich mich aus der Asche, hast du\n"
	.string "nichts zu lachen. Kiyaih!$"

Route113_Text_LaoRematchDefeat:
	.string "Eine Ehre, von dir besiegt zu werden!$"

Route113_Text_LaoPostRematch:
	.string "Mein Versteck ist so lausig wie mein\n"
	.string "Kampfstil. Und meine Wortwahl erst…\p"
	.string "Ich lasse das Reimen und sage Lebwohl.$"

Route113_Text_LungIntro:
	.string "Danke, dass du mich gefunden hast!\n"
	.string "Aber nun müssen wir kämpfen!$"

Route113_Text_LungDefeat:
	.string "Ich werde mein Ninjutsu gegen dich\n"
	.string "einsetzen…\p"
	.string "“VULKANASCHENWIRBLER”!\n"
	.string "… Was? Es ist schon vorbei?$"

Route113_Text_LungPostBattle:
	.string "Weißt du, was sch… am Verstecken ist?\n"
	.string "Es ist einsam, wenn keiner vorbeikommt.$"

Route113_Text_ToriIntro:
	.string "LI: Wir beide sammeln Asche.\n"
	.string "Wir beide kämpfen auch mit POKéMON.$"

Route113_Text_ToriDefeat:
	.string "LI: Wir haben verloren… Mir ist lang-\n"
	.string "weilig, daher sammle ich jetzt Asche.$"

Route113_Text_ToriPostBattle:
	.string "LI: Wie viel Asche wir haben? Ich\n"
	.string "hoffe, genug für eine WEISSE FLÖTE.$"

Route113_Text_ToriNotEnoughMons:
	.string "LI: Wir wollen einen 2-gegen-2-Kampf.\n"
	.string "Anderenfalls würden wir verlieren.$"

Route113_Text_TiaIntro:
	.string "FLO: Wir beide sammeln Asche.\n"
	.string "Wir beide kämpfen auch mit POKéMON.$"

Route113_Text_TiaDefeat:
	.string "FLO: Wir haben verloren… Mir ist lang-\n"
	.string "weilig, daher sammle ich jetzt Asche.$"

Route113_Text_TiaPostBattle:
	.string "FLO: Wie viel Asche wir haben? Ich\n"
	.string "hoffe, genug für eine WEISSE FLÖTE.$"

Route113_Text_TiaNotEnoughMons:
	.string "FLO: Wir wollen einen 2-gegen-2-Kampf.\n"
	.string "Anderenfalls würden wir verlieren.$"

Route113_Text_CobyIntro:
	.string "Pfft, mit diesen Flügeln fege ich dich\n"
	.string "vom Platz.$"

Route113_Text_CobyDefeat:
	.string "Was…$"

Route113_Text_CobyPostBattle:
	.string "Ich weiß nicht, was ich sagen soll… Ich\n"
	.string "bin viel zu einfach besiegt worden…$"

Route113_Text_SophieIntro:
	.string "Die Wärme hier macht mich ganz\n"
	.string "schläfrig. Kämpf mit mir, sonst schlafe\l"
	.string "ich noch ein.$"

Route113_Text_SophieDefeat:
	.string "Das ist ein Traum.\n"
	.string "Das kann gar nicht anders sein…$"

Route113_Text_SophiePostBattle:
	.string "Eine Niederlage ist viel zu warm…\n"
	.string "Deshalb werde ich jetzt hier und auf\l"
	.string "der Stelle einschlaf… Zzzzzz…$"

Route113_Text_LawrenceIntro:
	.string "Bist du gerade dabei, Vulkanasche zu\n"
	.string "sammeln?$"

Route113_Text_LawrenceDefeat:
	.string "Ihihi.\n"
	.string "Da wurden wir aber sauber geschlagen.$"

Route113_Text_LawrencePostBattle:
	.string "Ich werde mich unter der Asche\n"
	.string "verstecken.$"

Route113_Text_WyattIntro:
	.string "D-du willst gegen mich kä-kämpfen?\n"
	.string "Obwohl ich meine POKéMON eben erst\l"
	.string "gefangen habe?$"

Route113_Text_WyattDefeat:
	.string "D-du bist froh, weil du gewonnen hast?\n"
	.string "Obwohl doch nur ich dein Gegner war?$"

Route113_Text_WyattPostBattle:
	.string "Und? Was hast du einem Verlierertypen\n"
	.string "zu sagen?\p"
	.string "Du kommst dir doch echt cool vor, oder?\n"
	.string "Hmpf!$"

Route114_Text_LennyIntro:
	.string "Hollerididudljö!\p"
	.string "… …\p"
	.string "Du musst jetzt mit “Hollerididudljö!”\n"
	.string "antworten, da es hier kein Echo gibt!$"

Route114_Text_LennyDefeat:
	.string "Hollerididudljö!$"

Route114_Text_LennyPostBattle:
	.string "Als ich noch ein kleiner Lausbub war,\n"
	.string "habe ich immer gedacht, da wäre jemand,\l"
	.string "der mich ärgern will und \l"
	.string "“Hollerididudljö” antwortet.$"

Route114_Text_LucasIntro:
	.string "Ohne eine gute Ausrüstung solltest du\n"
	.string "dich nicht in die Berge wagen.$"

Route114_Text_LucasDefeat:
	.string "Die Berge sind unerbittlich…$"

Route114_Text_LucasPostBattle:
	.string "Im Winter sind Berge lebensgefährlich,\n"
	.string "wegen der Blizzards und Lawinen.$"

Route114_Text_ShaneIntro:
	.string "Campen macht Spaß! Du kannst angeln,\n"
	.string "Würstchen braten und andere mit\l"
	.string "Spukgeschichten zu Tode erschrecken!\p"
	.string "Aber das Beste sind die POKéMON-\n"
	.string "Kämpfe!$"

Route114_Text_ShaneDefeat:
	.string "Das war etwas zu schwer für mich!$"

Route114_Text_ShanePostBattle:
	.string "Ich finde es großartig, dass ich mit\n"
	.string "meinen POKéMON campen gehen kann.$"

Route114_Text_NancyIntro:
	.string "Nach dem Essen muss ich Sport treiben.\n"
	.string "Also lass uns kämpfen.$"

Route114_Text_NancyDefeat:
	.string "Oh, nein!$"

Route114_Text_NancyPostBattle:
	.string "Ich hatte so ein leckeres Essen. Des-\n"
	.string "halb bin ich jetzt pappsatt und müde.$"

Route114_Text_SteveIntro:
	.string "Hufhufhufhufhufhuf…\n"
	.string "Komm, tritt gegen mein POKéMON an.$"

Route114_Text_SteveDefeat:
	.string "Mei… Mein POKéMON… hiiii…$"

Route114_Text_StevePostBattle:
	.string "Einen großen Körper, der plump und hart\n"
	.string "ist, riesige Hörner und scharfe Fänge…\p"
	.string "Hufhufhufhuf…\n"
	.string "So ein POKéMON hätte ich gerne…$"

Route114_Text_SteveRegister:
	.string "Vergiss nicht, was du mir angetan hast!\n"
	.string "Ich werde dich immer wieder daran\l"
	.string "erinnern!$"

Route114_Text_SteveRematchIntro:
	.string "Hufhufhufhufhuf…\n"
	.string "Komm, mein POKéMON ist bereit.$"

Route114_Text_SteveRematchDefeat:
	.string "Ich bin so froh, dass ich deine POKéMON\n"
	.string "sehen durfte…$"

Route114_Text_StevePostRematch:
	.string "Hufhufhufhufhuf…\p"
	.string "Wenn ich POKéMON kämpfen sehe, fange\n"
	.string "ich an zu zittern und zu schaudern…$"

Route114_Text_BernieIntro:
	.string "Wenn du ein Lagerfeuer entzündest,\n"
	.string "muss immer Wasser in der Nähe sein.$"

Route114_Text_BernieDefeat:
	.string "Gut, du hast mein Feuer gelöscht.$"

Route114_Text_BerniePostBattle:
	.string "Du musst im Wald mit allen Arten von\n"
	.string "Feuer wirklich sehr vorsichtig sein.\p"
	.string "Unterschätze nie die Gefahr des\n"
	.string "Feuers!$"

Route114_Text_BernieRegister:
	.string "Du hast meinen Kampfgeist entfacht.\n"
	.string "Wir sollten uns gegenseitig im POKéNAV\l"
	.string "eintragen.$"

Route114_Text_BernieRematchIntro:
	.string "Hast du gelernt, dass man immer Wasser\n"
	.string "neben einem Lagerfeuer stehen hat?$"

Route114_Text_BernieRematchDefeat:
	.string "Ich wurde schon gelöscht, bevor ich\n"
	.string "überhaupt zur Flamme ansetzen konnte.$"

Route114_Text_BerniePostRematch:
	.string "Du musst im Wald mit allen Arten von\n"
	.string "Feuer wirklich sehr vorsichtig sein.\p"
	.string "Unterschätze nie die Gefahr des\n"
	.string "Feuers!$"

Route114_Text_ClaudeIntro:
	.string "Wenn wir Angeln wären, hättest du nicht\n"
	.string "den Hauch einer Chance gegen mich.\l"
	.string "Also, dann zeig mal deine POKéMON.$"

Route114_Text_ClaudeDefeat:
	.string "Wären wir Angeln, hätte ich gewonnen!$"

Route114_Text_ClaudePostBattle:
	.string "Ich werde mein Glück bei METEOR FALLS\n"
	.string "versuchen und ein dickes Ding an Land\l"
	.string "ziehen.\p"
	.string "Da muss es etwas geben, das weiß ich\n"
	.string "genau!$"

Route114_Text_NolanIntro:
	.string "Ich liebe das Angeln. Aber ich liebe\n"
	.string "auch das Kämpfen!\p"
	.string "Wenn mich jemand herausfordern will, ich\n"
	.string "bin bereit. Auch wenn ich angle.$"

Route114_Text_NolanDefeat:
	.string "Ich liebe Kämpfe, aber das heißt nicht,\n"
	.string "dass ich gut darin bin…$"

Route114_Text_NolanPostBattle:
	.string "Dieses Mal werde ich trainieren!\p"
	.string "Das denke ich jedes Mal und dann\n"
	.string "kann ich mich doch nicht von meiner\l"
	.string "Angel und meinen POKéMON trennen.$"

Route114_Text_TyraIntro:
	.string "TYRA: Natürlich. Ich bin in der\n"
	.string "richtigen Stimmung. Ich werde dir\l"
	.string "etwas über POKéMON beibringen.$"

Route114_Text_TyraDefeat:
	.string "TYRA: Was für ein atemberaubender\n"
	.string "Kampfstil.$"

Route114_Text_TyraPostBattle:
	.string "TYRA: Ich bringe meiner Juniorin IVY\n"
	.string "etwas über POKéMON bei.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Kicher…\n"
	.string "Wenn du mit uns kämpfen willst, reicht\l"
	.string "ein POKéMON nicht aus.$"

Route114_Text_IvyIntro:
	.string "IVY: Wer hat dir das alles über POKéMON\n"
	.string "beigebracht?$"

Route114_Text_IvyDefeat:
	.string "IVY: Was für ein unglaublicher\n"
	.string "Kampfstil!$"

Route114_Text_IvyPostBattle:
	.string "IVY: Ich habe angefangen, POKéMON zu\n"
	.string "trainieren, weil TYRA, meine Mentorin,\l"
	.string "es mir beigebracht hat!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: Hast du nur ein POKéMON? Ich\n"
	.string "glaube, das fühlt sich einsam!$"

Route114_Text_KaiIntro:
	.string "Ich habe da einen großen Fang gemacht!\n"
	.string "Riesig, sag ich dir!$"

Route114_Text_KaiDefeat:
	.string "Was war das denn?\n"
	.string "War es für einen Sieg nicht groß genug?$"

Route114_Text_KaiPostBattle:
	.string "Okay!\n"
	.string "Ich werde mir ein Größeres angeln!$"

Route114_Text_CharlotteIntro:
	.string "Ich!\n"
	.string "Ich bin nicht nur ein hübsches Gesicht.$"

Route114_Text_CharlotteDefeat:
	.string "Das war aber überhaupt nicht niedlich.$"

Route114_Text_CharlottePostBattle:
	.string "Ich will kein POKéMON haben, das\n"
	.string "einfach nur niedlich ist.\p"
	.string "Ich liebe die, die niedlich sind, aber\n"
	.string "ihre Macken und Schrullen haben.$"

Route114_Text_AngelinaIntro:
	.string "Haben sich deine POKéMON sehr\n"
	.string "entwickelt?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, ich verstehe.\n"
	.string "Gut zu wissen.$"

Route114_Text_AngelinaPostBattle:
	.string "Einige POKéMON verändern sich enorm,\n"
	.string "sobald sie sich entwickelt haben.$"

Route115_Text_TimothyIntro:
	.string "Hm…\n"
	.string "Du siehst ganz kompetent aus…\l"
	.string "Ich leiste dir Gesellschaft!$"

Route115_Text_TimothyDefeat:
	.string "Du bist viel stärker, als ich mir das\n"
	.string "vorgestellt hatte.$"

Route115_Text_TimothyPostBattle:
	.string "Man wird nicht als Genie geboren!\n"
	.string "Alles basiert auf Anstrengung!\l"
	.string "Das ist meine Meinung…$"

Route115_Text_TimothyRegister:
	.string "Hmm… Eine Niederlage diesen Ausmaßes\n"
	.string "wird zu einer dunklen Erinnerung.\p"
	.string "Wenn du es erlaubst, würde ich gerne mal\n"
	.string "wieder gegen dich antreten.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… Deine Flinkheit spricht mal wieder\n"
	.string "für sich.\l"
	.string "Komm, leiste mir erneut Gesellschaft!$"

Route115_Text_TimothyRematchDefeat:
	.string "Stark wie immer!$"

Route115_Text_TimothyPostRematch:
	.string "Alles verlangt ein Maß an Anstrengung!\p"
	.string "Ich habe verloren, weil ich mich nicht\n"
	.string "genügend angestrengt habe.$"

Route115_Text_KoichiIntro:
	.string "Du!\p"
	.string "Mein MACHOLLO!\p"
	.string "Verlangt einen Kampf!$"

Route115_Text_KoichiDefeat:
	.string "Aua aua aua aua!$"

Route115_Text_KoichiPostBattle:
	.string "Meine MACHOLLO haben gejauchzt!\p"
	.string "Solange meine POKéMON nach Stärke\n"
	.string "suchen, werde auch ich stärker!$"

Route115_Text_NobIntro:
	.string "Mein Talent ist, Ziegelsteine mit meiner\n"
	.string "Stirn zu zertrümmern.$"

Route115_Text_NobDefeat:
	.string "Uguaaah!\n"
	.string "Mein Kopf wurde zertrümmert.$"

Route115_Text_NobPostBattle:
	.string "Ich bringe meinem POKéMON Karate bei.\p"
	.string "Und es sieht so aus, als wäre es darin\n"
	.string "viel besser als ich. Das freut mich.$"

Route115_Text_NobRegister:
	.string "Du hast mich beeindruckt! Gib mir eine\n"
	.string "neue Chance, wenn ich mein Training\l"
	.string "abgeschlossen habe!$"

Route115_Text_NobRematchIntro:
	.string "Nachdem du uns besiegt hattest, haben\n"
	.string "wir hart trainiert, um besser zu werden.\l"
	.string "Heute fordern wir Revanche!$"

Route115_Text_NobRematchDefeat:
	.string "Uguaaah!\n"
	.string "Wir haben schon wieder verloren!$"

Route115_Text_NobPostRematch:
	.string "Meine POKéMON werden stärker! Ich\n"
	.string "habe mein Trainingspensum verdoppelt.$"

Route115_Text_CyndyIntro:
	.string "Dieser Strand ist mein geheimer\n"
	.string "Trainingsort. Du hast mich gestört!$"

Route115_Text_CyndyDefeat:
	.string "Ich habe nicht genug trainiert.$"

Route115_Text_CyndyPostBattle:
	.string "Der Sand ist wie ein Kissen, das den\n"
	.string "Sturz abfängt und Verletzungen ver-\l"
	.string "hindert. Der perfekte Trainingsort.$"

Route115_Text_CyndyRegister:
	.string "Okay, gut. Du kannst jederzeit wieder\n"
	.string "vorbeikommen. Dafür möchte ich dann\l"
	.string "aber wieder gegen dich antreten.$"

Route115_Text_CyndyRematchIntro:
	.string "Okay, lass uns weiterkämpfen.$"

Route115_Text_CyndyRematchDefeat:
	.string "Ich kann kämpfen, aber meine POKéMON…$"

Route115_Text_CyndyPostRematch:
	.string "Sogar wenn ich verliere, habe ich meine\n"
	.string "Freude an dem Kampf. Wahrscheinlich\l"
	.string "weil ich die POKéMON liebe.$"

Route115_Text_HectorIntro:
	.string "Ich habe ein seltenes POKéMON.\n"
	.string "Möchtest du das mal sehen?$"

Route115_Text_HectorDefeat:
	.string "Du…\n"
	.string "Du willst mein POKéMON haben, oder?$"

Route115_Text_HectorPostBattle:
	.string "Ich habe ein seltenes POKéMON. Das\n"
	.string "reicht mir, um zufrieden zu sein.$"

Route115_Text_KyraIntro:
	.string "Ich kämpfe im Laufen!\n"
	.string "Komm, versuch, mit mir Schritt zu halten.$"

Route115_Text_KyraDefeat:
	.string "Hechel… Keuch… Schnauf…$"

Route115_Text_KyraPostBattle:
	.string "Es war offensichtlich ein Fehler, im\n"
	.string "Laufen zu kämpfen!\p"
	.string "Ich sollte ein Wettrennen machen,\n"
	.string "um mich ein bisschen zu beruhigen…$"

Route115_Text_JaidenIntro:
	.string "Nimm das!\n"
	.string "Die Ultra-POKéMON-Ninja-Attacke!$"

Route115_Text_JaidenDefeat:
	.string "Waaahaaa!\n"
	.string "Meine Strategie war ein Fehlschlag.$"

Route115_Text_JaidenPostBattle:
	.string "Aber meine POKéMON sind ultra.\n"
	.string "Komm, sag, dass sie ultra sind!$"

Route115_Text_HeleneIntro:
	.string "Die Kraft meiner POKéMON ist der eines\n"
	.string "Schwarzgurts ebenbürtig.$"

Route115_Text_HeleneDefeat:
	.string "Das ist einfach erniedrigend.$"

Route115_Text_HelenePostBattle:
	.string "Ich treffe selten jemanden, der besser\n"
	.string "ist als ich…\p"
	.string "Hah, ich habe dich durchschaut!\n"
	.string "Du bist ein ARENALEITER, stimmt’s?$"

Route115_Text_AlixIntro:
	.string "Wir haben uns in die Augen geschaut!\n"
	.string "Nun gibt es kein Zurück mehr.$"

Route115_Text_AlixDefeat:
	.string "Pah!\n"
	.string "Das war nicht schlecht.$"

Route115_Text_AlixPostBattle:
	.string "Oh, okay.\n"
	.string "Ich werde mich jetzt nach Hause\l"
	.string "TELEPORTieren.$"

Route115_Text_MarleneIntro:
	.string "Du hast mich bei meiner Meditation\n"
	.string "gestört… Das verlangt nach einer\l"
	.string "Strafe…$"

Route115_Text_MarleneDefeat:
	.string "Du hast meine Konzentration gestört.$"

Route115_Text_MarlenePostBattle:
	.string "Ich habe zusammen mit meinen POKéMON\n"
	.string "meditiert. Aber dieser Ort ist nicht\l"
	.string "gerade sehr geeignet dafür…$"

Route116_Text_ClarkIntro:
	.string "Wenn es keinen Tunnel gibt, dann\n"
	.string "klettere ich eben über den Berg.$"

Route116_Text_ClarkDefeat:
	.string "Hechel… Keuch…\n"
	.string "Verlieren erschöpft mich…$"

Route116_Text_ClarkPostBattle:
	.string "Macht auch nichts, wenn es keinen\n"
	.string "Tunnel gibt. Für WANDERER sind Berge\l"
	.string "wie Straßen.$"

Route116_Text_JoeyIntro:
	.string "Meine POKéMON sind die Kings.\n"
	.string "Überzeug dich selbst!$"

Route116_Text_JoeyDefeat:
	.string "Auaaa! Ein Kratzer!\n"
	.string "Ich brauche dringend einen Verband.$"

Route116_Text_JoeyPostBattle:
	.string "Verbände sind Zeichen von Rauheit!\n"
	.string "Ich brauche unbedingt einen weiteren!$"

Route116_Text_JoseIntro:
	.string "Meine KÄFER-POKéMON sind stark!\n"
	.string "Lass uns kämpfen!$"

Route116_Text_JoseDefeat:
	.string "Ich habe verloren! Ich dachte,\n"
	.string "ich könnte dich am Kragen packen…$"

Route116_Text_JosePostBattle:
	.string "KÄFER-POKéMON entwickeln sich schnell.\n"
	.string "So werden sie auch schnell stark.$"

Route116_Text_JaniceIntro:
	.string "Ich bringe dir bei, wie stark mein\n"
	.string "geliebtes POKéMON ist!$"

Route116_Text_JaniceDefeat:
	.string "Du bist mir haushoch überlegen…$"

Route116_Text_JanicePostBattle:
	.string "POKéMON, die Anmut und Stärke besitzen,\n"
	.string "sind ideal, finde ich.$"

Route116_Text_JerryIntro:
	.string "Wir lernen alle möglichen Sachen in der\n"
	.string "TRAINERSCHULE.\p"
	.string "Ich will einiges jetzt mal ausprobieren.$"

Route116_Text_JerryDefeat:
	.string "Ich habe in der Schule nicht aufge-\n"
	.string "passt. Daher habe ich verloren.$"

Route116_Text_JerryPostBattle:
	.string "Ich muss einige Kurse in der TRAINER-\n"
	.string "SCHULE wiederholen.\l"
	.string "Sonst wird FELIZIA vor Wut schäumen.$"

Route116_Text_JerryRegister1:
	.string "In der TRAINERSCHULE habe ich gelernt,\n"
	.string "dass man im POKéNAV TRAINER eintragen\l"
	.string "kann.\p"
	.string "Und wozu macht man das? Darf ich das\n"
	.string "mal ausprobieren?$"

Route116_Text_JerryRegister2:
	.string "In der TRAINERSCHULE habe ich gelernt,\n"
	.string "dass man im POKéNAV TRAINER eintragen\l"
	.string "kann.\p"
	.string "Und wozu macht man das? Darf ich das\n"
	.string "mal ausprobieren?$"

Route116_Text_JerryRematchIntro:
	.string "Ich habe in der TRAINERSCHULE fleißig\n"
	.string "gelernt. Ich werde dieses Mal also mit\l"
	.string "Sicherheit nicht verlieren.$"

Route116_Text_JerryRematchDefeat:
	.string "Waaas?\n"
	.string "Aber ich habe doch so fleißig gelernt!$"

Route116_Text_JerryPostRematch:
	.string "Ich muss einige Kurse in der TRAINER-\n"
	.string "SCHULE wiederholen.\l"
	.string "Sonst wird FELIZIA vor Wut schäumen.$"

Route116_Text_KarenIntro:
	.string "Ich lerne in der Schule und auf dem\n"
	.string "Heimweg lerne ich auch!$"

Route116_Text_KarenDefeat:
	.string "Ich bin geschockt! Ich habe\n"
	.string "verloren?!?$"

Route116_Text_KarenPostBattle:
	.string "Argh, so werde ich nie so ein eleganter\n"
	.string "TRAINER wie FELIZIA!$"

Route116_Text_KarenRegister1:
	.string "Hey! Das ist doch ein POKéNAV! Ich habe\n"
	.string "auch einen! Komm, trag mich ein!$"

Route116_Text_KarenRegister2:
	.string "Hey! Das ist doch ein POKéNAV! Ich habe\n"
	.string "auch einen! Komm, trag mich ein!$"

Route116_Text_KarenRematchIntro:
	.string "Seit unserem letzten Kampf habe ich\n"
	.string "viel gelernt. Das musst du dir ansehen!$"

Route116_Text_KarenRematchDefeat:
	.string "Ach, das gibt es doch nicht…$"

Route116_Text_KarenPostRematch:
	.string "Du hast FELIZIA besiegt?!?\n"
	.string "Dann kann ich dich nicht besiegen. Nee…$"

Route116_Text_SarahIntro:
	.string "Damit du’s nur weißt! Ich bin noch nie\n"
	.string "von irgendjemand irgendwo in irgendwas\l"
	.string "geschlagen worden!$"

Route116_Text_SarahDefeat:
	.string "Du meine Güte!\n"
	.string "Das ist eine völlig neue Erfahrung für\l"
	.string "mich.$"

Route116_Text_SarahPostBattle:
	.string "Mein Leben im Luxus ermöglicht mir, alle\n"
	.string "Dinge zu kaufen, die ich haben will.\p"
	.string "Aber wenn es um POKéMON geht, bin ich\n"
	.string "nicht gerade auf Rosen gebettet.$"

Route116_Text_DawsonIntro:
	.string "Schau dir das hinreißende Fell meiner\n"
	.string "POKéMON an und du wirst dich vor\l"
	.string "Bewunderung kampflos ergeben!$"

Route116_Text_DawsonDefeat:
	.string "Oh, sag, dass das nicht wahr ist!$"

Route116_Text_DawsonPostBattle:
	.string "Nein, nein, nein, nein!\n"
	.string "Du hast das Fell meiner POKéMON gegen\l"
	.string "den Strich gebürstet!\p"
	.string "Und meine Frisur hast du auch\n"
	.string "durcheinander gebracht. Jetzt muss ich\l"
	.string "meinen Stylisten aufsuchen!$"

Route116_Text_DevanIntro:
	.string "Wir werden dich hart rannehmen!$"

Route116_Text_DevanDefeat:
	.string "Aiaiaiaiai!\n"
	.string "Das war aber kein fairer Wettbewerb!$"

Route116_Text_DevanPostBattle:
	.string "Ich sollte es mal mit verschiedenen\n"
	.string "POKéMON-Arten versuchen.$"

Route116_Text_JohnsonIntro:
	.string "Dies hier ist eine Sackgasse. Ich\n"
	.string "langweile mich zu Tode. Los, wir kämpfen.$"

Route116_Text_JohnsonDefeat:
	.string "Das hat Spaß gemacht, auch wenn ich\n"
	.string "verloren habe.$"

Route116_Text_JohnsonPostBattle:
	.string "Möchtest du nicht hier bleiben und mir\n"
	.string "Gesellschaft leisten?$"

Route117_Text_IsaacIntro:
	.string "Du? Würdest du gegen meine POKéMON\n"
	.string "kämpfen?$"

Route117_Text_IsaacDefeat:
	.string "Du hast einfach großartige POKéMON…$"

Route117_Text_IsaacPostBattle:
	.string "POKéMON werden nicht nur durch Stärke\n"
	.string "definiert.\p"
	.string "Jedes POKéMON hat seinen eigenen\n"
	.string "Charakter. Dadurch wird der Umgang\l"
	.string "mit ihnen noch viel interessanter.$"

Route117_Text_IsaacRegister:
	.string "Ich werde mein Trainingspensum\n"
	.string "verdoppeln. Wir sollten bald mal wieder\l"
	.string "kämpfen.$"

Route117_Text_IsaacRematchIntro:
	.string "Die POKéMON, die ich aufgezogen habe,\n"
	.string "sehen gut aus. Genau wie immer.$"

Route117_Text_IsaacRematchDefeat:
	.string "Du weißt, wie man sie richtig aufzieht.\n"
	.string "Du hast die Talente, die man in einer\l"
	.string "PENSION braucht.$"

Route117_Text_IsaacPostRematch:
	.string "Deine POKéMON entwickeln sich gut.\n"
	.string "Du solltest sie zu einem WETTBEWERB\l"
	.string "anmelden!$"

Route117_Text_LydiaIntro:
	.string "Bitte lass mich überprüfen, ob du deine\n"
	.string "POKéMON auch richtig aufgezogen hast.$"

Route117_Text_LydiaDefeat:
	.string "Ja, sie sehen sehr gut aus…$"

Route117_Text_LydiaPostBattle:
	.string "Versuche, POKéMON ihrem Charakter\n"
	.string "gemäß aufzuziehen.$"

Route117_Text_LydiaRegister:
	.string "Ich freue mich, einen so hervorragenden\n"
	.string "TRAINER wie dich getroffen zu haben.\l"
	.string "Ich hoffe, wir sehen uns bald wieder.$"

Route117_Text_LydiaRematchIntro:
	.string "Erlaube mir, noch einmal zu prüfen, ob\n"
	.string "du deine POKéMON richtig aufziehst.$"

Route117_Text_LydiaRematchDefeat:
	.string "Sie wurden sehr, sehr gut aufgezogen…$"

Route117_Text_LydiaPostRematch:
	.string "POKéMON mögen, abhängig von ihrem\n"
	.string "Wesen, die unterschiedlichsten {POKEBLOCK}.$"

Route117_Text_DylanIntro:
	.string "Ich bin mitten in einem Triathlon. Aber\n"
	.string "lass uns trotzdem kämpfen!$"

Route117_Text_DylanDefeat:
	.string "Ich habe keine Energie mehr!$"

Route117_Text_DylanPostBattle:
	.string "Ich habe es wohl verpatzt…\p"
	.string "Ich habe in meinem letzten Kampf\n"
	.string "stark nachgelassen…$"

Route117_Text_DylanRegister:
	.string "POKéMON müssen stark sein?\n"
	.string "Ich möchte, dass du mich trainierst.$"

Route117_Text_DylanRematchIntro:
	.string "Ich bin mitten in einem Triathlon, liege\n"
	.string "aber weit an der Spitze. Lass uns zu\l"
	.string "einem schnellen Kampf antreten.$"

Route117_Text_DylanRematchDefeat:
	.string "Ich habe schon wieder meine Energie\n"
	.string "verloren!$"

Route117_Text_DylanPostRematch:
	.string "Im Schwimmen und im Radfahren bin ich\n"
	.string "unschlagbar, aber meine Leistungen in\l"
	.string "POKéMON-Kämpfen sind unbefriedigend.$"

Route117_Text_MariaIntro:
	.string "Ich trainiere mit meinem POKéMON und\n"
	.string "bin mit meinen Fähigkeiten echt\l"
	.string "zufrieden.$"

Route117_Text_MariaDefeat:
	.string "Ich glaube, ich muss wirklich mehr üben.$"

Route117_Text_MariaPostBattle:
	.string "Training zahlt sich nur aus, wenn man\n"
	.string "regelmäßig trainiert.\p"
	.string "Okay! Ich setze mein Training fort!\n"
	.string "Morgen!$"

Route117_Text_MariaRegister:
	.string "Du scheinst ein sehr gutes Training zu\n"
	.string "haben… Ich würde gerne später\l"
	.string "wieder gegen dich antreten.$"

Route117_Text_MariaRematchIntro:
	.string "Trainierst du auch fleißig weiter?\n"
	.string "Ich trainiere sehr fleißig!\l"
	.string "Ich liefere dir den Beweis.$"

Route117_Text_MariaRematchDefeat:
	.string "Ich glaube, ich muss wirklich mehr üben.$"

Route117_Text_MariaPostRematch:
	.string "Ich werde mein Training morgen fort-\n"
	.string "setzen. Lass uns bald wieder kämpfen!$"

Route117_Text_DerekIntro:
	.string "Einst war ich KÄFERSAMMLER.\n"
	.string "Heute bin ich ein KÄFERFREAK!\p"
	.string "Aber meine Liebe zu POKéMON hat sich\n"
	.string "nicht verändert!$"

Route117_Text_DerekDefeat:
	.string "Meine Ungeschicktheit ist auch\n"
	.string "ungebrochen…$"

Route117_Text_DerekPostBattle:
	.string "Alles, was ich getan habe, war meinem\n"
	.string "Herzen zu folgen, und nun nennen sie\l"
	.string "mich den KÄFERFREAK…\p"
	.string "Aber ich bin ein Experte für KÄFER-\n"
	.string "POKéMON, daher ist es nur natürlich,\l"
	.string "dass sie mich KÄFERFREAK nennen.$"

Route117_Text_AnnaIntro:
	.string "IRM: Ich bin hier mit meiner hübschen\n"
	.string "Juniorpartnerin. Ich muss gut sein!$"

Route117_Text_AnnaDefeat:
	.string "IRM: Ich bin mit meiner hübschen\n"
	.string "Juniorpartnerin hier. Ich will so\l"
	.string "gerne gewinnen!$"

Route117_Text_AnnaPostBattle:
	.string "IRM: Deine POKéMON haben einige gute\n"
	.string "Kombinationen auf Lager.\p"
	.string "Trotzdem bist du uns gegenüber nur\n"
	.string "zweite Klasse.$"

Route117_Text_AnnaAndMegRegister:
	.string "IRM: Das können wir nicht auf sich\n"
	.string "beruhen lassen! Wir werden wieder\l"
	.string "gegeneinander antreten.$"

Route117_Text_AnnaNotEnoughMons:
	.string "IRM: Wenn du gegen uns antreten willst,\n"
	.string "bring zwei POKéMON mit.$"

Route117_Text_MegIntro:
	.string "IDA: Ich werde mich mit meiner Super-\n"
	.string "Seniorpartnerin verbünden und\l"
	.string "siegen!$"

Route117_Text_MegDefeat:
	.string "IDA: Oh, nein! Tut mir Leid, IRM.\n"
	.string "Ich habe dich im Stich gelassen.$"

Route117_Text_MegPostBattle:
	.string "IDA: Ich habe IRM in eine Niederlage\n"
	.string "gebracht. Ohne mich hätte sie\l"
	.string "gewonnen!$"

Route117_Text_MegNotEnoughMons:
	.string "IDA: Hast du nur ein POKéMON?\n"
	.string "Dann können wir nicht mit dir kämpfen.\p"
	.string "Wir wollen einen 2-gegen-2-Kampf.$"

Route117_Text_AnnaRematchIntro:
	.string "IRM: Ich kann doch nicht ständig vor\n"
	.string "meiner Juniorpartnerin verlieren…$"

Route117_Text_AnnaRematchDefeat:
	.string "IRM: Ich komme einfach nicht in Fahrt.$"

Route117_Text_AnnaPostRematch:
	.string "IRM: Deine POKéMON haben einige gute\n"
	.string "Kombinationen auf Lager.\p"
	.string "Trotzdem bist du uns gegenüber nur\n"
	.string "zweite Klasse.$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "IRM: Wenn du gegen uns antreten willst,\n"
	.string "bring zwei POKéMON mit.$"

Route117_Text_MegRematchIntro:
	.string "IDA: Ich werde mich mit meiner Senior-\n"
	.string "partnerin verbünden und siegen!$"

Route117_Text_MegRematchDefeat:
	.string "IDA: Viel zu stark!$"

Route117_Text_MegPostRematch:
	.string "IDA: Ich habe mit meiner Senior-\n"
	.string "partnerin gekämpft. Wir haben verloren.\p"
	.string "Das ist so entmutigend…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "IDA: Hast du nur ein POKéMON?\n"
	.string "Dann können wir nicht mit dir kämpfen.\p"
	.string "Wir wollen einen 2-gegen-2-Kampf.$"

Route117_Text_MelinaIntro:
	.string "Ist das nicht nett? Zu kämpfen,\n"
	.string "während man sich schöne Blumen\l"
	.string "anschaut?$"

Route117_Text_MelinaDefeat:
	.string "Das war wirklich sehr beeindruckend.$"

Route117_Text_MelinaPostBattle:
	.string "Es ist einfach toll, joggen zu gehen und\n"
	.string "dabei die Blumen zu betrachten.$"

Route117_Text_BrandiIntro:
	.string "Ich werde dir die verborgenen Kräfte\n"
	.string "der PSYCHO-POKéMON zeigen.$"

Route117_Text_BrandiDefeat:
	.string "Erstaunlich!$"

Route117_Text_BrandiPostBattle:
	.string "PSYCHO-POKéMON sind komplexe Wesen.\n"
	.string "Du solltest dir auch welche fangen.$"

Route117_Text_AishaIntro:
	.string "Konzentration auf den Sieg!\n"
	.string "So kämpfe ich!$"

Route117_Text_AishaDefeat:
	.string "Ich verschwende keine Zeit damit, mich\n"
	.string "über eine Niederlage aufzuregen. Ich\l"
	.string "nutze meine Zeit lieber zum Trainieren.$"

Route117_Text_AishaPostBattle:
	.string "Ich glaube, wenn man Angst vor einer\n"
	.string "Niederlage hat, dann verliert man auch.$"

Route118_Text_RoseIntro:
	.string "Der Duft von Blumen hat eine magische\n"
	.string "Kraft. Er reinigt Körper und Geist.$"

Route118_Text_RoseDefeat:
	.string "Oh, du meine Güte.\n"
	.string "Scheinbar habe ich verloren.$"

Route118_Text_RosePostBattle:
	.string "Blumen, POKéMON…\n"
	.string "Ich liebe alles, was gut riecht.\p"
	.string "Stinkende Dinge…\n"
	.string "Bah, da muss ich passen.$"

Route118_Text_RoseRegister:
	.string "Schnief… Dieser Geruch… Das ist ein\n"
	.string "POKéNAV! Wir müssen uns gegenseitig\l"
	.string "eintragen!$"

Route118_Text_RoseRematchIntro:
	.string "Hat dich der süße Duft hierher\n"
	.string "gebracht?$"

Route118_Text_RoseRematchDefeat:
	.string "Die Kraft des Duftes…\n"
	.string "Sie scheint nichts zu bewirken.$"

Route118_Text_RosePostRematch:
	.string "Wenn du einen süßen Duft richtig ein-\n"
	.string "setzt, werden POKéMON davon\l"
	.string "angezogen.$"

Route118_Text_PerryIntro:
	.string "VOGEL-POKéMON, die elegant durch die\n"
	.string "Lüfte FLIEGEN… Sie sind die Besten!$"

Route118_Text_PerryDefeat:
	.string "Argh… Das war eine Bruchlandung…$"

Route118_Text_PerryPostBattle:
	.string "Du hast großartige POKéMON.\n"
	.string "Ich muss meine besser trainieren.$"

Route118_Text_ChesterIntro:
	.string "Erhebt euch!\n"
	.string "Meine VOGEL-POKéMON!$"

Route118_Text_ChesterDefeat:
	.string "Sie sind abgehoben…$"

Route118_Text_ChesterPostBattle:
	.string "Wenn sie erst einmal stärker geworden\n"
	.string "sind, können sie auch freier fliegen.$"

Route118_Text_BarnyIntro:
	.string "Ich bin ein ANGLER, aber auch ein\n"
	.string "TRAINER. Ich ziehe die POKéMON auf,\l"
	.string "die ich gefangen habe.$"

Route118_Text_BarnyDefeat:
	.string "Ich dachte, ich wäre gut im Training…$"

Route118_Text_BarnyPostBattle:
	.string "Ich kann nicht gewinnen, wenn ich\n"
	.string "POKéMON trainiere, während ich angle.\p"
	.string "Habe ich alles nur halb getan?$"

Route118_Text_WadeIntro:
	.string "Für ANGLER ist die Ausrüstung\n"
	.string "entscheidend.\p"
	.string "Aber für TRAINER sind natürlich die\n"
	.string "POKéMON und das Herz entscheidend!$"

Route118_Text_WadeDefeat:
	.string "Ich wurde im Herzen geschlagen?$"

Route118_Text_WadePostBattle:
	.string "Wenn ich so darüber nachdenke, komme\n"
	.string "ich zu dem Schluss, dass Angeln ein\l"
	.string "Kampf zwischen ANGLER und POKéMON ist.$"

Route118_Text_DaltonIntro:
	.string "Meine Melodie wird deine Seele\n"
	.string "erschüttern.$"

Route118_Text_DaltonDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle:
	.string "Eine E-Gitarre muss nicht immer laut\n"
	.string "sein…\p"
	.string "Sie kann auch so gespielt werden, dass\n"
	.string "eine herzergreifende Melodie erklingt…$"

Route118_Text_DaltonRegister:
	.string "Sobald ich eine schöne Melodie\n"
	.string "komponiert habe, musst du sie anhören!$"

Route118_Text_DaltonRematchIntro:
	.string "Eine Melodie von meinen POKéMON und mir.\n"
	.string "Lass sie uns deiner Seele schenken.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
	.string "Wenn ich spiele, sollten dich meine Ge-\n"
	.string "fühle über meine E-Gitarre erreichen…$"

Route118_Text_DeandreIntro:
	.string "Los, los, los!\n"
	.string "POKéMON 1, 2 und 3!$"

Route118_Text_DeandreDefeat:
	.string "Los, ihr POKéMON! Geht es euch gut?\n"
	.string "POKéMON 1, 2 und 3?!?$"

Route118_Text_DeandrePostBattle:
	.string "Ich finde es megacool, dass ich ein\n"
	.string "POKéMON-Team besitze!\p"
	.string "Du kannst es mir ruhig nachmachen -\n"
	.string "das stört mich nicht!$"

Route119_Text_BrentIntro:
	.string "Wir gehören zum Mimikry-Zirkel!\n"
	.string "Wir ahmen nach, was du machst!$"

Route119_Text_BrentDefeat:
	.string "Huupsie!\n"
	.string "Ich habe verloren!$"

Route119_Text_BrentPostBattle:
	.string "Was so toll an Mimikry sein soll?\p"
	.string "Hähähä…\n"
	.string "Das wirst du nie verstehen…$"

Route119_Text_DonaldIntro:
	.string "So trifft man sich! Meine KÄFER-\n"
	.string "POKéMON leisten dir Gesellschaft!$"

Route119_Text_DonaldDefeat:
	.string "Ich wünschte, wir hätten uns nie\n"
	.string "getroffen…$"

Route119_Text_DonaldPostBattle:
	.string "Ich möchte noch Mimikry bei dir an-\n"
	.string "wenden.\p"
	.string "Kannst du dich mal ein bisschen\n"
	.string "bewegen?$"

Route119_Text_TaylorIntro:
	.string "Trittst du einen Schritt vor, treten wir\n"
	.string "auch einen Schritt vor.\p"
	.string "Drehst du dich nach rechts, drehen wir\n"
	.string "uns auch nach rechts…$"

Route119_Text_TaylorDefeat:
	.string "Aber wenn du gewinnst, verliere ich…$"

Route119_Text_TaylorPostBattle:
	.string "Ich kann nicht mit Mimikry nachahmen,\n"
	.string "wie du den Kampf gewinnst. Unmöglich!\l"
	.string "Das lässt mich kochen vor Wut.$"

Route119_Text_DougIntro:
	.string "Hey, geschafft! Du hast mich gefunden!\n"
	.string "Oder wolltest du mir ausweichen?$"

Route119_Text_DougDefeat:
	.string "Hui, was für ein großartiger Kampf!$"

Route119_Text_DougPostBattle:
	.string "Wir sind der Mimikry-Zirkel! Ich\n"
	.string "hoffe, dir gefiel unsere Vorstellung!$"

Route119_Text_GregIntro:
	.string "Du weißt nicht, wer ich bin, stimmt’s?\p"
	.string "Aber… Ich kenne dich auch nicht.\n"
	.string "Lass uns kämpfen.$"

Route119_Text_GregDefeat:
	.string "Du bist ganz schön stark!$"

Route119_Text_GregPostBattle:
	.string "Solange du hier bist, werden wir jede\n"
	.string "deiner Bewegungen nachahmen.$"

Route119_Text_KentIntro:
	.string "Der Mimikry-Zirkel wurde von Leuten\n"
	.string "gegründet, die die Mimikry lieben.\p"
	.string "Der Kampf beginnt, sobald wir aufei-\n"
	.string "nander treffen!$"

Route119_Text_KentDefeat:
	.string "Ich gebe auf!$"

Route119_Text_KentPostBattle:
	.string "Möchtest du nicht dem Mimikry-Zirkel\n"
	.string "beitreten?$"

Route119_Text_JacksonIntro:
	.string "Wer besitzt das Wissen und die Technik,\n"
	.string "um zu überleben?\p"
	.string "Das sind die POKéMON-RANGER!$"

Route119_Text_JacksonDefeat:
	.string "Ich besitze nicht genügend Wissen über\n"
	.string "POKéMON…$"

Route119_Text_JacksonPostBattle:
	.string "Aus der Zivilisation ausbrechen und die\n"
	.string "wilde Natur in uns erwecken!\p"
	.string "Das ist unsere Vision.$"

Route119_Text_JacksonRegister:
	.string "Ich hoffe, du kämpfst bald wieder gegen\n"
	.string "mich, ohne mich wegen meiner\l"
	.string "Unwissenheit aufzuziehen.$"

Route119_Text_JacksonRematchIntro:
	.string "Meine wilde Natur regt sich in mir, wenn\n"
	.string "ich mit POKéMON zusammen bin.$"

Route119_Text_JacksonRematchDefeat:
	.string "Du bist immer noch sehr stark!$"

Route119_Text_JacksonPostRematch:
	.string "Glaube an deine POKéMON.\n"
	.string "Glaube an dich.\p"
	.string "Dein Weg eröffnet sich von selbst.$"

Route119_Text_CatherineIntro:
	.string "Oh! Schau dich nur an!\p"
	.string "Für einen Abenteurer hast du\n"
	.string "sehr leichtes Gepäck dabei!$"

Route119_Text_CatherineDefeat:
	.string "Unfälle passieren immer dann, wenn du\n"
	.string "nicht damit rechnest!$"

Route119_Text_CatherinePostBattle:
	.string "Du hast leichtes Gepäck, aber alles, was\n"
	.string "du brauchst, dabei.\p"
	.string "Du bist an der Spitze deiner geistigen\n"
	.string "und körperlichen Kraft angekommen.$"

Route119_Text_CatherineRegister:
	.string "Hast du einen POKéNAV?\n"
	.string "Jeder TRAINER sollte so einen besitzen!\p"
	.string "Hey, du hast ja einen! Dann sollten wir\n"
	.string "uns gegenseitig eintragen.$"

Route119_Text_CatherineRematchIntro:
	.string "Wie läuft es auf deiner Reise mit den\n"
	.string "POKéMON?$"

Route119_Text_CatherineRematchDefeat:
	.string "Bei mir fehlt irgendetwas…$"

Route119_Text_CatherinePostRematch:
	.string "So, wie du als TRAINER deinen POKéMON\n"
	.string "vertraust, vertrauen dir deine POKéMON.$"

Route119_Text_HughIntro:
	.string "Die Weiten des Himmels strahlen die Aura\n"
	.string "unausgesprochener Versprechen aus.\p"
	.string "Nichts ist vergleichbar mit dem\n"
	.string "absoluten Glück des Fliegens!$"

Route119_Text_HughDefeat:
	.string "Abgewürgt und abgestürzt.$"

Route119_Text_HughPostBattle:
	.string "Meine VOGEL-POKéMON lassen den Traum\n"
	.string "vom Fliegen für mich wahr werden!$"

Route119_Text_PhilIntro:
	.string "Ich zeige dir meine wahre Stärke und\n"
	.string "die meiner VOGEL-POKéMON!$"

Route119_Text_PhilDefeat:
	.string "Uns fehlt es an Potenzial…$"

Route119_Text_PhilPostBattle:
	.string "Schon als kleines Kind habe ich VOGEL-\n"
	.string "POKéMON geliebt…$"

Route119_Text_YasuIntro:
	.string "Ich lauere in den Schatten und lebe in\n"
	.string "der Dunkelheit… Das ist mein Schicksal.\p"
	.string "Ich tauche auf, um dich heraus-\n"
	.string "zufordern!$"

Route119_Text_YasuDefeat:
	.string "Ich gestehe meine Niederlage ein.$"

Route119_Text_YasuPostBattle:
	.string "Die, die im Kampf geschlagen wurden,\n"
	.string "verschwinden lautlos in der Dunkelheit.\l"
	.string "Auch das ist Schicksal…$"

Route119_Text_TakashiIntro:
	.string "Wenn du nicht auf deine Deckung auf-\n"
	.string "passt, kommt der Schmerz zu dir!$"

Route119_Text_TakashiDefeat:
	.string "Du bist überraschend gut!$"

Route119_Text_TakashiPostBattle:
	.string "Mein Überraschungsangriff endete in\n"
	.string "einer Niederlage…$"

Route119_Text_HideoIntro:
	.string "Um einen Baum zu verstecken, nutze den\n"
	.string "Wald!$"

Route119_Text_HideoDefeat:
	.string "Ich verneige mich vor deiner Stärke.$"

Route119_Text_HideoPostBattle:
	.string "Um einen Baum zu verstecken, nutze den\n"
	.string "Wald. Um ein POKéMON zu verstecken,\l"
	.string "nutze ein POKéMON!\p"
	.string "Dahinter steckt keine tiefere\n"
	.string "Bedeutung.$"

Route119_Text_ChrisIntro:
	.string "Du hast mich angesprochen…\n"
	.string "Also willst du mit mir kämpfen!\p"
	.string "Sicher! Ich will das POKéMON einsetzen,\n"
	.string "das ich gefangen habe, als ich SURFER\l"
	.string "einsetzte.$"

Route119_Text_ChrisDefeat:
	.string "Ich habe keine Ahnung, was verlangt\n"
	.string "wird, um zu gewinnen.$"

Route119_Text_ChrisPostBattle:
	.string "Nutze ein POKéMON als SURFER…\p"
	.string "Dann angle von seinem Rücken aus…\p"
	.string "Ein äußerst angenehmer Zeitvertreib!$"

Route119_Text_FabianIntro:
	.string "Zeig mir deine Powerakkorde!\n"
	.string "Der Sieg gehört mir! Nun ist es an\l"
	.string "der Zeit, im Ruhm zu glänzen!$"

Route119_Text_FabianDefeat:
	.string "Du hast mir gezeigt, wer der Boss ist!\n"
	.string "Ich muss die Niederlage ertragen!$"

Route119_Text_FabianPostBattle:
	.string "Du hast mir deine starken Akkorde\n"
	.string "gezeigt! Lass mich allein!\l"
	.string "Dein Sieg muss gesühnt werden.$"

Route119_Text_DaytonIntro:
	.string "Hohoho! Ich mag Kinder, die meinen,\n"
	.string "sie wären TRAINER. Lass uns einen\l"
	.string "Kampf austragen.$"

Route119_Text_DaytonDefeat:
	.string "Du bist wirklich beeindruckend.\n"
	.string "Hohohoho!$"

Route119_Text_DaytonPostBattle:
	.string "Hohohoho!\n"
	.string "Ich versuche den Kindern, die meinen,\l"
	.string "sie wären TRAINER, nachzueifern.$"

Route119_Text_RachelIntro:
	.string "Egal, wo ich gerade bin, meinen\n"
	.string "Sonnenschirm habe ich immer dabei.$"

Route119_Text_RachelDefeat:
	.string "Aber…\n"
	.string "Das ist nicht fair.$"

Route119_Text_RachelPostBattle:
	.string "Du fragst, ob mein Sonnenschirm\n"
	.string "schwer ist? Dein BEUTEL ist mit mehr\l"
	.string "Mist gefüllt, als ich tragen könnte.$"

Route120_Text_ColinIntro:
	.string "Hast du Attacken auf Lager, die ein\n"
	.string "fliegendes POKéMON schlagen können?$"

Route120_Text_ColinDefeat:
	.string "Du bist mir überlegen!$"

Route120_Text_ColinPostBattle:
	.string "Die Attacke FLIEGEN ist sehr praktisch,\n"
	.string "meinst du nicht auch?\p"
	.string "Wenn ein POKéMON fliegt, kann ihm fast\n"
	.string "keine Attacke Schaden zufügen.$"

Route120_Text_RobertIntro:
	.string "Mein POKéMON ist stark!\n"
	.string "Wie sieht es mit deinen aus?$"

Route120_Text_RobertDefeat:
	.string "Deine POKéMON sind stärker…$"

Route120_Text_RobertPostBattle:
	.string "Ein POKéMON, das beständig wächst, ist\n"
	.string "absolut zuverlässig…$"

Route120_Text_RobertRegister:
	.string "Du wirst mit Sicherheit immer besser.\n"
	.string "Ich würde dich gerne in meinen POKéNAV\l"
	.string "eintragen.$"

Route120_Text_RobertRematchIntro:
	.string "Ein POKéMON, das beständig wächst, ist\n"
	.string "absolut zuverlässig…$"

Route120_Text_RobertRematchDefeat:
	.string "Deine POKéMON sind enorm stark.$"

Route120_Text_RobertPostRematch:
	.string "Meine POKéMON werden immer stärker.\n"
	.string "Ich muss auch immer stärker werden.$"

Route120_Text_LorenzoIntro:
	.string "Ich prüfe deine POKéMON und schaue, ob\n"
	.string "sie fit für das Leben im Freien sind.$"

Route120_Text_LorenzoDefeat:
	.string "Mit solch starken POKéMON brauchst du\n"
	.string "in der Natur keine Angst zu haben.$"

Route120_Text_LorenzoPostBattle:
	.string "Mit POKéMON dorthin zu reisen, wohin\n"
	.string "man auch immer will… Das ist das\l"
	.string "Schöne an einem Leben als TRAINER.$"

Route120_Text_JennaIntro:
	.string "Wie sieht es mit deiner Fitness aus?\n"
	.string "Wenn du nicht fit bist, könnten \l"
	.string "harte Zeiten auf dich zukommen.$"

Route120_Text_JennaDefeat:
	.string "Ich bin fit wie ein Turnschuh, aber…$"

Route120_Text_JennaPostBattle:
	.string "Fitnesstraining gehört zu meinem\n"
	.string "Leben. Ich laufe mit meinen POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Kampf gefällig?$"

Route120_Text_JeffreyDefeat:
	.string "Verloren…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Muss mich mehr anstrengen…$"

Route120_Text_JeffreyRegister:
	.string "… … … … …\n"
	.string "…\l"
	.string "… … … … …\l"
	.string "…\l"
	.string "Möchtest du noch einmal kämpfen?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Noch ein Kampf gefällig?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "Ich habe wieder verloren…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Ich werde mich mehr anstrengen…\l"
	.string "Für meine kostbaren KÄFER-POKéMON…$"

Route120_Text_JenniferIntro:
	.string "POKéMON haben viele spezielle Fähig-\n"
	.string "keiten. Wenn du ein klasse TRAINER\l"
	.string "werden willst, lerne etwas darüber.$"

Route120_Text_JenniferDefeat:
	.string "Du setzt offensichtlich dein Gehirn\n"
	.string "ein.$"

Route120_Text_JenniferPostBattle:
	.string "Die speziellen Fähigkeiten eines\n"
	.string "POKéMON bestimmen den Kampfstil.$"

Route120_Text_ChipIntro:
	.string "Wer magst du sein?\p"
	.string "Suchst du etwa nach antiken Ruinen,\n"
	.string "von denen die Legende sagt, sie\l"
	.string "seien hier zu finden?$"

Route120_Text_ChipDefeat:
	.string "Was für ein erbärmlicher Rückschritt…$"

Route120_Text_ChipPostBattle:
	.string "Dieser gigantische Felsen… Ich würde\n"
	.string "zu gerne glauben, er enthielte antike\l"
	.string "Schätze. Aber ich sehe keinen Eingang.$"

Route120_Text_ClarissaIntro:
	.string "Warum ich diesen Schirm trage?\p"
	.string "Das verrate ich dir, wenn du mich\n"
	.string "besiegen kannst.$"

Route120_Text_ClarissaDefeat:
	.string "Ein Schirm kann nicht vor den Attacken\n"
	.string "der POKéMON schützen…$"

Route120_Text_ClarissaPostBattle:
	.string "Ich glaube nicht, dass starkes Sonnen-\n"
	.string "licht gut für meine POKéMON ist.\l"
	.string "Daher schütze ich sie mit meinem Schirm.$"

Route120_Text_AngelicaIntro:
	.string "Mein Schirm, meine POKéMON und ich…\p"
	.string "Würde eines dieser Elemente fehlen,\n"
	.string "wäre dieses Bild der Schönheit ruiniert.$"

Route120_Text_AngelicaDefeat:
	.string "Du hast das Bild der Schönheit ruiniert!$"

Route120_Text_AngelicaPostBattle:
	.string "Mein Schirm würde dir überhaupt nicht\n"
	.string "stehen.\p"
	.string "Er wäre dir sogar hinderlich.$"

Route120_Text_KeigoIntro:
	.string "Ich werde die Techniken der POKéMON\n"
	.string "übernehmen und neue Ninja-Techniken\l"
	.string "daraus entwickeln.$"

Route120_Text_KeigoDefeat:
	.string "Die Entwicklung neuer Ninja-Techniken\n"
	.string "bleibt ein Traum…$"

Route120_Text_KeigoPostBattle:
	.string "Vielleicht sollte ich unter einem Ninja-\n"
	.string "Meister lernen…$"

Route120_Text_RileyIntro:
	.string "Wir Ninja verbergen uns unter unseren\n"
	.string "Tarnmänteln. Ich wette, du wusstest\l"
	.string "nicht, wo ich versteckt war!$"

Route120_Text_RileyDefeat:
	.string "Ich habe verloren! Ich wünschte, mein\n"
	.string "Tarnmantel würde meine Schande tarnen.$"

Route120_Text_RileyPostBattle:
	.string "Unsere Tarnmäntel sind alle handge-\n"
	.string "arbeitet.$"

Route120_Text_CallieIntro:
	.string "Wenn du nicht aufpasst, wirst du\n"
	.string "verletzt.$"

Route120_Text_CallieDefeat:
	.string "Aua!\n"
	.string "Ich wurde verletzt.$"

Route120_Text_CalliePostBattle:
	.string "Ich frage mich… sollen sich meine\n"
	.string "POKéMON entwickeln? Sie sind doch\l"
	.string "eigentlich niedlich, so wie sie sind.$"

Route120_Text_LeonelIntro:
	.string "Deine Team-POKéMON…\n"
	.string "Besitzt du verschiedene Arten?$"

Route120_Text_LeonelDefeat:
	.string "Ich wurde Zeuge deiner Taktik.$"

Route120_Text_LeonelPostBattle:
	.string "Ich finde es großartig, wie stark du im\n"
	.string "Kampf mit deinen Lieblings-POKéMON\l"
	.string "bist.$"

Route121_Text_VanessaIntro:
	.string "Möchtest du mit meinem wunderhübschen\n"
	.string "POKéMON spielen?$"

Route121_Text_VanessaDefeat:
	.string "So habe ich das aber nicht gemeint!$"

Route121_Text_VanessaPostBattle:
	.string "Ich gehe zu einem WETTBEWERB in\n"
	.string "LILYCOVE CITY.\p"
	.string "Mein POKéMON sollte kein Problem haben,\n"
	.string "in der MASTER-KLASSE zu glänzen.$"

Route121_Text_WalterIntro:
	.string "Mit meinem POKéMON habe ich alle vier\n"
	.string "Ecken der Welt bereist.\p"
	.string "Man könnte sagen, dass ich viel\n"
	.string "Vertrauen in mein Können habe.$"

Route121_Text_WalterDefeat:
	.string "Ah, gut gespielt.$"

Route121_Text_WalterPostBattle:
	.string "Ich möchte noch einmal die Welt mit\n"
	.string "meinem POKéMON umrunden.$"

Route121_Text_WalterRegister:
	.string "Die Tapferkeit deiner POKéMON ist\n"
	.string "bemerkenswert. Ich würde dich gerne\l"
	.string "zur Erinnerung im POKéNAV eintragen.$"

Route121_Text_WalterRematchIntro:
	.string "Mit meinem POKéMON habe ich alle vier\n"
	.string "Ecken der Welt bereist.\p"
	.string "Man könnte sagen, dass ich viel\n"
	.string "Vertrauen in mein Können habe.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, gut gespielt.$"

Route121_Text_WalterPostRematch:
	.string "Deine POKéMON und du…\p"
	.string "Eure Fähigkeiten werden auch in\n"
	.string "Übersee als außerordentlich angesehen.$"

Route121_Text_TammyIntro:
	.string "Auf der Welt gibt es Dinge, die jenseits\n"
	.string "deines Verständnisses liegen…$"

Route121_Text_TammyDefeat:
	.string "Ich habe verloren…$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE…\n"
	.string "Dort ist eine geheimnisvolle Kraft am\l"
	.string "Werk…$"

Route121_Text_KateIntro:
	.string "EVA: Zusammen sind wir furchtlos!\n"
	.string "Wir demonstrieren dir unsere Stärke!$"

Route121_Text_KateDefeat:
	.string "EVA: Ich habe vor den Augen meiner\n"
	.string "Juniorpartnerin versagt…$"

Route121_Text_KatePostBattle:
	.string "EVA: Wenn sich jemand auf mich\n"
	.string "verlässt, versuche ich ihm gegenüber\l"
	.string "immer cool aufzutreten…$"

Route121_Text_KateNotEnoughMons:
	.string "EVA: Wenn du nur ein POKéMON hast,\n"
	.string "können wir nicht mit dir kämpfen.\p"
	.string "Das wäre äußerst unfair.$"

Route121_Text_JoyIntro:
	.string "UTE: Zusammen sind wir furchtlos!\n"
	.string "Wir demonstrieren dir unsere Stärke!$"

Route121_Text_JoyDefeat:
	.string "UTE: Bitte vergib mir, EVA!$"

Route121_Text_JoyPostBattle:
	.string "UTE: Ehehehe, ich muss wohl noch etwas\n"
	.string "mit meiner Seniorpartnerin trainieren.$"

Route121_Text_JoyNotEnoughMons:
	.string "UTE: Du brauchst mindestens zwei\n"
	.string "POKéMON, um gegen uns zu kämpfen.$"

Route121_Text_JessicaIntro:
	.string "Stopp! Schau dir meine wunderbaren\n"
	.string "POKéMON gut an!$"

Route121_Text_JessicaDefeat:
	.string "Oh, wie konntest du nur! Nimm die\n"
	.string "Sache doch nicht gleich so ernst!$"

Route121_Text_JessicaPostBattle:
	.string "Vielleicht werde ich in die SAFARI ZONE\n"
	.string "gehen und mehr POKéMON fangen!$"

Route121_Text_JessicaRegister:
	.string "Diesmal habe ich es dir leicht gemacht!\n"
	.string "Das wird das nächste Mal anders sein.$"

Route121_Text_JessicaRematchIntro:
	.string "Meine wertvollen POKéMON sind ge-\n"
	.string "wachsen! Schau mal!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, du hast es wieder getan!\n"
	.string "Du nimmst es wirklich zu ernst!$"

Route121_Text_JessicaPostRematch:
	.string "Vielleicht werde ich in die SAFARI ZONE\n"
	.string "gehen und mehr POKéMON fangen!$"

Route121_Text_CristinIntro:
	.string "Ich habe dieses Prinzip. Jeden Tag\n"
	.string "besiege ich 5 TRAINER. Und jetzt rate\l"
	.string "mal! Du bist heute der fünfte TRAINER.$"

Route121_Text_CristinDefeat:
	.string "Nein!\n"
	.string "Du bist grausam.$"

Route121_Text_CristinPostBattle:
	.string "Ich hätte nicht gedacht, dass ich so\n"
	.string "leicht verlieren würde…\l"
	.string "Nächstes Mal gewinne ich!!!$"

Route121_Text_CristinRegister:
	.string "Das war einfach nur peinlich!\n"
	.string "Ich werde dich nicht vergessen…\l"
	.string "Gib mir deinen POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "Ich habe ein neues Prinzip. Jeden Tag\n"
	.string "besiege ich 10 TRAINER. Und stell dir\l"
	.string "vor! Du bist heute der 10. TRAINER.$"

Route121_Text_CristinRematchDefeat:
	.string "Jetzt warte mal! Das ist echt gemein!\n"
	.string "Ich verlange einen neuen Kampf.$"

Route121_Text_CristinPostRematch:
	.string "Ein Gegner, den ich einfach nicht\n"
	.string "besiegen kann… Schnief…\l"
	.string "Ich kann es nicht glauben…$"

Route121_Text_CaleIntro:
	.string "Siehst du nicht, dass ich schwer\n"
	.string "bepackt bin?\p"
	.string "Und trotzdem willst du gegen mich\n"
	.string "kämpfen?$"

Route121_Text_CaleDefeat:
	.string "Natürlich habe ich verloren! Ich habe\n"
	.string "beide Hände voll. Was hast du denn\l"
	.string "erwartet?!?$"

Route121_Text_CalePostBattle:
	.string "Ich habe im EINKAUFSZENTRUM von\n"
	.string "LILYCOVE einfach zu viel eingekauft.\p"
	.string "Du findest das Zentrum dort hinten.\n"
	.string "Ich wünschte, ich hätte auch einen\l"
	.string "BEUTEL, wie du einen hast.$"

Route121_Text_MylesIntro:
	.string "Ich liebe nichts mehr, als die POKéMON\n"
	.string "anderer Leute zu begutachten.$"

Route121_Text_MylesDefeat:
	.string "Wahnsinn! Unglaublich!$"

Route121_Text_MylesPostBattle:
	.string "Deine POKéMON sind wirklich große\n"
	.string "Klasse! Wie hast du sie aufgezogen?$"

Route121_Text_PatIntro:
	.string "Ich will jedem meine POKéMON zeigen.$"

Route121_Text_PatDefeat:
	.string "Wow!\n"
	.string "Spektakulär!$"

Route121_Text_PatPostBattle:
	.string "Ich habe jedes meiner POKéMON mit der\n"
	.string "gleichen Liebe und Fürsorge\l"
	.string "aufgezogen. Ich habe keines bevorzugt.$"

Route121_Text_MarcelIntro:
	.string "Meine POKéMON kennen das Gefühl der\n"
	.string "Niederlage noch nicht. Bald lasse ich\l"
	.string "sie an einem WETTBEWERB teilnehmen.$"

Route121_Text_MarcelDefeat:
	.string "Was war das denn?!?$"

Route121_Text_MarcelPostBattle:
	.string "Ich sollte mein Team noch besser\n"
	.string "trainieren, bevor ich es für einen\l"
	.string "WETTBEWERB anmelde.$"

Route123_Text_WendyIntro:
	.string "Möchtest du wissen, wie stark du bist?\n"
	.string "Ich werde dich testen!$"

Route123_Text_WendyDefeat:
	.string "Du hast glänzend abgeschnitten!$"

Route123_Text_WendyPostBattle:
	.string "Um gegen mich bestehen zu können…\n"
	.string "Deine Stärke ist einfach unglaublich!$"

Route123_Text_BraxtonIntro:
	.string "Du hast da aber eine große Sammlung an\n"
	.string "ORDEN der verschiedenen ARENen!\p"
	.string "Zeig mir, dass du diese ORDEN auch\n"
	.string "zu Recht trägst!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, du bist ihrer würdig, wirklich!$"

Route123_Text_BraxtonPostBattle:
	.string "Du wurdest deinen ORDEN in diesem\n"
	.string "Kampf mehr als gerecht.$"

Route123_Text_VioletIntro:
	.string "Man sagt, dass gute Zeiten auch mit\n"
	.string "guten Aromen erfüllt sind.$"

Route123_Text_VioletDefeat:
	.string "Oh… Ich rieche den bitteren Geruch\n"
	.string "der Niederlage…$"

Route123_Text_VioletPostBattle:
	.string "Der Garten des BEERENMEISTERs ist\n"
	.string "erfüllt mit den erhebendsten Aromen.$"

Route123_Text_CameronIntro:
	.string "Ein Psycho zu sein, ist eine Frage des\n"
	.string "Willens.\p"
	.string "Mein Wille will gegen niemanden\n"
	.string "verlieren. Das macht mich stark.$"

Route123_Text_CameronDefeat:
	.string "Mir ist schlecht…$"

Route123_Text_CameronPostBattle:
	.string "Es ist alles eine Frage des Willens. Ich\n"
	.string "dachte, ich würde gegen dich gewinnen.$"

Route123_Text_CameronRegister:
	.string "Ich spüre es!\n"
	.string "Wir beide - du und ich - werden\l"
	.string "gegeneinander antreten.\p"
	.string "Ich weiß aber nicht, ob ich gewinnen\n"
	.string "werde… Zeig mir deinen POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "Ich habe mich selbst davon überzeugt,\n"
	.string "dass ich einfach nicht verlieren werde.$"

Route123_Text_CameronRematchDefeat:
	.string "Mir ist schlecht…$"

Route123_Text_CameronPostRematch:
	.string "Ich sollte am MT. PYRE trainieren…\n"
	.string "So werde ich dich nie schlagen…$"

Route123_Text_JackiIntro:
	.string "Sei nicht zu erfreut, wenn deine\n"
	.string "POKéMON Psychokräfte entwickeln.\p"
	.string "Du musst diese Kräfte modellieren,\n"
	.string "um sie sinnvoll einsetzen zu können.$"

Route123_Text_JackiDefeat:
	.string "Erstaunlich!$"

Route123_Text_JackiPostBattle:
	.string "Wir alle besitzen Psychokräfte. Wir\n"
	.string "haben nur vergessen, sie zu nutzen.$"

Route123_Text_JackiRegister:
	.string "Ich würde gerne wieder gegen dich\n"
	.string "kämpfen. Und was ist mit dir?$"

Route123_Text_JackiRematchIntro:
	.string "Hast du die Psychokräfte in dir\n"
	.string "erweckt?$"

Route123_Text_JackiRematchDefeat:
	.string "Erstaunlich!$"

Route123_Text_JackiPostRematch:
	.string "Dein Einfluss auf deine POKéMON…\n"
	.string "Auch das sind Psychokräfte.$"

Route123_Text_MiuIntro:
	.string "LEA: Hallo, TRAINER. Ich hoffe, deine\n"
	.string "POKéMON fangen nicht an zu weinen,\l"
	.string "wenn sie verlieren.$"

Route123_Text_MiuDefeat:
	.string "LEA: Oh oh, wir haben verloren.$"

Route123_Text_MiuPostBattle:
	.string "LEA: TRAINER, deine POKéMON sind stark,\n"
	.string "weil ihr eine starke Freundschaft teilt.$"

Route123_Text_MiuNotEnoughMons:
	.string "LEA: Es macht keinen Spaß, wenn du\n"
	.string "weniger als zwei POKéMON hast.$"

Route123_Text_YukiIntro:
	.string "GRIT: Okay!\n"
	.string "Wir schlagen die POKéMON des TRAINERs.$"

Route123_Text_YukiDefeat:
	.string "GRIT: Oh oh. Wir haben verloren…$"

Route123_Text_YukiPostBattle:
	.string "GRIT: Wieso bist du so stark?\n"
	.string "Wir haben bisher noch nie verloren!$"

Route123_Text_YukiNotEnoughMons:
	.string "GRIT: Es macht keinen Spaß, wenn du\n"
	.string "weniger als zwei POKéMON hast.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE…\n"
	.string "Wo die Geister der POKéMON ruhen…\l"
	.string "Ruhen deine POKéMON auch?$"

Route123_Text_KindraDefeat:
	.string "Überschäumend mit Leben…$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE…\n"
	.string "Wo die Geister der POKéMON ruhen…\p"
	.string "Dort muss es eine Kraft geben, die die\n"
	.string "Geister beruhigt…$"

Route123_Text_FernandoIntro:
	.string "Diese Melodie wirkt nur im Dunklen\n"
	.string "wunderbar.$"

Route123_Text_FernandoDefeat:
	.string "Hey! Ich habe noch nicht einmal das\n"
	.string "Intro zu Ende gespielt!$"

Route123_Text_FernandoPostBattle:
	.string "Dein Kampfstil ist inspirierend. Ich\n"
	.string "würde gern ein Lied über dich schreiben.$"

Route123_Text_FernandoRegister:
	.string "Nächstes Mal hörst du dir aber das\n"
	.string "ganze Lied an!$"

Route123_Text_FernandoRematchIntro:
	.string "Heute ist der Tag der Tage!\n"
	.string "Ich werde mit meinem Lied die Welt\l"
	.string "zum Erbeben bringen.$"

Route123_Text_FernandoRematchDefeat:
	.string "Hey, jetzt warte mal! Wir haben den\n"
	.string "Refrain noch nicht gespielt.$"

Route123_Text_FernandoPostRematch:
	.string "Ich dachte, dass dich mein Lied so\n"
	.string "fesselt, dass du verlierst.$"

Route123_Text_DavisIntro:
	.string "Das ist mein unglaubliches KÄFER-\n"
	.string "POKéMON. Mein großer Bruder hat es für\l"
	.string "mich gefangen.$"

Route123_Text_DavisDefeat:
	.string "Waaaaahaaaa!\n"
	.string "Du Fiesling!!!$"

Route123_Text_DavisPostBattle:
	.string "Verrat meinem Bruder bloß nicht, dass\n"
	.string "ich verloren habe! Das muss ein\l"
	.string "Geheimnis zwischen uns bleiben.$"

Route123_Text_JazmynIntro:
	.string "Ich werde vor Selbstbewusstsein\n"
	.string "platzen, wenn ich einen starken\l"
	.string "TRAINER besiege.$"

Route123_Text_JazmynDefeat:
	.string "So viel zu meinem Selbstbewusstsein…$"

Route123_Text_JazmynPostBattle:
	.string "Man sagt, man soll einen Menschen nicht\n"
	.string "nach seinem Aussehen beurteilen.\p"
	.string "Aber manchmal täuscht der erste\n"
	.string "Eindruck doch nicht.$"

Route123_Text_FrederickIntro:
	.string "Hallo, Kind!\n"
	.string "Hast du ein bisschen Zeit übrig?$"

Route123_Text_FrederickDefeat:
	.string "Ah, ein äußerst fähiges Kind!\n"
	.string "Ich möchte dir etwas zu deinem\l"
	.string "Taschengeld dazugeben.$"

Route123_Text_FrederickPostBattle:
	.string "Etwas zum Taschengeld dazugeben?\n"
	.string "Reicht dir das Preisgeld nicht aus?$"

Route123_Text_AlbertoIntro:
	.string "VOGEL-POKéMON sind meine große\n"
	.string "Leidenschaft.\p"
	.string "Vögel sind absolut cool!\n"
	.string "Sie sind die Besten überhaupt!$"

Route123_Text_AlbertoDefeat:
	.string "Selbst in einer Niederlage sind VOGEL-\n"
	.string "POKéMON noch cool!$"

Route123_Text_AlbertoPostBattle:
	.string "Ich sammle die Federn von VOGEL-\n"
	.string "POKéMON, die sie im Kampf verlieren.\p"
	.string "Daraus werde ich mir einen Hut basteln.$"

Route123_Text_EdIntro:
	.string "Ist gerade kein TRAINER in der Nähe,\n"
	.string "lasse ich meine POKéMON gegeneinander\l"
	.string "antreten. Dabei schaue ich ihnen zu.$"

Route123_Text_EdDefeat:
	.string "Irgendwie mag ich deine POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Hähähä, ich klaue deine Kampfstrategie!\n"
	.string "Dadurch werde ich mit Sicherheit\l"
	.string "besser!$"

Route123_Text_JonasIntro:
	.string "Ich habe einen Hinterhalt vorbereitet\n"
	.string "und tatsächlich ist mir ein TRAINER in\l"
	.string "die Falle gegangen.$"

Route123_Text_JonasDefeat:
	.string "Wie soll ich am Ninjasein Spaß haben,\n"
	.string "wenn du nicht verlierst?!?$"

Route123_Text_JonasPostBattle:
	.string "Nächstes Mal locke ich einen schwachen\n"
	.string "TRAINER in meine Falle.$"

Route123_Text_KayleyIntro:
	.string "Ich habe mir gerade erst diesen\n"
	.string "Sonnenschirm gekauft. Dadurch steigt\l"
	.string "meine Niedlichkeit um 30 Prozent!$"

Route123_Text_KayleyDefeat:
	.string "Du bist bestimmt fünf Mal besser\n"
	.string "als ich!$"

Route123_Text_KayleyPostBattle:
	.string "Der richtige Einsatz von Accessoires\n"
	.string "ist das Geheimnis des guten\l"
	.string "Geschmacks.$"

Route124_Text_SpencerIntro:
	.string "Hey, hast du etwa auf dem Meer die\n"
	.string "Orientierung verloren?\p"
	.string "Wenn du meine POKéMON besiegst, zeige\n"
	.string "ich dir den richtigen Weg.$"

Route124_Text_SpencerDefeat:
	.string "Ich habe die Orientierung verloren…$"

Route124_Text_SpencerPostBattle:
	.string "Viele Menschen verlieren auf dem Meer\n"
	.string "die Orientierung.\p"
	.string "Wenn du zu denen gehörst, solltest du\n"
	.string "die KARTE des POKéNAV zu Hilfe nehmen.$"

Route124_Text_RolandIntro:
	.string "Hm! Du sitzt auf einem POKéMON, anstatt\n"
	.string "selbst zu schwimmen…\p"
	.string "Ich bin richtig neidisch!$"

Route124_Text_RolandDefeat:
	.string "Oh!\n"
	.string "Ich kann doch nicht…$"

Route124_Text_RolandPostBattle:
	.string "Langsam bekomme ich eine Gänsehaut.\n"
	.string "Ich bin schon zu lange im Wasser.\p"
	.string "Ich wollte, ich könnte auf einem\n"
	.string "POKéMON reiten. So wie du!$"

Route124_Text_JennyIntro:
	.string "Wenn du dich einfach nur im Meer treiben\n"
	.string "lässt, kommen POKéMON, um zu spielen.$"

Route124_Text_JennyDefeat:
	.string "Oh, verdammt.\n"
	.string "Aus und vorbei. Verloren.$"

Route124_Text_JennyPostBattle:
	.string "Ich habe beim Schwimmen festgestellt,\n"
	.string "dass einige POKéMON angreifen und\l"
	.string "manche einen nur beobachten.\p"
	.string "Ich glaube, POKéMON haben unter-\n"
	.string "schiedliche Persönlichkeiten.$"

Route124_Text_JennyRegister:
	.string "Vielleicht ist es ja nur eine Marotte\n"
	.string "von mir, aber ich möchte gerne, dass du\l"
	.string "mich in deinen POKéNAV einträgst.$"

Route124_Text_JennyRematchIntro:
	.string "Wenn du dich hier treiben lässt, triffst\n"
	.string "du auf TRAINER, die kämpfen wollen.$"

Route124_Text_JennyRematchDefeat:
	.string "Das ist sehr merkwürdig…\n"
	.string "Ich habe schon wieder verloren…$"

Route124_Text_JennyPostRematch:
	.string "Das hat zwar nichts damit zu tun, aber\n"
	.string "ich glaube, ich besuche das RÄTSELHAUS.$"

Route124_Text_GraceIntro:
	.string "Ich fange an, mich beim Schwimmen zu\n"
	.string "langweilen. Wie wär’s mit einem Kampf?$"

Route124_Text_GraceDefeat:
	.string "Ich hatte ja keine Ahnung, dass du so\n"
	.string "stark bist!$"

Route124_Text_GracePostBattle:
	.string "Alles, was du bisher erreicht hast, hat\n"
	.string "dich so stark werden lassen.$"

Route124_Text_ChadIntro:
	.string "Hähähä… Ich tauche tief hinab, um mich\n"
	.string "tief und sicher zu verstecken. Die\l"
	.string "Tiefen auszuloten, ist meine Mission.$"

Route124_Text_ChadDefeat:
	.string "Blubb, blubb, blubb…\n"
	.string "So saufe ich ab…$"

Route124_Text_ChadPostBattle:
	.string "Aus zuverlässiger Quelle weiß ich, dass\n"
	.string "es hier in der Nähe einen Platz zum\l"
	.string "TAUCHEN gibt.\p"
	.string "Das gibt mir das Verlangen, mich tief\n"
	.string "fallen zu lassen…$"

Route124_Text_LilaIntro:
	.string "MARIA: Seufz…\p"
	.string "Ich bin hier im Meer, aber wer ist bei\n"
	.string "mir? Mein kleiner Bruder!\p"
	.string "Lass uns kämpfen, dann brauche ich\n"
	.string "nicht darüber nachzudenken.$"

Route124_Text_LilaDefeat:
	.string "MARIA: KARL! Es ist deine Schuld, dass\n"
	.string "wir verloren haben! Das wirst du büßen!$"

Route124_Text_LilaPostBattle:
	.string "MARIA: Seufz…\p"
	.string "Wenn anstelle meines kleinen\n"
	.string "Bruders ein hübscher Freund hier wäre…$"

Route124_Text_LilaNotEnoughMons:
	.string "MARIA: Du willst gegen uns antreten?\n"
	.string "Dann brauchst du aber mehr POKéMON.$"

Route124_Text_RoyIntro:
	.string "KARL: Meine Schwester ist stark!\p"
	.string "Heul bloß nicht, wenn du verlierst!$"

Route124_Text_RoyDefeat:
	.string "KARL: Oh oh…\n"
	.string "Meine Schwester wird mich fressen…$"

Route124_Text_RoyPostBattle:
	.string "KARL: Meine Schwester wird richtig\n"
	.string "unheimlich, wenn sie wütend ist.\p"
	.string "Daher hat sie auch noch keinen Freund.$"

Route124_Text_LilaRoyRegister:
	.string "KARL: Wirst du wieder gegen uns\n"
	.string "kämpfen? Dann machst du es uns\l"
	.string "leichter, ja?$"

Route124_Text_RoyNotEnoughMons:
	.string "KARL: Willst du gegen uns antreten?\n"
	.string "Dann bring mehr POKéMON mit.$"

Route124_Text_LilaRematchIntro:
	.string "MARIA: Megaseufz… Ich bin hier mitten\n"
	.string "im Meer.\p"
	.string "Und mit wem? Meinem kleinen Bruder!\n"
	.string "Oh, dich habe ich lange nicht gesehen.\p"
	.string "Lass uns kämpfen, dann muss ich nicht\n"
	.string "länger über die Situation nachdenken.$"

Route124_Text_LilaRematchDefeat:
	.string "MARIA: KARL!!! Du hast schon wieder für\n"
	.string "eine Niederlage gesorgt!\p"
	.string "Ich werde dir gleich eine Lektion\n"
	.string "erteilen!$"

Route124_Text_LilaPostRematch:
	.string "MARIA: Seeeuuufz…\p"
	.string "Wenn ich einen netten Freund hätte,\n"
	.string "würden wir alle in Kombination schlagen.$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "MARIA: Du willst gegen uns antreten?\n"
	.string "Dann bring mehr POKéMON mit.$"

Route124_Text_RoyRematchIntro:
	.string "KARL: Wenn wir verlieren, stecke ich\n"
	.string "tief in der Klemme. Dann flippe ich aus!$"

Route124_Text_RoyRematchDefeat:
	.string "KARL: Oh oh…\n"
	.string "Meine Schwester wird mich umbringen…$"

Route124_Text_RoyPostRematch:
	.string "KARL: Meine Schwester ist bizarr und\n"
	.string "Furcht erregend, wenn sie wütend ist.\p"
	.string "Sie wird mich später hart mit den\n"
	.string "POKéMON trainieren lassen…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "KARL: Willst du gegen uns antreten?\n"
	.string "Dann bring mehr POKéMON mit.$"

Route124_Text_DeclanIntro:
	.string "Hier bin ich. Einsam gleite ich durch das\n"
	.string "weite, wunderschöne Meer.\p"
	.string "Andere Worte habe ich dafür nicht!\n"
	.string "Es ist einfach zu pathetisch.$"

Route124_Text_DeclanDefeat:
	.string "Irgendwie fühle ich mich verloren…\n"
	.string "Verloren unter dem unendlichen Himmel…$"

Route124_Text_DeclanPostBattle:
	.string "Ich könnte SCHWIMMERINnen ansprechen\n"
	.string "und mit ihnen meilenweit schwimmen.$"

Route124_Text_IsabellaIntro:
	.string "Ich werde doch nicht gegen einen\n"
	.string "dahergesurften TRAINER verlieren!$"

Route124_Text_IsabellaDefeat:
	.string "Das sind keine Tränen! Der Schweiß ist\n"
	.string "mir in die Augen gelaufen!$"

Route124_Text_IsabellaPostBattle:
	.string "Man findet hier wunderschöne Scherben\n"
	.string "in den herrlichsten Farben.$"

Route125_Text_NolenIntro:
	.string "Ich habe dich kommen hören und\n"
	.string "hier auf dich gewartet.$"

Route125_Text_NolenDefeat:
	.string "Ich ergebe mich!$"

Route125_Text_NolenPostBattle:
	.string "Der Schall bewegt sich im Wasser\n"
	.string "schneller als in der Luft.$"

Route125_Text_StanIntro:
	.string "Hey, du!\n"
	.string "Schau dir mein süßes POKéMON an!$"

Route125_Text_StanDefeat:
	.string "Da habe ich aber rumgewurstelt…$"

Route125_Text_StanPostBattle:
	.string "SEEPERs Charme hat mich gefangen, so\n"
	.string "habe ich angefangen zu schwimmen.$"

Route125_Text_TanyaIntro:
	.string "Das Schwimmen hat mich ermüdet.\n"
	.string "Willst du mit mir kämpfen?$"

Route125_Text_TanyaDefeat:
	.string "Du bist mir eine Nummer zu groß.$"

Route125_Text_TanyaPostBattle:
	.string "Huuh… Wo geht es denn hier\n"
	.string "nach MOSSDEEP CITY?$"

Route125_Text_SharonIntro:
	.string "Wie willst du gegen mein WASSER-\n"
	.string "POKéMON ankommen?$"

Route125_Text_SharonDefeat:
	.string "Verloren…$"

Route125_Text_SharonPostBattle:
	.string "Deine Kraft… Absolut unglaublich.\n"
	.string "Ich bin begeistert!$"

Route125_Text_ErnestIntro:
	.string "Ahoi! Ich bin ein raubeiniger MATROSE!\n"
	.string "Ich habe die Weltmeere umsegelt.$"

Route125_Text_ErnestDefeat:
	.string "Grrrrooooaaar!\n"
	.string "Ich konnte unmöglich gewinnen!$"

Route125_Text_ErnestPostBattle:
	.string "Die Flut kommt und geht in der\n"
	.string "SHOAL CAVE.\p"
	.string "Wusstest du eigentlich, dass zwischen\n"
	.string "Flut und Ebbe immer 6 Stunden liegen?$"

Route125_Text_ErnestRegister:
	.string "Trag mich in deinen POKéNAV ein und ich\n"
	.string "verrate dir etwas.$"

Route125_Text_ErnestRematchIntro:
	.string "Jetzt läuft die Flut ein und für dich\n"
	.string "ist Zahltag! Komm, wir kämpfen.$"

Route125_Text_ErnestRematchDefeat:
	.string "Ich konnte nicht gewinnen!\n"
	.string "Die Flut hat mich davongetragen!$"

Route125_Text_ErnestRematchPostBattle:
	.string "Die SHOAL CAVE…\p"
	.string "Es gibt Orte, die sind mal erreichbar und\n"
	.string "mal nicht. Ganz abhängig von Ebbe\l"
	.string "und Flut.\p"
	.string "Übrigens: Vergiss nicht, dass zwischen\n"
	.string "Flut und Ebbe sechs Stunden liegen!$"

Route125_Text_KimIntro:
	.string "ZOE: Ein lustiger alter Mann lebt in der\n"
	.string "SHOAL CAVE. Das hat mir jemand\l"
	.string "erzählt. Willst du ihn auch besuchen?$"

Route125_Text_KimDefeat:
	.string "ZOE: Ich dachte, wir könnten gewinnen.$"

Route125_Text_KimPostBattle:
	.string "ZOE: Ein lustiger alter Mann lebt in der\n"
	.string "SHOAL CAVE, stimmt’s?\p"
	.string "Komm, IRIS, wir besuchen ihn.$"

Route125_Text_KimNotEnoughMons:
	.string "ZOE: Nein, nein, nein! Du brauchst zwei\n"
	.string "POKéMON oder es funktioniert nicht!$"

Route125_Text_IrisIntro:
	.string "IRIS: ZOE, kannst du mir verraten, was\n"
	.string "wir hier draußen überhaupt wollen?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Oh, wir waren so nah dran.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: ZOE, gehen wir wirklich zur\n"
	.string "SHOAL CAVE?\l"
	.string "Dann werden wir ja ganz nass.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, wir würden niemals einen\n"
	.string "2-gegen-1-Kampf ausfechten! Niemals!$"

Route125_Text_PresleyIntro:
	.string "Warum befindet sich ein VOGELFÄNGER\n"
	.string "wie ich auf dem Meer?$"

Route125_Text_PresleyDefeat:
	.string "Okay.\n"
	.string "Ich verrate es dir.$"

Route125_Text_PresleyPostBattle:
	.string "Ich schreibe eine Flaschenpost und\n"
	.string "schmeiße sie ins Meer.\p"
	.string "Sicher wird die hübsche SCHWIMMERIN\n"
	.string "sie finden!$"

Route125_Text_AuronIntro:
	.string "Hey! Hast du hier den Müll ins Meer\n"
	.string "geschmissen?!?$"

Route125_Text_AuronDefeat:
	.string "Oh, du hast den Müll nicht ins Meer\n"
	.string "geschmissen.$"

Route125_Text_AuronPostBattle:
	.string "Vor kurzem habe ich eine unansehnliche\n"
	.string "Flasche in den Wellen treiben sehen.\p"
	.string "Mich macht das richtig wütend, dass\n"
	.string "jemand das Meer verschmutzt.$"

Route126_Text_BarryIntro:
	.string "Schwimmen verlangt vollen Körperein-\n"
	.string "satz. Und so wird man fit!$"

Route126_Text_BarryDefeat:
	.string "Ich gebe es zu! Du hast gewonnen!$"

Route126_Text_BarryPostBattle:
	.string "Dank meiner täglichen Schwimmrunden…\n"
	.string "Guck mal! Schau dir diesen Körperbau\l"
	.string "an!$"

Route126_Text_DeanIntro:
	.string "Dieser hohe weiße Berg dort ist\n"
	.string "SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:
	.string "Wie, das war’s schon?$"

Route126_Text_DeanPostBattle:
	.string "Ich kann den Eingang zu SOOTOPOLIS CITY\n"
	.string "nicht finden. Wo kann er sein?$"

Route126_Text_NikkiIntro:
	.string "Hihihihihi!\n"
	.string "Ich bin eine Meerjungfrau!$"

Route126_Text_NikkiDefeat:
	.string "Mein Traum platzt wie Seifenblasen!\n"
	.string "Plopp, plopp, plopp…$"

Route126_Text_NikkiPostBattle:
	.string "Du hast mich geschlagen… Ich möchte im\n"
	.string "Meer der Verzweiflung untergehen…$"

Route126_Text_BrendaIntro:
	.string "Hallo, Kindchen!\n"
	.string "Willst du gegen mich antreten?$"

Route126_Text_BrendaDefeat:
	.string "Oh, neeeiiin!$"

Route126_Text_BrendaPostBattle:
	.string "Ich liebe es, einfach so mit meinen \n"
	.string "POKéMON im Meer abzuhängen!$"

Route126_Text_PabloIntro:
	.string "Schau dir meinen durchtrainierten\n"
	.string "Körper an! Ich habe mehr Muskeln als ein\l"
	.string "SCHWARZGURT!$"

Route126_Text_PabloDefeat:
	.string "Hups! Viel zu stark!\n"
	.string "Nicht schlecht! Echt nicht schlecht!$"

Route126_Text_PabloPostBattle:
	.string "Eine Niederlage weckt meine Sinne!\n"
	.string "Ich werde mich und meine POKéMON noch\l"
	.string "härter trainieren.$"

Route126_Text_PabloRegister:
	.string "Ja, du bist wirklich nicht schlecht.\n"
	.string "Ich würde dich gerne besser kennen\l"
	.string "lernen.$"

Route126_Text_PabloRematchIntro:
	.string "Schau dir diesen wunderbaren Körper an!\n"
	.string "Ich bin durchtrainierter als ein\l"
	.string "SCHWIMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "Hups! Wirklich viel zu stark!\n"
	.string "Gar nicht mal schlecht! Echt gut!$"

Route126_Text_PabloPostRematch:
	.string "Ich werde noch härter trainieren!\n"
	.string "Du hast mich motiviert! Du musst\l"
	.string "unbedingt bald wieder vorbeischauen.$"

Route126_Text_LeonardoIntro:
	.string "Letztes Jahr konnte ich noch gar nicht\n"
	.string "schwimmen und jetzt bin ich ein sehr\l"
	.string "guter SCHWIMMER.\p"
	.string "Ich denke, ich bin in allem ein großes\n"
	.string "Talent!$"

Route126_Text_LeonardoDefeat:
	.string "Mist, ich sollte mich nicht selbst\n"
	.string "überschätzen.$"

Route126_Text_LeonardoPostBattle:
	.string "Wenn du etwas sehr viel übst, dann\n"
	.string "wirst du immer besser darin.\p"
	.string "Du bist noch jung - also probier alles\n"
	.string "Mögliche aus!$"

Route126_Text_IsobelIntro:
	.string "Es fühlt sich schrecklich an, wenn du\n"
	.string "Meerwasser in die Nase bekommst!$"

Route126_Text_IsobelDefeat:
	.string "Aua! Duuuu…\n"
	.string "Blubb gluck…$"

Route126_Text_IsobelPostBattle:
	.string "Oh, ich habe Wasser geschluckt!\n"
	.string "Bah, das ist eeekelig! Total salzig!$"

Route126_Text_SiennaIntro:
	.string "Ich bin mit ganzem Herzen dabei.$"

Route126_Text_SiennaDefeat:
	.string "Dein Herz ist größer als meins.$"

Route126_Text_SiennaPostBattle:
	.string "Ich muss mich jetzt beruhigen…\n"
	.string "Ich denke, ich werde ein bisschen\l"
	.string "abtauchen.$"

Route127_Text_CamdenIntro:
	.string "Ich sehe es dir an. Du willst mich\n"
	.string "herausfordern!$"

Route127_Text_CamdenDefeat:
	.string "Auauauauahahaha!$"

Route127_Text_CamdenPostBattle:
	.string "Ein gut gespieltes Match lässt immer\n"
	.string "ein frisches und heiteres Gefühl\l"
	.string "zurück.$"

Route127_Text_DonnyIntro:
	.string "Hast du auch einen Rivalen, gegen den\n"
	.string "du es hasst, zu verlieren?$"

Route127_Text_DonnyDefeat:
	.string "Aaargh!\n"
	.string "Ich hasse es, zu verlieren!$"

Route127_Text_DonnyPostBattle:
	.string "Wenn du einen Rivalen hast, willst du\n"
	.string "dann nicht auch immer besser werden?$"

Route127_Text_JonahIntro:
	.string "Durch das Angeln habe ich eine\n"
	.string "gelassene Heiterkeit entwickelt…\l"
	.string "Bitte lass mich sie dir zeigen…$"

Route127_Text_JonahDefeat:
	.string "Auch wenn ich verloren habe, so bleibt\n"
	.string "mein Herz doch ruhig…$"

Route127_Text_JonahPostBattle:
	.string "Es macht nichts, wenn ich nichts fange.\n"
	.string "Die Schnur bleibt im Wasser.$"

Route127_Text_HenryIntro:
	.string "Hups! Jetzt sag nicht, dass ich ein\n"
	.string "SURFendes POKéMON am Haken habe?$"

Route127_Text_HenryDefeat:
	.string "Ich kann so nicht weitermachen!$"

Route127_Text_HenryPostBattle:
	.string "Deine POKéMON sehen stark aus! Und\n"
	.string "doch wären sie nur ein Häppchen, wenn\l"
	.string "ich sie als Köder am Haken hätte.$"

Route127_Text_RogerIntro:
	.string "Nun! Das ist ein Kampf zwischen einem\n"
	.string "POKéMON-Fan und einem Angel-Fan.$"

Route127_Text_RogerDefeat:
	.string "Nein! Meine Schnur hat sich verheddert.\n"
	.string "Die Party ist vorbei!$"

Route127_Text_RogerPostBattle:
	.string "Meine Angelschnur tanzt im Wasser!\n"
	.string "Sie tanzt Tango! Hahahah, hiiiks!$"

Route127_Text_AidanIntro:
	.string "VOGEL-POKéMON haben exzellente Augen.\n"
	.string "Sie erspähen Beute aus großer Höhe.$"

Route127_Text_AidanDefeat:
	.string "Huuh… Ich gebe auf.$"

Route127_Text_AidanPostBattle:
	.string "Hier gibt es viele Plätze, an denen man\n"
	.string "sehr gut tauchen kann.\p"
	.string "Aus der Luft sind sie leicht zu\n"
	.string "erkennen, da sie dunkler sind.$"

Route127_Text_KojiIntro:
	.string "Lauf barfuß!\n"
	.string "Das stärkt deine Fußsohlen.$"

Route127_Text_KojiDefeat:
	.string "Auuuuaaa!\n"
	.string "Ich habe einen Splitter im Zeh.$"

Route127_Text_KojiPostBattle:
	.string "Barfuß zu laufen, ist klasse. Aber deine\n"
	.string "TURBOTRETER sind auch cool.$"

Route127_Text_KojiRegister:
	.string "Das mache ich mit Leuten, die mich\n"
	.string "besiegt haben! Ich hoffe, wir\l"
	.string "wiederholen das mal!$"

Route127_Text_KojiRematchIntro:
	.string "Ich laufe jeden Tag barfuß.\n"
	.string "Meine Sohlen sind schon ganz hart.$"

Route127_Text_KojiRematchDefeat:
	.string "Auuuuaaa!\n"
	.string "Die Steine tun weh! Meine armen Füße!$"

Route127_Text_KojiPostRematch:
	.string "Hast du nicht Lust, ein bisschen\n"
	.string "barfuß zu laufen? Ich würde gerne\l"
	.string "deine TURBOTRETER ausprobieren.$"

Route127_Text_AthenaIntro:
	.string "Unser Kampf soll langsam und\n"
	.string "methodisch sein.$"

Route127_Text_AthenaDefeat:
	.string "Du hast mir gar keine Zeit gegeben, mir\n"
	.string "eine Strategie auszudenken.$"

Route127_Text_AthenaPostBattle:
	.string "Wenn ich vom blauen Meer und vom blauen\n"
	.string "Himmel umgeben bin, dann bleibt die Zeit\l"
	.string "für mich stehen.$"

Route128_Text_IsaiahIntro:
	.string "EVER GRANDE CITY ist weit entfernt…$"

Route128_Text_IsaiahDefeat:
	.string "Mein erster Sieg scheint weit entfernt\n"
	.string "zu sein…$"

Route128_Text_IsaiahPostBattle:
	.string "Mein ganzes Leben ist eine einzige\n"
	.string "Niederlage, aber ich gebe nicht auf!$"

Route128_Text_IsaiahRegister:
	.string "Noch bin ich nicht gut genug, aber\n"
	.string "irgendwann werde ich gewinnen!\p"
	.string "Bitte trag mich in deinen POKéNAV ein.$"

Route128_Text_IsaiahRematchIntro:
	.string "Ich fühle mich gut. Ich werde weiter\n"
	.string "Richtung EVER GRANDE CITY schwimmen.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Ich möchte sehr gerne einmal vom Sieg\n"
	.string "kosten…$"

Route128_Text_IsaiahPostRematch:
	.string "Ich werde EVER GRANDE CITY eventuell\n"
	.string "erreichen und dort eventuell gewinnen…$"

Route128_Text_KatelynIntro:
	.string "In einem Triathlon musst du schwimmen,\n"
	.string "Rad fahren und einen Marathon laufen.\p"
	.string "Es ist ein mörderisches Rennen, das aus\n"
	.string "drei Disziplinen besteht.$"

Route128_Text_KatelynDefeat:
	.string "Ein POKéMON-Kampf ist auch mörderisch.$"

Route128_Text_KatelynPostBattle:
	.string "Ich muss als Nächstes mit dem RAD\n"
	.string "fahren, aber… ich möchte eigentlich\l"
	.string "das Handtuch werfen.$"

Route128_Text_KatelynRegister:
	.string "Nun, ich muss das Beste daraus machen.\n"
	.string "Ich möchte irgendwann wieder gegen\l"
	.string "dich kämpfen.$"

Route128_Text_KatelynRematchIntro:
	.string "Ein Triathlon ist lang. Aber ich glaube,\n"
	.string "um POKéMON CHAMP zu werden, hat\l"
	.string "man auch einen langen Weg vor sich.$"

Route128_Text_KatelynRematchDefeat:
	.string "Ein POKéMON-Kampf ist hart und \n"
	.string "unbarmherzig…$"

Route128_Text_KatelynPostRematch:
	.string "Du solltest ernsthaft darüber nach-\n"
	.string "denken, die VICTORY ROAD zu betreten.$"

Route128_Text_AlexaIntro:
	.string "Wir haben hart dafür gearbeitet, die\n"
	.string "POKéMON LEAGUE herauszufordern…\p"
	.string "Wir können es uns nicht erlauben,\n"
	.string "jetzt zu verlieren!$"

Route128_Text_AlexaDefeat:
	.string "Oh!\n"
	.string "Wie konnte das passieren?$"

Route128_Text_AlexaPostBattle:
	.string "Ich bin so weit gekommen, ich gebe\n"
	.string "jetzt bestimmt nicht auf.$"

Route128_Text_RubenIntro:
	.string "Es gibt keinen stärkeren TRAINER als\n"
	.string "mich!$"

Route128_Text_RubenDefeat:
	.string "Das darf nicht wahr sein!$"

Route128_Text_RubenPostBattle:
	.string "Es gibt wohl keinen stärkeren TRAINER\n"
	.string "als dich!$"

Route128_Text_WayneIntro:
	.string "Ich will nach EVER GRANDE CITY, daher\n"
	.string "habe ich ein POKéMON gefangen, das\p"
	.string "weiß, wie man mit KASKADE den Wasserfall\n"
	.string "erklimmt.$"

Route128_Text_WayneDefeat:
	.string "Ich bin abgestürzt.$"

Route128_Text_WaynePostBattle:
	.string "Ooh, jeeeeh!\p"
	.string "Mein POKéMON kennt KASKADE, aber mir\n"
	.string "fehlt der ORDEN der ARENA von\l"
	.string "SOOTOPOLIS CITY!$"

Route128_Text_HarrisonIntro:
	.string "Du siehst unglaublich stark aus.\n"
	.string "Ob ich gegen dich wohl gewinnen kann?$"

Route128_Text_HarrisonDefeat:
	.string "Aua! Dich zu besiegen zu\n"
	.string "wollen war aussichtslos.$"

Route128_Text_HarrisonPostBattle:
	.string "In der Nähe von EVER GRANDE CITY gibt\n"
	.string "es jede Menge starke TRAINER.\p"
	.string "Ob ich damit außerhalb meiner Liga\n"
	.string "spiele?$"

Route128_Text_CarleeIntro:
	.string "In dieser Region scheint die Sonne\n"
	.string "besonders stark zu scheinen.$"

Route128_Text_CarleeDefeat:
	.string "Die Sonnenstrahlen haben mich\n"
	.string "geblendet.$"

Route128_Text_CarleePostBattle:
	.string "Ich sollte bald zurück. Ich muss\n"
	.string "mich neu mit Sonnenmilch einschmieren.$"

Route129_Text_ChaseIntro:
	.string "Das ist mein erster Triathlon.\n"
	.string "Ich bin schon ganz hibbelig und nervös!$"

Route129_Text_ChaseDefeat:
	.string "Wooooaaaaaargh! Ich habe es\n"
	.string "nicht geschafft, zu gewinnen.$"

Route129_Text_ChasePostBattle:
	.string "Wenn ich so hibbelig bin, kann ich nicht\n"
	.string "alles geben.$"

Route129_Text_AllisonIntro:
	.string "Ich bin mitten in einem Triathlon, aber\n"
	.string "warum sollten wir nicht kämpfen?$"

Route129_Text_AllisonDefeat:
	.string "Ich war sicher, ich würde gewinnen!$"

Route129_Text_AllisonPostBattle:
	.string "Weißt du, was das Beste am Triathlon\n"
	.string "ist?\p"
	.string "Man kommt an seine eigenen Grenzen und\n"
	.string "zeigt seine Ausdauer gegenüber Mutter\l"
	.string "Natur.$"

Route129_Text_ReedIntro:
	.string "Sag: Hey, hey!\n"
	.string "Los geht’s!$"

Route129_Text_ReedDefeat:
	.string "Geschlagen, ich wurde geschlagen.\n"
	.string "Das war’s. Fertig!$"

Route129_Text_ReedPostBattle:
	.string "Hier gibt es für Verlierer nichts zu tun.\n"
	.string "Zeit für mich, nach Hause zu gehen.$"

Route129_Text_TishaIntro:
	.string "Warum so eilig?\n"
	.string "Immer mit der Ruhe…$"

Route129_Text_TishaDefeat:
	.string "Oh, meine Güte. Dabei wollte ich\n"
	.string "nur ein bisschen entspannen.$"

Route129_Text_TishaPostBattle:
	.string "Hasst du es nicht auch, Fehler zu\n"
	.string "machen, nur weil du es eilig hast?\p"
	.string "Daher gehe ich alles langsam an.$"

Route129_Text_ClarenceIntro:
	.string "Surfen ist bestimmt nicht so einfach,\n"
	.string "wie es aussieht?$"

Route129_Text_ClarenceDefeat:
	.string "Gewinnen ist bestimmt auch nicht\n"
	.string "leicht.$"

Route129_Text_ClarencePostBattle:
	.string "Dein nächstes Ziel ist die POKéMON\n"
	.string "LIGA? Verlier dein Ziel nicht aus den\l"
	.string "Augen!$"

Route130_Text_RodneyIntro:
	.string "Was für eine Überraschung! Ich habe im\n"
	.string "Meer keinen TRAINER erwartet.\p"
	.string "Ich denke, wir sollten kämpfen.$"

Route130_Text_RodneyDefeat:
	.string "Dieses Kind ist unglaublich stark.$"

Route130_Text_RodneyPostBattle:
	.string "Deine Augen haben den Ausdruck eines\n"
	.string "Menschen, der harte Herausforderungen\l"
	.string "siegreich gemeistert hat. Das steht dir.$"

Route130_Text_KatieIntro:
	.string "Im tiefen, blauen Meer fand mein\n"
	.string "schwermütiges Herz Trost in den\l"
	.string "wogenden Wellen.$"

Route130_Text_KatieDefeat:
	.string "Wie das weite Meer umspannt auch die \n"
	.string "Welt der POKéMON Weiten jenseits\l"
	.string "unseres Erfahrungshorizontes.$"

Route130_Text_KatiePostBattle:
	.string "Die Kinder dieser Welt träumen davon,\n"
	.string "eines Tages der POKéMON CHAMP zu\l"
	.string "werden.$"

Route130_Text_SantiagoIntro:
	.string "Sich im offenen Meer treiben zu lassen…\n"
	.string "Das ist friedlich und entspannend.$"

Route130_Text_SantiagoDefeat:
	.string "Ich sollte weniger friedlich sein!$"

Route130_Text_SantiagoPostBattle:
	.string "Schwimmen und kämpfen…\n"
	.string "Ich bin echt ein Glückspilz…$"

Route131_Text_RichardIntro:
	.string "Das Meer wimmelt von POKéMON.\n"
	.string "Es ist nicht leicht, hier zu schwimmen.$"

Route131_Text_RichardDefeat:
	.string "POKéMON, die von TRAINERn aufgezogen\n"
	.string "wurden, sind sehr stark…$"

Route131_Text_RichardPostBattle:
	.string "Keuch… Schnauf… Ich bin K.O.\p"
	.string "Der Hinweg ist leicht. Der Heimweg umso\n"
	.string "härter.\p"
	.string "Ob ich genug Energie für die Heimreise\n"
	.string "habe?$"

Route131_Text_HermanIntro:
	.string "Die See… Die See… Die See…\n"
	.string "Die See… So weit ich mit den Augen seh.\l"
	.string "Das Meer macht mich krank und müde.$"

Route131_Text_HermanDefeat:
	.string "Bah!$"

Route131_Text_HermanPostBattle:
	.string "Gelangweilt bin ich von der See, aber\n"
	.string "ich muss schwimmen.\p"
	.string "Ich bin der geborene Schwimmer!\n"
	.string "Das bin ich.$"

Route131_Text_SusieIntro:
	.string "Hey, Engelchen, warte!\n"
	.string "Wir sollten kämpfen, du und ich!$"

Route131_Text_SusieDefeat:
	.string "Du bist stärker, als du aussiehst.$"

Route131_Text_SusiePostBattle:
	.string "Hast du einen Typen gesehen, der heult,\n"
	.string "weil das Meer ihn langweilt?\p"
	.string "Das ist nur Gerede.\n"
	.string "Er liebt das Meer aus tiefstem Herzen!$"

Route131_Text_KaraIntro:
	.string "Warum lieben Männer Bikinis nur so?\p"
	.string "Sie starren alle meinen Bikini an.$"

Route131_Text_KaraDefeat:
	.string "Ich bin erledigt.$"

Route131_Text_KaraPostBattle:
	.string "Vielleicht bewundern die Männer nicht\n"
	.string "meinen Bikini, sondern mich!$"

Route131_Text_ReliIntro:
	.string "UNA: Wir nehmen es als Geschwister mit\n"
	.string "dir auf!$"

Route131_Text_ReliDefeat:
	.string "UNA: Wir konnten nicht gewinnen. Trotz\n"
	.string "unserer Zusammenarbeit.$"

Route131_Text_ReliPostBattle:
	.string "UNA: Die Menschen in PACIFIDLOG TOWN\n"
	.string "leben von Geburt an mit POKéMON\l"
	.string "und dem Meer zusammen.$"

Route131_Text_ReliNotEnoughMons:
	.string "UNA: Du hast keine zwei POKéMON?\n"
	.string "Dann werden wir keinen Spaß haben!$"

Route131_Text_IanIntro:
	.string "TOBI: Ich gebe zusammen mit meiner\n"
	.string "Schwester mein Bestes!$"

Route131_Text_IanDefeat:
	.string "TOBI: Meine Schwester und ich gaben\n"
	.string "unser Bestes und haben doch verloren.$"

Route131_Text_IanPostBattle:
	.string "TOBI: Du weißt, dass PACIFIDLOG TOWN\n"
	.string "eine schwimmende Stadt ist?\p"
	.string "Wo immer auch das Meer ist, ist es Teil\n"
	.string "von PACIFIDLOG TOWN!$"

Route131_Text_IanNotEnoughMons:
	.string "TOBI: Wenn du zwei POKéMON mitbringst,\n"
	.string "werden wir es mit dir aufnehmen!$"

Route131_Text_TaliaIntro:
	.string "Besiegst du mich, gebe ich dir ein paar\n"
	.string "interessante Informationen!$"

Route131_Text_TaliaDefeat:
	.string "Oh?\n"
	.string "Habe ich etwa verloren?$"

Route131_Text_TaliaPostBattle:
	.string "Hier in der Nähe gibt es einen seltsamen\n"
	.string "Ort. Mit einem großen Turm. Schau ihn\l"
	.string "dir doch mal an.$"

Route131_Text_KevinIntro:
	.string "Die Menschen von PACIFIDLOG TOWN sind\n"
	.string "sehr friedlich.\p"
	.string "Sie werden niemals wütend.\n"
	.string "Das trifft auch auf mich zu.$"

Route131_Text_KevinDefeat:
	.string "Uuups!$"

Route131_Text_KevinPostBattle:
	.string "Argh, Mist… Oh, warte, warte!\n"
	.string "Ich bin kein bisschen wütend! Ehrlich!\p"
	.string "Junge, Junge, du bist vielleicht stark!\n"
	.string "Hahahaha!$"

Route132_Text_GilbertIntro:
	.string "Als Kind war ich andauernd erkältet,\n"
	.string "aber seit ich mit dem Schwimmen\l"
	.string "angefangen habe, bin ich fit.$"

Route132_Text_GilbertDefeat:
	.string "Ich bitte um mehr Kraft…$"

Route132_Text_GilbertPostBattle:
	.string "TRAINER reisen über Berg und Tal\n"
	.string "und müssen deshalb auch fit sein.$"

Route132_Text_DanaIntro:
	.string "Ich versuche, mich von den Strömungen\n"
	.string "fern zu halten.$"

Route132_Text_DanaDefeat:
	.string "Oh, bitte, nein!$"

Route132_Text_DanaPostBattle:
	.string "Ich wurde weggespült. Ich habe voll-\n"
	.string "ständig die Orientierung verloren.$"

Route132_Text_RonaldIntro:
	.string "Sieg oder Niederlage. Das weiß man\n"
	.string "erst, wenn man es ausprobiert hat.$"

Route132_Text_RonaldDefeat:
	.string "Aaah!\n"
	.string "Ich versinke in einer Niederlage.$"

Route132_Text_RonaldPostBattle:
	.string "Ich kämpfe nie, wenn ich weiß, dass ich\n"
	.string "gewinne. Ich liebe den Kampf an der\l"
	.string "Grenze zwischen Sieg und Niederlage.$"

Route132_Text_KiyoIntro:
	.string "Ich widme mich 24 Stunden am Tag den\n"
	.string "POKéMON. Ob du mich besiegen kannst?$"

Route132_Text_KiyoDefeat:
	.string "Ich habe verloren.\n"
	.string "Ich gestehe die Niederlage ein.$"

Route132_Text_KiyoPostBattle:
	.string "Aargh…\n"
	.string "Du bist ein POKéMON-Fanatiker, oder?\p"
	.string "Du widmest dich den POKéMON\n"
	.string "24 Stunden am Tag, oder?$"

Route132_Text_MakaylaIntro:
	.string "Ich bin immer mit meinem Mann zusammen,\n"
	.string "aber auch ohne ihn kann ich gewinnen!$"

Route132_Text_MakaylaDefeat:
	.string "Mh, ich war wohl nicht gut genug.$"

Route132_Text_MakaylaPostBattle:
	.string "Der junge Mann dort drüben sieht\n"
	.string "genauso aus wie mein Mann, als er\l"
	.string "jung war.\p"
	.string "Der bringt mich zum Erröten.$"

Route132_Text_JonathanIntro:
	.string "Jemand hat mich angestrengt\n"
	.string "beobachtet. Warst du das?$"

Route132_Text_JonathanDefeat:
	.string "Wow!\n"
	.string "Du bist echt stark!$"

Route132_Text_JonathanPostBattle:
	.string "Ich werde das Gefühl nicht los, dass\n"
	.string "mich jemand beobachtet.\p"
	.string "Ich kann mich überhaupt nicht\n"
	.string "konzentrieren.$"

Route132_Text_PaxtonIntro:
	.string "Wo könnte meine Frau wohl hingegangen\n"
	.string "sein? Wir sind doch sonst immer zu-\l"
	.string "sammen. Ob ich ohne sie gewinnen kann?$"

Route132_Text_PaxtonDefeat:
	.string "Tja, ich habe es nicht geschafft, ohne\n"
	.string "meine Frau zu gewinnen.$"

Route132_Text_PaxtonPostBattle:
	.string "Meine Frau sucht mich bestimmt schon.\n"
	.string "Ich mache mich besser auf den Weg.$"

Route132_Text_DarcyIntro:
	.string "Ich wollte hier in aller Ruhe trainieren.\n"
	.string "Und jetzt sind so viele Leute hier…$"

Route132_Text_DarcyDefeat:
	.string "Ich werde mich nicht weiter darüber\n"
	.string "beschweren, dass hier so viele Leute\l"
	.string "sind.$"

Route132_Text_DarcyPostBattle:
	.string "Ich kann mich bestimmt mit dem älteren\n"
	.string "Herrn dort zusammentun und das andere\l"
	.string "Team da besiegen.$"

Route133_Text_FranklinIntro:
	.string "Hat die Strömung dich hergebracht? Das\n"
	.string "nenne ich Schicksal. Lass uns kämpfen!$"

Route133_Text_FranklinDefeat:
	.string "Stark!\n"
	.string "Viel zu stark!$"

Route133_Text_FranklinPostBattle:
	.string "Soll ich das jetzt Glück nennen, dass\n"
	.string "ich auf einen so starken TRAINER wie\l"
	.string "dich gestoßen bin? Ich bin verflucht…$"

Route133_Text_DebraIntro:
	.string "Ich führte ein Leben in Kummer und\n"
	.string "Elend. Es hat mich hierher verschlagen\l"
	.string "und hier bin ich gestrandet…$"

Route133_Text_DebraDefeat:
	.string "Eine weitere Niederlage…$"

Route133_Text_DebraPostBattle:
	.string "Treibend auf dem Meer des Lebens…\n"
	.string "Ich habe dazu keine Lust mehr!$"

Route133_Text_LindaIntro:
	.string "Willkommen!\n"
	.string "Ich habe dich schon erwartet!$"

Route133_Text_LindaDefeat:
	.string "Nein! Bitte!$"

Route133_Text_LindaPostBattle:
	.string "Ein Kind als starker TRAINER…\n"
	.string "Boh, ist das äääärgerlich!$"

Route133_Text_WarrenIntro:
	.string "Ich möchte, wie jeder andere auch,\n"
	.string "gewinnen, aber ich ziehe meine POKéMON\l"
	.string "nicht auf wie jeder andere auch…$"

Route133_Text_WarrenDefeat:
	.string "Mist!\n"
	.string "Meine Art und Weise reicht nicht aus!$"

Route133_Text_WarrenPostBattle:
	.string "Es macht mehr Spaß, die Dinge auf meine\n"
	.string "Art zu erledigen, als auf die Art aller\l"
	.string "anderen. Das ist doch klar!$"

Route133_Text_BeckIntro:
	.string "Ich bin mit meinen VOGEL-POKéMON\n"
	.string "hierher gekommen.$"

Route133_Text_BeckDefeat:
	.string "Du…\n"
	.string "Du bist total cool!$"

Route133_Text_BeckPostBattle:
	.string "Ich könnte nach FORTREE CITY zu-\n"
	.string "rückkehren, aber ich mag Orte wie diese.$"

Route133_Text_MollieIntro:
	.string "Ich habe bestimmt schon über tausend\n"
	.string "Mal gekämpft. Aber nachzählen kann ich\l"
	.string "das nicht.$"

Route133_Text_MollieDefeat:
	.string "Ich habe bestimmt schon tausend Mal\n"
	.string "verloren, trotzdem tut jede Niederlage\l"
	.string "weh.$"

Route133_Text_MolliePostBattle:
	.string "Mach weiter so, Kindchen. Dann wirst du\n"
	.string "irgendwann so wie mein Mann und ich.$"

Route133_Text_ConorIntro:
	.string "Junge Menschen schließen sich nur zu\n"
	.string "gerne der Masse an. Und haben keine\l"
	.string "eigenen Ziele.$"

Route133_Text_ConorDefeat:
	.string "Du hast dein Ziel klar vor Augen.$"

Route133_Text_ConorPostBattle:
	.string "Lass dich nicht von anderen vom Weg\n"
	.string "abbringen! Behalte immer deine Ziele\l"
	.string "im Auge!$"

Route134_Text_JackIntro:
	.string "Selbst POKéMON, die schwimmen können,\n"
	.string "werden oft von der Strömung erfasst.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "Ich glaube, POKéMON mögen diese\n"
	.string "schnellen Strömungen hier sehr.$"

Route134_Text_LaurelIntro:
	.string "Meine LIEBISKUS möchten ihren Spaß\n"
	.string "bei einem Kampf haben. Machst du mit?$"

Route134_Text_LaurelDefeat:
	.string "Huupsie!$"

Route134_Text_LaurelPostBattle:
	.string "Es gibt da einen Sammler, der sich für \n"
	.string "SCHUPPEn von LIEBISKUS interessiert.$"

Route134_Text_AlexIntro:
	.string "Okeydokey! Genug gerastet, Jungs!\n"
	.string "Zeit für ein Kämpfchen!$"

Route134_Text_AlexDefeat:
	.string "Wir wurden wieder fertig gemacht.$"

Route134_Text_AlexPostBattle:
	.string "Meine VOGEL-POKéMON werden nach einem\n"
	.string "langen Flug schnell müde…$"

Route134_Text_HitoshiIntro:
	.string "Du bist ein POKéMON-TRAINER.\n"
	.string "Worte sind da überflüssig. Wir kämpfen.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "Ich habe dich herausgefordert und\n"
	.string "doch verloren. Ich bin tief beschämt.$"

Route134_Text_AaronIntro:
	.string "Die wilde Strömung in dieser Region\n"
	.string "hilft uns dabei, stärker denn je zu\l"
	.string "werden.$"

Route134_Text_AaronDefeat:
	.string "Ich gebe meine Niederlage zu.$"

Route134_Text_AaronPostBattle:
	.string "Wir werden für weiteres Training nach\n"
	.string "METEOR FALLS zurückkehren.\p"
	.string "Wenn du magst, komm doch auch mit.\n"
	.string "Das wird auch dich stärker machen!$"

Route134_Text_KelvinIntro:
	.string "U-unser Schiff!\n"
	.string "Die Flut hat es mitgenommen!$"

Route134_Text_KelvinDefeat:
	.string "Ohoooohooo!\n"
	.string "Bitte, hör auf! Stopp!$"

Route134_Text_KelvinPostBattle:
	.string "Wenn wir SURFER nicht einsetzen\n"
	.string "können, wie sollen wir dann nach Hause\l"
	.string "kommen?!?\p"
	.string "Ich weiß, dass ein besiegtes POKéMON\n"
	.string "SURFER einsetzen kann, aber irgendwie\l"
	.string "finde ich das nicht richtig.$"

Route134_Text_MarleyIntro:
	.string "Können deine POKéMON unseren\n"
	.string "blitzschnellen Attacken ausweichen?$"

Route134_Text_MarleyDefeat:
	.string "Ich wusste gar nicht, dass es so eine\n"
	.string "Technik gibt. Du hast uns gründlich\l"
	.string "besiegt.$"

Route134_Text_MarleyPostBattle:
	.string "Ich habe meine Leidenschaft für die\n"
	.string "Geschwindigkeit nicht verloren.\l"
	.string "Ich werde mich noch mehr anstrengen.$"

Route134_Text_ReynaIntro:
	.string "Meine POKéMON lassen sich nicht so\n"
	.string "leicht besiegen!$"

Route134_Text_ReynaDefeat:
	.string "Das soll doch wohl ein Witz sein!\n"
	.string "Erklär mir, wieso ich verloren habe!$"

Route134_Text_ReynaPostBattle:
	.string "Haha!\n"
	.string "Du hast gewonnen, na schön!\p"
	.string "Ich werde besser werden, indem ich\n"
	.string "alle TRAINER herausfordere, denen ich\l"
	.string "begegne.$"

Route134_Text_HudsonIntro:
	.string "Du hast nicht zufällig einen anderen\n"
	.string "MATROSEn hier in der Nähe gesehen?$"

Route134_Text_HudsonDefeat:
	.string "Na, das ist doch mal was!$"

Route134_Text_HudsonPostBattle:
	.string "Unser Schiff ist aufs Meer\n"
	.string "hinausgetrieben.\p"
	.string "Mein Freund ist ein ängstlicher Typ,\n"
	.string "daher mache ich mir Sorgen um ihn.$"

VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "The battery isn't charged enough.\p"
	.string "No. of steps required to fully\n"
	.string "charge the battery: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "There are no Trainers within range\n"
	.string "who can battle…\p"
	.string "The VS Seeker was turned off.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "The other Trainers don't appear\n"
	.string "to be ready for battle.\p"
	.string "Let's wait till later.{PAUSE_UNTIL_PRESS}$"
