VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "Weit von hier, in EVER GRANDE CITY,\n"
	.string "findest du die POKéMON LEAGUE.\p"
	.string "Die TRAINER dort sind alle geradezu\n"
	.string "Furcht erregend talentiert.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "In der POKéMON LEAGUE musst du die TOP\n"
	.string "VIER hintereinander besiegen. Das\l"
	.string "sagen die Regeln.\p"
	.string "Wenn du gegen einen dieser TRAINER\n"
	.string "verlierst, musst du die Herausforderung\l"
	.string "von vorne beginnen.$"

