SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "Ein Unterwasservulkan brach aus\n"
	.string "und schob sich an die Oberfläche.\p"
	.string "Der Krater lag über der Meeresober-\n"
	.string "fläche und konnte sich so mit Regen-\p"
	.string "wasser füllen.\n"
	.string "Und so entstand SOOTOPOLIS CITY.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "Die Höhle, die SOOTOPOLIS CITY mit der Welt\n"
	.string "verbindet…\p"
	.string "Sie sollte ursprünglich wohl etwas\n"
	.string "in der Stadt festhalten.\p"
	.string "Oder bilde ich mir das nur ein?$"

