PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "De SIMON K. isch echt en\n"
	.string "Zahlejongleur!\p"
	.string "Er kalkuliert sini Strat\n"
	.string "wie en G!$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "De SIMON K. het mich mit\n"
	.string "nur 1 Pokemon besiegt.\p"
	.string "Ich glaub er isch de besti\n"
	.string "Trainer uf dere Welt.$"

