gText_HowMayIServeYou::
        .string "Ouh NJERI!\p"
        .string "Was bruchsch?$"

gText_PleaseComeAgain::
        .string "Machs guet, NJERI!$"

gText_PlayerWhatCanIDoForYou::
        .string "Ouh NJERI!\p"
        .string "Was bruchsch?$"

Pokemart_DefaultItemList::
	.2byte ITEM_ULTRA_BALL
	.2byte ITEM_HYPER_POTION
	.2byte ITEM_MAX_POTION
	.2byte ITEM_FULL_RESTORE
	.2byte ITEM_FULL_HEAL
	.2byte ITEM_REVIVE
	.2byte ITEM_MAX_REPEL
	pokemartlistend
