SafariZone_EventScript_OutOfBallsMidBattle::
#if IS_FRLG
	setvar VAR_MAP_SCENE_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE, 3
#else
	setvar VAR_SAFARI_ZONE_STATE, 1
#endif
	special ExitSafariMode
#if IS_FRLG
	setwarp MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE, 4, 1
#else
	setwarp MAP_ROUTE121_SAFARI_ZONE_ENTRANCE, 2, 5
#endif
	end

SafariZone_EventScript_Exit::
#if IS_FRLG
	setvar VAR_MAP_SCENE_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE, 1
#else
	setvar VAR_SAFARI_ZONE_STATE, 1
#endif
	special ExitSafariMode
#if IS_FRLG
	warp MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE, 4, 1
#else
	warp MAP_ROUTE121_SAFARI_ZONE_ENTRANCE, 2, 5
#endif
	waitstate
	end

SafariZone_EventScript_RetirePrompt::
	lockall
	msgbox SafariZone_Text_WouldYouLikeToExit, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, SafariZone_EventScript_Retire
	releaseall
	end

SafariZone_EventScript_Retire::
	goto SafariZone_EventScript_Exit

SafariZone_EventScript_TimesUp::
	lockall
	playse SE_DING_DONG
	message SafariZone_Text_TimesUp
	waitmessage
	waitbuttonpress
	releaseall
	goto SafariZone_EventScript_Exit

SafariZone_EventScript_OutOfBalls::
	lockall
	playse SE_DING_DONG
	message SafariZone_Text_OutOfBalls
	waitmessage
	waitbuttonpress
	releaseall
	goto SafariZone_EventScript_Exit

EventScript_PokeBlockFeeder::
	lockall
	special GetPokeblockFeederInFront
	goto_if_ne VAR_RESULT, 0xFFFF, SafariZone_EventScript_PokeblockPresent
	msgbox SafariZone_Text_PlacePokeblockOnFeeder, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, SafariZone_EventScript_ChoosePokeblock
	releaseall
	end

SafariZone_EventScript_ChoosePokeblock::
	fadescreen FADE_TO_BLACK
	special OpenPokeblockCaseOnFeeder
	goto_if_ne VAR_RESULT, 0xFFFF, SafariZone_EventScript_PokeblockPlaced
#ifdef BUGFIX
	releaseall  @ Only gets called from EventScript_PokeBlockFeeder which uses lockall.
#endif
	end

SafariZone_EventScript_PokeblockPlaced::
	message SafariZone_Text_PokeblockWasPlaced
	waitmessage
	waitbuttonpress
	releaseall
	end

SafariZone_EventScript_PokeblockPresent::
	message SafariZone_Text_PokeblockStillHere
	waitmessage
	waitbuttonpress
	releaseall
	end

SafariZone_Text_WouldYouLikeToExit:
	.string "Möchtest du die SAFARI-ZONE jetzt\n"
	.string "verlassen?$"

SafariZone_Text_TimesUp:
	.string "Ding Dong! Die Zeit ist abgelaufen!\n"
	.string "Dein SAFARI-Spiel ist vorbei.$"

SafariZone_Text_OutOfBalls:
	.string "Du hast keine SAFARIBÄLLe mehr.\n"
	.string "Dein SAFARI-Spiel ist vorbei.$"

SafariZone_Text_PlacePokeblockOnFeeder:
	.string "Möchtest du einen {POKEBLOCK} in den\n"
	.string "{POKEBLOCK}NAPF legen?$"

SafariZone_Text_PokeblockStillHere:
	.string "Dein {STR_VAR_1} liegt immer hier.$"

SafariZone_Text_PokeblockWasPlaced:
	.string "{STR_VAR_1} wurde in den {POKEBLOCK}-\n"
	.string "NAPF gelegt.$"

Route121_SafariZoneEntrance_Text_WelcomeToSafariZone:
	.string "Willkommen in der SAFARI-ZONE!\p"
	.string "Hier bekommst du viele POKéMON zu\n"
	.string "Gesicht, die sehr selten in der HOENN-\l"
	.string "Region sind.\p"
	.string "Du kannst sie in ihrer ganzen Wildheit\n"
	.string "und ungezähmt in ihrer natürlichen\l"
	.string "Umgebung beobachten.\p"
	.string "Wir haben unsere Tore für die POKéMON-\n"
	.string "TRAINER geöffnet.\p"
	.string "Fangt euch POKéMON. Und behaltet sie!\p"
	.string "Kommt und genießt die Welt der\n"
	.string "SAFARI-ZONE!$"

Route121_SafariZoneEntrance_Text_WelcomeFirstTime:
	.string "Willkommen in der SAFARI-ZONE!\n"
	.string "Bist du zum ersten Mal hier?$"

Route121_SafariZoneEntrance_Text_ComeInAndEnjoy:
	.string "Komm und genieße die SAFARI-ZONE!$"

Route121_SafariZoneEntrance_Text_FirstTimeInfo:
	.string "Sobald du die SAFARI-ZONE betrittst,\n"
	.string "stehen dir 30 SAFARIBÄLLe zur Ver-\l"
	.string "fügung, um POKéMON zu fangen.\p"
	.string "Das SAFARI-Spiel ist vorbei, sobald du\n"
	.string "deine SAFARIBÄLLe verbraucht oder\l"
	.string "500 Schritte gemacht hast.\p"
	.string "Komm und genieße die SAFARI-ZONE!$"

Route121_SafariZoneEntrance_Text_WouldYouLikeToPlay:
	.string "Willkommen in der SAFARI-ZONE!\p"
	.string "Alles, was du für nur ¥500 fangen\n"
	.string "kannst! Möchtest du es probieren?$"

Route121_SafariZoneEntrance_Text_PlayAnotherTime:
	.string "Okay.\n"
	.string "Bitte beehre uns doch später einmal.$"

Route121_SafariZoneEntrance_Text_NotEnoughMoney:
	.string "Du hast nicht genug Geld dabei.\n"
	.string "Tut mir Leid.$"

Route121_SafariZoneEntrance_Text_ThatWillBe500Please:
	.string "Das macht dann ¥500, bitte.$"

Route121_SafariZoneEntrance_Text_HereAreYourSafariBalls:
	.string "Hier sind deine SAFARIBÄLLe.$"

Route121_SafariZoneEntrance_Text_Received30SafariBalls:
	.string "{PLAYER} erhält 30 SAFARIBÄLLe.$"

Route121_SafariZoneEntrance_Text_PleaseEnjoyYourself:
	.string "Wir geben dir Bescheid, wenn das Spiel\n"
	.string "vorbei ist.\p"
	.string "Bis dahin wünschen wir viel Spaß!\n"
	.string "Und auf geht’s in die Wildnis!$"

Route121_SafariZoneEntrance_Text_PCIsFull:
	.string "Entschuldigung!\n"
	.string "Deine PC-BOXen sind voll.$"

Route121_SafariZoneEntrance_Text_YouNeedPokeblockCase:
	.string "Entschuldigung!\n"
	.string "Du besitzt keine {POKEBLOCK}BOX.\p"
	.string "Dein SAFARI-Spiel wäre viel erfolg-\n"
	.string "reicher, wenn du {POKEBLOCK} benutzen\l"
	.string "würdest.\p"
	.string "Bitte besorge dir doch eine {POKEBLOCK}BOX.\p"
	.string "Vielleicht erhältst du in der WETT-\n"
	.string "BEWERBSHALLE von\l"
	.string "SEEGRASULB CITY eine.$"

SafariZone_South_Text_StillHaveTimeExit:
	.string "Du hast noch Zeit übrig. Möchtest du\n"
	.string "die SAFARI-ZONE jetzt verlassen?$"

SafariZone_South_Text_EnjoyTheRestOfYourAdventure:
	.string "Viel Vergnügen bei dem Rest deines\n"
	.string "wilden Abenteuers!$"

SafariZone_South_Text_ExitEarlyThankYouForPlaying:
	.string "Okay.\p"
	.string "Ich nehme die verbleibenden\n"
	.string "SAFARIBÄLLe zurück.\p"
	.string "Vielen Dank für deine Teilnahme.\n"
	.string "Komm bald wieder!$"

SafariZone_South_Text_GoodLuck:
	.string "Viel Glück!\p"
	.string "Wenn du irgendetwas brauchst, zögere\n"
	.string "nicht, mich anzusprechen!$"

SafariZone_South_Text_Boy:
	.string "Weißt du was?\p"
	.string "Wenn du einen {POKEBLOCK} in diese Kiste\n"
	.string "dort legst, werden POKéMON angelockt.$"

SafariZone_South_Text_Man:
	.string "Ich wollte noch weiter hinein, aber\n"
	.string "ich habe mein RAD vergessen.\p"
	.string "Irgendetwas sagt mir, dass in den abge-\n"
	.string "legenen Gegenden seltene POKéMON\l"
	.string "leben.$"

SafariZone_Southwest_Text_Woman:
	.string "Manchmal, wenn ich einem POKéMON einen\n"
	.string "{POKEBLOCK} zuwerfe, ignoriert es das total.\p"
	.string "Ob POKéMON auch manche Dinge mögen\n"
	.string "und manche nicht? Wie wir Menschen?$"

SafariZone_Northwest_Text_Man:
	.string "Hechel… Keuch…\n"
	.string "Ich… bin hierher gekommen… aber…\p"
	.string "Ich bin erschöpft… Japs… Ich habe\n"
	.string "keine Energie, ein POKéMON zu fangen.$"

SafariZone_North_Text_Fisherman:
	.string "Ich habe eine Mission. Ich will WASSER-\n"
	.string "POKéMON fangen, die es in HOENN nicht\l"
	.string "gibt.\p"
	.string "Weißt du zufällig, wo hier der See ist?$"

SafariZone_North_Text_Man:
	.string "Ich will viele seltene POKéMON fangen\n"
	.string "und mit meinen Freunden tauschen.$"

SafariZone_South_Text_Youngster:
	.string "Ich habe einen {POKEBLOCK} in den {POKEBLOCK}-\n"
	.string "NAPF gelegt. Er ist verschwunden.\p"
	.string "Ein POKéMON muss ihn gefuttert haben,\n"
	.string "ohne dass ich das gemerkt habe.$"

Route121_SafariZoneEntrance_Text_TrainerTip:
	.string "TIPP für TRAINER in der SAFARI-ZONE!\p"
	.string "Wirf POKéMON {POKEBLOCK} zu, dann ergreifen\n"
	.string "sie nicht so schnell die Flucht.$"

SafariZone_Southwest_Text_RestHouseSign:
	.string "RASTHAUS\n"
	.string "“Erhole deine gemarterten Füße.”$"

SafariZone_RestHouse_Text_Youngster:
	.string "Ich habe keine {POKEBLOCK}, aber ich habe\n"
	.string "trotzdem viele POKéMON gefangen.\p"
	.string "Du kannst deine Chancen erhöhen, indem\n"
	.string "du näher an das POKéMON herangehst,\l"
	.string "bevor du den SAFARIBALL wirfst.$"

SafariZone_RestHouse_Text_PsychicM:
	.string "POKéMON fliehen nicht so schnell, wenn\n"
	.string "man ihnen {POKEBLOCK} zuwirft.\p"
	.string "POKéMON, die von Natur aus nicht\n"
	.string "schnell fliehen, braucht man sie nicht\l"
	.string "unbedingt zuzuwerfen.$"

SafariZone_RestHouse_Text_FatMan:
	.string "Wird ein {POKEBLOCK} in den NAPF gelegt,\n"
	.string "werden POKéMON angelockt.\p"
	.string "Ich glaube, POKéMON mit der gleichen\n"
	.string "Wesensart werden von ähnlichen\l"
	.string "{POKEBLOCK}n angezogen.$"

SafariZone_South_Text_AreaOffLimits1:
	.string "In diesem Gebiet finden Bauarbeiten\n"
	.string "statt. Zutritt verboten!$"

SafariZone_Southeast_Text_ExpansionIsFinished:
	.string "Der Ausbau der SAFARI-ZONE ist\n"
	.string "abgeschlossen.\p"
	.string "Wir hoffen, du genießt den Aufenthalt.$"

SafariZone_South_Text_AreaOffLimits2:
	.string "In diesem Gebiet finden Bauarbeiten\n"
	.string "statt. Zutritt verboten!$"

SafariZone_Southeast_Text_LittleGirl:
	.string "Wow! Huiii! Diese POKéMON habe ich noch\n"
	.string "nie vorher gesehen!$"

SafariZone_Southeast_Text_FatMan:
	.string "Die POKéMON in diesem Gebiet sind mir\n"
	.string "völlig unbekannt.\p"
	.string "Und ich darf diese seltenen POKéMON\n"
	.string "auch noch fangen! Ich kann mein Glück\l"
	.string "kaum fassen! Cool!$"

SafariZone_Southeast_Text_RichBoy:
	.string "Die POKéMON in diesem Gebiet scheinen\n"
	.string "nicht aus HOENN zu kommen.$"

SafariZone_Northeast_Text_Boy:
	.string "Ich habe nur noch wenige SAFARIBÄLLe\n"
	.string "übrig.\p"
	.string "Mir fällt es schwer, mich zu\n"
	.string "entscheiden, welches POKéMON ich\l"
	.string "nun fangen soll.$"

SafariZone_Northeast_Text_Woman:
	.string "Ich habe gehört, man könne hier auf\n"
	.string "PIKACHU treffen. Wo mag nur eins sein?$"

SafariZone_Northeast_Text_Girl:
	.string "Schluchz heul!\n"
	.string "Ich schaffe es nicht, eines zu fangen.\p"
	.string "Ich habe mein Geld umsonst ausgegeben,\n"
	.string "wenn ich nichts fange.$"
