OldaleTown_House2_MapScripts::
	.byte 0

OldaleTown_House2_EventScript_Woman::
	msgbox OldaleTown_House2_Text_PokemonLevelUp, MSGBOX_NPC
	end

OldaleTown_House2_EventScript_Man::
	msgbox OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon, MSGBOX_NPC
	end

OldaleTown_House2_Text_PokemonLevelUp:
	.string "Während eines Kampfes können POKéMON\n"
	.string "manchmal einen Level dazugewinnen und\l"
	.string "stärker werden.$"

OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon:
	.string "Ich freu mich scho wieder\n"
	.string "uf Basi-Fasi!$"

