PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Okay?...\p"
	.string "Au mal über ahchlopfe\n"
	.string "nahdenkt?$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Seufz…\p"
	.string "Ich wünschte, ich könnte mit einigen\n"
	.string "POKéMON auf Abenteuerreise gehen…\p"
	.string "Sich durch hohes Gras schleichen…\n"
	.string "Steile, zerklüftete Berge erklimmen…\p"
	.string "Das tosende Meer überqueren…\n"
	.string "Dunkle Höhlen erforschen…\p"
	.string "Und manchmal ein wenig Heimweh haben…\p"
	.string "Reisen muss einfach toll sein!$"

