AbandonedShip_Rooms2_B1F_MapScripts::
	.byte 0

AbandonedShip_Rooms2_B1F_EventScript_Camper::
	msgbox AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring, MSGBOX_NPC
	end

AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring:
	.string "Ein perfekter Ort, auf Erkundungstour\n"
	.string "zu gehen. Es ist aufregend hier!\p"
	.string "Ich wette, hier sind wertvolle Schätze\n"
	.string "versteckt…$"

