LittlerootTown_ProfessorBirchsLab_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, LittlerootTown_ProfessorBirchsLab_OnTransition
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, LittlerootTown_ProfessorBirchsLab_OnWarp
	map_script MAP_SCRIPT_ON_FRAME_TABLE, LittlerootTown_ProfessorBirchsLab_OnFrame
	.byte 0

	@ State descriptions for VAR_DEX_UPGRADE_JOHTO_STARTER_STATE
	@ 1: Beat Elite Four, Dex upgrade ready
	@ 2: Received National Dex
	@ 3: Left lab after receiving National Dex
	@ 4: Entered lab after catching all Hoenn mons
	@ 5: Birch told player to choose Johto starter
	@ 6: Chose Johto starter

	@ State descriptions for VAR_BIRCH_LAB_STATE
	@ 1: Never occurs
	@ 2: Chose starter
	@ 3: Received starter in lab
	@ 4: Defeated rival on Route 103
	@ 5: Received pokedex

LittlerootTown_ProfessorBirchsLab_OnTransition:
	call Common_EventScript_SetupRivalGfxId
	call ProfBirch_EventScript_UpdateLocation
	goto_if_ge VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 6, LittlerootTown_ProfessorBirchsLab_EventScript_SetAfterJohtoStarterLayout
	goto_if_ge VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 4, LittlerootTown_ProfessorBirchsLab_EventScript_SetJohtoStarterLayout
	goto_if_eq VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 3, LittlerootTown_ProfessorBirchsLab_EventScript_CheckReadyForJohtoStarter
	end

LittlerootTown_ProfessorBirchsLab_EventScript_CheckReadyForJohtoStarter::
	specialvar VAR_RESULT, HasAllHoennMons
	goto_if_eq VAR_RESULT, TRUE, LittlerootTown_ProfessorBirchsLab_EventScript_SetReadyForJohtoStarter
	setobjectmovementtype LOCALID_BIRCHS_LAB_RIVAL, MOVEMENT_TYPE_WANDER_UP_AND_DOWN
	setobjectxyperm LOCALID_BIRCHS_LAB_RIVAL, 5, 10
	end

LittlerootTown_ProfessorBirchsLab_EventScript_SetReadyForJohtoStarter::
	setvar VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 4
	goto LittlerootTown_ProfessorBirchsLab_EventScript_SetJohtoStarterLayout

LittlerootTown_ProfessorBirchsLab_EventScript_SetJohtoStarterLayout::
	setmaplayoutindex LAYOUT_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB_WITH_TABLE
	end

LittlerootTown_ProfessorBirchsLab_EventScript_SetAfterJohtoStarterLayout::
	setmaplayoutindex LAYOUT_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB_WITH_TABLE
	setobjectmovementtype LOCALID_BIRCHS_LAB_RIVAL, MOVEMENT_TYPE_WANDER_UP_AND_DOWN
	setobjectxyperm LOCALID_BIRCHS_LAB_RIVAL, 5, 10
	end

LittlerootTown_ProfessorBirchsLab_OnWarp:
	map_script_2 VAR_BIRCH_LAB_STATE, 2, LittlerootTown_ProfessorBirchsLab_EventScript_SetPlayerPosForReceiveStarter
	map_script_2 VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 1, LittlerootTown_ProfessorBirchsLab_EventScript_SetObjectPosForDexUpgrade
	map_script_2 VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 2, LittlerootTown_ProfessorBirchsLab_EventScript_SetObjectPosForDexUpgrade
	map_script_2 VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 3, LittlerootTown_ProfessorBirchsLab_EventScript_AddRivalObject
	map_script_2 VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 6, LittlerootTown_ProfessorBirchsLab_EventScript_AddRivalObject
	map_script_2 VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 4, LittlerootTown_ProfessorBirchsLab_EventScript_SetObjectPosForJohtoStarters
	map_script_2 VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 5, LittlerootTown_ProfessorBirchsLab_EventScript_SetObjectPosForJohtoStarters
	.2byte 0

LittlerootTown_ProfessorBirchsLab_EventScript_SetPlayerPosForReceiveStarter::
	turnobject LOCALID_PLAYER, DIR_NORTH
	end

LittlerootTown_ProfessorBirchsLab_EventScript_SetObjectPosForDexUpgrade::
	turnobject LOCALID_PLAYER, DIR_NORTH
	addobject LOCALID_BIRCHS_LAB_BIRCH
	addobject LOCALID_BIRCHS_LAB_RIVAL
	turnobject LOCALID_BIRCHS_LAB_RIVAL, DIR_NORTH
	setobjectxy LOCALID_BIRCHS_LAB_RIVAL, 5, 5
	turnobject LOCALID_BIRCHS_LAB_BIRCH, DIR_SOUTH
	setobjectxy LOCALID_BIRCHS_LAB_BIRCH, 6, 4
	turnobject LOCALID_BIRCHS_LAB_AIDE, DIR_EAST
	setobjectxy LOCALID_BIRCHS_LAB_AIDE, 10, 10
	end

LittlerootTown_ProfessorBirchsLab_EventScript_AddRivalObject::
	addobject LOCALID_BIRCHS_LAB_RIVAL
	end

LittlerootTown_ProfessorBirchsLab_EventScript_SetObjectPosForJohtoStarters::
	addobject LOCALID_BIRCHS_LAB_CYNDAQUIL_BALL
	addobject LOCALID_BIRCHS_LAB_TOTODILE_BALL
	addobject LOCALID_BIRCHS_LAB_CHIKORITA_BALL
	addobject LOCALID_BIRCHS_LAB_RIVAL
	turnobject LOCALID_BIRCHS_LAB_CYNDAQUIL_BALL, DIR_SOUTH
	setobjectxy LOCALID_BIRCHS_LAB_CYNDAQUIL_BALL, 8, 4
	turnobject LOCALID_BIRCHS_LAB_TOTODILE_BALL, DIR_SOUTH
	setobjectxy LOCALID_BIRCHS_LAB_TOTODILE_BALL, 9, 4
	turnobject LOCALID_BIRCHS_LAB_CHIKORITA_BALL, DIR_SOUTH
	setobjectxy LOCALID_BIRCHS_LAB_CHIKORITA_BALL, 10, 4
	turnobject LOCALID_BIRCHS_LAB_BIRCH, DIR_SOUTH
	setobjectxy LOCALID_BIRCHS_LAB_BIRCH, 6, 4
	turnobject LOCALID_BIRCHS_LAB_RIVAL, DIR_EAST
	setobjectxy LOCALID_BIRCHS_LAB_RIVAL, 5, 5
	end

LittlerootTown_ProfessorBirchsLab_OnFrame:
	map_script_2 VAR_BIRCH_LAB_STATE, 2, LittlerootTown_ProfessorBirchsLab_EventScript_GiveStarterEvent
	map_script_2 VAR_BIRCH_LAB_STATE, 4, LittlerootTown_ProfessorBirchsLab_EventScript_GivePokedexEvent
	map_script_2 VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 1, LittlerootTown_ProfessorBirchsLab_EventScript_UpgradeToNationalDex
	map_script_2 VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 4, LittlerootTown_ProfessorBirchsLab_EventScript_ChooseJohtoStarter
	.2byte 0

@ The starter is technically given prior to this on Route 101 by special ChooseStarter
@ This is just where the game tells you its yours and lets you nickname it
LittlerootTown_ProfessorBirchsLab_EventScript_GiveStarterEvent::
	lockall
	bufferleadmonspeciesname STR_VAR_1
	message LittlerootTown_ProfessorBirchsLab_Text_LikeYouToHavePokemon
	waitmessage
	playfanfare MUS_OBTAIN_ITEM
	waitfanfare
	msgbox LittlerootTown_ProfessorBirchsLab_Text_WhyNotGiveNicknameToMon, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, LittlerootTown_ProfessorBirchsLab_EventScript_NicknameStarter
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_GoSeeRival
	end

LittlerootTown_ProfessorBirchsLab_EventScript_NicknameStarter::
	setvar VAR_0x8004, 0
	call Common_EventScript_NameReceivedPartyMon
	goto LittlerootTown_ProfessorBirchsLab_EventScript_GoSeeRival
	end

LittlerootTown_ProfessorBirchsLab_EventScript_GoSeeRival::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_MightBeGoodIdeaToGoSeeRival, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, LittlerootTown_ProfessorBirchsLab_EventScript_AgreeToSeeRival
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_DeclineSeeingRival
	end

LittlerootTown_ProfessorBirchsLab_EventScript_AgreeToSeeRival::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_GetRivalToTeachYou, MSGBOX_DEFAULT
	clearflag FLAG_HIDE_ROUTE_101_BOY
	setvar VAR_BIRCH_LAB_STATE, 3
	releaseall
	end

LittlerootTown_ProfessorBirchsLab_EventScript_DeclineSeeingRival::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_DontBeThatWay, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, LittlerootTown_ProfessorBirchsLab_EventScript_AgreeToSeeRival
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_DeclineSeeingRival
	end

LittlerootTown_ProfessorBirchsLab_EventScript_GivePokedexEvent::
	lockall
	applymovement LOCALID_PLAYER, LittlerootTown_ProfessorBirchsLab_Movement_PlayerEnterLabForPokedex
	waitmovement 0
	goto LittlerootTown_ProfessorBirchsLab_EventScript_GivePokedex
	end

LittlerootTown_ProfessorBirchsLab_Movement_PlayerEnterLabForPokedex:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

LittlerootTown_ProfessorBirchsLab_EventScript_UpgradeToNationalDex::
	lockall
	delay 30
	msgbox LittlerootTown_ProfessorBirchsLab_Text_OtherRegionsUpgradeToNational, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_BIRCHS_LAB_BIRCH, LittlerootTown_ProfessorBirchsLab_Movement_BirchRetrievePokedexes
	waitmovement 0
	delay 20
	playse SE_CLICK
	delay 10
	playse SE_CLICK
	delay 10
	playse SE_CLICK
	delay 10
	playse SE_CLICK
	delay 20
	applymovement LOCALID_BIRCHS_LAB_RIVAL, Common_Movement_WalkInPlaceFasterRight
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
	waitmovement 0
	checkplayergender
	call_if_eq VAR_RESULT, MALE, LittlerootTown_ProfessorBirchsLab_EventScript_MayUpgradeComment
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_ProfessorBirchsLab_EventScript_BrendanUpgradeComment
	playse SE_PC_ON
	waitse
	delay 20
	applymovement LOCALID_BIRCHS_LAB_BIRCH, LittlerootTown_ProfessorBirchsLab_Movement_BirchReturnPokedex
	waitmovement 0
	applymovement LOCALID_BIRCHS_LAB_RIVAL, Common_Movement_WalkInPlaceFasterUp
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	msgbox LittlerootTown_ProfessorBirchsLab_Text_OkayAllDone, MSGBOX_DEFAULT
	playfanfare MUS_OBTAIN_ITEM
	message LittlerootTown_ProfessorBirchsLab_Text_PokedexUpgradedToNational
	waitmessage
	waitfanfare
	setflag FLAG_SYS_NATIONAL_DEX
	special EnableNationalPokedex
	msgbox LittlerootTown_ProfessorBirchsLab_Text_GrassyPatchWaiting2, MSGBOX_DEFAULT
	closemessage
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BIRCH
	setflag FLAG_HIDE_LITTLEROOT_TOWN_RIVAL
	setvar VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 2
	setvar VAR_SCOTT_BF_CALL_STEP_COUNTER, 0
	setflag FLAG_SCOTT_CALL_BATTLE_FRONTIER
	releaseall
	end

LittlerootTown_ProfessorBirchsLab_EventScript_MayUpgradeComment::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_MayUpgradeSoCool, MSGBOX_DEFAULT
	closemessage
	return

LittlerootTown_ProfessorBirchsLab_EventScript_BrendanUpgradeComment::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_BrendanYouCanThankMe, MSGBOX_DEFAULT
	closemessage
	return

LittlerootTown_ProfessorBirchsLab_Movement_BirchRetrievePokedexes:
	walk_left
	walk_in_place_faster_down
	delay_16
	delay_16
	walk_right
	walk_in_place_faster_down
	delay_16
	delay_16
	walk_right
	walk_down
	walk_down
	walk_down
	walk_down
	walk_right
	walk_right
	walk_right
	walk_in_place_faster_up
	step_end

LittlerootTown_ProfessorBirchsLab_Movement_BirchReturnPokedex:
	walk_left
	walk_left
	walk_left
	walk_up
	walk_up
	walk_up
	walk_up
	walk_left
	walk_in_place_faster_down
	step_end

LittlerootTown_ProfessorBirchsLab_EventScript_ChooseJohtoStarter::
	lockall
	applymovement LOCALID_PLAYER, LittlerootTown_ProfessorBirchsLab_Movement_PlayerEnterLabForJohtoStarter
	waitmovement 0
	msgbox LittlerootTown_ProfessorBirchsLab_Text_CompletedDexChoosePokemon, MSGBOX_DEFAULT
	setvar VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 5
	releaseall
	end

LittlerootTown_ProfessorBirchsLab_Movement_PlayerEnterLabForJohtoStarter:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

LittlerootTown_ProfessorBirchsLab_EventScript_Aide::
	lock
	faceplayer
	goto_if_ge VAR_BIRCH_LAB_STATE, 3, LittlerootTown_ProfessorBirchsLab_EventScript_AideReceivedStarter
	goto_if_set FLAG_BIRCH_AIDE_MET, LittlerootTown_ProfessorBirchsLab_EventScript_AideAlreadyMet
	msgbox LittlerootTown_ProfessorBirchsLab_Text_BirchAwayOnFieldwork, MSGBOX_DEFAULT
	setflag FLAG_BIRCH_AIDE_MET
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_AideAlreadyMet::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_BirchIsntOneForDeskWork, MSGBOX_DEFAULT
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_AideReceivedStarter::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_BirchEnjoysRivalsHelpToo, MSGBOX_DEFAULT
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_Cyndaquil::
	release
	goto_if_ge VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 6, LittlerootTown_ProfessorBirchsLab_EventScript_AlreadyChoseJohtoStarter
	applymovement LOCALID_BIRCHS_LAB_BIRCH, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	showmonpic SPECIES_CYNDAQUIL, 10, 3
	msgbox LittlerootTown_ProfessorBirchsLab_Text_YoullTakeCyndaquil, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_TakeYourTime
	goto LittlerootTown_ProfessorBirchsLab_EventScript_GiveCyndaquil
	end

LittlerootTown_ProfessorBirchsLab_EventScript_Totodile::
	release
	goto_if_ge VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 6, LittlerootTown_ProfessorBirchsLab_EventScript_AlreadyChoseJohtoStarter
	applymovement LOCALID_BIRCHS_LAB_BIRCH, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	showmonpic SPECIES_TOTODILE, 10, 3
	msgbox LittlerootTown_ProfessorBirchsLab_Text_YoullTakeTotodile, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_TakeYourTime
	goto LittlerootTown_ProfessorBirchsLab_EventScript_GiveTotodile
	end

LittlerootTown_ProfessorBirchsLab_EventScript_Chikorita::
	release
	goto_if_ge VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 6, LittlerootTown_ProfessorBirchsLab_EventScript_AlreadyChoseJohtoStarter
	applymovement LOCALID_BIRCHS_LAB_BIRCH, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	showmonpic SPECIES_CHIKORITA, 10, 3
	msgbox LittlerootTown_ProfessorBirchsLab_Text_YoullTakeChikorita, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_TakeYourTime
	goto LittlerootTown_ProfessorBirchsLab_EventScript_GiveChikorita
	end

LittlerootTown_ProfessorBirchsLab_EventScript_AlreadyChoseJohtoStarter::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_BetterLeaveOthersAlone, MSGBOX_DEFAULT
	releaseall
	end

LittlerootTown_ProfessorBirchsLab_EventScript_TakeYourTime::
	hidemonpic
	msgbox LittlerootTown_ProfessorBirchsLab_Text_TakeYourTimeAllInvaluable, MSGBOX_DEFAULT
	releaseall
	end

LittlerootTown_ProfessorBirchsLab_EventScript_GiveCyndaquil::
	bufferspeciesname STR_VAR_1, SPECIES_CYNDAQUIL
	setvar VAR_TEMP_TRANSFERRED_SPECIES, SPECIES_CYNDAQUIL
	givemon SPECIES_CYNDAQUIL, 5
	goto_if_eq VAR_RESULT, MON_GIVEN_TO_PARTY, LittlerootTown_ProfessorBirchsLab_EventScript_SendCyndaquilToParty
	goto_if_eq VAR_RESULT, MON_GIVEN_TO_PC, LittlerootTown_ProfessorBirchsLab_EventScript_SendCyndaquilToPC
	hidemonpic
	goto Common_EventScript_NoMoreRoomForPokemon
	end

LittlerootTown_ProfessorBirchsLab_EventScript_SendCyndaquilToParty::
	call LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedJohtoStarter
	removeobject LOCALID_BIRCHS_LAB_CYNDAQUIL_BALL
	msgbox gText_NicknameThisPokemon, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedCyndaquil
	call Common_EventScript_GetGiftMonPartySlot
	call Common_EventScript_NameReceivedPartyMon
	goto LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedCyndaquil
	end

LittlerootTown_ProfessorBirchsLab_EventScript_SendCyndaquilToPC::
	call LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedJohtoStarter
	removeobject LOCALID_BIRCHS_LAB_CYNDAQUIL_BALL
	msgbox gText_NicknameThisPokemon, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_CyndaquilTransferredToPC
	call Common_EventScript_NameReceivedBoxMon
	goto LittlerootTown_ProfessorBirchsLab_EventScript_CyndaquilTransferredToPC
	end

LittlerootTown_ProfessorBirchsLab_EventScript_CyndaquilTransferredToPC::
	call Common_EventScript_TransferredToPC
	goto LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedCyndaquil
	end

LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedCyndaquil::
	hidemonpic
	msgbox LittlerootTown_ProfessorBirchsLab_Text_GrassyPatchWaiting, MSGBOX_DEFAULT
	setvar VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 6
	releaseall
	end

LittlerootTown_ProfessorBirchsLab_EventScript_GiveTotodile::
	bufferspeciesname STR_VAR_1, SPECIES_TOTODILE
	setvar VAR_TEMP_TRANSFERRED_SPECIES, SPECIES_TOTODILE
	givemon SPECIES_TOTODILE, 5
	goto_if_eq VAR_RESULT, MON_GIVEN_TO_PARTY, LittlerootTown_ProfessorBirchsLab_EventScript_SendTotodileToParty
	goto_if_eq VAR_RESULT, MON_GIVEN_TO_PC, LittlerootTown_ProfessorBirchsLab_EventScript_SendTotodileToPC
	hidemonpic
	goto Common_EventScript_NoMoreRoomForPokemon
	end

LittlerootTown_ProfessorBirchsLab_EventScript_SendTotodileToParty::
	call LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedJohtoStarter
	removeobject LOCALID_BIRCHS_LAB_TOTODILE_BALL
	msgbox gText_NicknameThisPokemon, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedTotodile
	call Common_EventScript_GetGiftMonPartySlot
	call Common_EventScript_NameReceivedPartyMon
	goto LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedTotodile
	end

LittlerootTown_ProfessorBirchsLab_EventScript_SendTotodileToPC::
	call LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedJohtoStarter
	removeobject LOCALID_BIRCHS_LAB_TOTODILE_BALL
	msgbox gText_NicknameThisPokemon, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_TotodileTransferredToPC
	call Common_EventScript_NameReceivedBoxMon
	goto LittlerootTown_ProfessorBirchsLab_EventScript_TotodileTransferredToPC
	end

LittlerootTown_ProfessorBirchsLab_EventScript_TotodileTransferredToPC::
	call Common_EventScript_TransferredToPC
	goto LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedTotodile
	end

LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedTotodile::
	hidemonpic
	msgbox LittlerootTown_ProfessorBirchsLab_Text_GrassyPatchWaiting, MSGBOX_DEFAULT
	setvar VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 6
	releaseall
	end

LittlerootTown_ProfessorBirchsLab_EventScript_GiveChikorita::
	bufferspeciesname STR_VAR_1, SPECIES_CHIKORITA
	setvar VAR_TEMP_TRANSFERRED_SPECIES, SPECIES_CHIKORITA
	givemon SPECIES_CHIKORITA, 5
	goto_if_eq VAR_RESULT, MON_GIVEN_TO_PARTY, LittlerootTown_ProfessorBirchsLab_EventScript_SendChikoritaToParty
	goto_if_eq VAR_RESULT, MON_GIVEN_TO_PC, LittlerootTown_ProfessorBirchsLab_EventScript_SendChikoritaToPC
	hidemonpic
	goto Common_EventScript_NoMoreRoomForPokemon
	end

LittlerootTown_ProfessorBirchsLab_EventScript_SendChikoritaToParty::
	call LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedJohtoStarter
	removeobject LOCALID_BIRCHS_LAB_CHIKORITA_BALL
	msgbox gText_NicknameThisPokemon, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedChikorita
	call Common_EventScript_GetGiftMonPartySlot
	call Common_EventScript_NameReceivedPartyMon
	goto LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedChikorita
	end

LittlerootTown_ProfessorBirchsLab_EventScript_SendChikoritaToPC::
	call LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedJohtoStarter
	removeobject LOCALID_BIRCHS_LAB_CHIKORITA_BALL
	msgbox gText_NicknameThisPokemon, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_ChikoritaTransferredToPC
	call Common_EventScript_NameReceivedBoxMon
	goto LittlerootTown_ProfessorBirchsLab_EventScript_ChikoritaTransferredToPC
	end

LittlerootTown_ProfessorBirchsLab_EventScript_ChikoritaTransferredToPC::
	call Common_EventScript_TransferredToPC
	goto LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedChikorita
	end

LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedChikorita::
	hidemonpic
	msgbox LittlerootTown_ProfessorBirchsLab_Text_GrassyPatchWaiting, MSGBOX_DEFAULT
	setvar VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 6
	releaseall
	end

LittlerootTown_ProfessorBirchsLab_EventScript_ReceivedJohtoStarter::
	playfanfare MUS_OBTAIN_ITEM
	message LittlerootTown_ProfessorBirchsLab_Text_ReceivedJohtoStarter
	waitmessage
	waitfanfare
	return

LittlerootTown_ProfessorBirchsLab_EventScript_Birch::
	lock
	faceplayer
	goto_if_set FLAG_ADVENTURE_STARTED, LittlerootTown_ProfessorBirchsLab_EventScript_AlreadyGotStarters
	msgbox LittlerootTown_ProfessorBirchsLab_Text_LunteChooseTwo, MSGBOX_DEFAULT
	setvar VAR_0x8008, 0
	setvar VAR_0x8009, 0
	setvar VAR_0x800A, 0
	call LittlerootTown_ProfessorBirchsLab_EventScript_ChooseCharmander
	call LittlerootTown_ProfessorBirchsLab_EventScript_ChooseCyndaquil
	call LittlerootTown_ProfessorBirchsLab_EventScript_ChooseTepig
	call LittlerootTown_ProfessorBirchsLab_EventScript_ChooseTurtwig
	call LittlerootTown_ProfessorBirchsLab_EventScript_ChooseTreecko
	call LittlerootTown_ProfessorBirchsLab_EventScript_ChooseSnivy
	call LittlerootTown_ProfessorBirchsLab_EventScript_ChooseSquirtle
	call LittlerootTown_ProfessorBirchsLab_EventScript_ChooseMudkip
	call LittlerootTown_ProfessorBirchsLab_EventScript_ChoosePiplup
	goto_if_ne VAR_0x8008, 2, LittlerootTown_ProfessorBirchsLab_EventScript_NotEnoughPokemon
	call LittlerootTown_ProfessorBirchsLab_EventScript_GiveSelectedStarterOne
	call LittlerootTown_ProfessorBirchsLab_EventScript_GiveSelectedStarterTwo
	msgbox LittlerootTown_ProfessorBirchsLab_Text_LunteAfterChoice, MSGBOX_DEFAULT
	setflag FLAG_SYS_POKEMON_GET
	setflag FLAG_SYS_POKEDEX_GET
	setflag FLAG_ADVENTURE_STARTED
	playfanfare MUS_OBTAIN_ITEM
	message LittlerootTown_ProfessorBirchsLab_Text_ObtainedPokedex
	waitfanfare
	msgbox LittlerootTown_ProfessorBirchsLab_Text_LunteGo, MSGBOX_DEFAULT
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_AlreadyGotStarters::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_AlreadyGotStarters, MSGBOX_DEFAULT
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_NotEnoughPokemon::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_NotEnoughPokemon, MSGBOX_DEFAULT
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_ChooseCharmander::
	goto_if_eq VAR_0x8008, 2, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	showmonpic SPECIES_CHARMANDER, 10, 3
	msgbox LittlerootTown_ProfessorBirchsLab_Text_ChooseCharmander, MSGBOX_YESNO
	hidemonpic
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	goto_if_eq VAR_0x8009, 0, LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstCharmander
	setvar VAR_0x800A, 1
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstCharmander::
	setvar VAR_0x8009, 1
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_ChooseCyndaquil::
	goto_if_eq VAR_0x8008, 2, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	showmonpic SPECIES_CYNDAQUIL, 10, 3
	msgbox LittlerootTown_ProfessorBirchsLab_Text_ChooseCyndaquil, MSGBOX_YESNO
	hidemonpic
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	goto_if_eq VAR_0x8009, 0, LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstCyndaquil
	setvar VAR_0x800A, 2
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstCyndaquil::
	setvar VAR_0x8009, 2
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_ChooseTepig::
	goto_if_eq VAR_0x8008, 2, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	showmonpic SPECIES_TEPIG, 10, 3
	msgbox LittlerootTown_ProfessorBirchsLab_Text_ChooseTepig, MSGBOX_YESNO
	hidemonpic
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	goto_if_eq VAR_0x8009, 0, LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstTepig
	setvar VAR_0x800A, 3
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstTepig::
	setvar VAR_0x8009, 3
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_ChooseTurtwig::
	goto_if_eq VAR_0x8008, 2, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	showmonpic SPECIES_TURTWIG, 10, 3
	msgbox LittlerootTown_ProfessorBirchsLab_Text_ChooseTurtwig, MSGBOX_YESNO
	hidemonpic
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	goto_if_eq VAR_0x8009, 0, LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstTurtwig
	setvar VAR_0x800A, 4
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstTurtwig::
	setvar VAR_0x8009, 4
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_ChooseTreecko::
	goto_if_eq VAR_0x8008, 2, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	showmonpic SPECIES_TREECKO, 10, 3
	msgbox LittlerootTown_ProfessorBirchsLab_Text_ChooseTreecko, MSGBOX_YESNO
	hidemonpic
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	goto_if_eq VAR_0x8009, 0, LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstTreecko
	setvar VAR_0x800A, 5
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstTreecko::
	setvar VAR_0x8009, 5
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_ChooseSnivy::
	goto_if_eq VAR_0x8008, 2, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	showmonpic SPECIES_SNIVY, 10, 3
	msgbox LittlerootTown_ProfessorBirchsLab_Text_ChooseSnivy, MSGBOX_YESNO
	hidemonpic
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	goto_if_eq VAR_0x8009, 0, LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstSnivy
	setvar VAR_0x800A, 6
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstSnivy::
	setvar VAR_0x8009, 6
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_ChooseSquirtle::
	goto_if_eq VAR_0x8008, 2, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	showmonpic SPECIES_SQUIRTLE, 10, 3
	msgbox LittlerootTown_ProfessorBirchsLab_Text_ChooseSquirtle, MSGBOX_YESNO
	hidemonpic
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	goto_if_eq VAR_0x8009, 0, LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstSquirtle
	setvar VAR_0x800A, 7
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstSquirtle::
	setvar VAR_0x8009, 7
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_ChooseMudkip::
	goto_if_eq VAR_0x8008, 2, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	showmonpic SPECIES_MUDKIP, 10, 3
	msgbox LittlerootTown_ProfessorBirchsLab_Text_ChooseMudkip, MSGBOX_YESNO
	hidemonpic
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	goto_if_eq VAR_0x8009, 0, LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstMudkip
	setvar VAR_0x800A, 8
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstMudkip::
	setvar VAR_0x8009, 8
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_ChoosePiplup::
	goto_if_eq VAR_0x8008, 2, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	showmonpic SPECIES_PIPLUP, 10, 3
	msgbox LittlerootTown_ProfessorBirchsLab_Text_ChoosePiplup, MSGBOX_YESNO
	hidemonpic
	goto_if_eq VAR_RESULT, NO, LittlerootTown_ProfessorBirchsLab_EventScript_Return
	goto_if_eq VAR_0x8009, 0, LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstPiplup
	setvar VAR_0x800A, 9
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_SetFirstPiplup::
	setvar VAR_0x8009, 9
	addvar VAR_0x8008, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_Return::
	return

LittlerootTown_ProfessorBirchsLab_EventScript_GiveSelectedStarterOne::
	goto_if_eq VAR_0x8009, 1, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveCharmander
	goto_if_eq VAR_0x8009, 2, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveCyndaquil
	goto_if_eq VAR_0x8009, 3, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveTepig
	goto_if_eq VAR_0x8009, 4, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveTurtwig
	goto_if_eq VAR_0x8009, 5, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveTreecko
	goto_if_eq VAR_0x8009, 6, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveSnivy
	goto_if_eq VAR_0x8009, 7, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveSquirtle
	goto_if_eq VAR_0x8009, 8, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveMudkip
	goto_if_eq VAR_0x8009, 9, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGivePiplup
	return

LittlerootTown_ProfessorBirchsLab_EventScript_GiveSelectedStarterTwo::
	goto_if_eq VAR_0x800A, 1, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveCharmander
	goto_if_eq VAR_0x800A, 2, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveCyndaquil
	goto_if_eq VAR_0x800A, 3, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveTepig
	goto_if_eq VAR_0x800A, 4, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveTurtwig
	goto_if_eq VAR_0x800A, 5, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveTreecko
	goto_if_eq VAR_0x800A, 6, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveSnivy
	goto_if_eq VAR_0x800A, 7, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveSquirtle
	goto_if_eq VAR_0x800A, 8, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveMudkip
	goto_if_eq VAR_0x800A, 9, LittlerootTown_ProfessorBirchsLab_EventScript_LunteGivePiplup
	return

LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveCharmander::
	givemon SPECIES_CHARMANDER, 5, ITEM_NONE
	return

LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveCyndaquil::
	givemon SPECIES_CYNDAQUIL, 5, ITEM_NONE
	return

LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveTepig::
	givemon SPECIES_TEPIG, 5, ITEM_NONE
	return

LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveTurtwig::
	givemon SPECIES_TURTWIG, 5, ITEM_NONE
	return

LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveTreecko::
	givemon SPECIES_TREECKO, 5, ITEM_NONE
	return

LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveSnivy::
	givemon SPECIES_SNIVY, 5, ITEM_NONE
	return

LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveSquirtle::
	givemon SPECIES_SQUIRTLE, 5, ITEM_NONE
	return

LittlerootTown_ProfessorBirchsLab_EventScript_LunteGiveMudkip::
	givemon SPECIES_MUDKIP, 5, ITEM_NONE
	return

LittlerootTown_ProfessorBirchsLab_EventScript_LunteGivePiplup::
	givemon SPECIES_PIPLUP, 5, ITEM_NONE
	return

LittlerootTown_ProfessorBirchsLab_EventScript_CanHaveAnyOneOfRarePokemon::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_CanHaveAnyOneOfRarePokemon, MSGBOX_DEFAULT
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_GrassyPatchWaiting::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_GrassyPatchWaiting2, MSGBOX_DEFAULT
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_TryRatePokedexOrRegister::
	goto_if_unset FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_UNKNOWN_0x380, ProfBirch_EventScript_RatePokedexOrRegister
	goto_if_eq VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 3, ProfBirch_EventScript_RatePokedexOrRegister
	goto_if_ge VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 6, ProfBirch_EventScript_RatePokedexOrRegister
	goto_if_eq VAR_BIRCH_LAB_STATE, 5, LittlerootTown_ProfessorBirchsLab_EventScript_PokemonAwait
	msgbox LittlerootTown_ProfessorBirchsLab_Text_BirchRivalGoneHome, MSGBOX_DEFAULT
	release
	end

EventScript_RegisterProfBirch::
	msgbox MatchCall_Text_BirchRegisterCall, MSGBOX_DEFAULT
	closemessage
	delay 30
	playfanfare MUS_REGISTER_MATCH_CALL
	msgbox MatchCall_Text_RegisteredBirch, MSGBOX_DEFAULT
	waitfanfare
	closemessage
	delay 30
	setflag FLAG_ENABLE_PROF_BIRCH_MATCH_CALL
	setvar VAR_REGISTER_BIRCH_STATE, 2
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_GivePokedex::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_HeardYouBeatRivalTakePokedex, MSGBOX_DEFAULT
	call LittlerootTown_ProfessorBirchsLab_EventScript_ReceivePokedex
	msgbox LittlerootTown_ProfessorBirchsLab_Text_ExplainPokedex, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_BIRCHS_LAB_RIVAL, LittlerootTown_ProfessorBirchsLab_Movement_RivalApproachPlayer
	waitmovement 0
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	checkplayergender
	call_if_eq VAR_RESULT, MALE, LittlerootTown_ProfessorBirchsLab_EventScript_MayGivePokeBalls
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_ProfessorBirchsLab_EventScript_BrendanGivePokeBalls
	setvar VAR_BIRCH_LAB_STATE, 5
	setflag FLAG_ADVENTURE_STARTED
	setvar VAR_OLDALE_TOWN_STATE, 1
	setvar VAR_LITTLEROOT_RIVAL_STATE, 4
	setvar VAR_LITTLEROOT_TOWN_STATE, 3
	warp MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F, 6, 4, 3
	waitstate
	releaseall
	end

LittlerootTown_ProfessorBirchsLab_EventScript_MayGivePokeBalls::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_MayGotPokedexTooTakeThese, MSGBOX_DEFAULT
	giveitem ITEM_POKE_BALL, 5
	call_if_eq VAR_RESULT, FALSE, LittlerootTown_ProfessorBirchsLab_EventScript_MayNoRoomForPokeBalls
	msgbox LittlerootTown_ProfessorBirchsLab_Text_CatchCutePokemonWithPokeBalls, MSGBOX_DEFAULT
	setvar VAR_RESULT, 0
	return

LittlerootTown_ProfessorBirchsLab_EventScript_BrendanGivePokeBalls::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_BrendanGotPokedexTooTakeThese, MSGBOX_DEFAULT
	giveitem ITEM_POKE_BALL, 5
	call_if_eq VAR_RESULT, FALSE, LittlerootTown_ProfessorBirchsLab_EventScript_BrendanNoRoomForPokeBalls
	msgbox LittlerootTown_ProfessorBirchsLab_Text_CatchCoolPokemonWithPokeBalls, MSGBOX_DEFAULT
	setvar VAR_RESULT, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_ReceivePokedex::
	playfanfare MUS_OBTAIN_ITEM
	message LittlerootTown_ProfessorBirchsLab_Text_ReceivedPokedex
	waitfanfare
	setflag FLAG_SYS_POKEDEX_GET
	special SetUnlockedPokedexFlags
	setflag FLAG_RECEIVED_POKEDEX_FROM_BIRCH
	setvar VAR_CABLE_CLUB_TUTORIAL_STATE, 1
	return

LittlerootTown_ProfessorBirchsLab_EventScript_PokemonAwait::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_CountlessPokemonAwait, MSGBOX_DEFAULT
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_MayNoRoomForPokeBalls::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_OhYourBagsFull, MSGBOX_DEFAULT
	return

LittlerootTown_ProfessorBirchsLab_EventScript_BrendanNoRoomForPokeBalls::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_HeyYourBagsFull, MSGBOX_DEFAULT
	return

LittlerootTown_ProfessorBirchsLab_Movement_RivalApproachPlayer:
	walk_down
	walk_in_place_faster_left
	step_end

LittlerootTown_ProfessorBirchsLab_EventScript_Machine::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_SeriousLookingMachine, MSGBOX_SIGN
	end

LittlerootTown_ProfessorBirchsLab_EventScript_Rival::
	lock
	faceplayer
	goto_if_eq VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 5, LittlerootTown_ProfessorBirchsLab_EventScript_RivalFuturePlans
	goto_if_ge VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 6, LittlerootTown_ProfessorBirchsLab_EventScript_RivalHaveYouGoneToBattleFrontier
	goto_if_ge VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 2, LittlerootTown_ProfessorBirchsLab_EventScript_RivalTakeBreakFromFieldwork
	checkplayergender
	call_if_eq VAR_RESULT, MALE, LittlerootTown_ProfessorBirchsLab_EventScript_MayWhereShouldIGoNext
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_ProfessorBirchsLab_EventScript_BrendanWhereShouldIGoNext
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_MayWhereShouldIGoNext::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_MayWhereShouldIGoNext, MSGBOX_DEFAULT
	return

LittlerootTown_ProfessorBirchsLab_EventScript_BrendanWhereShouldIGoNext::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_BrendanWhereShouldIGoNext, MSGBOX_DEFAULT
	return

LittlerootTown_ProfessorBirchsLab_EventScript_RivalFuturePlans::
	checkplayergender
	call_if_eq VAR_RESULT, MALE, LittlerootTown_ProfessorBirchsLab_EventScript_MayWhatNextImStayingHere
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_ProfessorBirchsLab_EventScript_BrendanPreferCollectingSlowly
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_MayWhatNextImStayingHere::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_MayWhatNextImStayingHere, MSGBOX_DEFAULT
	return

LittlerootTown_ProfessorBirchsLab_EventScript_BrendanPreferCollectingSlowly:
	msgbox LittlerootTown_ProfessorBirchsLab_Text_BrendanPreferCollectingSlowly, MSGBOX_DEFAULT
	return

LittlerootTown_ProfessorBirchsLab_EventScript_RivalHaveYouGoneToBattleFrontier::
	checkplayergender
	call_if_eq VAR_RESULT, MALE, LittlerootTown_ProfessorBirchsLab_EventScript_MayHaveYouGoneToBattleFrontier
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_ProfessorBirchsLab_EventScript_BrendanHaveYouGoneToBattleFrontier
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_MayHaveYouGoneToBattleFrontier::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_MayHaveYouGoneToBattleFrontier, MSGBOX_DEFAULT
	return

LittlerootTown_ProfessorBirchsLab_EventScript_BrendanHaveYouGoneToBattleFrontier::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_BrendanHaveYouGoneToBattleFrontier, MSGBOX_DEFAULT
	return

LittlerootTown_ProfessorBirchsLab_EventScript_RivalTakeBreakFromFieldwork::
	checkplayergender
	call_if_eq VAR_RESULT, MALE, LittlerootTown_ProfessorBirchsLab_EventScript_MayTakeBreakFromFieldwork
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_ProfessorBirchsLab_EventScript_BrendanTakeBreakFromFieldwork
	release
	end

LittlerootTown_ProfessorBirchsLab_EventScript_MayTakeBreakFromFieldwork::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_MayTakeBreakFromFieldwork, MSGBOX_DEFAULT
	return

LittlerootTown_ProfessorBirchsLab_EventScript_BrendanTakeBreakFromFieldwork::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_BrendanTakeBreakFromFieldwork, MSGBOX_DEFAULT
	return

LittlerootTown_ProfessorBirchsLab_EventScript_PC::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_PCUsedForResearch, MSGBOX_SIGN
	end

LittlerootTown_ProfessorBirchsLab_EventScript_Bookshelf::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_CrammedWithBooksOnPokemon, MSGBOX_SIGN
	end

LittlerootTown_ProfessorBirchsLab_EventScript_Book::
	msgbox LittlerootTown_ProfessorBirchsLab_Text_BookTooHardToRead, MSGBOX_SIGN
	end

LittlerootTown_ProfessorBirchsLab_EventScript_ScottAboardSSTidalCall::
	lockall
	pokenavcall LittlerootTown_ProfessorBirchsLab_Text_ScottAboardSSTidalCall
	waitmessage
	clearflag FLAG_SCOTT_CALL_BATTLE_FRONTIER
	releaseall
	end

LittlerootTown_ProfessorBirchsLab_Text_BirchAwayOnFieldwork:
	.string "Ouh NJIERI!\p"
	.string "Ich hoffe du freusch dich\n"
	.string "über dini Pokemon!\p"
	.string "Jetzt gah da use und füll\n"
	.string "für mich de Pokedex!$"

LittlerootTown_ProfessorBirchsLab_Text_BirchIsntOneForDeskWork:
	.string "Glaub mer, mengisch musch\n"
	.string "eifach gnueg lang sueche,\p"
	.string "bis selteni Pokemon findsch.\p"
	.string "Es git sogar Pokemon wo\n"
	.string "Shiny sii chönnd.\p"
	.string "D' Chance e so eis\n"
	.string "ahztreffe isch bi 0.012%\l"
	.string "pro Pokemon.\p"
	.string "Also chli meh als 8000\n"
	.string "Begegnige zum so eis\l"
	.string "finde xD.$"

LittlerootTown_ProfessorBirchsLab_Text_BirchEnjoysRivalsHelpToo:
	.string "Wenn du dich ahstrengsch\n"
	.string "und min Respekt verdiensch,\p"
	.string "fightemer mal gegenenand.$"

LittlerootTown_ProfessorBirchsLab_Text_LikeYouToHavePokemon:
	.string "PROF. LUNTE: Du bist also {PLAYER}{KUN}!\p"
	.string "Dein Vater hat mir schon viel von dir\n"
	.string "erzählt.\p"
	.string "Ich habe auch erfahren, dass du noch\n"
	.string "kein eigenes POKéMON besitzt.\p"
	.string "Aber wie du eben gekämpft hast…\n"
	.string "Diese Gelassenheit…\p"
	.string "In deinen Adern fließt wirklich das Blut\n"
	.string "deines Vaters!\p"
	.string "Als Dank dafür, dass du mich gerettet\n"
	.string "hast, möchte ich dir das POKéMON\l"
	.string "schenken, das du dabei benutzt hast.\p"
	.string "{PLAYER} erhält {STR_VAR_1}!$"

LittlerootTown_ProfessorBirchsLab_Text_WhyNotGiveNicknameToMon:
	.string "PROF. LUNTE: Willst du dem\n"
	.string "{STR_VAR_1} einen Kosenamen geben?$"

LittlerootTown_ProfessorBirchsLab_Text_MightBeGoodIdeaToGoSeeRival:
	.string "PROF. LUNTE: Wenn du dich mit POKéMON\n"
	.string "beschäftigst und Erfahrungen\p"
	.string "sammelst, wirst du mit Sicherheit ein\n"
	.string "sehr guter TRAINER!\p"
	.string "Mein Kind, {RIVAL}, studiert ebenfalls\n"
	.string "POKéMON und hilft mir dabei sehr.\p"
	.string "{PLAYER}{KUN}, meinst du nicht, es wäre eine\n"
	.string "gute Idee, wenn du dich mit {RIVAL}\l"
	.string "triffst?$"

LittlerootTown_ProfessorBirchsLab_Text_GetRivalToTeachYou:
	.string "PROF. LUNTE: Großartig!\n"
	.string "{RIVAL} wird sich auch sehr freuen.\p"
	.string "{RIVAL} soll dir beibringen, was es\n"
	.string "bedeutet, ein TRAINER zu sein.$"

LittlerootTown_ProfessorBirchsLab_Text_DontBeThatWay:
	.string "PROF. LUNTE: Ach, sei doch nicht so!\n"
	.string "Du solltest dich wirklich mit meinem\l"
	.string "Sprössling treffen!$"

LittlerootTown_ProfessorBirchsLab_Text_BirchRivalGoneHome:
	.string "PROF. LUNTE: {RIVAL}? {RIVAL} ist,\n"
	.string "glaube ich, nach Hause gegangen.\p"
	.string "Oder das Kind krabbelt mal wieder\n"
	.string "irgendwo durch hohes Gras…\p"
	.string "Wenn du und deine POKéMON müde\n"
	.string "sind, dann ruht euch zu Hause aus.$"

LittlerootTown_ProfessorBirchsLab_Text_HeardYouBeatRivalTakePokedex:
	.string "PROF. LUNTE: Oh, hallo, {PLAYER}{KUN}!\p"
	.string "Ich habe gehört, du hast {RIVAL} \n"
	.string "besiegt! Super! Das war dein erster\l"
	.string "Kampf gegen einen TRAINER!\p"
	.string "{RIVAL} hilft mir schon sehr lange bei\n"
	.string "meinen Forschungen.\p"
	.string "{RIVAL} besitzt eine respektable\n"
	.string "Geschichte als TRAINER.\p"
	.string "Hier, das hilft mir bei meinen For-\n"
	.string "schungen. Aber ich denke, du kannst\l"
	.string "den POKéDEX auch gebrauchen.$"

LittlerootTown_ProfessorBirchsLab_Text_ReceivedPokedex:
	.string "{PLAYER} erhält den POKéDEX!$"

LittlerootTown_ProfessorBirchsLab_Text_ExplainPokedex:
	.string "PROF. LUNTE: Der POKéDEX ist ein hoch\n"
	.string "entwickeltes, technisches Gerät, das\l"
	.string "automatisch jedes POKéMON, das du\l"
	.string "siehst oder fängst, registriert.\p"
	.string "{RIVAL} geht nie ohne ihn aus dem Haus.\p"
	.string "Immer, wenn mein Kind ein seltenes\n"
	.string "POKéMON fängt, kommt es und\l"
	.string "zeigt mir den Eintrag im POKéDEX,\l"
	.string "während ich draußen forsche.$"

LittlerootTown_ProfessorBirchsLab_Text_CountlessPokemonAwait:
	.string "PROF. LUNTE: Unzählige POKéMON erwarten\n"
	.string "dich bereits.\p"
	.string "Hach, ich muss jetzt auch dringend\n"
	.string "wieder meinen Forschungen nachgehen.$"

LittlerootTown_ProfessorBirchsLab_Text_MayGotPokedexTooTakeThese:
	.string "MAIKE: Oh, wow, {PLAYER}{KUN}!\n"
	.string "Jetzt hast du auch einen POKéDEX!\p"
	.string "Das ist ja toll! Genau wie ich!\n"
	.string "Ich habe hier etwas für dich!$"

LittlerootTown_ProfessorBirchsLab_Text_CatchCutePokemonWithPokeBalls:
	.string "MAIKE: Es macht unheimlich viel Spaß, all\n"
	.string "die verschiedenen POKéMON zu fangen!\p"
	.string "Ich schaue mich wirklich überall um,\n"
	.string "denn ich will die unterschiedlichsten\l"
	.string "POKéMON fangen.\p"
	.string "Sobald ich niedliche POKéMON entdecke,\n"
	.string "fange ich sie mit POKéBÄLLen.$"

LittlerootTown_ProfessorBirchsLab_Text_OhYourBagsFull:
	.string "Oh! Dein BEUTEL ist voll.$"

LittlerootTown_ProfessorBirchsLab_Text_MayWhereShouldIGoNext:
	.string "MAIKE: Ich frage mich, wo ich jetzt nach\n"
	.string "weiteren POKéMON suchen soll.$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanGotPokedexTooTakeThese:
	.string "BRIX: Ach…\n"
	.string "Du hast auch einen POKéDEX.\p"
	.string "Na, dann.\n"
	.string "Ich gebe dir dies.$"

LittlerootTown_ProfessorBirchsLab_Text_CatchCoolPokemonWithPokeBalls:
	.string "BRIX: Weißt du, je mehr POKéMON du\n"
	.string "besitzt, desto mehr Spaß macht es.\p"
	.string "Ich reise viel umher, um die unter-\n"
	.string "schiedlichsten POKéMON zu finden.\p"
	.string "Und wenn ich ein cooles POKéMON sehe,\n"
	.string "versuche ich natürlich, es zu fangen.$"

LittlerootTown_ProfessorBirchsLab_Text_HeyYourBagsFull:
	.string "Hey, dein BEUTEL ist voll.$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanWhereShouldIGoNext:
	.string "BRIX: Und wo soll ich jetzt mal nach\n"
	.string "POKéMON suchen?$"

LittlerootTown_ProfessorBirchsLab_Text_SeriousLookingMachine:
	.string "Das ist eine kompliziert aussehende\n"
	.string "Maschine. Der PROF wird sie für seine\l"
	.string "Forschungen brauchen…$"

LittlerootTown_ProfessorBirchsLab_Text_PCUsedForResearch:
	.string "Ein PC, der in der Forschung eingesetzt\n"
	.string "wird. Besser nicht damit spielen!$"

LittlerootTown_ProfessorBirchsLab_Text_CrammedWithBooksOnPokemon:
	.string "Es ist voll mit Büchern über POKéMON.$"

LittlerootTown_ProfessorBirchsLab_Text_BookTooHardToRead:
	.string "Dieses Buch ist viel zu kompliziert…$"

LittlerootTown_ProfessorBirchsLab_Text_OtherRegionsUpgradeToNational:
	.string "PROF. LUNTE: Nun…\p"
	.string "{PLAYER}{KUN} und {RIVAL}, ich hatte euch\n"
	.string "gebeten, mir bei meinen POKéMON-\l"
	.string "Studien zu helfen.\p"
	.string "Dank eurer Hilfe kommen neue Fakten\n"
	.string "ans Tageslicht.\p"
	.string "Scheinbar sind in der HOENN-Region\n"
	.string "auch PKMN anderer Regionen ansässig.\p"
	.string "Das ist auch ein Beweis, wie reich die\n"
	.string "Natur in HOENN ist.\p"
	.string "Daher ist es sinnvoll, wenn ich eure\n"
	.string "POKéDEXe mit dem NATIONALEN MODUS\l"
	.string "ausrüste.\p"
	.string "Gebt mir mal eure POKéDEXe.$"

LittlerootTown_ProfessorBirchsLab_Text_MayUpgradeSoCool:
	.string "MAIKE: Hihihi!\p"
	.string "Ich finde es total cool, dass mein\n"
	.string "POKéDEX auch verbessert wird!\p"
	.string "Dank dir, {PLAYER}{KUN}! Denn du hast so\n"
	.string "viele POKéMON gefangen!$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanYouCanThankMe:
	.string "BRIX: Ich bin durch ganz HOENN gereist\n"
	.string "und habe die POKéMON untersucht.\p"
	.string "Dank mir bekommen wir beide jetzt den\n"
	.string "NATIONALEN MODUS.\p"
	.string "Ja ja, heute ist dein Glückstag,\n"
	.string "{PLAYER}!$"

LittlerootTown_ProfessorBirchsLab_Text_OkayAllDone:
	.string "PROF. LUNTE: Okay, fertig!$"

LittlerootTown_ProfessorBirchsLab_Text_PokedexUpgradedToNational:
	.string "Der POKéDEX von {PLAYER} wurde mit dem\n"
	.string "NATIONALEN MODUS ausgerüstet.$"

LittlerootTown_ProfessorBirchsLab_Text_GrassyPatchWaiting2:
	.string "PROF. LUNTE: Vergiss nicht! Du bist der\n"
	.string "CHAMP, aber deine POKéMON-Reise ist\l"
	.string "noch lange nicht zu Ende.\p"
	.string "Die Straße namens POKéMON findet\n"
	.string "niemals ein Ende.\p"
	.string "Irgendwo gibt es hohes Gras, das auf\n"
	.string "dich wartet.$"

LittlerootTown_ProfessorBirchsLab_Text_MayTakeBreakFromFieldwork:
	.string "MAIKE: Ich glaube, ich gönne mir eine\n"
	.string "kurze Pause von der Arbeit draußen.\p"
	.string "Ich werde dem PROF hier ein bisschen\n"
	.string "helfen.$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanTakeBreakFromFieldwork:
	.string "BRIX: Ich glaube, ich gönne mir eine\n"
	.string "kurze Pause von der Arbeit draußen.\p"
	.string "Ich werde dem PROF hier ein bisschen\n"
	.string "helfen.$"

LittlerootTown_ProfessorBirchsLab_Text_CompletedDexChoosePokemon:
	.string "PROF. LUNTE: Oh, {PLAYER}{KUN}!\n"
	.string "Lass mich einen Blick auf deinen\l"
	.string "POKéDEX werfen.\p"
	.string "… … … … …\n"
	.string "…\l"
	.string "… … … … …\l"
	.string "…\p"
	.string "Ja, es besteht kein Zweifel.\p"
	.string "Dein POKéDEX der HOENN-Region ist\n"
	.string "vollständig!\p"
	.string "Das ist mehr als beeindruckend.\p"
	.string "Ich habe ein Geschenk für dich.\p"
	.string "Nimm es als Anerkennung der\n"
	.string "fantastischen Arbeit, die du geleistet\l"
	.string "hast.\p"
	.string "Ich schenke dir ein seltenes POKéMON,\n"
	.string "das nur in einer anderen Region zu\l"
	.string "finden ist.\p"
	.string "Such dir eines von diesen drei POKéMON\n"
	.string "aus.$"

LittlerootTown_ProfessorBirchsLab_Text_CanHaveAnyOneOfRarePokemon:
	.string "PROF. LUNTE: Dies sind seltene POKéMON,\n"
	.string "die in anderen Regionen beheimatet\l"
	.string "sind.\p"
	.string "Such dir eines von den drei POKéMON\n"
	.string "aus.$"

LittlerootTown_ProfessorBirchsLab_Text_YoullTakeCyndaquil:
	.string "PROF. LUNTE: Das FEUER-POKéMON\n"
	.string "FEURIGEL hat dein Interesse geweckt?\p"
	.string "Du bist clever wie immer!\p"
	.string "Du möchtest FEURIGEL haben?$"

LittlerootTown_ProfessorBirchsLab_Text_YoullTakeTotodile:
	.string "PROF. LUNTE: Das WASSER-POKéMON\n"
	.string "KARNIMANI hat dein Interesse geweckt?\p"
	.string "Eine gute Wahl!\p"
	.string "Du möchtest KARNIMANI haben?$"

LittlerootTown_ProfessorBirchsLab_Text_YoullTakeChikorita:
	.string "PROF. LUNTE: Das PFLANZEN-POKéMON\n"
	.string "ENDIVIE hat dein Interesse geweckt?\p"
	.string "Du weißt, was gut für dich ist!\p"
	.string "Du möchtest ENDIVIE haben?$"

LittlerootTown_ProfessorBirchsLab_Text_TakeYourTimeAllInvaluable:
	.string "PROF. LUNTE: Lass dir Zeit, bevor du dich\n"
	.string "entscheidest.\p"
	.string "Es sind alles POKéMON von\n"
	.string "unschätzbarem Wert.$"

@ Unused
LittlerootTown_ProfessorBirchsLab_Text_PickedFinePokemon:
	.string "PROF. BIRCH: I see!\n"
	.string "You picked a fine POKéMON!$"

LittlerootTown_ProfessorBirchsLab_Text_ReceivedJohtoStarter:
	.string "{PLAYER} erhält\n"
	.string "{STR_VAR_1} von PROF. LUNTE!$"

@ Unused
LittlerootTown_ProfessorBirchsLab_Text_NicknameJohtoStarter:
	.string "Want to give a nickname to\n"
	.string "the {STR_VAR_1} you received?$"

LittlerootTown_ProfessorBirchsLab_Text_GrassyPatchWaiting:
	.string "PROF. LUNTE: Vergiss nicht! Dein\n"
	.string "HOENN-POKéDEX ist vollständig.\p"
	.string "Die Straße namens POKéMON findet\n"
	.string "niemals ein Ende.\p"
	.string "Irgendwo gibt es hohes Gras, das auf\n"
	.string "dich wartet.$"

LittlerootTown_ProfessorBirchsLab_Text_BetterLeaveOthersAlone:
	.string "Du hast das POKéMON erhalten.\n"
	.string "Lass die anderen lieber in Ruhe.$"

@ Unused
LittlerootTown_ProfessorBirchsLab_Text_DontHaveAnyRoomForPokemon:
	.string "Oh, you don’t have any room for\n"
	.string "this POKéMON.$"

LittlerootTown_ProfessorBirchsLab_Text_MayWhatNextImStayingHere:
	.string "MAIKE: {PLAYER}{KUN}, jetzt…\n"
	.string "Was wirst du jetzt tun?\p"
	.string "Wirst du weiter in Kämpfen antreten\n"
	.string "und deine Fähigkeiten verbessern?\p"
	.string "Oder versuchst du, den NATIONALEN\n"
	.string "POKéDEX vollständig zu bekommen?\p"
	.string "Ich werde hier bleiben und dem PROF\n"
	.string "helfen.$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanPreferCollectingSlowly:
	.string "BRIX: Statt nur POKéMON zu sammeln,\n"
	.string "konzentriere ich mich lieber auf das\l"
	.string "Aufziehen eines bestimmten POKéMON.$"

LittlerootTown_ProfessorBirchsLab_Text_MayHaveYouGoneToBattleFrontier:
	.string "MAIKE: Oh, hi {PLAYER}{KUN}!\n"
	.string "Hast du schon die BATTLE FRONTIER\l"
	.string "besucht?$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanHaveYouGoneToBattleFrontier:
	.string "BRIX: Hey, {PLAYER}!\n"
	.string "Hast du schon die BATTLE FRONTIER\l"
	.string "besucht?$"

LittlerootTown_ProfessorBirchsLab_Text_ScottAboardSSTidalCall:
	.string "… … … … …\n"
	.string "…\l"
	.string "… … … … …Piep!\p"
	.string "SCOTT: Hallo {PLAYER}!\n"
	.string "Ich bin’s, SCOTT.\p"
	.string "Ich bin auf der MS TIDE. Auf See zu\n"
	.string "sein ist einfach großartig!\p"
	.string "Übrigens…\p"
	.string "Ich würde dich gerne an einen\n"
	.string "bestimmten Ort einladen.\p"
	.string "Wenn du interessiert bist, dann\n"
	.string "nimm entweder in SLATEPORT oder\l"
	.string "LILYCOVE die Fähre.\p"
	.string "Alles Weitere besprechen wir, wenn\n"
	.string "wir uns an Bord treffen. Bis dann!\p"
	.string "… … … … …\n"
	.string "…\l"
	.string "… … … … …Klick!$"

LittlerootTown_ProfessorBirchsLab_Text_LunteChooseTwo:
	.string "Ouh NJIERI!\p"
	.string "Du dörfsch der 2 POKEMON\n"
	.string "ussueche und denn für mich\l"
	.string "de POKEDEX vollmache.$"

LittlerootTown_ProfessorBirchsLab_Text_LunteAfterChoice:
	.string "Sehr gueti Wahl!\p"
	.string "Jetzt nimm no de POKEDEX\n"
	.string "und denn gib ihm!$"

LittlerootTown_ProfessorBirchsLab_Text_ObtainedPokedex:
	.string "{PLAYER} het de POKEDEX\n"
	.string "erhalte!$"

LittlerootTown_ProfessorBirchsLab_Text_LunteGo:
	.string "LUNTE: Und jetzt verreis!\n"
	.string "Zeig dere Welt, wer de NJIERI isch!$"

LittlerootTown_ProfessorBirchsLab_Text_AlreadyGotStarters:
	.string "LUNTE: Du hesch dini POKEMON\n"
	.string "und de POKEDEX.\p"
	.string "Jetzt gib ihm!$"

LittlerootTown_ProfessorBirchsLab_Text_NotEnoughPokemon:
	.string "LUNTE: Bro, du muesch genau\n"
	.string "2 POKEMON ussueche.$"

LittlerootTown_ProfessorBirchsLab_Text_ChooseCharmander:
	.string "GLUMANDA waehle?$"

LittlerootTown_ProfessorBirchsLab_Text_ChooseCyndaquil:
	.string "FEURIGEL waehle?$"

LittlerootTown_ProfessorBirchsLab_Text_ChooseTepig:
	.string "FLOINK waehle?$"

LittlerootTown_ProfessorBirchsLab_Text_ChooseTurtwig:
	.string "CHELAST waehle?$"

LittlerootTown_ProfessorBirchsLab_Text_ChooseTreecko:
	.string "GECKARBOR waehle?$"

LittlerootTown_ProfessorBirchsLab_Text_ChooseSnivy:
	.string "SERPIFEU waehle?$"

LittlerootTown_ProfessorBirchsLab_Text_ChooseSquirtle:
	.string "SCHIGGY waehle?$"

LittlerootTown_ProfessorBirchsLab_Text_ChooseMudkip:
	.string "HYDROPI waehle?$"

LittlerootTown_ProfessorBirchsLab_Text_ChoosePiplup:
	.string "PLINFA waehle?$"