PetalburgCity_Gym_MapScripts::
	map_script MAP_SCRIPT_ON_LOAD, PetalburgCity_Gym_OnLoad
	map_script MAP_SCRIPT_ON_TRANSITION, PetalburgCity_Gym_OnTransition
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PetalburgCity_Gym_OnWarp
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PetalburgCity_Gym_OnFrame
	.byte 0

PetalburgCity_Gym_OnLoad:
	goto_if_eq VAR_PETALBURG_GYM_STATE, 6, PetalburgCity_Gym_EventScript_OpenUnlockedDoors
	call_if_ge VAR_PETALBURG_GYM_STATE, 7, PetalburgCity_Gym_EventScript_UnlockAllDoors
	end

@ NOTE: Strength and OHKO rooms are misleading. Both are more accurately Critical-Hit
PetalburgCity_Gym_EventScript_OpenUnlockedDoors::
	setvar VAR_0x8005, 1
	call PetalburgCity_Gym_EventScript_OpenGymEntranceDoors
	call_if_defeated TRAINER_RANDALL, PetalburgCity_Gym_EventScript_OpenSpeedRoomDoors
	call_if_defeated TRAINER_MARY, PetalburgCity_Gym_EventScript_OpenAccuracyRoomDoors
	call_if_defeated TRAINER_PARKER, PetalburgCity_Gym_EventScript_OpenConfusionRoomDoors
	call_if_defeated TRAINER_ALEXIA, PetalburgCity_Gym_EventScript_OpenDefenseRoomDoors
	call_if_defeated TRAINER_GEORGE, PetalburgCity_Gym_EventScript_OpenRecoveryRoomDoors
	call_if_defeated TRAINER_JODY, PetalburgCity_Gym_EventScript_OpenStrengthRoomDoors
	call_if_defeated TRAINER_BERKE, PetalburgCity_Gym_EventScript_OpenOHKORoomDoors
	end

PetalburgCity_Gym_EventScript_UnlockAllDoors::
	setvar VAR_0x8005, 1
	call PetalburgCity_Gym_EventScript_OpenGymEntranceDoors
	call PetalburgCity_Gym_EventScript_OpenSpeedRoomDoors
	call PetalburgCity_Gym_EventScript_OpenAccuracyRoomDoors
	call PetalburgCity_Gym_EventScript_OpenConfusionRoomDoors
	call PetalburgCity_Gym_EventScript_OpenDefenseRoomDoors
	call PetalburgCity_Gym_EventScript_OpenRecoveryRoomDoors
	call PetalburgCity_Gym_EventScript_OpenStrengthRoomDoors
	call PetalburgCity_Gym_EventScript_OpenOHKORoomDoors
	return

PetalburgCity_Gym_OnTransition:
	call_if_eq VAR_PETALBURG_GYM_STATE, 1, PetalburgCity_Gym_EventScript_MoveWallyToEntrance
	call_if_lt VAR_PETALBURG_GYM_STATE, 6, PetalburgCity_Gym_EventScript_MoveNormanToEntrance
	call_if_set FLAG_SYS_GAME_CLEAR, PetalburgCity_Gym_EventScript_CheckNormanForRematch
	end

PetalburgCity_Gym_EventScript_MoveWallyToEntrance::
	setobjectxyperm LOCALID_PETALBURG_GYM_WALLY, 5, 108
	return

PetalburgCity_Gym_EventScript_MoveNormanToEntrance::
	setobjectxyperm LOCALID_PETALBURG_GYM_NORMAN, 4, 107
	return

PetalburgCity_Gym_EventScript_CheckNormanForRematch::
	setorcopyvar VAR_TRAINER_BATTLE_OPPONENT_A, TRAINER_NORMAN_1
	specialvar VAR_RESULT, IsTrainerReadyForRematch
	goto_if_eq VAR_RESULT, TRUE, PetalburgCity_Gym_EventScript_DontMoveNormanToFront
	goto_if_eq VAR_PETALBURG_GYM_STATE, 8, PetalburgCity_Gym_EventScript_DontMoveNormanToFront
	setobjectxyperm LOCALID_PETALBURG_GYM_NORMAN, 4, 107
	return

PetalburgCity_Gym_EventScript_DontMoveNormanToFront::
	setvar VAR_PETALBURG_GYM_STATE, 8
	end

PetalburgCity_Gym_OnWarp:
	map_script_2 VAR_PETALBURG_GYM_STATE, 1, PetalburgCity_Gym_EventScript_TurnPlayerNorth
	.2byte 0

PetalburgCity_Gym_EventScript_TurnPlayerNorth::
	turnobject LOCALID_PLAYER, DIR_NORTH
	end

PetalburgCity_Gym_OnFrame:
	map_script_2 VAR_PETALBURG_GYM_STATE, 1, PetalburgCity_Gym_EventScript_ReturnFromWallyTutorial
	.2byte 0

PetalburgCity_Gym_EventScript_ReturnFromWallyTutorial::
	lockall
	msgbox PetalburgCity_Gym_Text_DadSoDidItWorkOut, MSGBOX_DEFAULT
	msgbox PetalburgCity_Gym_Text_WallyThankYouBye, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterDown
	applymovement LOCALID_PETALBURG_GYM_WALLY, PetalburgCity_Gym_Movement_WallyExitGym
	waitmovement 0
	playse SE_EXIT
	removeobject LOCALID_PETALBURG_GYM_WALLY
	setflag FLAG_HIDE_PETALBURG_CITY_WALLY
	delay 30
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	msgbox PetalburgCity_Gym_Text_DadGoCollectBadges, MSGBOX_DEFAULT
	setvar VAR_PETALBURG_GYM_STATE, 2
	releaseall
	end

PetalburgCity_Gym_Movement_WallyExitGym:
	walk_down
	walk_down
	walk_down
	delay_16
	step_end

PetalburgCity_Gym_EventScript_Norman::
	lock
	faceplayer
	goto_if_set FLAG_BADGE01_GET, PetalburgCity_Gym_EventScript_NormanPostBattle
	goto PetalburgCity_Gym_EventScript_NormanBattle
	end

PetalburgCity_Gym_EventScript_BeginWallyTutorialSouth::
	setvar VAR_0x8008, 0
	goto PetalburgCity_Gym_EventScript_BeginWallyTutorial
	end

PetalburgCity_Gym_EventScript_BeginWallyTutorialNorth::
	setvar VAR_0x8008, 1
	goto PetalburgCity_Gym_EventScript_BeginWallyTutorial
	end

PetalburgCity_Gym_EventScript_BeginWallyTutorialWest::
	setvar VAR_0x8008, 2
	goto PetalburgCity_Gym_EventScript_BeginWallyTutorial
	end

PetalburgCity_Gym_EventScript_BeginWallyTutorialEast::
	setvar VAR_0x8008, 3
	goto PetalburgCity_Gym_EventScript_BeginWallyTutorial
	end

PetalburgCity_Gym_EventScript_BeginWallyTutorial::
	addobject LOCALID_PETALBURG_GYM_WALLY
	playse SE_DOOR
	call_if_eq VAR_0x8008, 0, PetalburgCity_Gym_EventScript_WallyArriveSouth
	call_if_eq VAR_0x8008, 1, PetalburgCity_Gym_EventScript_WallyArriveNorth
	call_if_eq VAR_0x8008, 2, PetalburgCity_Gym_EventScript_WallyArriveWestEast
	call_if_eq VAR_0x8008, 3, PetalburgCity_Gym_EventScript_WallyArriveWestEast
	msgbox PetalburgCity_Gym_Text_WallyIdLikeAPokemon, MSGBOX_DEFAULT
	msgbox PetalburgCity_Gym_Text_DadOhYoureWallyRight, MSGBOX_DEFAULT
	msgbox PetalburgCity_Gym_Text_WallyIveNeverCaughtAPokemon, MSGBOX_DEFAULT
	msgbox PetalburgCity_Gym_Text_DadHmISee, MSGBOX_DEFAULT
	call_if_eq VAR_0x8008, 0, PetalburgCity_Gym_EventScript_NormanAddressPlayerSouth
	call_if_eq VAR_0x8008, 1, PetalburgCity_Gym_EventScript_NormanAddressPlayerNorth
	call_if_eq VAR_0x8008, 2, PetalburgCity_Gym_EventScript_NormanAddressPlayerWest
	call_if_eq VAR_0x8008, 3, PetalburgCity_Gym_EventScript_NormanAddressPlayerEast
	msgbox PetalburgCity_Gym_Text_DadPlayerGoWithWally, MSGBOX_DEFAULT
	call_if_eq VAR_0x8008, 0, PetalburgCity_Gym_EventScript_NormanAddressWallySouth
	call_if_eq VAR_0x8008, 1, PetalburgCity_Gym_EventScript_NormanAddressWallyNorth
	call_if_eq VAR_0x8008, 2, PetalburgCity_Gym_EventScript_NormanAddressWallyWest
	call_if_eq VAR_0x8008, 3, PetalburgCity_Gym_EventScript_NormanAddressWallyEast
	msgbox PetalburgCity_Gym_Text_IllLoanYouMyZigzagoon, MSGBOX_DEFAULT
	msgbox PetalburgCity_Gym_Text_WallyThankYouAndDadGivesPokeBall, MSGBOX_DEFAULT
	msgbox PetalburgCity_Gym_Text_WallyOhWowThankYou, MSGBOX_DEFAULT
	call_if_eq VAR_0x8008, 0, PetalburgCity_Gym_EventScript_NormanFaceDoorSouth
	call_if_eq VAR_0x8008, 1, PetalburgCity_Gym_EventScript_NormanFaceDoorNorth
	call_if_eq VAR_0x8008, 2, PetalburgCity_Gym_EventScript_NormanFaceDoorWest
	call_if_eq VAR_0x8008, 3, PetalburgCity_Gym_EventScript_NormanFaceDoorEast
	call_if_eq VAR_0x8008, 0, PetalburgCity_Gym_EventScript_WallyFacePlayer
	call_if_eq VAR_0x8008, 1, PetalburgCity_Gym_EventScript_WallyFaceDown
	call_if_eq VAR_0x8008, 2, PetalburgCity_Gym_EventScript_WallyFacePlayer
	call_if_eq VAR_0x8008, 3, PetalburgCity_Gym_EventScript_WallyFacePlayer
	msgbox PetalburgCity_Gym_Text_WouldYouReallyComeWithMe, MSGBOX_DEFAULT
	closemessage
	setflag FLAG_DONT_TRANSITION_MUSIC
	playbgm MUS_FOLLOW_ME, FALSE
	call_if_eq VAR_0x8008, 0, PetalburgCity_Gym_EventScript_ExitGymWithWallySouth
	call_if_eq VAR_0x8008, 1, PetalburgCity_Gym_EventScript_ExitGymWithWallyNorth
	call_if_eq VAR_0x8008, 2, PetalburgCity_Gym_EventScript_ExitGymWithWallyWest
	call_if_eq VAR_0x8008, 3, PetalburgCity_Gym_EventScript_ExitGymWithWallyEast
	removeobject LOCALID_PETALBURG_GYM_WALLY
	setflag FLAG_HIDE_PETALBURG_CITY_WALLYS_MOM
	setvar VAR_PETALBURG_GYM_STATE, 1
	setvar VAR_PETALBURG_CITY_STATE, 2
	clearflag FLAG_HIDE_PETALBURG_CITY_WALLY
	clearflag FLAG_HIDE_PETALBURG_GYM_WALLY
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_RIVAL
	special InitBirchState
	warp MAP_PETALBURG_CITY, 15, 8
	waitstate
	release
	end

PetalburgCity_Gym_EventScript_WallyArriveSouth::
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterDown
	applymovement LOCALID_PETALBURG_GYM_WALLY, PetalburgCity_Gym_Movement_WallyArrive
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_WallyArriveNorth::
	applymovement LOCALID_PETALBURG_GYM_WALLY, PetalburgCity_Gym_Movement_WallyArriveNorth
	waitmovement 0
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterRight
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_WallyArriveWestEast::
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterDown
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterDown
	applymovement LOCALID_PETALBURG_GYM_WALLY, PetalburgCity_Gym_Movement_WallyArrive
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_ExitGymWithWallySouth::
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterDown
	applymovement LOCALID_PETALBURG_GYM_WALLY, PetalburgCity_Gym_Movement_WallyExitSouthWest
	applymovement LOCALID_PLAYER, PetalburgCity_Gym_Movement_PlayerExitWithWallySouth
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_ExitGymWithWallyNorth::
	applymovement LOCALID_PETALBURG_GYM_WALLY, PetalburgCity_Gym_Movement_WallyExitNorth
	applymovement LOCALID_PLAYER, PetalburgCity_Gym_Movement_PlayerExitWithWallyNorth
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_ExitGymWithWallyWest::
	applymovement LOCALID_PETALBURG_GYM_WALLY, PetalburgCity_Gym_Movement_WallyExitSouthWest
	applymovement LOCALID_PLAYER, PetalburgCity_Gym_Movement_PlayerExitWithWallyWest
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_ExitGymWithWallyEast::
	applymovement LOCALID_PETALBURG_GYM_WALLY, PetalburgCity_Gym_Movement_WallyExitEast
	applymovement LOCALID_PLAYER, PetalburgCity_Gym_Movement_PlayerExitWithWallyEast
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_NormanAddressPlayerSouth::
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_NormanAddressPlayerNorth::
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterDown
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_NormanAddressPlayerWest::
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterRight
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_NormanAddressPlayerEast::
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterLeft
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_NormanAddressWallySouth::
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_NormanAddressWallyNorth::
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_NormanAddressWallyWest::
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_NormanAddressWallyEast::
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_WallyFacePlayer::
	applymovement LOCALID_PETALBURG_GYM_WALLY, Common_Movement_FacePlayer
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_WallyFaceDown::
	applymovement LOCALID_PETALBURG_GYM_WALLY, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_NormanNoBadges::
	msgbox PetalburgCity_Gym_Text_NormanGoToRustboro, MSGBOX_DEFAULT
	release
	end

PetalburgCity_Gym_EventScript_NormanOneBadge::
	msgbox PetalburgCity_Gym_Text_NormanGoToDewford, MSGBOX_DEFAULT
	release
	end

PetalburgCity_Gym_EventScript_NormanTwoBadges::
	msgbox PetalburgCity_Gym_Text_YouHaveGottenStronger, MSGBOX_DEFAULT
	release
	end

PetalburgCity_Gym_EventScript_NormanThreeBadges::
	msgbox PetalburgCity_Gym_Text_YouHaveGottenStronger, MSGBOX_DEFAULT
	release
	end

PetalburgCity_Gym_EventScript_NormanFaceDoorSouth::
	return

@ For all other NormanFaceDoorX, Norman is already facing the door from NormanAddressWallyX
PetalburgCity_Gym_EventScript_NormanFaceDoorNorth::
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_NormanFaceDoorWest::
	return

PetalburgCity_Gym_EventScript_NormanFaceDoorEast::
	return

PetalburgCity_Gym_EventScript_NormanPostBattle::
	msgbox PetalburgCity_Gym_Text_SimonGoDubi, MSGBOX_DEFAULT
	release
	end

PetalburgCity_Gym_EventScript_GiveFacade2::
	call PetalburgCity_Gym_EventScript_GiveFacade
	release
	end

PetalburgCity_Gym_EventScript_NormanRematch::
	trainerbattle_rematch_double TRAINER_NORMAN_1, PetalburgCity_Gym_Text_NormanPreRematch, PetalburgCity_Gym_Text_NormanRematchDefeat, PetalburgCity_Gym_Text_NormanRematchNeedTwoMons
	msgbox PetalburgCity_Gym_Text_NormanPostRematch, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_ShouldGiveEnigmaBerry::
	specialvar VAR_RESULT, IsEnigmaBerryValid
	goto_if_eq VAR_RESULT, FALSE, PetalburgCity_Gym_EventScript_DontGiveEnigmaBerry
	checkitem ITEM_ENIGMA_BERRY_E_READER
	goto_if_eq VAR_RESULT, TRUE, PetalburgCity_Gym_EventScript_DontGiveEnigmaBerry
	checkpcitem ITEM_ENIGMA_BERRY_E_READER
	goto_if_eq VAR_RESULT, TRUE, PetalburgCity_Gym_EventScript_DontGiveEnigmaBerry
	goto_if_eq VAR_ENIGMA_BERRY_AVAILABLE, 0, PetalburgCity_Gym_EventScript_DontGiveEnigmaBerry
	msgbox PetalburgCity_Gym_Text_GiveEnigmaBerry, MSGBOX_DEFAULT
	setvar VAR_RESULT, TRUE
	return

PetalburgCity_Gym_EventScript_DontGiveEnigmaBerry::
	setvar VAR_RESULT, FALSE
	return

PetalburgCity_Gym_EventScript_GiveEnigmaBerry::
	giveitem ITEM_ENIGMA_BERRY_E_READER
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
	setvar VAR_ENIGMA_BERRY_AVAILABLE, 0
	release
	end

PetalburgCity_Gym_EventScript_NormanBattle::
	trainerbattle_double TRAINER_NORMAN_1, PetalburgCity_Gym_Text_SimonIntro, PetalburgCity_Gym_Text_SimonDefeat, PetalburgCity_Gym_Text_SimonNotEnoughMons
	message PetalburgCity_Gym_Text_ReceivedFirstBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	setflag FLAG_DEFEATED_PETALBURG_GYM
	setflag FLAG_BADGE01_GET
	setvar VAR_PETALBURG_GYM_STATE, 7
	msgbox PetalburgCity_Gym_Text_SimonAfterBadge, MSGBOX_DEFAULT
	release
	end

PetalburgCity_Gym_EventScript_GiveFacade::
	giveitem ITEM_TM_FACADE
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_BagIsFull
	setflag FLAG_RECEIVED_TM_FACADE
	msgbox PetalburgCity_Gym_Text_ExplainFacade, MSGBOX_DEFAULT
	return

PetalburgCity_Gym_EventScript_WallysDadArrivesNorth::
	setvar VAR_0x8008, 1
	goto PetalburgCity_Gym_EventScript_WallysDadArrives

PetalburgCity_Gym_EventScript_WallysDadArrivesEast::
	setvar VAR_0x8008, 2
	goto PetalburgCity_Gym_EventScript_WallysDadArrives

PetalburgCity_Gym_EventScript_WallysDadArrivesWest::
	setvar VAR_0x8008, 3
	goto PetalburgCity_Gym_EventScript_WallysDadArrives

PetalburgCity_Gym_EventScript_WallysDadArrives::
	applymovement LOCALID_PETALBURG_GYM_WALLYS_DAD, PetalburgCity_Gym_Movement_WallysDadEnterGym
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_PETALBURG_GYM_WALLYS_DAD, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_PETALBURG_GYM_WALLYS_DAD, Common_Movement_Delay48
	waitmovement 0
	delay 10
	call_if_eq VAR_0x8008, 1, PetalburgCity_Gym_EventScript_WallysDadApproachPlayerNorth
	call_if_eq VAR_0x8008, 2, PetalburgCity_Gym_EventScript_WallysDadApproachPlayerEast
	call_if_eq VAR_0x8008, 3, PetalburgCity_Gym_EventScript_WallysDadApproachPlayerWest
	msgbox PetalburgCity_Gym_Text_PleaseComeWithMe, MSGBOX_DEFAULT
	closemessage
	delay 20
	call_if_eq VAR_0x8008, 1, PetalburgCity_Gym_EventScript_WallysDadFaceNormanNorth
	call_if_eq VAR_0x8008, 2, PetalburgCity_Gym_EventScript_WallysDadFaceNormanEast
	call_if_eq VAR_0x8008, 3, PetalburgCity_Gym_EventScript_WallysDadFaceNormanWest
	msgbox PetalburgCity_Gym_Text_LetMeBorrowPlayer, MSGBOX_DEFAULT
	closemessage
	setflag FLAG_DONT_TRANSITION_MUSIC
	playbgm MUS_FOLLOW_ME, FALSE
	call_if_eq VAR_0x8008, 1, PetalburgCity_Gym_EventScript_ExitGymWithWallysDadNorth
	call_if_eq VAR_0x8008, 2, PetalburgCity_Gym_EventScript_ExitGymWithWallysDadEast
	call_if_eq VAR_0x8008, 3, PetalburgCity_Gym_EventScript_ExitGymWithWallysDadWest
	removeobject LOCALID_PETALBURG_GYM_WALLYS_DAD
	setvar VAR_PETALBURG_CITY_STATE, 4
	clearflag FLAG_HIDE_PETALBURG_CITY_WALLYS_DAD
	warp MAP_PETALBURG_CITY, 15, 8
	waitstate
	release
	end

PetalburgCity_Gym_EventScript_WallysDadFaceNormanNorth::
	applymovement LOCALID_PETALBURG_GYM_WALLYS_DAD, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_WallysDadFaceNormanEast::
	applymovement LOCALID_PETALBURG_GYM_WALLYS_DAD, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_WallysDadFaceNormanWest::
	applymovement LOCALID_PETALBURG_GYM_WALLYS_DAD, Common_Movement_WalkInPlaceFasterLeft
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_WallysDadApproachPlayerNorth::
	applymovement LOCALID_PETALBURG_GYM_WALLYS_DAD, PetalburgCity_Gym_Movement_WallysDadApproachPlayerNorth
	waitmovement 0
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterLeft
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_WallysDadApproachPlayerEast::
	applymovement LOCALID_PETALBURG_GYM_WALLYS_DAD, PetalburgCity_Gym_Movement_WallysDadApproachPlayerEast
	waitmovement 0
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterDown
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_WallysDadApproachPlayerWest::
	applymovement LOCALID_PETALBURG_GYM_WALLYS_DAD, PetalburgCity_Gym_Movement_WallysDadApproachPlayerWest
	waitmovement 0
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterDown
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_ExitGymWithWallysDadNorth::
	applymovement LOCALID_PETALBURG_GYM_WALLYS_DAD, PetalburgCity_Gym_Movement_WallysDadExitNorth
	applymovement LOCALID_PETALBURG_GYM_NORMAN, Common_Movement_WalkInPlaceFasterDown
	applymovement LOCALID_PLAYER, PetalburgCity_Gym_Movement_PlayerExitWithWallysDadNorth
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_ExitGymWithWallysDadEast::
	applymovement LOCALID_PETALBURG_GYM_WALLYS_DAD, PetalburgCity_Gym_Movement_WallysDadExitEast
	applymovement LOCALID_PLAYER, PetalburgCity_Gym_Movement_PlayerExitWithWallysDadEast
	waitmovement 0
	return

PetalburgCity_Gym_EventScript_ExitGymWithWallysDadWest::
	applymovement LOCALID_PETALBURG_GYM_WALLYS_DAD, PetalburgCity_Gym_Movement_WallysDadExitWest
	applymovement LOCALID_PLAYER, PetalburgCity_Gym_Movement_PlayerExitWithWallysDadWest
	waitmovement 0
	return

PetalburgCity_Gym_Movement_WallysDadExitNorth:
	walk_down
	walk_down
	walk_left
	walk_left
	walk_down
	walk_down
	walk_in_place_faster_up
	delay_8
	walk_in_place_down
	set_invisible
	step_end

PetalburgCity_Gym_Movement_WallysDadExitEast:
	walk_down
	walk_down
	walk_left
	walk_left
	walk_down
	walk_down
	walk_in_place_faster_up
	delay_8
	walk_in_place_down
	set_invisible
	step_end

PetalburgCity_Gym_Movement_WallysDadExitWest:
	walk_down
	walk_down
	walk_left
	walk_left
	walk_left
	walk_left
	walk_down
	walk_down
	walk_in_place_faster_up
	delay_8
	walk_in_place_down
	set_invisible
	step_end

PetalburgCity_Gym_Movement_PlayerExitWithWallysDadNorth:
	delay_16
	walk_down
	walk_down
	walk_left
	walk_left
	walk_down
	walk_down
	step_end

PetalburgCity_Gym_Movement_PlayerExitWithWallysDadEast:
	delay_16
	walk_down
	walk_down
	walk_left
	walk_down
	walk_down
	walk_down
	step_end

PetalburgCity_Gym_Movement_PlayerExitWithWallysDadWest:
	delay_16
	walk_down
	walk_down
	walk_down
	walk_left
	walk_left
	walk_left
	walk_down
	walk_down
	step_end

PetalburgCity_Gym_Movement_WallysDadEnterGym:
	walk_up
	delay_8
	walk_in_place_faster_right
	delay_8
	walk_in_place_faster_left
	delay_16
	walk_in_place_faster_up
	step_end

PetalburgCity_Gym_Movement_WallysDadApproachPlayerNorth:
	walk_right
	walk_right
	walk_up
	walk_up
	walk_up
	walk_in_place_faster_right
	step_end

PetalburgCity_Gym_Movement_WallysDadApproachPlayerEast:
	walk_right
	walk_right
	walk_up
	walk_up
	walk_up
	step_end

PetalburgCity_Gym_Movement_WallysDadApproachPlayerWest:
	walk_right
	walk_right
	walk_up
	walk_up
	walk_right
	walk_right
	walk_up
	step_end

PetalburgCity_Gym_Movement_Unused:
	walk_in_place_faster_up
	delay_16
	delay_16
	delay_16
	delay_16
	delay_16
	delay_8
	walk_in_place_faster_down
	step_end

PetalburgCity_Gym_Movement_WallyArriveNorth:
	delay_16
	walk_up
	delay_16
	delay_8
	walk_up
	walk_right
	walk_up
	walk_up
	walk_in_place_faster_left
	step_end

PetalburgCity_Gym_Movement_WallyArrive:
	delay_16
	walk_up
	delay_16
	delay_8
	walk_up
	walk_up
	step_end

PetalburgCity_Gym_Movement_WallyExitNorth:
	walk_down
	walk_down
	walk_down
	walk_down
	walk_in_place_faster_up
	delay_16
	walk_in_place_down
	step_end

PetalburgCity_Gym_Movement_WallyExitEast:
	walk_down
	walk_down
	walk_right
	walk_down
	walk_in_place_faster_up
	delay_16
	walk_in_place_down
	step_end

PetalburgCity_Gym_Movement_WallyExitSouthWest:
	walk_down
	walk_down
	walk_down
	walk_in_place_faster_up
	delay_16
	walk_in_place_down
	step_end

PetalburgCity_Gym_Movement_PlayerExitWithWallyNorth:
	delay_16
	delay_16
	delay_16
	walk_down
	walk_down
	walk_down
	delay_8
	step_end

PetalburgCity_Gym_Movement_PlayerExitWithWallySouth:
	delay_16
	delay_16
	walk_right
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	delay_8
	step_end

PetalburgCity_Gym_Movement_PlayerExitWithWallyWest:
	delay_16
	delay_16
	walk_down
	walk_down
	walk_down
	walk_down
	delay_8
	step_end

PetalburgCity_Gym_Movement_PlayerExitWithWallyEast:
	walk_in_place_faster_down
	delay_16
	delay_16
	walk_down
	walk_down
	walk_down
	walk_right
	walk_down
	delay_8
	step_end

PetalburgCity_Gym_EventScript_NoAmountOfTrainingIsEnough::
	msgbox PetalburgCity_Gym_Text_DadNoAmountOfTrainingIsEnough, MSGBOX_DEFAULT
	release
	end

PetalburgCity_Gym_EventScript_SpeedRoomDoor::
	lockall
	goto_if_lt VAR_PETALBURG_GYM_STATE, 6, PetalburgCity_Gym_EventScript_DoorLocked
	setvar VAR_0x8008, 7
	setvar VAR_0x8009, 85
	msgbox PetalburgCity_Gym_Text_EnterSpeedRoom, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, PetalburgCity_Gym_EventScript_EnterRoom
	goto_if_eq VAR_RESULT, NO, PetalburgCity_Gym_EventScript_DontEnterRoom
	end

PetalburgCity_Gym_EventScript_EnterRoom::
	closemessage
	delay 30
	warpdoor MAP_PETALBURG_CITY_GYM, VAR_0x8008, VAR_0x8009
	waitstate
	releaseall
	end

PetalburgCity_Gym_EventScript_DontEnterRoom::
	releaseall
	end

PetalburgCity_Gym_EventScript_DoorLocked::
	msgbox PetalburgCity_Gym_Text_DoorAppearsLocked, MSGBOX_DEFAULT
	releaseall
	end

@ VAR_0x8008 and VAR_0x8009 below are the x and y coordinates of the warp
PetalburgCity_Gym_EventScript_AccuracyRoomDoor::
	lockall
	goto_if_lt VAR_PETALBURG_GYM_STATE, 6, PetalburgCity_Gym_EventScript_DoorLocked
	setvar VAR_0x8008, 1
	setvar VAR_0x8009, 98
	msgbox PetalburgCity_Gym_Text_EnterAccuracyRoom, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, PetalburgCity_Gym_EventScript_EnterRoom
	goto_if_eq VAR_RESULT, NO, PetalburgCity_Gym_EventScript_DontEnterRoom
	end

PetalburgCity_Gym_EventScript_ConfusionRoomDoor::
	lockall
	goto_if_not_defeated TRAINER_RANDALL, PetalburgCity_Gym_EventScript_DoorLocked
	setvar VAR_0x8008, 7
	setvar VAR_0x8009, 46
	msgbox PetalburgCity_Gym_Text_EnterConfusionRoom, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, PetalburgCity_Gym_EventScript_EnterRoom
	goto_if_eq VAR_RESULT, NO, PetalburgCity_Gym_EventScript_DontEnterRoom
	end

PetalburgCity_Gym_EventScript_LeftDefenseRoomDoor::
	lockall
	goto_if_not_defeated TRAINER_RANDALL, PetalburgCity_Gym_EventScript_DoorLocked
	setvar VAR_0x8008, 1
	setvar VAR_0x8009, 59
	msgbox PetalburgCity_Gym_Text_EnterDefenseRoom, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, PetalburgCity_Gym_EventScript_EnterRoom
	goto_if_eq VAR_RESULT, NO, PetalburgCity_Gym_EventScript_DontEnterRoom
	end

PetalburgCity_Gym_EventScript_RightDefenseRoomDoor::
	lockall
	goto_if_not_defeated TRAINER_MARY, PetalburgCity_Gym_EventScript_DoorLocked
	setvar VAR_0x8008, 7
	setvar VAR_0x8009, 59
	msgbox PetalburgCity_Gym_Text_EnterDefenseRoom, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, PetalburgCity_Gym_EventScript_EnterRoom
	goto_if_eq VAR_RESULT, NO, PetalburgCity_Gym_EventScript_DontEnterRoom
	end

PetalburgCity_Gym_EventScript_RecoveryRoomDoor::
	lockall
	goto_if_not_defeated TRAINER_MARY, PetalburgCity_Gym_EventScript_DoorLocked
	setvar VAR_0x8008, 1
	setvar VAR_0x8009, 72
	msgbox PetalburgCity_Gym_Text_EnterRecoveryRoom, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, PetalburgCity_Gym_EventScript_EnterRoom
	goto_if_eq VAR_RESULT, NO, PetalburgCity_Gym_EventScript_DontEnterRoom
	end

PetalburgCity_Gym_EventScript_LeftStrengthRoomDoor::
	lockall
	goto_if_not_defeated TRAINER_PARKER, PetalburgCity_Gym_EventScript_DoorLocked
	setvar VAR_0x8008, 1
	setvar VAR_0x8009, 20
	msgbox PetalburgCity_Gym_Text_EnterStrengthRoom, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, PetalburgCity_Gym_EventScript_EnterRoom
	goto_if_eq VAR_RESULT, NO, PetalburgCity_Gym_EventScript_DontEnterRoom
	end

PetalburgCity_Gym_EventScript_RightStrengthRoomDoor::
	lockall
	goto_if_not_defeated TRAINER_ALEXIA, PetalburgCity_Gym_EventScript_DoorLocked
	setvar VAR_0x8008, 7
	setvar VAR_0x8009, 20
	msgbox PetalburgCity_Gym_Text_EnterStrengthRoom, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, PetalburgCity_Gym_EventScript_EnterRoom
	goto_if_eq VAR_RESULT, NO, PetalburgCity_Gym_EventScript_DontEnterRoom
	end

PetalburgCity_Gym_EventScript_LeftOHKORoomDoor::
	lockall
	goto_if_not_defeated TRAINER_ALEXIA, PetalburgCity_Gym_EventScript_DoorLocked
	setvar VAR_0x8008, 1
	setvar VAR_0x8009, 33
	msgbox PetalburgCity_Gym_Text_EnterOHKORoom, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, PetalburgCity_Gym_EventScript_EnterRoom
	goto_if_eq VAR_RESULT, NO, PetalburgCity_Gym_EventScript_DontEnterRoom
	end

PetalburgCity_Gym_EventScript_RightOHKORoomDoor::
	lockall
	goto_if_not_defeated TRAINER_GEORGE, PetalburgCity_Gym_EventScript_DoorLocked
	setvar VAR_0x8008, 7
	setvar VAR_0x8009, 33
	msgbox PetalburgCity_Gym_Text_EnterOHKORoom, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, PetalburgCity_Gym_EventScript_EnterRoom
	goto_if_eq VAR_RESULT, NO, PetalburgCity_Gym_EventScript_DontEnterRoom
	end

PetalburgCity_Gym_EventScript_LeftGymLeadersRoomDoor::
	lockall
	goto_if_not_defeated TRAINER_JODY, PetalburgCity_Gym_EventScript_DoorLocked
	setvar VAR_0x8008, 1
	setvar VAR_0x8009, 7
	msgbox PetalburgCity_Gym_Text_EnterGymLeadersRoom, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, PetalburgCity_Gym_EventScript_EnterRoom
	goto_if_eq VAR_RESULT, NO, PetalburgCity_Gym_EventScript_DontEnterRoom
	end

PetalburgCity_Gym_EventScript_RightGymLeadersRoomDoor::
	lockall
	goto_if_not_defeated TRAINER_BERKE, PetalburgCity_Gym_EventScript_DoorLocked
	setvar VAR_0x8008, 7
	setvar VAR_0x8009, 7
	msgbox PetalburgCity_Gym_Text_EnterGymLeadersRoom, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, PetalburgCity_Gym_EventScript_EnterRoom
	goto_if_eq VAR_RESULT, NO, PetalburgCity_Gym_EventScript_DontEnterRoom
	end

PetalburgCity_Gym_EventScript_Randall::
	trainerbattle_double TRAINER_RANDALL, PetalburgCity_Gym_Text_RandallIntro, PetalburgCity_Gym_Text_RandallDefeat, PetalburgCity_Gym_Text_RandallNotEnoughMons
	msgbox PetalburgCity_Gym_Text_RandallAfter, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_Faba::
	trainerbattle_double TRAINER_PARKER, PetalburgCity_Gym_Text_FabaIntro, PetalburgCity_Gym_Text_FabaDefeat, PetalburgCity_Gym_Text_FabaNotEnoughMons
	msgbox PetalburgCity_Gym_Text_FabaAfter, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_SlideOpenSpeedRoomDoors::
	setvar VAR_0x8005, 0
	call PetalburgCity_Gym_EventScript_OpenSpeedRoomDoors
	special DrawWholeMapView
	release
	end

PetalburgCity_Gym_EventScript_RandallPostBadge::
	msgbox PetalburgCity_Gym_Text_RandallPostBadge, MSGBOX_NPC
	end

PetalburgCity_Gym_EventScript_Parker::
	trainerbattle_single TRAINER_PARKER, PetalburgCity_Gym_Text_ParkerIntro, PetalburgCity_Gym_Text_ParkerDefeat, PetalburgCity_Gym_EventScript_SlideOpenConfusionRoomDoors
	goto_if_set FLAG_DEFEATED_PETALBURG_GYM, PetalburgCity_Gym_EventScript_ParkerPostBadge
	msgbox PetalburgCity_Gym_Text_ParkerPostBattle, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_SlideOpenConfusionRoomDoors::
	setvar VAR_0x8005, 0
	call PetalburgCity_Gym_EventScript_OpenConfusionRoomDoors
	special DrawWholeMapView
	release
	end

PetalburgCity_Gym_EventScript_ParkerPostBadge::
	msgbox PetalburgCity_Gym_Text_ParkerPostBadge, MSGBOX_NPC
	end

PetalburgCity_Gym_EventScript_George::
	trainerbattle_single TRAINER_GEORGE, PetalburgCity_Gym_Text_GeorgeIntro, PetalburgCity_Gym_Text_GeorgeDefeat, PetalburgCity_Gym_EventScript_SlideOpenRecoveryRoomDoors
	goto_if_set FLAG_DEFEATED_PETALBURG_GYM, PetalburgCity_Gym_EventScript_GeorgePostBadge
	msgbox PetalburgCity_Gym_Text_GeorgePostBattle, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_SlideOpenRecoveryRoomDoors::
	setvar VAR_0x8005, 0
	call PetalburgCity_Gym_EventScript_OpenRecoveryRoomDoors
	special DrawWholeMapView
	release
	end

PetalburgCity_Gym_EventScript_GeorgePostBadge::
	msgbox PetalburgCity_Gym_Text_GeorgePostBadge, MSGBOX_NPC
	end

PetalburgCity_Gym_EventScript_Berke::
	trainerbattle_single TRAINER_BERKE, PetalburgCity_Gym_Text_BerkeIntro, PetalburgCity_Gym_Text_BerkeDefeat, PetalburgCity_Gym_EventScript_SlideOpenOHKORoomDoors
	goto_if_set FLAG_DEFEATED_PETALBURG_GYM, PetalburgCity_Gym_EventScript_BerkePostBadge
	msgbox PetalburgCity_Gym_Text_BerkePostBattle, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_SlideOpenOHKORoomDoors::
	setvar VAR_0x8005, 0
	call PetalburgCity_Gym_EventScript_OpenOHKORoomDoors
	special DrawWholeMapView
	release
	end

PetalburgCity_Gym_EventScript_BerkePostBadge::
	msgbox PetalburgCity_Gym_Text_BerkePostBadge, MSGBOX_NPC
	end

PetalburgCity_Gym_EventScript_Mary::
	trainerbattle_single TRAINER_MARY, PetalburgCity_Gym_Text_MaryIntro, PetalburgCity_Gym_Text_MaryDefeat, PetalburgCity_Gym_EventScript_SlideOpenAccuracyRoomDoors
	goto_if_set FLAG_DEFEATED_PETALBURG_GYM, PetalburgCity_Gym_EventScript_MaryPostBadge
	msgbox PetalburgCity_Gym_Text_MaryPostBattle, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_SlideOpenAccuracyRoomDoors::
	setvar VAR_0x8005, 0
	call PetalburgCity_Gym_EventScript_OpenAccuracyRoomDoors
	special DrawWholeMapView
	release
	end

PetalburgCity_Gym_EventScript_MaryPostBadge::
	msgbox PetalburgCity_Gym_Text_MaryPostBadge, MSGBOX_NPC
	end

PetalburgCity_Gym_EventScript_Alexia::
	trainerbattle_single TRAINER_ALEXIA, PetalburgCity_Gym_Text_AlexiaIntro, PetalburgCity_Gym_Text_AlexiaDefeat, PetalburgCity_Gym_EventScript_SlideOpenDefenseRoomDoors
	goto_if_set FLAG_DEFEATED_PETALBURG_GYM, PetalburgCity_Gym_EventScript_AlexiaPostBadge
	msgbox PetalburgCity_Gym_Text_AlexiaPostBattle, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_SlideOpenDefenseRoomDoors::
	setvar VAR_0x8005, 0
	call PetalburgCity_Gym_EventScript_OpenDefenseRoomDoors
	special DrawWholeMapView
	release
	end

PetalburgCity_Gym_EventScript_AlexiaPostBadge::
	msgbox PetalburgCity_Gym_Text_AlexiaPostBadge, MSGBOX_NPC
	end

PetalburgCity_Gym_EventScript_Jody::
	trainerbattle_single TRAINER_JODY, PetalburgCity_Gym_Text_JodyIntro, PetalburgCity_Gym_Text_JodyDefeat, PetalburgCity_Gym_EventScript_SlideOpenStrengthRoomDoors
	goto_if_set FLAG_DEFEATED_PETALBURG_GYM, PetalburgCity_Gym_EventScript_JodyPostBadge
	msgbox PetalburgCity_Gym_Text_JodyPostBattle, MSGBOX_AUTOCLOSE
	end

PetalburgCity_Gym_EventScript_SlideOpenStrengthRoomDoors::
	setvar VAR_0x8005, 0
	call PetalburgCity_Gym_EventScript_OpenStrengthRoomDoors
	special DrawWholeMapView
	release
	end

PetalburgCity_Gym_EventScript_JodyPostBadge::
	msgbox PetalburgCity_Gym_Text_JodyPostBadge, MSGBOX_NPC
	end

@ VAR_0x8004 below is the room number
@ VAR_0x8005 below is 0 when the door should be slid open and 1 when it should be unlocked immediately
PetalburgCity_Gym_EventScript_OpenGymEntranceDoors::
	setvar VAR_0x8004, 1
	call_if_eq VAR_0x8005, 0, PetalburgCity_Gym_EventScript_SlideOpenRoomDoors
	call_if_eq VAR_0x8005, 1, PetalburgCity_Gym_EventScript_UnlockRoomDoors
	call PetalburgCity_Gym_EventScript_SetEntranceRoomDoorMetatiles
	return

PetalburgCity_Gym_EventScript_OpenSpeedRoomDoors::
	setvar VAR_0x8004, 2
	call_if_eq VAR_0x8005, 0, PetalburgCity_Gym_EventScript_SlideOpenRoomDoors
	call_if_eq VAR_0x8005, 1, PetalburgCity_Gym_EventScript_UnlockRoomDoors
	call PetalburgCity_Gym_EventScript_SetSpeedRoomDoorMetatiles
	return

PetalburgCity_Gym_EventScript_OpenAccuracyRoomDoors::
	setvar VAR_0x8004, 3
	call_if_eq VAR_0x8005, 0, PetalburgCity_Gym_EventScript_SlideOpenRoomDoors
	call_if_eq VAR_0x8005, 1, PetalburgCity_Gym_EventScript_UnlockRoomDoors
	call PetalburgCity_Gym_EventScript_SetAccuracyRoomDoorMetatiles
	return

PetalburgCity_Gym_EventScript_OpenConfusionRoomDoors::
	setvar VAR_0x8004, 4
	call_if_eq VAR_0x8005, 0, PetalburgCity_Gym_EventScript_SlideOpenRoomDoors
	call_if_eq VAR_0x8005, 1, PetalburgCity_Gym_EventScript_UnlockRoomDoors
	call PetalburgCity_Gym_EventScript_SetConfusionRoomDoorMetatiles
	return

PetalburgCity_Gym_EventScript_OpenDefenseRoomDoors::
	setvar VAR_0x8004, 5
	call_if_eq VAR_0x8005, 0, PetalburgCity_Gym_EventScript_SlideOpenRoomDoors
	call_if_eq VAR_0x8005, 1, PetalburgCity_Gym_EventScript_UnlockRoomDoors
	call PetalburgCity_Gym_EventScript_SetDefenseRoomDoorMetatiles
	return

PetalburgCity_Gym_EventScript_OpenRecoveryRoomDoors::
	setvar VAR_0x8004, 6
	call_if_eq VAR_0x8005, 0, PetalburgCity_Gym_EventScript_SlideOpenRoomDoors
	call_if_eq VAR_0x8005, 1, PetalburgCity_Gym_EventScript_UnlockRoomDoors
	call PetalburgCity_Gym_EventScript_SetRecoveryRoomDoorMetatiles
	return

PetalburgCity_Gym_EventScript_OpenStrengthRoomDoors::
	setvar VAR_0x8004, 7
	call_if_eq VAR_0x8005, 0, PetalburgCity_Gym_EventScript_SlideOpenRoomDoors
	call_if_eq VAR_0x8005, 1, PetalburgCity_Gym_EventScript_UnlockRoomDoors
	call PetalburgCity_Gym_EventScript_SetStrengthRoomDoorMetatiles
	return

PetalburgCity_Gym_EventScript_OpenOHKORoomDoors::
	setvar VAR_0x8004, 8
	call_if_eq VAR_0x8005, 0, PetalburgCity_Gym_EventScript_SlideOpenRoomDoors
	call_if_eq VAR_0x8005, 1, PetalburgCity_Gym_EventScript_UnlockRoomDoors
	call PetalburgCity_Gym_EventScript_SetOHKORoomDoorMetatiles
	return

PetalburgCity_Gym_EventScript_SetEntranceRoomDoorMetatiles::
	setmetatile 6, 85, METATILE_PetalburgGym_RoomEntrance_Left, FALSE
	setmetatile 7, 85, METATILE_PetalburgGym_RoomEntrance_Right, FALSE
	setmetatile 1, 98, METATILE_PetalburgGym_RoomEntrance_Left, FALSE
	setmetatile 2, 98, METATILE_PetalburgGym_RoomEntrance_Right, FALSE
	return

PetalburgCity_Gym_EventScript_SetSpeedRoomDoorMetatiles::
	setmetatile 6, 46, METATILE_PetalburgGym_RoomEntrance_Left, FALSE
	setmetatile 7, 46, METATILE_PetalburgGym_RoomEntrance_Right, FALSE
	setmetatile 1, 59, METATILE_PetalburgGym_RoomEntrance_Left, FALSE
	setmetatile 2, 59, METATILE_PetalburgGym_RoomEntrance_Right, FALSE
	return

PetalburgCity_Gym_EventScript_SetAccuracyRoomDoorMetatiles::
	setmetatile 6, 59, METATILE_PetalburgGym_RoomEntrance_Left, FALSE
	setmetatile 7, 59, METATILE_PetalburgGym_RoomEntrance_Right, FALSE
	setmetatile 1, 72, METATILE_PetalburgGym_RoomEntrance_Left, FALSE
	setmetatile 2, 72, METATILE_PetalburgGym_RoomEntrance_Right, FALSE
	return

PetalburgCity_Gym_EventScript_SetConfusionRoomDoorMetatiles::
	setmetatile 1, 20, METATILE_PetalburgGym_RoomEntrance_Left, FALSE
	setmetatile 2, 20, METATILE_PetalburgGym_RoomEntrance_Right, FALSE
	return

PetalburgCity_Gym_EventScript_SetDefenseRoomDoorMetatiles::
	setmetatile 6, 20, METATILE_PetalburgGym_RoomEntrance_Left, FALSE
	setmetatile 7, 20, METATILE_PetalburgGym_RoomEntrance_Right, FALSE
	setmetatile 1, 33, METATILE_PetalburgGym_RoomEntrance_Left, FALSE
	setmetatile 2, 33, METATILE_PetalburgGym_RoomEntrance_Right, FALSE
	return

PetalburgCity_Gym_EventScript_SetRecoveryRoomDoorMetatiles::
	setmetatile 6, 33, METATILE_PetalburgGym_RoomEntrance_Left, FALSE
	setmetatile 7, 33, METATILE_PetalburgGym_RoomEntrance_Right, FALSE
	return

PetalburgCity_Gym_EventScript_SetStrengthRoomDoorMetatiles::
	setmetatile 1, 7, METATILE_PetalburgGym_RoomEntrance_Left, FALSE
	setmetatile 2, 7, METATILE_PetalburgGym_RoomEntrance_Right, FALSE
	return

PetalburgCity_Gym_EventScript_SetOHKORoomDoorMetatiles::
	setmetatile 6, 7, METATILE_PetalburgGym_RoomEntrance_Left, FALSE
	setmetatile 7, 7, METATILE_PetalburgGym_RoomEntrance_Right, FALSE
	return

PetalburgCity_Gym_EventScript_SlideOpenRoomDoors::
	special PetalburgGymSlideOpenRoomDoors
	return

PetalburgCity_Gym_EventScript_UnlockRoomDoors::
	special PetalburgGymUnlockRoomDoors
	return

PetalburgCity_Gym_EventScript_GymGuide::
	lock
	faceplayer
	goto_if_set FLAG_DEFEATED_PETALBURG_GYM, PetalburgCity_Gym_EventScript_GymGuidePostVictory
	msgbox PetalburgCity_Gym_Text_GymGuideAdvice, MSGBOX_DEFAULT
	release
	end

PetalburgCity_Gym_EventScript_GymGuidePostVictory::
	msgbox PetalburgCity_Gym_Text_GymGuidePostVictory, MSGBOX_DEFAULT
	release
	end

PetalburgCity_Gym_EventScript_LeftGymStatue::
	lockall
	goto_if_set FLAG_BADGE05_GET, PetalburgCity_Gym_EventScript_GymStatueCertified
	goto PetalburgCity_Gym_EventScript_GymStatue
	end

PetalburgCity_Gym_EventScript_RightGymStatue::
	lockall
	goto_if_set FLAG_BADGE05_GET, PetalburgCity_Gym_EventScript_GymStatueCertified
	goto PetalburgCity_Gym_EventScript_GymStatue
	end

PetalburgCity_Gym_EventScript_GymStatueCertified::
	msgbox PetalburgCity_Gym_Text_GymStatueCertified, MSGBOX_DEFAULT
	releaseall
	end

PetalburgCity_Gym_EventScript_GymStatue::
	msgbox PetalburgCity_Gym_Text_GymStatue, MSGBOX_DEFAULT
	releaseall
	end

PetalburgCity_Gym_Text_DadYoureHereWithYourPokemon:
	.string "VATER: Hm?\p"
	.string "Na, wenn das nicht {PLAYER} ist!\n"
	.string "Dann habt ihr also den Umzug beendet?\p"
	.string "Ich bin überrascht, dass du ganz\n"
	.string "alleine hierher gefunden hast.\p"
	.string "Oh, so ist das.\n"
	.string "Du bist in POKéMON-Begleitung.\p"
	.string "Ich glaube, du wirst einmal in meine\n"
	.string "Fußstapfen als TRAINER treten,\l"
	.string "{PLAYER}.\p"
	.string "Das sind großartige Aussichten!\n"
	.string "Ich kann es kaum erwarten!$"

PetalburgCity_Gym_Text_WallyIdLikeAPokemon:
	.string "Äh… Ich… Ich hätte so gerne ein\n"
	.string "POKéMON. Bitte…$"

PetalburgCity_Gym_Text_DadOhYoureWallyRight:
	.string "VATER: Wie? Du… Ach… Gut.\n"
	.string "Du bist HEIKO, nicht wahr?$"

PetalburgCity_Gym_Text_WallyIveNeverCaughtAPokemon:
	.string "HEIKO: Ich werde meine Verwandten\n"
	.string "in VERDANTURF TOWN besuchen.\p"
	.string "Ich glaube, ich werde mich da doch\n"
	.string "einsam fühlen, daher würde ich gerne ein\l"
	.string "POKéMON mitnehmen.\p"
	.string "Aber ich habe noch nie eines gefangen.\n"
	.string "Ich weiß nicht, wie das geht…$"

PetalburgCity_Gym_Text_DadHmISee:
	.string "VATER: Oh, ich verstehe…$"

PetalburgCity_Gym_Text_DadPlayerGoWithWally:
	.string "VATER: {PLAYER}, hast du das gehört?\p"
	.string "Hilf doch bitte HEIKO dabei,\n"
	.string "ein POKéMON zu fangen.$"

PetalburgCity_Gym_Text_IllLoanYouMyZigzagoon:
	.string "HEIKO, hier, ich leihe dir mein\n"
	.string "POKéMON.\p"
	.string "HEIKO hat ein ZIGZACHS erhalten.$"

PetalburgCity_Gym_Text_WallyThankYouAndDadGivesPokeBall:
	.string "HEIKO: Oh, wow!!!\n"
	.string "Ein POKéMON!\p"
	.string "VATER: Hm. Ich gebe dir auch diesen\n"
	.string "POKéBALL. Dann leg los!\p"
	.string "HEIKO erhält einen POKéBALL!$"

PetalburgCity_Gym_Text_WallyOhWowThankYou:
	.string "HEIKO: Oh, wow!!!\n"
	.string "Danke schön!$"

PetalburgCity_Gym_Text_WouldYouReallyComeWithMe:
	.string "{PLAYER}… Kommst du wirklich mit mir???$"

PetalburgCity_Gym_Text_DadSoDidItWorkOut:
	.string "VATER: Und? Hat es geklappt?$"

PetalburgCity_Gym_Text_WallyThankYouBye:
	.string "HEIKO: Danke. Ja, wunderbar.\n"
	.string "Hier haben Sie Ihr POKéMON zurück.\p"
	.string "Danke, {PLAYER}, dass du mit mir\n"
	.string "gegangen bist.\p"
	.string "Euch beiden habe ich es zu verdanken,\n"
	.string "dass ich mein erstes POKéMON fangen\l"
	.string "konnte.\p"
	.string "Ich verspreche, ich werde mich gut\n"
	.string "darum kümmern!\p"
	.string "Oh! Meine Mama wartet sicher schon auf\n"
	.string "mich! Ich muss nach Hause!\p"
	.string "Bis bald, {PLAYER}!$"

PetalburgCity_Gym_Text_DadGoCollectBadges:
	.string "VATER: Nun…\p"
	.string "{PLAYER}, wenn du ein guter TRAINER\n"
	.string "werden willst - hier ist mein Rat.\p"
	.string "Gehe nach RUSTBORO CITY, gleich hinter\n"
	.string "diesem Ort.\p"
	.string "Dort solltest du die ARENALEITERIN\n"
	.string "FELIZIA herausfordern.\p"
	.string "Suche danach die anderen POKéMON\n"
	.string "ARENen auf und besiege die LEITER.\p"
	.string "Sammle die ORDEN der verschiedenen\n"
	.string "ARENen, verstehst du?\p"
	.string "Ich bin natürlich auch ein ARENALEITER.\n"
	.string "Auch wir werden eines Tages\l"
	.string "gegeneinander antreten.\p"
	.string "Aber erst, wenn du stärker geworden\n"
	.string "bist, {PLAYER}.$"

PetalburgCity_Gym_Text_NormanGoToRustboro:
	.string "VATER: Hm? Wolltest du nicht zur\n"
	.string "POKéMON ARENA in RUSTBORO CITY?\p"
	.string "Für mich ist es keine Herausforderung,\n"
	.string "gegen einen Grünschnabel anzutreten.\p"
	.string "{PLAYER}, ich möchte, dass du mich he-\n"
	.string "rausforderst, sobald du stärker bist.\p"
	.string "Ich werde gegen dich kämpfen, {PLAYER},\n"
	.string "sobald du vier ORDEN erhalten hast, ja?$"

PetalburgCity_Gym_Text_NormanGoToDewford:
	.string "VATER: Oh, ich sehe schon… Du hast die\n"
	.string "ARENALEITERIN in RUSTBORO CITY\l"
	.string "besiegt.\p"
	.string "Aber es gibt weitere TRAINER, die\n"
	.string "stärker sind als du, {PLAYER}.\p"
	.string "Wenn du das Meer überquerst, kommst du\n"
	.string "nach DEWFORD TOWN. Dort triffst du auf\l"
	.string "den ARENALEITER KAMILLO.\p"
	.string "Du solltest ihn wirklich herausfordern…$"

PetalburgCity_Gym_Text_YouHaveGottenStronger:
	.string "VATER: Hm… {PLAYER}, du bist stärker\n"
	.string "geworden.\p"
	.string "Das sehe ich an der Anzahl der ORDEN,\n"
	.string "die du dir verdient hast.$"

PetalburgCity_Gym_Text_NormanIntro:
	.string "VATER: Hm…\n"
	.string "Du besitzt vier ORDEN.\p"
	.string "Fein. Wie versprochen werden wir nun\n"
	.string "einen POKéMON-Kampf ausfechten.\p"
	.string "{PLAYER}…\p"
	.string "Ich bin so glücklich, dass mein eigenes\n"
	.string "Kind stark genug ist, gegen\l"
	.string "mich zu kämpfen!\p"
	.string "Aber: Kampf ist Kampf!\p"
	.string "Ich werde als ARENALEITER alles tun, um\n"
	.string "diesen Kampf zu gewinnen!\p"
	.string "{PLAYER}, du solltest ebenfalls dein\n"
	.string "Bestes geben!$"

PetalburgCity_Gym_Text_NormanDefeat:
	.string "…\p"
	.string "Ich… Ich kann es nicht…\p"
	.string "Ich kann es nicht glauben, {PLAYER}…\p"
	.string "Ich habe gegen {PLAYER} verloren?\p"
	.string "Nun, Regeln sind Regeln!\n"
	.string "Hier, das ist für dich.$"

PetalburgCity_Gym_Text_ReceivedBalanceBadge:
	.string "{PLAYER} hat den BALANCEORDEN vom\n"
	.string "VATER erhalten!$"

PetalburgCity_Gym_Text_ExplainBalanceBadgeTakeThis:
	.string "VATER: Mit diesem ORDEN erhöht sich die\n"
	.string "VERTEIDIGUNG all deiner POKéMON.\p"
	.string "POKéMON, die die VM SURFER erlernt\n"
	.string "haben, können diese auch zum Reisen\l"
	.string "über das Wasser einsetzen.\p"
	.string "{PLAYER}, das ist mein Geschenk für\n"
	.string "dich. Ich bin sicher, du wirst es gut\l"
	.string "nutzen.$"

PetalburgCity_Gym_Text_ExplainFacade:
	.string "VATER: TM42 enthält FASSADE.\p"
	.string "Sie verdoppelt die Stärke der Attacken,\n"
	.string "wenn das POKéMON vergiftet,\l"
	.string "paralysiert oder verbrannt wurde.\p"
	.string "So kann eine vermeintlich aussichts-\n"
	.string "lose Situation vielleicht gerettet\l"
	.string "werden.$"

PetalburgCity_Gym_Text_DadHappyAndSad:
	.string "VATER: Als ARENALEITER kann ich gar\n"
	.string "nicht sagen, wie bestürzt ich bin…\p"
	.string "Als Vater macht es mich einerseits sehr\n"
	.string "stolz, andererseits aber auch traurig…$"

PetalburgCity_Gym_Text_PleaseComeWithMe:
	.string "Ah, da bist du ja, {PLAYER}{KUN}!\p"
	.string "Komm doch bitte mal mit.\n"
	.string "Ich habe hier etwas für dich.$"

PetalburgCity_Gym_Text_LetMeBorrowPlayer:
	.string "NORMAN, du hast doch nichts dagegen?\p"
	.string "Ich entführe dir {PLAYER}{KUN} mal eben für\n"
	.string "ein paar Minuten.$"

PetalburgCity_Gym_Text_DadGoingToKeepTraining:
	.string "VATER: {PLAYER}, du solltest deine\n"
	.string "Mutter öfter mal besuchen.\p"
	.string "Ich bleibe hier und werde mein Training\n"
	.string "verdoppeln.\p"
	.string "Als TRAINER lässt es mir keine Ruhe. Ich\n"
	.string "möchte irgendwann gegen dich gewinnen.$"

PetalburgCity_Gym_Text_DadNoAmountOfTrainingIsEnough:
	.string "VATER: {PLAYER}! Wie geht es dir?\p"
	.string "Die Welt der POKéMON ist vielfältig.\p"
	.string "Ich bin überzeugt, dass selbst das \n"
	.string "härteste Training dieser Vielfalt nicht\l"
	.string "gerecht wird.$"

PetalburgCity_Gym_Text_GymGuideAdvice:
	.string "Na, wie sieht es aus, auf dem Weg zum\n"
	.string "CHAMP, {PLAYER}?\p"
	.string "Die Türen dieser ARENA öffnen sich,\n"
	.string "wenn du die einzelnen TRAINER besiegst.\p"
	.string "Huups! Die Türen in diesem Raum sind ja\n"
	.string "schon offen, greif mich bitte nicht an!\p"
	.string "Die TRAINER der ARENA von GRASWINKEL\n"
	.string "CITY setzen die verschiedensten\l"
	.string "Items ein.\p"
	.string "Die Tür auf der linken Seite führt in\n"
	.string "den INITIATIVE-RAUM.\p"
	.string "Die Tür auf der rechten Seite führt in\n"
	.string "den RAUM der GENAUIGKEIT.\p"
	.string "Die Türen sind beschriftet, lies genau\n"
	.string "und triff eine überlegte Wahl.\p"
	.string "Hast du dich für eine Tür entschieden…\n"
	.string "Nun, ähm, genug der Worte!$"

PetalburgCity_Gym_Text_GymGuidePostVictory:
	.string "{PLAYER}! Hui! Du hast sogar deinen\n"
	.string "eigenen Vater besiegt!\p"
	.string "Wie… Unglaublich!\n"
	.string "Die Ereignisse überschlagen sich!$"

PetalburgCity_Gym_Text_RandallIntro:
	.string "Wenn du zum Simi wettsch,\n"
	.string "musch zersch a mir verbii. >:)$"

PetalburgCity_Gym_Text_RandallDefeat:
	.string "Ach...$"

PetalburgCity_Gym_Text_RandallNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

PetalburgCity_Gym_Text_RandallAfter:
	.string "Janu, de Simi schlahsch\n"
	.string "nöd...$"

PetalburgCity_Gym_Text_FabaIntro:
	.string "Yo Jungs man, egal wie\n"
	.string "ihr mich dissed...$"

PetalburgCity_Gym_Text_FabaDefeat:
	.string "Du Scheiss Trampeltier!$"

PetalburgCity_Gym_Text_FabaNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

PetalburgCity_Gym_Text_FabaAfter:
	.string "Jetzt muss ich dopplet\n"
	.string "zude Tüecher griife.$"

PetalburgCity_Gym_Text_SimonIntro:
	.string "Schön das de Professor Lunte\n"
	.string "dir es paar Pokemon\l"
	.string "abdruckt het, hmm?\p"
	.string "Jetzt träumsch du sicher\n"
	.string "devo, mich und die andere\l"
	.string "Arenaleiter z' besiege\p"
	.string "und dich denn ade Top 4\n"
	.string "chönne z'stelle, hmm? :\p"
	.string "Zeig mer mal was du chasch...\n"
	.string "Doch nimm dich in acht,\l"
	.string "mini Jöges sind hütt on fire!$"

PetalburgCity_Gym_Text_SimonDefeat:
	.string "Hahhaha...$"

PetalburgCity_Gym_Text_SimonNotEnoughMons:
	.string "Du bruchsch mindestens zwei\n"
	.string "Pokemon für en Doppelkampf.$"

PetalburgCity_Gym_Text_ReceivedFirstBadge:
	.string "NJIERI snaggt sich de\n"
	.string "erst Orde!$"

PetalburgCity_Gym_Text_SimonAfterBadge:
	.string "Ich glaub ich bruch chli\n"
	.string "me Glück negscht mal.\p"
	.string "Aber mer chan ja nöd immer\n"
	.string "lucky sii, oder?\p"
	.string "Du verdiensch der de\n"
	.string "ersti Orde!$"

PetalburgCity_Gym_Text_SimonGoDubi:
	.string "Dini Reis gaht wiiter\n"
	.string "richtig Dübi.\p"
	.string "Glaub mer, dett gits\n"
	.string "mieses Züüg und usserdem\l"
	.string "die negscht Arena vom Julian.\p"
	.string "Vill Erfolg uf dim Weg!$"

PetalburgCity_Gym_Text_ParkerIntro:
	.string "Dies ist der RAUM der VERWIRRUNG.\p"
	.string "Zeig mir, wie stark das Band zwischen\n"
	.string "dir und deinen POKéMON ist.$"

PetalburgCity_Gym_Text_ParkerDefeat:
	.string "Ich konnte dein Team nicht genug\n"
	.string "verwirren… Euer Band ist stark.$"

PetalburgCity_Gym_Text_ParkerPostBattle:
	.string "Der nächste Raum ist der RAUM der\n"
	.string "STÄRKE. Kommst du gegen pure\l"
	.string "Gewalt an?$"

PetalburgCity_Gym_Text_ParkerPostBadge:
	.string "Jetzt muss ich dopplet\n"
	.string "zude Tüecher griife.$"

PetalburgCity_Gym_Text_GeorgeIntro:
	.string "Immer, wenn du den Sieg in greifbarer\n"
	.string "Nähe siehst, füllt dein Gegner KP auf…\p"
	.string "Kannst du dir vorstellen, wie man sich in\n"
	.string "so einer Situation fühlt?\p"
	.string "Ich werde dir so eine Situation\n"
	.string "demonstrieren!$"

PetalburgCity_Gym_Text_GeorgeDefeat:
	.string "Ich konnte nicht genügend KP\n"
	.string "auffüllen… Welch eine ANGRIFFskraft…$"

PetalburgCity_Gym_Text_GeorgePostBattle:
	.string "Ich hatte vom Kind unseres ARENA-\n"
	.string "LEITERs nichts anderes erwartet!\p"
	.string "Nein! Die Fähigkeiten eines TRAINERs\n"
	.string "entwickeln sich mit dem Training.\p"
	.string "Ich habe mich offensichtlich nicht\n"
	.string "genug angestrengt.\p"
	.string "Geh! Der nächste Raum ist der K.O.-\n"
	.string "TREFFER-RAUM.$"

PetalburgCity_Gym_Text_GeorgePostBadge:
	.string "Ich werde auch weiterhin in den ARENen\n"
	.string "trainieren. Und ARENALEITER werden!$"

PetalburgCity_Gym_Text_BerkeIntro:
	.string "Ich werde es dir nicht leicht machen,\n"
	.string "nur weil du das Kind unseres LEITERs\l"
	.string "bist.\p"
	.string "Ich werde dir beibringen, was es für ein\n"
	.string "POKéMON bedeutet, einen Volltreffer\l"
	.string "zu erhalten.$"

PetalburgCity_Gym_Text_BerkeDefeat:
	.string "Deine Stärke…\n"
	.string "Du kämpfst großartig!$"

PetalburgCity_Gym_Text_BerkePostBattle:
	.string "Dein Vater ist stark. Als TRAINER\n"
	.string "erweise ich ihm den größten Respekt.\p"
	.string "Und ich sehe, dass die gleiche Stärke\n"
	.string "auch in dir ruht.\p"
	.string "Ich fühle, dass du dich nun einem\n"
	.string "Kampf mit deinem Vater stellen kannst.$"

PetalburgCity_Gym_Text_BerkePostBadge:
	.string "Seit dein Vater der LEITER der ARENA\n"
	.string "von GRASWINKEL TOWN ist, sind die\l"
	.string "TRAINER dort viel stärker geworden.$"

PetalburgCity_Gym_Text_MaryIntro:
	.string "Kicher…\n"
	.string "Dies ist der RAUM der GENAUIGKEIT.\p"
	.string "Es ist schon ziemlich fies, wenn jede\n"
	.string "Attacke ein Treffer ist.$"

PetalburgCity_Gym_Text_MaryDefeat:
	.string "Du bist ein bisschen stärker als ich…$"

PetalburgCity_Gym_Text_MaryPostBattle:
	.string "Es warten noch weitaus stärkere\n"
	.string "TRAINER auf dich.\p"
	.string "Der linke ist der RAUM der VERTEIDIGUNG\n"
	.string "und der rechte der RAUM der ERHOLUNG.\p"
	.string "Die ATTACKEN deiner POKéMON werden\n"
	.string "in beiden Räumen auf die Probe gestellt.$"

PetalburgCity_Gym_Text_MaryPostBadge:
	.string "Weißt du, wonach wir als TRAINER\n"
	.string "streben?\p"
	.string "Wir streben danach, die Seelenfreunde\n"
	.string "unserer POKéMON zu werden.$"

PetalburgCity_Gym_Text_AlexiaIntro:
	.string "Je stärker die VERTEIDIGUNG ist, desto\n"
	.string "rücksichtsloser kann ich angreifen.$"

PetalburgCity_Gym_Text_AlexiaDefeat:
	.string "Unsere Verteidigung reichte nicht aus…$"

PetalburgCity_Gym_Text_AlexiaPostBattle:
	.string "Ich denke, du hast mir eine wertvolle\n"
	.string "Lektion erteilt.\p"
	.string "Nun, geh weiter. Die linke Tür führt in\n"
	.string "den RAUM der STÄRKE.\p"
	.string "Die rechte Tür öffnet den\n"
	.string "K.O.-TREFFER-RAUM.\p"
	.string "In beiden warten äußerst talentierte\n"
	.string "TRAINER.$"

PetalburgCity_Gym_Text_AlexiaPostBadge:
	.string "Hallo! Hast du mal SURFER ausprobiert?$"

PetalburgCity_Gym_Text_JodyIntro:
	.string "Unser ARENALEITER hat uns angewiesen,\n"
	.string "alles zu geben und dich zu besiegen.\p"
	.string "Auch wenn du das Kind des LEITERs bist!$"

PetalburgCity_Gym_Text_JodyDefeat:
	.string "Aber… Das war wohl nichts!$"

PetalburgCity_Gym_Text_JodyPostBattle:
	.string "Wie du deine POKéMON einsetzt…\n"
	.string "Du bist wie dein Vater.\p"
	.string "Geh weiter! Der ARENALEITER, dein\n"
	.string "Vater, erwartet dich bereits!$"

PetalburgCity_Gym_Text_JodyPostBadge:
	.string "Sicher, es ist immer von Vorteil, die\n"
	.string "POKéMON stärker werden zu lassen.\p"
	.string "Aber was macht einen Gewinner aus?\p"
	.string "Nun, das sind die Gefühle, die ein\n"
	.string "TRAINER seinen POKéMON entgegen-\l"
	.string "bringt.$"

PetalburgCity_Gym_Text_DoorAppearsLocked:
	.string "Die Tür ist noch verschlossen…$"

PetalburgCity_Gym_Text_EnterSpeedRoom:
	.string "“INITIATIVE-RAUM” steht auf\n"
	.string "dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

@ Unused
PetalburgCity_Gym_Text_DoorAppearsLocked2:
	.string "This door appears to be locked\n"
	.string "right now…$"

PetalburgCity_Gym_Text_EnterAccuracyRoom:
	.string "“RAUM der GENAUIGKEIT” steht\n"
	.string "auf dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_EnterConfusionRoom:
	.string "“RAUM der VERWIRRUNG”\n"
	.string "steht auf dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_EnterDefenseRoom:
	.string "“RAUM der VERTEIDIGUNG” steht\n"
	.string "auf dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_EnterRecoveryRoom:
	.string "“RAUM der ERHOLUNG” steht auf\n"
	.string "dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_EnterStrengthRoom:
	.string "“RAUM der STÄRKE” steht auf\n"
	.string "dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_EnterOHKORoom:
	.string "“K.O.-TREFFER-RAUM”\n"
	.string "steht auf dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_EnterGymLeadersRoom:
	.string "“ARENALEITER”\p"
	.string "“Sieh selbst, welche POKéMON dich\n"
	.string "erwarten!” steht auf dem Schild.\p"
	.string "Möchtest du die Tür öffnen?$"

PetalburgCity_Gym_Text_GymStatue:
	.string "POKéMON ARENA von GRASWINKEL TOWN$"

PetalburgCity_Gym_Text_GymStatueCertified:
	.string "POKéMON ARENA von GRASWINKEL TOWN\p"
	.string "NORMANs ANERKANNTE TRAINER:\n"
	.string "{PLAYER}$"

PetalburgCity_Gym_Text_NormanPreRematch:
	.string "VATER: {PLAYER}…\n"
	.string "Ich wusste, du würdest kommen.\p"
	.string "Niemals würde ich eine Herausforderung\n"
	.string "von dir ablehnen!\p"
	.string "Du verstehst, was ich meine?\p"
	.string "In einer ARENA ist es ohne Bedeutung,\n"
	.string "dass du mein Kind bist.\p"
	.string "Im Gegenteil, da wir Vater und Kind sind,\n"
	.string "müssen wir beide unser Bestes geben.\l"
	.string "Meinst du nicht auch, {PLAYER}?$"

PetalburgCity_Gym_Text_NormanRematchDefeat:
	.string "Äh… Haha…\n"
	.string "Du bist ein harter Brocken…$"

PetalburgCity_Gym_Text_NormanPostRematch:
	.string "VATER: {PLAYER}…\n"
	.string "Was ist dein Traum?\p"
	.string "Mein Traum…\n"
	.string "Hahaha…\l"
	.string "Er wurde bereits Wirklichkeit.$"

PetalburgCity_Gym_Text_NormanRematchNeedTwoMons:
	.string "VATER: {PLAYER}…\n"
	.string "Ich wusste, du würdest kommen.\p"
	.string "Niemals würde ich eine Herausforderung\n"
	.string "von dir ablehnen!\p"
	.string "Du verstehst, was ich meine?\p"
	.string "In einer ARENA ist es ohne Bedeutung,\n"
	.string "dass du mein Kind bist.\p"
	.string "Hm? Warte mal, {PLAYER}.\p"
	.string "Du hast nur ein POKéMON, das kämpfen\n"
	.string "kann?\p"
	.string "Tut mir Leid, aber du brauchst\n"
	.string "mindestens zwei POKéMON.$"

PetalburgCity_Gym_Text_RandallPostBadge:
	.string "Janu, de Simi schlahsch\n"
	.string "nöd...$"
