#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("");
const u8 gText_ExpandedPlaceholder_Chan[] = _("");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("SAPPHIRE");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("RUBY");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("EMERALD");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("AQUA");
const u8 gText_ExpandedPlaceholder_Magma[] = _("MAGMA");
const u8 gText_ExpandedPlaceholder_Archie[] = _("ARCHIE");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("MAXIE");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("KYOGRE");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("GROUDON");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("BRENDAN");
const u8 gText_ExpandedPlaceholder_May[] = _("MAY");
const u8 gText_ExpandedPlaceholder_Red[] = _("RED");
const u8 gText_ExpandedPlaceholder_Green[] = _("GREEN");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("EI");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("POKEMON");
const u8 gText_Player[] = _("SPIELER"); // Unused
const u8 gText_Pokedex[] = _("POKEDEX"); // Unused
const u8 gText_Time[] = _("ZEIT");
const u8 gText_Badges[] = _("ORDEN"); // Unused
const u8 gText_AButton[] = _("A Button"); // Unused
const u8 gText_BButton[] = _("B Button"); // Unused
const u8 gText_RButton[] = _("R Button"); // Unused
const u8 gText_LButton[] = _("L Button"); // Unused
const u8 gText_Start[] = _("START"); // Unused
const u8 gText_Select[] = _("SELECT"); // Unused
const u8 gText_ControlPad[] = _("+ Control Pad"); // Unused
const u8 gText_LButtonRButton[] = _("L Button  R Button"); // Unused
const u8 gText_Controls[] = _("  CONTROLS"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}WEITER");
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}NEXT {B_BUTTON}ZURÜCK");
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}WÄHLEN {A_BUTTON}WEITER {B_BUTTON}ZURÜCK");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}WÄHLEN {A_BUTTON}{B_BUTTON}ZURÜCK");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}ZURÜCK");
const u8 gText_Boy[] = _("BUEB");
const u8 gText_Girl[] = _("MEITLI");
const u8 gText_ThisIsAPokemon[] = _("Dies ist ein so genanntes\n“POKéMON”.{PAUSE 96}\p");
const u8 gText_5MarksPokemon[] = _("?????");
const u8 gText_UnkHeight[] = _("{CLEAR_TO 12}??'??”");
const u8 gText_UnkHeightMetric[] = _("???.? m");
const u8 gText_UnkWeight[] = _("???,? kg");
const u8 gText_UnkWeightMetric[] = _("???.? kg.");
const u8 gText_EmptyPkmnCategory[] = _("                       POKéMON"); // Unused
const u8 gText_EmptyHeight[] = _("{CLEAR_TO 12}    '    ”"); // Unused
const u8 gText_EmptyWeight[] = _("          kg"); // Unused
const u8 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u8 gText_CryOf[] = _("RUF VON");
const u8 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u8 gText_SizeComparedTo[] = _("GRÖSSE VERGL. MIT ");
const u8 gText_PokedexRegistration[] = _("POKéDEX regist. komplett.");
const u8 gText_HTHeight[] = _("GR");
const u8 gText_WTWeight[] = _("GW");
const u8 gText_SearchingPleaseWait[] = _("Suche…\nBitte warte.");
const u8 gText_SearchCompleted[] = _("Suche fertig.");
const u8 gText_NoMatchingPkmnWereFound[] = _("Keine POKéMON gefunden.");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("Suche POKéMON mit\nParametern.");
const u8 gText_SwitchPokedexListings[] = _("Wechsle POKéDEX Liste.");
const u8 gText_ReturnToPokedex[] = _("Zurück zum POKéDEX.");
const u8 gText_SelectPokedexMode[] = _("Wähle den POKéDEX Modus.");
const u8 gText_SelectPokedexListingMode[] = _("Wähle die POKéDEX Auflistung.");
const u8 gText_ListByFirstLetter[] = _("Sort. nach Alphabet.\nnur gesehene POKéMON.");
const u8 gText_ListByBodyColor[] = _("Sort. nach Farbe.\nnur gesehene POKéMON.");
const u8 gText_ListByType[] = _("Sort. nach Typ.\nnur gefangene POKéMON.");
const u8 gText_ExecuteSearchSwitch[] = _("Ausführen suchen/wechseln.");
const u8 gText_DexHoennTitle[] = _("HOENN DEX");
const u8 gText_DexNatTitle[] = _("NATIONALER DEX");
const u8 gText_DexSortNumericalTitle[] = _("NUMMERNMODUS");
const u8 gText_DexSortAtoZTitle[] = _("A BIS Z MODUS");
const u8 gText_DexSortHeaviestTitle[] = _("SCHWERSTE");
const u8 gText_DexSortLightestTitle[] = _("LEICHTESTE");
const u8 gText_DexSortTallestTitle[] = _("GRÖSSTE");
const u8 gText_DexSortSmallestTitle[] = _("KLEINSTE");
const u8 gText_DexSearchAlphaABC[] = _("ABC");
const u8 gText_DexSearchAlphaDEF[] = _("DEF");
const u8 gText_DexSearchAlphaGHI[] = _("GHI");
const u8 gText_DexSearchAlphaJKL[] = _("JKL");
const u8 gText_DexSearchAlphaMNO[] = _("MNO");
const u8 gText_DexSearchAlphaPQR[] = _("PQR");
const u8 gText_DexSearchAlphaSTU[] = _("STU");
const u8 gText_DexSearchAlphaVWX[] = _("VWX");
const u8 gText_DexSearchAlphaYZ[] = _("YZ");
const u8 gText_DexSearchColorRed[] = _("ROT");
const u8 gText_DexSearchColorBlue[] = _("BLAU");
const u8 gText_DexSearchColorYellow[] = _("GELB");
const u8 gText_DexSearchColorGreen[] = _("GRÜN");
const u8 gText_DexSearchColorBlack[] = _("SCHWARZ");
const u8 gText_DexSearchColorBrown[] = _("BRAUN");
const u8 gText_DexSearchColorPurple[] = _("VIOLETT");
const u8 gText_DexSearchColorGray[] = _("GRAU");
const u8 gText_DexSearchColorWhite[] = _("WEISS");
const u8 gText_DexSearchColorPink[] = _("ROSA");
const u8 gText_DexHoennDescription[] = _("POKéDEX der HOENN-Region");
const u8 gText_DexNatDescription[] = _("Nationale POKéDEX-Ausgabe");
const u8 gText_DexSortNumericalDescription[] = _("POKéMON werden nach ihrer\nNummer sortiert.");
const u8 gText_DexSortAtoZDescription[] = _("Gesehene und gefangene POKéMON\nwerden alphabetisch sortiert.");
const u8 gText_DexSortHeaviestDescription[] = _("Gefangene POKéMON werden vom\nschwersten zum leichtesten sortiert.");
const u8 gText_DexSortLightestDescription[] = _("Gefangene POKéMON werden vom\nleichtesten zum schwersten sortiert.");
const u8 gText_DexSortTallestDescription[] = _("Gefangene POKéMON werden vom\ngrössten zum kleinsten sortiert.");
const u8 gText_DexSortSmallestDescription[] = _("Gefangene POKéMON werden vom\nkleinsten zum grössten sortiert.");
const u8 gText_DexEmptyString[] = _("");
const u8 gText_DexSearchDontSpecify[] = _("EGAL.");
const u8 gText_DexSearchTypeNone[] = _("KEINER");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(" "); // Unused
const u8 gText_WelcomeToHOF[] = _("Willkommen in der RUHMESHALLE!");
const u8 gText_HOFDexRating[] = _("Gesehene POKéMON: {STR_VAR_1}!\nGefangene POKéMON: {STR_VAR_2}!\pPROF. LUNTES POKéDEX-Bewertung!\pPROF. LUNTE: Mal sehen…\p");
const u8 gText_HOFDexSaving[] = _("SPEICHERN…\nNICHT AUSSCHALTEN.");
const u8 gText_HOFCorrupted[] = _("Die RUHMESHALLE-Daten sind beschädigt.");
const u8 gText_HOFNumber[] = _("RUHMESHALLE Nr. {STR_VAR_1}");
const u8 gText_LeagueChamp[] = _("LIGA-CHAMPION!\nHERZLICHEN GLÜCKWUNSCH!");
const u8 gText_Number[] = _("Nr. ");
const u8 gText_Level[] = _("Lv.");
const u8 gText_IdNumberSlash[] = _("ID-Nr. /"); // Unused
const u8 gText_Name[] = _("TRAINER");
const u8 gText_IDNumber[] = _("ID-Nr.");
const u8 gText_BirchInTrouble[] = _("PROF. LUNTE ist in Gefahr!\nLass ein POKéMON frei und rette ihn!");
const u8 gText_ConfirmStarterChoice[] = _("Wählst du dieses POKéMON?");
const u8 gText_Pokemon4[] = _("POKéMON"); // Unused
const u8 gText_FlyToWhere[] = _("WOHIN FLIEGEN?");
const u8 gMenuText_Use[] = _("NUTZEN");
const u8 gMenuText_Toss[] = _("WEGWERFEN");
const u8 gMenuText_Register[] = _("REGISTRIEREN");
const u8 gMenuText_Give[] = _("GEBEN");
const u8 gMenuText_Confirm[] = _("BESTÄTIGEN");
const u8 gText_Cancel[] = _("ZURÜCK");
const u8 gText_Cancel2[] = _("ZURÜCK");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("KEINS");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("-");
const u8 gText_TwoDashes[] = _("--");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("Lv.");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 1}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("Zurück zum\nvorherigen Menü.");
const u8 gText_WhatWouldYouLike[] = _("Was wetsch mache?");
const u8 gMenuText_Give2[] = _("GEBEN");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _(" BEERE"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1} MÜNZEN");
const u8 gText_CloseBag[] = _("BEUTEL SCHLIESSEN");
const u8 gText_Var1IsSelected[] = _("{STR_VAR_1}\nisch usgwählt.");
const u8 gText_CantWriteMail[] = _("Du chasch da\nkei MAIL schribe.");
const u8 gText_NoPokemon[] = _("Es isch keis\nPOKéMON da.");
const u8 gText_MoveVar1Where[] = _("Wohin soll\n{STR_VAR_1}\nverschoben werden?");
const u8 gText_Var1CantBeHeld[] = _("{STR_VAR_1} chan nöd\ngetragen werde.");
const u8 gText_TossHowManyVar1s[] = _("Wie vill\n{STR_VAR_1} wegwerfe?");
const u8 gText_ThrewAwayVar2Var1s[] = _("{STR_VAR_2}× {STR_VAR_1}\nwegworfe.");
const u8 gText_ConfirmTossItems[] = _("Würkli {STR_VAR_2}×\n{STR_VAR_1} wegwerfe?");
const u8 gText_DadsAdvice[] = _("PAPAS Rat…\n{PLAYER}, für alles git es\leine Ziit und en Ort!{PAUSE_UNTIL_PRESS}");
const u8 gText_PlayerUsedVar2[] = _("{PLAYER} setzt\n{STR_VAR_2} ii.{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("Aber de SCHUTZ\nwirkt immer no.{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("Aber de LOCKDUFT\nwirkt immer no.{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("Die BOX ist voll.{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("s Feld");
const u8 gText_TheBattle[] = _("de Kampf");
const u8 gText_ThePokemonList[] = _("die POKéMON-LISTE");
const u8 gText_TheShop[] = _("de Shop");
const u8 gText_ThePC[] = _("den PC");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("Zurück\n{STR_VAR_1}.");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS]      = COMPOUND_STRING("ITEMS"),
    [POCKET_POKE_BALLS] = COMPOUND_STRING("POKé BÄLLE"),
    [POCKET_TM_HM]      = COMPOUND_STRING("TMs & VMs"),
    [POCKET_BERRIES]    = COMPOUND_STRING("BEEREN"),
    [POCKET_KEY_ITEMS]  = COMPOUND_STRING("BASIS ITEMS")
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 3}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 17}{STR_VAR_1}{CLEAR 5}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("CHAUFE");
const u8 gText_ShopSell[] = _("VERCHAUFE");
const u8 gText_ShopQuit[] = _("TSCHÜSS");
const u8 gText_ThatItemIsSoldOut[] = _("Sorry, aber das gits nüme.{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("USVERKAUFT");
const u8 gText_InBagVar1[] = _("IM BEUTEL: {STR_VAR_1}");
const u8 gText_QuitShopping[] = _("Shop verlah.");
const u8 gText_Var1CertainlyHowMany[] = _("{STR_VAR_1}?\nWie vill wotsch ha?");
const u8 gText_Var1CertainlyHowMany2[] = _("{STR_VAR_1}?\nWie vill wotsch ha?");
const u8 gText_Var1AndYouWantedVar2[] = _("{STR_VAR_1}? Du wotsch {STR_VAR_2}?\nDas macht ¥{STR_VAR_3}.");
const u8 gText_Var1IsItThatllBeVar2[] = _("{STR_VAR_1}, gell?\nDas macht ¥{STR_VAR_2}. Passt?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("Du wotsch {STR_VAR_1}?\nDas macht ¥{STR_VAR_2}. Passt?");
const u8 gText_HereYouGoThankYou[] = _("Da, bitte.");
const u8 gText_ThankYouIllSendItHome[] = _("Da, bitte.\nIch schicks uf din PC.");
const u8 gText_ThanksIllSendItHome[] = _("Da, bitte.\nIch schicks uf din PC.");
const u8 gText_YouDontHaveMoney[] = _("Sorry NJIERI, du bisch zu\nbroke für das Item.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreRoomForThis[] = _("Du hesch kei Platz meh\nfür das Item.{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("Kei Platz meh für\n{STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("Bruchsch suscht no öppis?");
const u8 gText_CanIHelpWithAnythingElse[] = _("Bruchsch suscht no öppis?");
const u8 gText_ThrowInPremierBall[] = _("Ich leg der no en\nPREMIER BALL dezue.{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("Ich leg der no\n{STR_VAR_1} PREMIER BALLS dezue.{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{STR_VAR_2}? Nei sorry,\ndas chan ich nöd chaufe.{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("{STR_VAR_2}?\nWie vill wotsch verchaufe?");
const u8 gText_ICanPayVar1[] = _("Ich gib der ¥{STR_VAR_1}.\nPasst das?");
const u8 gText_TurnedOverVar1ForVar2[] = _("{STR_VAR_2} abgäh\nund ¥{STR_VAR_1} kassiert.");
const u8 gText_PokedollarVar1[] = _("¥{STR_VAR_1}");
const u8 gText_HP3[] = _("KP");
const u8 gText_SpAtk3[] = _("SP. ANG");
const u8 gText_SpDef3[] = _("SP. VER");
const u8 gText_WontHaveEffect[] = _("Das zeigt keine Wirkung.{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("Wähle {PKMN} zum Fusionieren.");
const u8 gText_CantBeUsedOnPkmn[] = _("Das kann bei diesem\nPOKéMON nicht genutzt werden.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("{STR_VAR_1} kann nicht\nausgewechselt werden!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1} ist bereits\nim Kampf!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1} wurde bereits\nausgewählt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1} hat keine Kraft\nmehr zum Kämpfen!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("Du kannst {STR_VAR_1}s\nPOKéMON nicht mit deinem tauschen!{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("Ein EI kann nicht kämpfen!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("Das geht erst, wenn du\neinen neuen ORDEN hast.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("Es dürfen höchstens {STR_VAR_1}\nPOKéMON teilnehmen.{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("Entfernte MAIL an\ndeinen PC senden?");
const u8 gText_MailSentToPC[] = _("Die MAIL wurde an deinen PC\ngesendet.{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("Das MAIL-FACH deines PCs\nist voll.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("Wenn die MAIL entfernt wird,\ngeht die Nachricht verloren. OK?");
const u8 gText_RemoveMailBeforeItem[] = _("MAIL muss entfernt werden,\nbevor ein Item getragen wird.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("{STR_VAR_1} trägt nun\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1} trägt bereits\n{STR_VAR_2}.\pMöchtest du die beiden\nItems tauschen?");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1} trägt\nnichts.{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("{STR_VAR_2} von\n{STR_VAR_1} erhalten.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("MAIL wurde dem\nPOKéMON abgenommen.{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("{STR_VAR_2} wurde genommen\nund durch {STR_VAR_1} ersetzt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("Dieses POKéMON trägt ein Item.\nEs kann keine MAIL tragen.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("MAIL wurde aus dem\nMAIL-FACH übertragen.{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("Der BEUTEL ist voll. Das Item\ndes POKéMON blieb dort.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{STR_VAR_1} erlernt\n{STR_VAR_2}!");
const u8 gText_PkmnLearnedMove4[] = _("{STR_VAR_1} erlernt\n{STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1} und {STR_VAR_2}\nsind nicht kompatibel.\p{STR_VAR_2} kann nicht\nerlernt werden.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1} möchte\n{STR_VAR_2} erlernen.\pAber {STR_VAR_1} kennt\nbereits vier Attacken.\pSoll eine Attacke vergessen\nund durch {STR_VAR_2} ersetzt werden?");
const u8 gText_StopLearningMove2[] = _("{STR_VAR_2} doch\nnicht beibringen?");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1} hat\n{STR_VAR_2} nicht erlernt.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("Welche Attacke soll vergessen werden?{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("1, {PAUSE 15}2 und{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Puff!\p{STR_VAR_1} hat vergessen,\nwie man {STR_VAR_2} einsetzt.\pUnd…{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1} kennt\n{STR_VAR_2} bereits.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("{STR_VAR_1}s KP wurden um\n{STR_VAR_2} Punkt(e) aufgefüllt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("{STR_VAR_1} wurde von\nVergiftung geheilt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1} wurde von\nParalyse geheilt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1} ist aufgewacht.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("{STR_VAR_1}s Verbrennung\nwurde geheilt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1}s Frostbeule\nwurde geheilt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1} ist aufgetaut.{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("AP wurden aufgefüllt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1} wurde geheilt.{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1} ist wieder fit.{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("{STR_VAR_1}s AP wurden erhöht.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1} erreicht\nLv. {STR_VAR_2}.");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1} erhält {STR_VAR_2} EP!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1} erhält {STR_VAR_2} EP\nund erreicht Lv. {STR_VAR_3}!");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_1}s Basiswert\n{STR_VAR_2} wurde erhöht.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1} wurde zutraulicher.\nBasiswert {STR_VAR_2} sank!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1} liebt dich!\nBasiswert {STR_VAR_2} sank!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1} wurde zutraulicher.\nBasiswert {STR_VAR_2} kann nicht sinken!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1} ist nicht mehr\nverwirrt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1} ist nicht mehr\nvernarrt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1} hat sich verwandelt!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("{STR_VAR_1}\nwegwerfen?");
const u8 gText_ItemThrownAway[] = _("{STR_VAR_1}\nwurde weggeworfen.{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("Welchem POKéMON beibringen?"); // Unused
const u8 gText_ChoosePokemon[] = _("Wähle ein POKéMON.");
const u8 gText_MoveToWhere[] = _("Wohin bewegen?");
const u8 gText_TeachWhichPokemon[] = _("Welchem POKéMON beibringen?");
const u8 gText_UseOnWhichPokemon[] = _("Bei welchem POKéMON nutzen?");
const u8 gText_GiveToWhichPokemon[] = _("Welchem POKéMON geben?");
const u8 gText_DoWhatWithPokemon[] = _("Was tun mit {PKMN}?");
const u8 gText_NothingToCut[] = _("Es gibt nichts zu ZERSCHNEIDEN.");
const u8 gText_CantSurfHere[] = _("Hier kannst du nicht SURFEN.");
const u8 gText_AlreadySurfing[] = _("Du SURFST bereits.");
const u8 gText_CantUseHere[] = _("Das geht hier nicht.");
const u8 gText_RestoreWhichMove[] = _("Welche Attacke auffüllen?");
const u8 gText_BoostPp[] = _("AP welcher Attacke erhöhen?");
const u8 gText_DoWhatWithItem[] = _("Was soll mit dem Item geschehen?");
const u8 gText_NoPokemonForBattle[] = _("Kein POKéMON kampffähig!");
const u8 gText_ChoosePokemon2[] = _("Wähle ein POKéMON.");
const u8 gText_NotEnoughHp[] = _("Nicht genug KP…");
const u8 gText_PokemonAreNeeded[] = _("{STR_VAR_1} POKéMON werden benötigt.");
const u8 gText_PokemonCantBeSame[] = _("POKéMON dürfen nicht gleich sein.");
const u8 gText_NoIdenticalHoldItems[] = _("Keine gleichen getragenen Items.");
const u8 gText_CurrentIsTooFast[] = _("Die Strömung ist viel zu stark!");
const u8 gText_DoWhatWithMail[] = _("Was tun mit der MAIL?");
const u8 gText_ChoosePokemonCancel[] = _("POKéMON wählen oder ZURÜCK.");
const u8 gText_ChoosePokemonConfirm[] = _("POKéMON wählen und bestätigen.");
const u8 gText_SendWhichMonToPC[] = _("Welches POKéMON an den PC senden?");
const u8 gText_MoveItemWhere[] = _("Item wohin bewegen?");
const u8 gText_XsYAnd[] = _("{STR_VAR_1}s {STR_VAR_2} und\n");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_1}s {STR_VAR_2} wurden getauscht!{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("Viel Spass beim Radfahren!");
const u8 gText_InUseAlready_PM[] = _("Das wird bereits genutzt.");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1} trägt bereits\n{STR_VAR_2}.");
const u8 gText_WhichAppliance[] = _("Welches Gerät\nbestellen?");
const u8 gText_NoUse[] = _("Keine Wirkung.");
const u8 gText_Able[] = _("MÖGLICH");
const u8 gText_First_PM[] = _("ERSTES");
const u8 gText_Second_PM[] = _("ZWEITES");
const u8 gText_Third_PM[] = _("DRITTES");
const u8 gText_Able2[] = _("MÖGLICH");
const u8 gText_NotAble[] = _("UNMÖGLICH");
const u8 gText_Able3[] = _("MÖGLICH!");
const u8 gText_NotAble2[] = _("UNMÖGLICH!");
const u8 gText_Learned[] = _("ERLERNT");
const u8 gText_Have[] = _("HAST");
const u8 gText_DontHave[] = _("FEHLT");
const u8 gText_Fourth[] = _("VIERTES");
const u8 gText_PkmnCantParticipate[] = _("Dieses POKéMON kann nicht teilnehmen.{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("Teilnahme abbrechen?");
const u8 gText_CancelBattle[] = _("Kampf abbrechen?");
const u8 gText_ReturnToWaitingRoom[] = _("Zum WARTERAUM zurück?");
const u8 gText_CancelChallenge[] = _("Herausforderung abbrechen?");
const u8 gText_EscapeFromHere[] = _("Von hier fliehen und nach\n{STR_VAR_1} zurück?");
const u8 gText_ReturnToHealingSpot[] = _("Zum letzten Heilpunkt in\n{STR_VAR_1} zurück?");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{STR_VAR_1}を ぐるぐるこうかんに\nだして よろしいですか？");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("Das ist dein einziges\nkampffähiges POKéMON.");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("Dieses POKéMON kann jetzt\nnicht getauscht werden.");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("Dieses POKéMON kann nicht\ngetauscht werden.");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("Ein EI kann jetzt nicht\ngetauscht werden.");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("Das POKéMON des anderen TRAINERS\nkann jetzt nicht getauscht werden.");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("Der andere TRAINER kann dieses\nPOKéMON jetzt nicht annehmen.");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("Du kannst mit diesem TRAINER\njetzt nicht tauschen.");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("Das ist nicht die Art POKéMON,\ndie der andere TRAINER will.");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("Das ist kein EI.");
const u8 gText_Register[] = _("REGISTRIEREN");
const u8 gText_Attack3[] = _("ANGRIFF");
const u8 gText_Defense3[] = _("VERTEIDIGUNG");
const u8 gText_SpAtk4[] = _("SP. ANG");
const u8 gText_SpDef4[] = _("SP. VER");
const u8 gText_Speed2[] = _("INIT");
const u8 gText_HP4[] = _("KP");
const u8 gText_EmptyString8[] = _(""); // Unused
const u8 gText_OTSlash[] = _("OT:");
const u8 gText_RentalPkmn[] = _("LEIH-POKéMON");
const u8 gText_TypeSlash[] = _("TYP/");
const u8 gText_Power[] = _("STÄRKE");
const u8 gText_Accuracy2[] = _("GENAU");
const u8 gText_Appeal[] = _("AUSDRUCK");
const u8 gText_Jam[] = _("STÖRUNG");
const u8 gText_Status[] = _("STATUS");
const u8 gText_ExpPoints[] = _("EP-PUNKTE");
const u8 gText_NextLv[] = _("NÄCHST. LV.");
const u8 gText_RibbonsVar1[] = _("BÄNDER: {STR_VAR_1}");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("EVENTS"); // Unused
const u8 gText_Switch[] = _("TAUSCHEN");
const u8 gText_PkmnInfo[] = _("POKéMON-INFO");
const u8 gText_PkmnSkills[] = _("POKéMON-WERTE");
const u8 gText_BattleMoves[] = _("KAMPFATTACKEN");
const u8 gText_ContestMoves[] = _("WETTBEWERBSATT.");
const u8 gText_Info[] = _("INFO");
const u8 gText_EggWillTakeALongTime[] = _("Dieses EI braucht wohl\nnoch sehr lange.");
const u8 gText_EggWillTakeSomeTime[] = _("Was daraus wohl schlüpft?\nEs dauert noch etwas.");
const u8 gText_EggWillHatchSoon[] = _("Es bewegt sich manchmal.\nEs schlüpft wohl bald.");
const u8 gText_EggAboutToHatch[] = _("Es macht Geräusche.\nEs schlüpft gleich!");
const u8 gText_HMMovesCantBeForgotten2[] = _("VM-Attacken können jetzt\nnicht vergessen werden.");
const u8 gText_XNatureMetAtYZ[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\ngetroffen mit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedAtYZ[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\ngeschlüpft mit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureObtainedInTrade[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\ndurch Tausch erhalten.");
const u8 gText_XNatureFatefulEncounter[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\ndurch schicksalhafte Begegnung\nmit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1} erhalten.");
const u8 gText_XNatureProbablyMetAt[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nwohl getroffen mit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNature[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}");
const u8 gText_XNatureMetSomewhereAt[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nirgendwo getroffen mit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedSomewhereAt[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nirgendwo geschlüpft mit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_OddEggFoundByCouple[] = _("Ein seltsames POKéMON-EI,\ngefunden beim PENSIONS-Paar.");
const u8 gText_PeculiarEggNicePlace[] = _("Ein besonderes POKéMON-EI,\nerhalten an einem schönen Ort.");
const u8 gText_PeculiarEggTrade[] = _("Ein besonderes POKéMON-EI,\ndurch Tausch erhalten.");
const u8 gText_EggFromHotSprings[] = _("Ein POKéMON-EI,\nerhalten bei den heissen Quellen.");
const u8 gText_EggFromTraveler[] = _("Ein seltsames POKéMON-EI,\nerhalten von einem Reisenden.");
const u8 gText_ApostropheSBase[] = _("S BASIS");
const u8 gText_OkayToDeleteFromRegistry[] = _("{STR_VAR_1} wirklich aus der\nREGISTRIERUNG löschen?");
const u8 gText_RegisteredDataDeleted[] = _("Registrierte Daten wurden gelöscht.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("Keine REGISTRIERUNG vorhanden.{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("REG. LÖSCH.");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("DEKORIEREN");
const u8 gText_PutAway[] = _("WEGRÄUMEN");
const u8 gText_Toss2[] = _("WEGWERFEN");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("Ausgewählte Deko platzieren.");
const u8 gText_StoreChosenDecorInPC[] = _("Gewählte Deko im PC lagern.");
const u8 gText_ThrowAwayUnwantedDecors[] = _("Ungewollte Deko wegwerfen.");
const u8 gText_NoDecorations[] = _("Keine Dekoration vorhanden.{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("TISCH");
const u8 gText_Chair[] = _("STUHL");
const u8 gText_Plant[] = _("PFLANZE");
const u8 gText_Ornament[] = _("ORNAMENT");
const u8 gText_Mat[] = _("MATTE");
const u8 gText_Poster[] = _("POSTER");
const u8 gText_Doll[] = _("PUPPE");
const u8 gText_Cushion[] = _("KISSEN");
const u8 gText_Gold[] = _("GOLD");
const u8 gText_Silver[] = _("SILBER");
const u8 gText_PlaceItHere[] = _("Hier platzieren?");
const u8 gText_CantBePlacedHere[] = _("Das kann hier nicht\nplatziert werden.");
const u8 gText_CancelDecorating[] = _("Dekorieren beenden?");
const u8 gText_InUseAlready[] = _("Das ist bereits in Gebrauch.");
const u8 gText_NoMoreDecorations[] = _("Es kann keine Deko mehr\nplatziert werden. Max.: {STR_VAR_1}.");
const u8 gText_NoMoreDecorations2[] = _("Es kann keine Deko mehr\nplatziert werden. Max.: {STR_VAR_1}.");
const u8 gText_MustBePlacedOnDesk[] = _("Das geht hier nicht.\nEs muss auf einen TISCH."); // Unused
const u8 gText_CantPlaceInRoom[] = _("Diese Deko kann nicht in\ndeinem Zimmer platziert werden.");
const u8 gText_CantThrowAwayInUse[] = _("Diese Deko ist in Gebrauch.\nSie kann nicht weggeworfen werden.");
const u8 gText_DecorationWillBeDiscarded[] = _("Diese Deko wird entsorgt.\nIst das okay?");
const u8 gText_DecorationThrownAway[] = _("Die Deko wurde weggeworfen.");
const u8 gText_StopPuttingAwayDecorations[] = _("Deko wegräumen beenden?");
const u8 gText_NoDecorationHere[] = _("Hier ist keine Deko.");
const u8 gText_ReturnDecorationToPC[] = _("Diese Deko an den PC senden?");
const u8 gText_DecorationReturnedToPC[] = _("Die Deko wurde an den PC gesendet.");
const u8 gText_NoDecorationsInUse[] = _("Es ist keine Deko in Gebrauch.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("Keine Items vorhanden.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("Hier ist keine MAIL.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("Was soll mit {STR_VAR_1}s\nMAIL geschehen?");
const u8 gText_MessageWillBeLost[] = _("Die Nachricht geht verloren.\nIst das okay?");
const u8 gText_BagIsFull[] = _("Der BEUTEL ist voll.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("Die MAIL ging zurück in den BEUTEL.\nDie Nachricht wurde gelöscht.{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("PAPA");
const u8 gText_Mom[] = _("MAMA");
const u8 gText_CoolnessContest[] = _("COOLNESS-WETTBEWERB");
const u8 gText_BeautyContest[] = _("SCHÖNHEITS-WETTBEWERB");
const u8 gText_CutenessContest[] = _("ANMUTS-WETTBEWERB");
const u8 gText_SmartnessContest[] = _("KLUGHEITS-WETTBEWERB");
const u8 gText_ToughnessContest[] = _("STÄRKE-WETTBEWERB");
const u8 gText_Information[] = _("INFORMATION");
const u8 gText_Yes[] = _("JA");
const u8 gText_No[] = _("NEIN");
const u8 gText_Lv50[] = _("Lv. 50");
const u8 gText_OpenLevel[] = _("OFFENES LV.");
const u8 gText_BattleFrontier[] = _("KAMPFZONE");
const u8 gText_Cool[] = _("COOL.");
const u8 gText_Beauty[] = _("SCHÖN");
const u8 gText_Cute[] = _("ANMUTIG");
const u8 gText_Smart[] = _("KLUG");
const u8 gText_Tough[] = _("STARK");
const u8 gText_Normal[] = _("NORMAL");
const u8 gText_Super[] = _("SUPER");
const u8 gText_Hyper[] = _("HYPER");
const u8 gText_Master[] = _("MASTER");
const u8 gText_SomeonesPC[] = _("FREMDER PC");
const u8 gText_LanettesPC[] = _("LANETTES PC");
const u8 gText_BillsPc[] = _("BILLS PC");
const u8 gText_PlayersPC[] = _("{PLAYER}s PC");
const u8 gText_HallOfFame[] = _("RUHMESHALLE");
const u8 gText_LogOff[] = _("ABMELDEN");
const u8 gText_Single2[] = _("EINZEL");
const u8 gText_Double2[] = _("DOPPEL");
const u8 gText_Multi[] = _("MULTI");
const u8 gText_MultiLink[] = _("MULTI-LINK");
const u8 gText_MenuOptionPokedex[] = _("POKéDEX");
const u8 gText_MenuOptionPokemon[] = _("POKéMON");
const u8 gText_MenuOptionBag[] = _("BEUTEL");
const u8 gText_MenuOptionPokenav[] = _("POKéNAV");
const u8 gText_MenuOptionSave[] = _("SPEICH.");
const u8 gText_MenuOptionOption[] = _("OPTIONEN");
const u8 gText_MenuOptionExit[] = _("ZURÜCK");
const u8 gText_SouthernIsland[] = _("SÜDLICHE INSEL");
const u8 gText_BirthIsland[] = _("ENTSTEHUNGSINSEL");
const u8 gText_FarawayIsland[] = _("FERNEILAND");
const u8 gText_NavelRock[] = _("NABELFELS");
const u8 gText_NormalTagMatch[] = _("NORMALER TAG-KAMPF");
const u8 gText_VarietyTagMatch[] = _("VARIABLER TAG-KAMPF");
const u8 gText_UniqueTagMatch[] = _("EINZIGART. TAG-KAMPF");
const u8 gText_ExpertTagMatch[] = _("EXPERTEN-TAG-KAMPF");
const u8 gText_BattleBasics[] = _("KAMPF-GRUNDLAGEN");
const u8 gText_PokemonNature[] = _("POKéMON-WESEN");
const u8 gText_PokemonMoves[] = _("POKéMON-ATTACKEN");
const u8 gText_Underpowered[] = _("ZU SCHWACH");
const u8 gText_WhenInDanger[] = _("BEI GEFAHR");
const u8 gText_BattlePokemon[] = _("KAMPF-POKéMON");
const u8 gText_BattleTrainers[] = _("KAMPF-TRAINER");
const u8 gText_1F[] = _("EG");
const u8 gText_2F[] = _("1. OG");
const u8 gText_3F[] = _("2. OG");
const u8 gText_4F[] = _("3. OG");
const u8 gText_5F[] = _("4. OG");
const u8 gText_6F[] = _("5. OG");
const u8 gText_7F[] = _("6. OG");
const u8 gText_8F[] = _("7. OG");
const u8 gText_9F[] = _("8. OG");
const u8 gText_10F[] = _("9. OG");
const u8 gText_11F[] = _("10. OG");
const u8 gText_B1F[] = _("UG1");
const u8 gText_B2F[] = _("UG2");
const u8 gText_B3F[] = _("UG3");
const u8 gText_B4F[] = _("UG4");
const u8 gText_Rooftop[] = _("DACH");
const u8 gText_ElevatorNowOn[] = _("Jetzt auf:");
const u8 gText_BP[] = _("GP");
const u8 gText_RankingHall[] = _("RANGLISTE");
const u8 gText_ExchangeService[] = _("TAUSCHSERVICE");
const u8 gText_SlateportCity[] = _("GRAPHITPORT CITY");
const u8 gText_Exit[] = _("ZURÜCK");
const u8 gText_YourPartysFull[] = _("Dein Team ist voll!{PAUSE_UNTIL_PRESS}");
const u8 gText_InParty[] = _("IM TEAM");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("Kombiniere vier Wörter oder Sätze");
const u8 gText_AndMakeYourProfile[] = _("und erstelle dein Profil.");
const u8 gText_CombineSixWordsOrPhrases[] = _("Kombiniere sechs Wörter oder Sätze");
const u8 gText_AndMakeAMessage[] = _("und erstelle eine Nachricht.");
const u8 gText_FindWordsThatDescribeYour[] = _("Finde Wörter, die deine");
const u8 gText_FeelingsRightNow[] = _("aktuellen Gefühle beschreiben.");
const u8 gText_WithFourPhrases[] = _("Mit vier Sätzen,"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("Kombiniere neun Wörter oder Sätze");
const u8 gText_AndMakeAMessage2[] = _("und erstelle eine Nachricht.");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("Ändere nur ein Wort oder Satzteil");
const u8 gText_AndImproveTheBardsSong[] = _("und verbessere das Lied des Barden.");
const u8 gText_YourProfile[] = _("Dein Profil");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("Dein Gefühl bei Kampfbeginn");
const u8 gText_WhatYouSayIfYouWin[] = _("Was du nach einem Sieg sagst");
const u8 gText_WhatYouSayIfYouLose[] = _("Was du nach einer Niederlage sagst");
const u8 gText_TheAnswer[] = _("Die Antwort");
const u8 gText_TheMailMessage[] = _("Die MAIL-Nachricht");
const u8 gText_TheMailSalutation[] = _("Die MAIL-Anrede"); // Unused
const u8 gText_TheBardsSong2[] = _("Das neue Lied");
const u8 gText_CombineTwoWordsOrPhrases[] = _("Kombiniere zwei Wörter oder Sätze");
const u8 gText_AndMakeATrendySaying[] = _("und erstelle einen Trend-Spruch.");
const u8 gText_TheTrendySaying[] = _("Der Trend-Spruch");
const u8 gText_IsAsShownOkay[] = _("wird so angezeigt. OK?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("Kombiniere zwei Wörter oder Sätze");
const u8 gText_ToTeachHerAGoodSaying[] = _("und bring ihr einen guten Spruch bei.");
const u8 gText_FindWordsWhichFit[] = _("Finde passende Wörter");
const u8 gText_TheTrainersImage[] = _("zum Image des TRAINERS.");
const u8 gText_TheImage[] = _("Das Image:");
const u8 gText_OutOfTheListedChoices[] = _("Wähle aus den Optionen");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("die Antwort auf das Quiz!");
const u8 gText_AndCreateAQuiz[] = _("und erstelle ein Quiz!");
const u8 gText_PickAWordOrPhraseAnd[] = _("Wähle ein Wort oder einen Satz");
const u8 gText_SetTheQuizAnswer[] = _("und lege die Quizantwort fest.");
const u8 gText_TheAnswerColon[] = _("Die Antwort:");
const u8 gText_TheQuizColon[] = _("Das Quiz:"); // Unused
const u8 gText_ApprenticePhrase[] = _("Spruch des Lehrlings:");
const u8 gText_QuitEditing[] = _("Bearbeitung beenden?");
const u8 gText_StopGivingPkmnMail[] = _("POKéMON keine MAIL mehr geben?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("und fülle den Fragebogen aus.");
const u8 gText_LetsReplyToTheInterview[] = _("Beantworte das Interview!");
const u8 gText_AllTextBeingEditedWill[] = _("Der bearbeitete Text wird");
const u8 gText_BeDeletedThatOkay[] = _("gelöscht. Ist das okay?");
const u8 gText_QuitEditing2[] = _("Bearbeitung beenden?"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("Der bearbeitete Text wird nicht gespeichert."); // Unused
const u8 gText_IsThatOkay[] = _("Ist das okay?"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("Bitte gib ein Wort oder einen Satz ein."); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("Der ganze Text kann nicht gelöscht werden.");
const u8 gText_OnlyOnePhrase[] = _("Nur ein Satzteil darf geändert werden.");
const u8 gText_OriginalSongWillBeUsed[] = _("Das ursprüngliche Lied wird genutzt.");
const u8 gText_ThatsTrendyAlready[] = _("Das ist schon trendy!"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("Kombiniere zwei Wörter oder Sätze.");
const u8 gText_QuitGivingInfo[] = _("Informationseingabe beenden?"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("POKéMON keine MAIL mehr geben?"); // Unused
const u8 gText_CreateAQuiz2[] = _("Quiz erstellen!"); // Unused
const u8 gText_SetTheAnswer[] = _("Antwort festlegen!"); // Unused
const u8 gText_CancelSelection[] = _("Auswahl abbrechen?"); // Unused
const u8 gText_Profile[] = _("PROFIL");
const u8 gText_AtTheBattlesStart[] = _("Bei Kampfbeginn:");
const u8 gText_UponWinningABattle[] = _("Nach einem Sieg:");
const u8 gText_UponLosingABattle[] = _("Nach einer Niederlage:");
const u8 gText_TheBardsSong[] = _("Das Lied des Barden");
const u8 gText_WhatsHipAndHappening[] = _("Was ist gerade angesagt?");
const u8 gText_Interview[] = _("Interview");
const u8 gText_GoodSaying[] = _("Guter Spruch");
const u8 gText_FansQuestion[] = _("Fan-Frage");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは？"); // Unused
const u8 gText_ApprenticesPhrase[] = _("Spruch des Lehrlings");
const u8 gText_Questionnaire[] = _("FRAGEBOGEN");
const u8 gText_YouCannotQuitHere[] = _("Hier kannst du nicht abbrechen.");
const u8 gText_SectionMustBeCompleted[] = _("Dieser Abschnitt muss fertig sein.");
const u8 gText_F700sQuiz[] = _("{DYNAMIC 0}s Quiz");
const u8 gText_Lady[] = _("Dame");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("Wenn du die Quizfrage gelesen hast,");
const u8 gText_QuestionPressTheAButton[] = _("drücke den A-Knopf.");
const u8 gText_TheQuizAnswerIs[] = _("Die Quizantwort lautet?");
const u8 gText_LikeToQuitQuiz[] = _("Möchtest du diese Quiz-");
const u8 gText_ChallengeQuestionMark[] = _("Herausforderung beenden?");
const u8 gText_IsThisQuizOK[] = _("Ist dieses Quiz OK?");
const u8 gText_CreateAQuiz[] = _("Quiz erstellen!");
const u8 gText_SelectTheAnswer[] = _("Antwort wählen!");
const u8 gText_LyricsCantBeDeleted[] = _("Der Liedtext kann nicht gelöscht werden.");
const u8 gText_PokemonLeague[] = _("POKéMON-LIGA");
const u8 gText_PokemonCenter[] = _("POKéMON-CENTER");
const u8 gText_Coolness[] = _("Coolness ");
const u8 gText_Beauty3[] = _("Schönheit ");
const u8 gText_Cuteness[] = _("Anmut ");
const u8 gText_Smartness[] = _("Klugheit ");
const u8 gText_Toughness[] = _("Stärke ");
const u8 gText_SaveFailedCheckingBackup[] = _("Speichern fehlgeschlagen.\nBackup-Speicher wird geprüft…\n{COLOR RED}Dauer: ca. 1 Minute");
const u8 gText_BackupMemoryDamaged[] = _("Backup-Speicher beschädigt,\noder Batterie leer.\nSpielen geht, Speichern nicht.");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}Spiel kann nicht fortgesetzt werden.\nZurück zum Titelbildschirm…");
const u8 gText_CheckCompleted[] = _("Prüfung fertig.\nSpeichern wird erneut versucht.\nBitte warten.");
const u8 gText_SaveCompleteGameCannotContinue[] = _("Speichern abgeschlossen.\n{COLOR RED}Spiel kann nicht fortgesetzt werden.\nZurück zum Titelbildschirm.");
const u8 gText_SaveCompletePressA[] = _("Speichern abgeschlossen.\n{COLOR RED}Bitte A-Knopf drücken.");
const u8 gText_Ferry[] = _("FÄHRE");
const u8 gText_SecretBase[] = _("GEHEIMBASIS");
const u8 gText_Hideout[] = _("VERSTECK");
const u8 gText_ResetRTCConfirmCancel[] = _("RTC zurücksetzen?\nA: Bestätigen, B: Zurück");
const u8 gText_PresentTime[] = _("Aktuelle Spielzeit");
const u8 gText_PreviousTime[] = _("Vorherige Spielzeit");
const u8 gText_PleaseResetTime[] = _("Bitte stelle die Zeit neu ein.");
const u8 gText_ClockHasBeenReset[] = _("Die Uhr wurde zurückgesetzt.\nDaten werden gespeichert. Bitte warten.");
const u8 gText_SaveCompleted[] = _("Speichern abgeschlossen.");
const u8 gText_SaveFailed[] = _("Speichern fehlgeschlagen…");
const u8 gText_NoSaveFileCantSetTime[] = _("Keine Speicherdatei vorhanden.\nZeit kann nicht eingestellt werden.");
const u8 gText_InGameClockUsable[] = _("Die Spieluhr kann jetzt\nangepasst werden.");
const u8 gText_Spicy2[] = _("scharf");
const u8 gText_Dry2[] = _("trocken");
const u8 gText_Sweet2[] = _("süss");
const u8 gText_Bitter2[] = _("bitter");
const u8 gText_Sour2[] = _("sauer");
const u8 gText_Single[] = _("EINZEL");
const u8 gText_Double[] = _("DOPPEL");
const u8 gText_Knockout[] = _("K.O.");
const u8 gText_Mixed[] = _("GEMISCHT");
const u8 gText_First[] = _("erstes");
const u8 gText_Second[] = _("zweites");
const u8 gText_Third[] = _("drittes");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} wurde besiegt…\p\n");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} hat die Vergiftung\nüberstanden. Das Gift verschwand!\p");
#endif
const u8 gText_Marco[] = _("MARCO");
const u8 gText_TrainerCardName[] = _("NAME ");
const u8 gText_TrainerCardIDNo[] = _("ID-Nr.");
const u8 gText_TrainerCardMoney[] = _("GELD");
const u8 gText_PokeDollar[] = _("¥"); // Unused
const u8 gText_TrainerCardPokedex[] = _("POKéDEX");
const u8 gText_EmptyString6[] = _("");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _(" Punkte"); // Unused
const u8 gText_TrainerCardTime[] = _("ZEIT");
const u8 gJPText_BattlePoints[] = _("ゲ-ムポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("{STR_VAR_1}s TRAINERPASS");
const u8 gText_HallOfFameDebut[] = _("RUHMESHALLE-DEBÜT  ");
const u8 gText_LinkBattles[] = _("LINK-KÄMPFE");
const u8 gText_LinkCableBattles[] = _("LINKKABEL-KÄMPFE");
const u8 gText_WinsLosses[] = _("S:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  N:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("POKéMON-TAUSCH");
const u8 gText_UnionTradesAndBattles[] = _("UNION-TAUSCH & KÄMPFE");
const u8 gText_BerryCrush[] = _("BEEREN-CRUSH");
const u8 gText_WaitingTrainerFinishReading[] = _("Warten, bis der andere TRAINER\ndeinen TRAINERPASS gelesen hat.");
const u8 gText_PokeblocksWithFriends[] = _("{POKEBLOCK}S MIT FREUNDEN");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("WETTBEW. MIT FREUNDEN");
const u8 gText_BattlePtsWon[] = _("GEWONNENE GP");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}GP");
const u8 gText_BattleTower[] = _("DUELLTURM");
const u8 gText_WinsStraight[] = _("S/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  SERIE/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("KAMPFTURM");
const u8 gText_BattleDome[] = _("KAMPFARENA");
const u8 gText_BattlePalace[] = _("KAMPFPALAST");
const u8 gText_BattleFactory[] = _("KAMPFFABRIK");
const u8 gText_BattleArena[] = _("KAMPFARENA");
const u8 gText_BattlePike[] = _("KAMPFVIPER");
const u8 gText_BattlePyramid[] = _("KAMPFPYRAMIDE");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} EINZEL");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} DOPPEL");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} MULTI");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} LINK");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("Geben");
const u8 gText_NoNeed[] = _("Nicht nötig");
const u8 gText_AnnouncingResults[] = _("Die Ergebnisse werden verkündet!");
const u8 gText_PreliminaryResults[] = _("Die Zwischenergebnisse!");
const u8 gText_Round2Results[] = _("Ergebnisse von Runde 2!");
const u8 gText_ContestantsMonWon[] = _("{STR_VAR_1}s {STR_VAR_2} hat gewonnen!");
const u8 gText_CommunicationStandby[] = _("Kommunikation läuft…");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{BACKGROUND WHITE}{TEXT_COLORS DYNAMIC_COLOR6 DYNAMIC_COLOR5 WHITE}"); // Unused
const u8 gText_HealthboxNickname[] = _("{BACKGROUND DARK_GRAY}{ACCENT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("GROSS");
const u8 gText_Lower[] = _("klein");
const u8 gText_Others[] = _("SONSTIGE");
const u8 gText_Symbols[] = _("SYMBOLE");
const u8 gText_Register2[] = _("REGISTRIEREN");
const u8 gText_Exit2[] = _("ZURÜCK");
const u8 gText_QuitChatting[] = _("Chat beenden?");
const u8 gText_RegisterTextWhere[] = _("Text wo registrieren?");
const u8 gText_RegisterTextHere[] = _("Text hier registrieren?");
const u8 gText_InputText[] = _("Text eingeben.");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0} ist dem Chat beigetreten!");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0} hat den Chat verlassen.");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("Chat wird beendet…");
const u8 gText_LeaderLeftEndingChat[] = _("LEITER {DYNAMIC 0} ist gegangen.\nDer Chat wird beendet.");
const u8 gText_RegisteredTextChangedOKToSave[] = _("Der registrierte Text wurde geändert.\nSpiel speichern?");
const u8 gText_AlreadySavedFile_Chat[] = _("Es gibt bereits eine Datei.\nÜberschreiben?");
const u8 gText_SavingDontTurnOff_Chat[] = _("SPEICHERN…\nNICHT AUSSCHALTEN.");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0} hat gespeichert.");
const u8 gText_IfLeaderLeavesChatEnds[] = _("Wenn der LEITER geht,\nwird der Chat beendet. OK?");
const u8 gText_Hello[] = _("HALLO");
const u8 gText_Pokemon2[] = _("POKéMON");
const u8 gText_Trade[] = _("TAUSCH");
const u8 gText_Battle[] = _("KAMPF");
const u8 gText_Lets[] = _("LOS");
const u8 gText_Ok[] = _("O.K.!");
const u8 gText_Sorry[] = _("SORRY");
const u8 gText_YaySmileEmoji[] = _("YEAH{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("DANKE");
const u8 gText_ByeBye[] = _("TSCHÜSS!");
const u8 gText_HatchedFromEgg[] = _("{STR_VAR_1} ist aus dem EI geschlüpft!");
const u8 gText_NicknameHatchPrompt[] = _("Möchtest du dem frisch geschlüpften\n{STR_VAR_1} einen Spitznamen geben?");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("Bereit für BEEREN-CRUSH?\nWähle bitte eine BEERE aus.\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("Bitte warten, bis alle\nMitspieler eine BEERE wählen.");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}Du hast {STR_VAR_1} Einheiten\nseidenfeines BEERENPULVER erhalten.{RESUME_MUSIC}\pDeine Gesamtmenge an BEERENPULVER\nbeträgt {STR_VAR_2}.\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("Spielergebnisse werden in der\nSpeicherdatei gesichert.\lBitte warten.");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("BEEREN-CRUSH erneut spielen?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("Du hast keine BEEREN.\nDas Spiel wird beendet.");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("Ein Mitspieler ist ausgestiegen.\nDas Spiel wird beendet.");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("Zeit vorbei.\pGutes BEERENPULVER konnte\nnicht hergestellt werden…\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("Kommunikation läuft…");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _(" Mal");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("{STR_VAR_1}-BEERE");
ALIGNED(4) const u8 gText_TimeColon[] = _("Zeit:");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("Drücktempo:");
ALIGNED(4) const u8 gText_Silkiness[] = _("Feinheit:");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _(" Min. ");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _(" Sek.");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _(" Mal/Sek.");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1} %");
ALIGNED(4) const u8 gText_PressesRankings[] = _("Rangliste Tastendrücke");
ALIGNED(4) const u8 gText_CrushingResults[] = _("Crush-Ergebnisse");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("Feinheits-Rangliste");
ALIGNED(4) const u8 gText_CoopRankings[] = _("Teamwork-Rangliste");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("Druckkraft-Rangliste");
const u8 gText_BerryCrush2[] = _("BEEREN-CRUSH");
const u8 gText_PressingSpeedRankings[] = _("Drücktempo-Rangliste");
const u8 gText_Var1Players[] = _("{STR_VAR_1} SPIELER");
const u8 gText_SymbolsEarned[] = _("Erhaltene Symbole");
const u8 gText_BattleRecord[] = _("Kampfrekord");
const u8 gText_BattlePoints[] = _("Gewinnpunkte");
const u8 gText_UnusedCancel[] = _("ZURÜCK"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("KAMPFZONEN-KARTE ansehen.");
const u8 gText_CheckTrainerCard[] = _("TRAINERPASS ansehen.");
const u8 gText_ViewRecordedBattle[] = _("Aufgezeichneten Kampf ansehen.");
const u8 gText_PutAwayFrontierPass[] = _("KAMPFZONEN-PASS weglegen.");
const u8 gText_CurrentBattlePoints[] = _("Deine aktuellen Gewinnpunkte.");
const u8 gText_CollectedSymbols[] = _("Deine gesammelten Symbole.");
const u8 gText_BattleTowerAbilitySymbol[] = _("Kampfturm - Fähigkeitssymbol");
const u8 gText_BattleDomeTacticsSymbol[] = _("Kampfkuppel - Taktiksymbol");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("Kampfpalast - Spiritsymbol");
const u8 gText_BattleArenaGutsSymbol[] = _("Kampfarena - Mutsymbol");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("Kampffabrik - Wissenssymbol");
const u8 gText_BattlePikeLuckSymbol[] = _("Kampfviper - Glückssymbol");
const u8 gText_BattlePyramidBraveSymbol[] = _("Kampfpyramide - Tapferkeitssymbol");
const u8 gText_ThereIsNoBattleRecord[] = _("Es gibt keinen Kampfrekord.");
const u8 gText_BattleTower3[] = _("KAMPFTURM");
const u8 gText_BattleDome2[] = _("KAMPFKUPPEL");
const u8 gText_BattlePalace2[] = _("KAMPFPALAST");
const u8 gText_BattleArena2[] = _("KAMPFARENA");
const u8 gText_BattleFactory2[] = _("KAMPFFABRIK");
const u8 gText_BattlePike2[] = _("KAMPFVIPER");
const u8 gText_BattlePyramid2[] = _("KAMPFPYRAMIDE");
const u8 gText_BattleTowerDesc[] = _("Besiege Gegner und strebe zur Spitze!\nDeine Fähigkeit wird geprüft.");
const u8 gText_BattleDomeDesc[] = _("Gewinne im Turnier weiter!\nDeine Taktik wird geprüft.");
const u8 gText_BattlePalaceDesc[] = _("Sieh deinen POKéMON beim Kampf zu!\nDein Geist wird geprüft.");
const u8 gText_BattleArenaDesc[] = _("Gewinne mit Team-POKéMON!\nDein Mut wird geprüft.");
const u8 gText_BattleFactoryDesc[] = _("Siege mit Leih-POKéMON!\nDein Wissen wird geprüft.");
const u8 gText_BattlePikeDesc[] = _("Wähle einen von drei Wegen!\nDein Glück wird geprüft.");
const u8 gText_BattlePyramidDesc[] = _("Erkunde alles bis zur Spitze!\nDeine Tapferkeit wird geprüft.");
const u8 gText_Powder[] = _("PULVER");
const u8 gText_BerryPickingRecords[] = _("DODRI-BEERENPFLÜCK-REKORDE");
const u8 gText_BerriesPicked[] = _("Gepflückte BEEREN:");
const u8 gText_BestScore[] = _("Bestpunktzahl:");
const u8 gText_BerriesInRowFivePlayers[] = _("BEEREN in Folge gepflückt\nmit fünf Spielern:");
const u8 gText_BerryPickingResults[] = _("BEERENPFLÜCK-Ergebnisse!");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 3}10P{CLEAR_TO 43}30P{CLEAR_TO 83}50P{CLEAR_TO 119}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("Rangliste wird verkündet!");
const u8 gText_AnnouncingPrizes[] = _("Preise werden verkündet!");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("Der Sieger erhält\n{DYNAMIC 0}!");
const u8 gText_CantHoldAnyMore[] = _("Du kannst nicht mehr tragen!");
const u8 gText_FilledStorageSpace[] = _("Der Lagerplatz ist voll.");
const u8 gText_WantToPlayAgain[] = _("Noch einmal spielen?");
const u8 gText_SomeoneDroppedOut[] = _("Jemand ist ausgestiegen.\nDie Verbindung wird beendet.");
const u8 gText_SpacePoints[] = _(" Punkte");
const u8 gText_CommunicationStandby3[] = _("Kommunikation läuft…");
const u8 gText_SpacePoints2[] = _(" Punkte");
const u8 gText_SpaceTimes3[] = _(" Mal");
const u8 gText_PkmnJumpRecords[] = _("POKéMON-SPRUNG-REKORDE");
const u8 gText_JumpsInARow[] = _("Sprünge in Folge:");
const u8 gText_BestScore2[] = _("Bestpunktzahl:");
const u8 gText_ExcellentsInARow[] = _("PERFEKT in Folge:");
const u8 gText_AwesomeWonF701F700[] = _("Starkes Ergebnis!\nDu erhältst {DYNAMIC 1} {DYNAMIC 0}!");
const u8 gText_FilledStorageSpace2[] = _("Der Lagerplatz ist voll.");
const u8 gText_CantHoldMore[] = _("Du kannst nicht mehr tragen!");
const u8 gText_WantToPlayAgain2[] = _("Noch einmal spielen?");
const u8 gText_SomeoneDroppedOut2[] = _("Jemand ist ausgestiegen.\nDie Verbindung wird beendet.");
const u8 gText_CommunicationStandby4[] = _("Kommunikation läuft…");
const u8 gText_LinkContestResults[] = _("{PLAYER}s Link-Wettbewerb-Ergebnisse");
const u8 gText_1st[] = _("1.");
const u8 gText_2nd[] = _("2.");
const u8 gText_3rd[] = _("3.");
const u8 gText_4th[] = _("4.");
const u8 gText_Friend[] = _("Freund");
const u8 gText_Pokemon3[] = _("POKéMON"); // Unused
const u8 gJPText_MysteryGift[] = _("GEHEIMGESCHEHEN");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}OK {B_BUTTON}ZURÜCK");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("Mit dem Karten-e-Reader{PLUS}\nwird das GEHEIMGESCHEHEN gelesen.");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("Wähle im Menü des Karten-e-Readers{PLUS}\nden Punkt Kommunikation.");
const u8 gJPText_SelectConnectWithGBA[] = _("Wähle Verbindung mit\nGAME BOY ADVANCE.");
const u8 gJPText_SelectConnectAndPressA[] = _("Wähle Kommunikation\nund drücke den A-Knopf."); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("Die Verbindung ist fehlerhaft.");
const u8 gJPText_CardReadingHasBeenHalted[] = _("Das Lesen der Karte\nwurde abgebrochen.");
const u8 gJPText_UnableConnectWithEReader[] = _("Verbindung zum Karten-e-Reader{PLUS}\nnicht möglich."); // Unused
const u8 gJPText_Connecting[] = _("Kommunikation läuft.");
const u8 gJPText_ConnectionErrorCheckLink[] = _("Verbindungsfehler.\nBitte Verbindung prüfen.");
const u8 gJPText_ConnectionErrorTryAgain[] = _("Verbindungsfehler.\nBitte erneut versuchen."); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("Bitte Karte in den\nKarten-e-Reader{PLUS} einlesen.");
const u8 gJPText_ConnectionComplete[] = _("Kommunikation abgeschlossen!");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("Ein neuer TRAINER\nist nach HOENN gekommen!");
const u8 gJPText_PleaseWaitAMoment[] = _("Bitte kurz warten.");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("Schreibfehler.\nDaten konnten nicht gespeichert werden.");
const u8 gText_SingleBattleRoomResults[] = _("{PLAYER}s Einzelkampf-Raum-Ergebnisse");
const u8 gText_DoubleBattleRoomResults[] = _("{PLAYER}s Doppelkampf-Raum-Ergebnisse");
const u8 gText_MultiBattleRoomResults[] = _("{PLAYER}s Multi-Kampf-Raum-Ergebnisse");
const u8 gText_LinkMultiBattleRoomResults[] = _("{PLAYER}s Link-Multi-Raum-Ergebnisse");
const u8 gText_SingleBattleTourneyResults[] = _("{PLAYER}s Einzelkampf-Turnier-Ergebnisse");
const u8 gText_DoubleBattleTourneyResults[] = _("{PLAYER}s Doppelkampf-Turnier-Ergebnisse");
const u8 gText_SingleBattleHallResults[] = _("{PLAYER}s Einzelkampf-Hallen-Ergebnisse");
const u8 gText_DoubleBattleHallResults[] = _("{PLAYER}s Doppelkampf-Hallen-Ergebnisse");
const u8 gText_BattleChoiceResults[] = _("{PLAYER}s Kampfwahl-Ergebnisse");
const u8 gText_SetKOTourneyResults[] = _("{PLAYER}s K.O.-Turnier-Ergebnisse");
const u8 gText_BattleSwapSingleResults[] = _("{PLAYER}s Leih-Tausch-Einzel-Ergebnisse");
const u8 gText_BattleSwapDoubleResults[] = _("{PLAYER}s Leih-Tausch-Doppel-Ergebnisse");
const u8 gText_BattleQuestResults[] = _("{PLAYER}s Kampfquest-Ergebnisse");
const u8 gText_Lv502[] = _("Lv. 50");
const u8 gText_OpenLv[] = _("OFFENES LV.");
const u8 gText_WinStreak[] = _("Siegesserie: {STR_VAR_1}");
const u8 gText_Current[] = _("AKTUELL");
const u8 gText_Record[] = _("REKORD");
const u8 gText_Prev[] = _("VORHER");
const u8 gText_RentalSwap[] = _("Leih/Tausch");
const u8 gText_Total[] = _("Gesamt");
const u8 gText_ClearStreak[] = _("Abschlussserie: {STR_VAR_1}");
const u8 gText_Championships[] = _("Meistertitel: {STR_VAR_1}");
const u8 gText_RoomsCleared[] = _("Räume geschafft: {STR_VAR_1}");
const u8 gText_TimesCleared[] = _("Geschafft:{CLEAR 5}{STR_VAR_1}");
const u8 gText_KOsInARow[] = _("K.O.s in Folge: {STR_VAR_1}");
const u8 gText_TimesVar1[] = _("Mal: {STR_VAR_1}");
const u8 gText_FloorsCleared[] = _("Etagen geschafft: {STR_VAR_1}");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("Lv. 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("OFFENES LEVEL");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("Siegesserie: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("Abschlussserie: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("Räume geschafft: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("K.O.s in Folge: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("Etagen geschafft: {STR_VAR_2}");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _(" und {STR_VAR_2} deiner gefangenen\nPOKéMON-Arten sind nicht zugelassen");
const u8 gText_FrontierFacilityIncluding[] = _(".\pDazu zählen ");
const u8 gText_FrontierFacilityAreInelegible[] = _(" sind nicht zugelassen");

const u8 gText_YesNo[] = _("JA\nNEIN");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("GUCKGUCK!");
const u8 gText_CommErrorCheckConnections[] = _("Kommunikationsfehler…\nBitte Verbindungen prüfen,\ndann aus- und einschalten.");
const u8 gText_CommErrorEllipsis[] = _("Kommunikationsfehler…");
const u8 gText_MoveCloserToLinkPartner[] = _("Geh näher zum Link-Partner.\nHindernisse vermeiden.");
const u8 gText_ABtnRegistrationCounter[] = _("A-Knopf: Registrierung");
const u8 gText_ABtnTitleScreen[] = _("A-Knopf: Titelbildschirm");
const u8 gText_NumPlayerLink[] = _("{STR_VAR_1}SP-LINK");
const u8 gText_BronzeCard[] = _("BRONZE");
const u8 gText_CopperCard[] = _("KUPFER");
const u8 gText_SilverCard[] = _("SILBER");
const u8 gText_GoldCard[] = _("GOLD");
const u8 gText_Day[] = _("TAG");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("BESTÄTIGEN");
const u8 gText_Days[] = _("Tage"); // Unused
const u8 gText_TimeColon2[] = _("Zeit:"); // Unused
const u8 gText_GameTime[] = _("Spielzeit"); // Unused
const u8 gText_RTCTime[] = _("RTC-Zeit"); // Unused
const u8 gText_UpdatedTime[] = _("Neue Zeit"); // Unused
const u8 gText_MenuPokedex[] = _("POKéDEX");
const u8 gText_MenuPokemon[] = _("POKéMON");
const u8 gText_MenuBag[] = _("BEUTEL");
const u8 gText_MenuPokenav[] = _("POKéNAV");
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("SPEICH.");
const u8 gText_MenuOption[] = _("OPTIONEN");
const u8 gText_MenuExit[] = _("ZURÜCK");
const u8 gText_MenuRetire[] = _("AUFGEBEN");
const u8 gText_MenuRest[] = _("PAUSE");
const u8 gText_MenuDexNav[] = _("DEXNAV");
const u8 gText_SafariBallStock[] = _("SAFARI-BÄLLE\nVorrat: {STR_VAR_1}");
const u8 gText_MenuSafariStats[] = _("{STR_VAR_1}/{STR_VAR_2}\nBÄLLE  {STR_VAR_3}");
const u8 gText_BattlePyramidFloor[] = _("Kampfpyramide\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("Etage 1");
const u8 gText_Floor2[] = _("Etage 2");
const u8 gText_Floor3[] = _("Etage 3");
const u8 gText_Floor4[] = _("Etage 4");
const u8 gText_Floor5[] = _("Etage 5");
const u8 gText_Floor6[] = _("Etage 6");
const u8 gText_Floor7[] = _("Etage 7");
const u8 gText_Peak[] = _("Spitze");
const u8 gText_LinkStandby2[] = _("Link-Bereitschaft…\n… … B-Knopf: Zurück");
const u8 gText_PressAToLoadEvent[] = _("A-Knopf drücken, um Event zu laden.\n… … B-Knopf: Zurück");
const u8 gText_LoadingEvent[] = _("Event wird geladen…");
const u8 gText_DontRemoveCableTurnOff[] = _("Linkkabel nicht entfernen.\nNicht ausschalten.");
const u8 gText_EventSafelyLoaded[] = _("Das Event wurde sicher geladen.");
const u8 gText_LoadErrorEndingSession[] = _("Ladefehler.\nSitzung wird beendet.");
const u8 gJPText_Player[] = _("SPIELER"); // Unused
const u8 gJPText_Sama[] = _(""); // Unused
const u8 gText_DexHoenn[] = _("HOENN");
const u8 gText_DexNational[] = _("NATIONALER");
const u8 gText_PokedexDiploma[] = _("SPIELER: {CLEAR 16}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\nDieses Dokument bestätigt,\ndass du deinen\n{STR_VAR_1} POKéDEX\nerfolgreich vervollständigt hast.\n\n{CLEAR_TO 66}{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("HOENN");
const u8 gText_Kanto[] = _("KANTO");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_2} wird an\n{STR_VAR_1} gesendet.");
const u8 gText_ByeByeVar1[] = _("Tschüss, {STR_VAR_2}!");
const u8 gText_XSentOverY[] = _("{STR_VAR_1} hat\n{STR_VAR_3} gesendet.");
const u8 gText_TakeGoodCareOfX[] = _("Pass gut auf\n{STR_VAR_3} auf!");

const u8 gText_ThreeQuestionMarks[] = _("???");
const u8 gText_MaxHP[] = _("MAX. KP");
const u8 gText_Attack[] = _("ANGRIFF");
const u8 gText_Defense[] = _("VERT.");
const u8 gText_Speed[] = _("INIT");
const u8 gText_SpAtk[] = _("SP. ANG");
const u8 gText_SpDef[] = _("SP. VER");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("-");
const u8 gText_MixingRecords[] = _("Daten werden gemischt…");
const u8 gText_RecordMixingComplete[] = _("Datenmischung abgeschlossen.\nDanke fürs Warten.");
const u8 gText_RentalPkmn2[] = _("LEIH-POKéMON");
const u8 gText_SelectFirstPkmn[] = _("Wähle das erste POKéMON.");
const u8 gText_SelectSecondPkmn[] = _("Wähle das zweite POKéMON.");
const u8 gText_SelectThirdPkmn[] = _("Wähle das dritte POKéMON.");
const u8 gText_Rent[] = _("LEIHEN");
const u8 gText_Summary[] = _("BERICHT");
const u8 gText_Deselect[] = _("ABWÄHLEN");
const u8 gText_Others2[] = _("ANDERE");
const u8 gText_TheseThreePkmnOkay[] = _("Sind diese drei\nPOKéMON okay?");
const u8 gText_CantSelectSamePkmn[] = _("Dasselbe POKéMON kann\nnicht gewählt werden.");
const u8 gText_SelectPkmnToAccept[] = _("Wähle ein POKéMON\nzum Annehmen.");
const u8 gText_Summary2[] = _("BERICHT");
const u8 gText_Swap[] = _("TAUSCH");
const u8 gText_PkmnSwap[] = _("POKéMON-TAUSCH");
const u8 gText_SelectPkmnToSwap[] = _("Wähle ein POKéMON\nzum Tauschen.");
const u8 gText_Yes2[] = _("JA");
const u8 gText_No2[] = _("NEIN");
const u8 gText_Rechoose[] = _("NEU WÄHLEN");
const u8 gText_QuitSwapping[] = _("Tausch beenden?");
const u8 gText_Yes3[] = _("JA");
const u8 gText_No3[] = _("NEIN");
const u8 gText_PkmnForSwap[] = _("{PKMN} ZUM TAUSCH");
const u8 gText_Cancel3[] = _("ZURÜCK");
const u8 gText_Swap2[] = _("TAUSCH"); // Unused
const u8 gText_Accept[] = _("ANNEHMEN"); // Unused
const u8 gText_AcceptThisPkmn[] = _("Dieses POKéMON annehmen?");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("Dieses {PKMN} ist schon im Team.");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("SPIELER");
const u8 gText_SavingBadges[] = _("ORDEN");
const u8 gText_SavingPokedex[] = _("POKéDEX");
const u8 gText_SavingTime[] = _("ZEIT");
const u8 gText_WirelessCommStatus[] = _("Drahtlos-Status");
const u8 gText_PeopleTrading[] = _("Beim Tauschen:");
const u8 gText_PeopleBattling[] = _("Beim Kämpfen:");
const u8 gText_PeopleInUnionRoom[] = _("Im UNION-RAUM:");
const u8 gText_PeopleCommunicating[] = _("Kommunizieren:");
const u8 gText_F700Players[] = _("{DYNAMIC 0} Spieler");
const u8 gText_F701Players[] = _("{DYNAMIC 1} Spieler");
const u8 gText_F702Players[] = _("{DYNAMIC 2} Spieler");
const u8 gText_F703Players[] = _("{DYNAMIC 3} Spieler");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("WUNDERKARTEn");
ALIGNED(4) const u8 gText_WonderNews[] = _("WUNDERNEWS");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("DRAHTLOSE VERBINDUNGEN");
ALIGNED(4) const u8 gText_Friend2[] = _("FREUND");
ALIGNED(4) const u8 gText_Exit3[] = _("ZURUECK");
ALIGNED(4) const u8 gText_Receive[] = _("ERHALTEN");
ALIGNED(4) const u8 gText_Send[] = _("SENDEN");
ALIGNED(4) const u8 gText_Toss[] = _("MÜLL");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("Einige Geschehen werden über die\nDrahtlose Verbindung importiert.");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("Lies die WUNDERKARTEn in\ndeinem Besitz.");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("Lies die NEWS!");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("Zurück zum Titelbildschirm.");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("Du hast keine WUNDERKARTE,\nalso wird eine neue KARTE angelegt.");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("Du hast keine WUNDERNEWS,\nalso werden neue NEWS angelegt.");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("Wo soll auf die WUNDERKARTE\nzugegriffen werden?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("Wo soll auf die WUNDERNEWS\nzugegriffen werden?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("Communication standby…\nB Button: Cancel"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("Übertragung… ");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("Verbindung vollständig.");
ALIGNED(4) const u8 gText_CommunicationError[] = _("Übertragungsfehler.");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("Die Verbindung wurde abgebrochen.");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("Soll die WUNDERKARTE weggeworfen\nund die neue Karte benutzt werden?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("Geschenk dieser Karte noch nicht\nerhalten! Neue Karte benutzen?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("Eine WUNDERKARTE von {STR_VAR_1}\nerhalten.");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("Ein WUNDERNEWS-Item von {STR_VAR_1}\nerhalten.");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("Eine neue WUNDERKARTE erhalten.");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("Ein neues WUNDERNEWS-Item erhalten.");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("Einen neuen STEMPEL erhalten.");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("Ein neuer TRAINER ist eingetroffen.");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("Diese WUNDERKARTE hattest\ndu bereits!");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("Dieses WUNDERNEWS-Item\nhattest du bereits.");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("Diesen STEMPEL hattest\ndu bereits.");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("Es gibt keinen Platz mehr, um\nSTEMPEL hinzuzufügen.");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("Dein Rekord wurde DRAHTLOS\nübertragen.");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("Du kannst von diesem TRAINER\nkeine WUNDERKARTE annehmen.");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("Du kannst von diesem TRAINER\nkeine WUNDERNEWS annehmen.");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("Es wurde nichts übertragen…");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("Was möchtest du mit den\nWUNDERKARTEn anstellen?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("Was möchtest du mit den\nWUNDERNEWS anstellen?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("WUNDERKARTE wird übertragen…");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("WUNDERNEWS werden übertragen…");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("Deine WUNDERKARTE wurde zu\n{STR_VAR_1} übertragen.");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("Deine WUNDERNEWS wurden zu\n{STR_VAR_1} übertragen.");
ALIGNED(4) const u8 gText_StampSentTo[] = _("{STR_VAR_1} erhält einen STEMPEL.");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("{STR_VAR_1} erhält GESCHEHEN.");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("Der andere TRAINER hat diese\nWUNDERKARTE bereits.");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("Der andere TRAINER hat diese\nWUNDERNEWS bereits.");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("Der andere TRAINER hat diesen\nSTEMPEL bereits.");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("Der andere TRAINER hat die\nVerbindung abgebrochen.");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("Du kannst diesem TRAINER kein\nGEHEIMGESCHEHEN übertragen.");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("Wenn du die KARTE weg-\nwirfst, passiert nichts! O.K.?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("Soll dieses NEWS-Item weg-\ngeworfen werden?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("Kein GEHEIMGESCHEHEN!\nTrotzdem wegwerfen?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("Daten werden gesichert.\nBitte warten…");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("Speichern beendet.\nBitte A-Knopf drücken.");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("WUNDERKARTE weggeworfen!");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("WUNDERNEWS weggeworfen!");
ALIGNED(4) const u8 gText_MysteryGift[] = _("GEHEIMGESCHEHEN");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}WAHL {A_BUTTON}OK {B_BUTTON}ZURUECK");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}WAHL {A_BUTTON}O.K. {B_BUTTON}ZURÜCK");
const u8 gText_PlayersBattleResults[] = _("KAMPFERGEBNISSE von {PLAYER}");
const u8 gText_TotalRecordWLD[] = _("GESAMT-REKORD S.:{STR_VAR_1} N.:{STR_VAR_2} P.:{STR_VAR_3}");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 83}WIN{CLEAR_TO 128}LOSE{CLEAR_TO 176}DRAW");
const u8 gText_CommunicationStandby5[] = _("Verbindung…");
const u8 gDaycareText_GetAlongVeryWell[] = _("Die zwei verstönd sich\nmega guet.");
const u8 gDaycareText_GetAlong[] = _("Die zwei verstönd sich guet.");
const u8 gDaycareText_DontLikeOther[] = _("Die zwei möged sich\nnöd bsunders.");
const u8 gDaycareText_PlayOther[] = _("Die zwei spieled lieber mit andere\nPOKéMON als mitenand.");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("ZURÜCK");
const u8 gText_Lv[] = _("{LV}");
const u8 gText_TimeBoard[] = _("ZIITTAFLE");
const u8 gText_TimeCleared[] = _("ZIIT GSCHAFFT ");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1} Min. {STR_VAR_2}.{STR_VAR_3} Sek.");
const u8 gText_TrainerHill1F[] = _("EG");
const u8 gText_TrainerHill2F[] = _("1. OG");
const u8 gText_TrainerHill3F[] = _("2. OG");
const u8 gText_TrainerHill4F[] = _("3. OG");
const u8 gText_TeachWhichMoveToPkmn[] = _("Weli {STR_VAR_3} söll\n{STR_VAR_1} lerne?");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("{STR_VAR_2} beibringe?");
const u8 gText_MoveRelearnerTeachMoveConfirmUseTm[] = _("{STR_VAR_2} beibringe?\nDas verbraucht ein {STR_VAR_3}.");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1} het\n{STR_VAR_2} glernt!");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1} will\n{STR_VAR_2} lerne.\pAber {STR_VAR_1} kennt scho\nvier Attacke.\pSöll e alti Attacke weg,\ndamit Platz für {STR_VAR_2} isch?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("{STR_VAR_2} doch\nnöd beibringe?");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1, {PAUSE 15}2 und {PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Puff!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1} het {STR_VAR_3}\nvergässe.\pUnd…\p{STR_VAR_1} het {STR_VAR_2}\nglernt.");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1} het\n{STR_VAR_2} nöd glernt."); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("Ufgeh und {STR_VAR_1}\nkei neui Attacke biebringe?");
const u8 gText_MoveRelearnerStop[] = _("Uf mit neue Attacke\nfür {STR_VAR_1}?");
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("Weli Attacke söll\nvergässe werde?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("KAMPFATTACKEN");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("WETTBEWERBSATT.");
const u8 gText_MoveRelearnerType[] = _("TYP/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("AP/");
const u8 gText_MoveRelearnerPower[] = _("STÄRKE/");
const u8 gText_MoveRelearnerAccuracy[] = _("GENAUIGKEIT/");
const u8 gText_MoveRelearnerAppeal[] = _("AUSDRUCK");
const u8 gText_MoveRelearnerJam[] = _("STÖRUNG");
const u8 gText_ClearAllSaveData[] = _("Alli Speicherdate lösche?");
const u8 gText_ClearingData[] = _("Date werded glöscht…\nBitte warte.");
const u8 gText_IsThisTheCorrectTime[] = _("Stimmt die Ziit so?");
const u8 gText_Confirm3[] = _("BESTÄTIGEN");
const u8 gText_Cancel4[] = _("ZURÜCK");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("Kommunikation läuft…\nWarte uf de andere Spieler.");
const u8 gText_BattleWasRefused[] = _("De Kampf wurde abglehnt.{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("Kampf abglehnt.{PAUSE 60}");
const u8 gText_NoWeather[] = _("KEI WETTER"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("SUNNIG"); // Unused
const u8 gText_Sunny2[] = _("SUNNIG2"); // Unused
const u8 gText_Rain[] = _("RÄGE"); // Unused
const u8 gText_Snow[] = _("SCHNEE"); // Unused
const u8 gText_Lightning[] = _("BLITZ"); // Unused
const u8 gText_Fog[] = _("NEBEL"); // Unused
const u8 gText_VolcanoAsh[] = _("VULKANASCHE"); // Unused
const u8 gText_Sandstorm[] = _("SANDSTURM"); // Unused
const u8 gText_Fog2[] = _("NEBEL2"); // Unused
const u8 gText_Seafloor[] = _("MEERESGRUND"); // Unused
const u8 gText_Cloudy[] = _("WOLKIG"); // Unused
const u8 gText_Sunny3[] = _("SUNNIG3"); // Unused
const u8 gText_HeavyRain[] = _("STARCHER RÄGE"); // Unused
const u8 gText_Seafloor2[] = _("MEERESGRUND2"); // Unused
const u8 gText_DelAll[] = _("ALLS LÖSCH.");
const u8 gText_Cancel5[] = _("ZURÜCK");
const u8 gText_Ok2[] = _("O.K.");
const u8 gText_Quiz[] = _("QUIZ");
const u8 gText_Answer[] = _("ANTWORT");
const u8 gText_PokeBalls[] = _("POKéBÄLLE");
const u8 gText_Berry[] = _("BEERE");
const u8 gText_Berries[] = _("BEEREN");
const u8 gText_ExpShareOn[] = _("De EP-Teiler isch jetzt aa.{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("De EP-Teiler isch jetzt us.{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("GEIST");
const u8 gText_Boulderbadge[] = _("FELSORDEN");
const u8 gText_Cascadebadge[] = _("QUELLORDEN");
const u8 gText_Thunderbadge[] = _("DONNERORDEN");
const u8 gText_Rainbowbadge[] = _("FARBORDEN");
const u8 gText_Soulbadge[] = _("SEELENORDEN");
const u8 gText_Marshbadge[] = _("SUMPFORDEN");
const u8 gText_Volcanobadge[] = _("VULKANORDEN");
const u8 gText_Earthbadge[] = _("ERDORDEN");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("LUNTE: Es isch wichtig, dass du\ndini POKéMON richtig guet kennsch.\p");
const u8 gText_OakThisIsListOfPokemon[] = _("Das isch d' Liste vo dine POKéMON,\n{PLAYER}.\pDa chasch du Werte und Attacke\nvo dine POKéMON checke.\pDu wählsch hier au POKéMON us,\nwenn du es Item nutze wotsch.{PAUSE_UNTIL_PRESS}");