SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
	.string "Die Konstruktion eines großen Schiffes\n"
	.string "ist eher vergleichbar mit der eines\l"
	.string "Gebäudes, als eines Transportmittels.$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
	.string "Findest du es nicht auch seltsam, dass\n"
	.string "ein Schiff aus Eisen gebaut wird?\p"
	.string "Es schwimmt aufgrund des so genannten\n"
	.string "Auftriebs.$"

