LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "Das größte Geheimnis dieses Planeten\n"
	.string "hütet der Meeresboden.\p"
	.string "Das hat mal jemand gesagt, aber ich\n"
	.string "weiß nicht…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "Zwischen MOSSDEEP CITY und\n"
	.string "SOOTOPOLIS CITY befindet sich ein\l"
	.string "tiefer Unterwassergraben.\p"
	.string "Das hat mir jemand erzählt.$"

